### ISSUE TITLE
Update bower?

### ISSUE THREAD

**Issue by AnthonySchultz** [jtblin/angular-chart.js#100]
I just started testing this wrapper out, the first issue I came across was not being able to access ChartJsProvider via a config module. Further investigation shows that bower is installing 0.6.0, package.json shows a version 0.7.0, but there are no repo tags for 0.7.0.

By copy/paste the latest angular-charts.js from the dist dir I was able to access the provider. Not sure what the disconnect is or if there is a reason for it, but I thought I would bring it to your attention.

**Comment by jtblin** [comment]
Thanks @AnthonySchultz. Reason I haven't published to npm, bumped bower version is that I found a regression. I need to write a test case and fixed the issue before I can publish the latest changes.

**Comment by jtblin** [comment]
False alert, just a different option used in example. Now bumped bower to 0.7 and published to npm.

**Comment by AnthonySchultz** [comment]
Right on, thanks man.
