### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by googol7** [jtblin/angular-chart.js#102]
I couldn't find a Changelog for angular-chart.js Would be very helpful to decide whether or not an update makes sense or not.

Thanks

**Comment by jtblin** [comment]
Good point, I was actually thinking about that. I'll add one shortly, thanks for the suggestion.

**Comment by jtblin** [comment]
Added for latest releases, will update going forward: https://github.com/jtblin/angular-chart.js/releases
