### ISSUE TITLE
Setting Default Colours

### ISSUE THREAD

**Issue by AnthonySchultz** [jtblin/angular-chart.js#103]
In attempting to set default colours via `setOptions()` in the `.config` module the colours are not respected. I can, however, use `Chart.defaults.global.colours`. Looking at the code, in the [`getColours()`](https://github.com/jtblin/angular-chart.js/blob/master/dist/angular-chart.js#L196) it would seem that colours have precedence based on where they are set. 
1. scope
2. Chart.defaults.global.colours
3. via setOptions.

To me this seems slightly out of order. I would think the would be 
1. setOptions
2. scope
3. default

That way if someone needs to default all charts they can in one place, however, if colors are defined on the scope for an individual chart, they could be respected, and finally everything would fallback to the default colours.

What are your thoughts?

**Comment by jtblin** [comment]
Yeah makes sense to me as well. Can fix that later or feel free to send a PR.

**Comment by langan** [comment]
I've forked your repo and made the change here

https://github.com/langan/angular-chart.js/commit/ae14e17ae7493fa7252a330d73b386f8976caccf

Not sure how I make a pull request

**Comment by jtblin** [comment]
Cool, click the green button on your fork above the file list and follow the instructions:

![image](https://cloud.githubusercontent.com/assets/1388974/7479715/49ab9498-f318-11e4-88b3-177139caf2bf.png)

**Comment by langan** [comment]
Ok did that, let me know if that looks ok :)

**Comment by jtblin** [comment]
Thanks for the PR! Merged and published `0.7.1`.
