### ISSUE TITLE
Legend configurability / question

### ISSUE THREAD

**Issue by ronnyek** [jtblin/angular-chart.js#104]
I've got a chart with very basic setup, and noticed that the legend works, but is overlapping hte top of my chart in a simple donut configuration.

My question is that with raw chartsjs, I've been able to modify the legend template and do stuff like display out the items vertically off to the right. Should something like that work with this out of the box? (so as to not overlap the top of my donut chart?

**Comment by jtblin** [comment]
Would you have an example of what / how you'd configure that on chart.js and maybe a screenshot on how it looks right now?

**Comment by jtblin** [comment]
Feel free to re-open with more details.
