### ISSUE TITLE
bar chart is cropped on the right

### ISSUE THREAD

**Issue by shula** [jtblin/angular-chart.js#106]
not sure if it's angular-chart.js or chart.js related.

my bar charts are cropped on the right side.
it doesn't matter where the graph is in the view (wrapped in divs/spans/etc)

in this screenshot, the page's background is blue, and the <CANVAS....> background is white.
http://i59.tinypic.com/nwlmc9.png
you can see how tooltip and the right-most bar are cropped.

**Comment by Nazgard** [comment]
I have same problem
http://i.imgur.com/HoIp8h6.png

**Comment by MichMich** [comment]
You probably have more data items than labels. Check if those two match.

**Comment by Nazgard** [comment]
Both items and labels is equal
http://i.imgur.com/RTgpfWk.png

**Comment by jtblin** [comment]
Can you post a jsbin exampe to repo: http://jsbin.com/dufibi/3/edit?html,js,output?

**Comment by Nazgard** [comment]
Example http://jsbin.com/tebubafafi/1/

**Comment by jtblin** [comment]
Thank you. Just to make sure, are you talking about the number disappearing a bit on the left?
If that's the case, as I've removed all styles and still see the issue, I'd think the issue is with [chart.js](github.com/nnnick/Chart.js) itself,
see http://jsbin.com/diciyitedo/3/edit

**Comment by Nazgard** [comment]
Thank you for answer! Yes, i was talking about numbers on the left side.
I'll ask a question in chart.js github page.

**Comment by shula** [comment]
body p { margin-bottom: 0.6cm; margin-top: 0pt; } 
  
  
    I was refering to the cart clipped on
      the right side,
      and tooltips being cropped.
      
      On 2015-04-29 16:11, Jerome Touffe-Blin wrote:
    
    
      Thank you. Just to make sure, are you talking about the number
        disappearing a bit on the left?
        If that's the case, as I've removed all styles and still see the
        issue, I'd think the issue is with chart.js itself,
        see http://jsbin.com/diciyitedo/3/edit
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jtblin** [comment]
@shula nothing's cropped on the demo page, without a repro and more details e.g. browser, desktop/mobile?, etc. it's hard to investigate anything:

![image](https://cloud.githubusercontent.com/assets/1388974/7910240/460f4ac6-0896-11e5-9eb0-25ce8f8d8fb0.png)

Feel free to reopen when you have a [repro case](http://jsbin.com/dufibi/3/edit?html,js,output).

**Comment by reinaldo13** [comment]
@jtblin:  I was able to reproduce this "left side label cropping" here: http://jsbin.com/tatafakuke/1/edit?html,js,output. Here is a screenshot:
![screen shot 2015-11-27 at 9 51 50 am](https://cloud.githubusercontent.com/assets/3922614/11446490/80acc1b2-94ec-11e5-9b10-0067b1a5abf3.png)
