### ISSUE TITLE
Single column dataset with negative values and scaleIntegersOnly:false crashes control

### ISSUE THREAD

**Issue by leighghunt** [jtblin/angular-chart.js#107]
Hi,

I ran into an issue with some data I'm using in a project that causes the barchart to crash.

I've narrowed it down to the following set of conditions:

- Data must contain a single column.
- Data must contain a negative value.
- ````scaleIntegersOnly```` must be ````false````.

Workaround
----------------
- Don't set ````scaleIntegersOnly```` option to ````false````.

Example code
-------------------

I've created a project illustrating the issue at https://github.com/leighghunt/angular-chart.js-perf-issue.

The changeset that triggers the issue can be seen at https://github.com/leighghunt/angular-chart.js-perf-issue/commit/b672e69b6007086c421de60b4c5bf6a899b8412b

**Comment by leighghunt** [comment]
Actually - I've been investigating this further, and I suspect it's an issue with chart.js, not your angular directive. I'll create a new issue there and close this one.

For info, it seems to be an infinite loop here: https://github.com/nnnick/Chart.js/blob/master/Chart.js#L441

**Comment by jtblin** [comment]
Thanks Leigh, that's what I was going to suggest.
