### ISSUE TITLE
Does not work correctly when angular is loaded from cdn using browserify shim

### ISSUE THREAD

**Issue by Kuraturpa** [jtblin/angular-chart.js#109]
I'm using browserify and browserify shim to load angularjs from cdn. When I require angular-chart.js I get error "WARNING: Tried to load angular more than once.".

I think the reason for this warning is that angular-chart.js is requiring angular from node_modules folder even though its already loaded from cdn.

**Comment by jtblin** [comment]
Can you provide some code to repro e.g. http://jsbin.com/dufibi/3/edit?html,js,output?
