### ISSUE TITLE
Documentation website take to much CPU

### ISSUE THREAD

**Issue by gagarine** [jtblin/angular-chart.js#116]
The moving background take a lot a resources on my laptop (osx + Firefox). I don't think it's necessary.

![screen shot 2015-05-27 at 23 25 02](https://cloud.githubusercontent.com/assets/164074/7847953/aa50a0ca-04c7-11e5-91e0-a7d08f40931e.png)

**Comment by jtblin** [comment]
Yes Firefox performance sucks, use Chrome it's smooth with it.

**Comment by gagarine** [comment]
Com'on... wasting resource is never fun. I tried on chrome and it's also take an insane amount of CPU. You are basically using battery life for nothing. So I guess you sucks.. not Firefox or Chrome.

**Comment by jtblin** [comment]
It's trolls like you who put a drag on open-source, if you have nothing better to do than insulting me just GTFO.

**Comment by gagarine** [comment]
I'm sorry for the "you suck" part. Nerveless I still think you are wasting resources and the problem affect Chrome and Firefox.

**Comment by vrcod** [comment]
+1 Both Chrome and Firefox bounce the CPU way too much for something like this.
