### ISSUE TITLE
Info Required: Resize/Redraw Charts

### ISSUE THREAD

**Issue by devlanp** [jtblin/angular-chart.js#118]
In my application, I have a side bar and charts on the main body. The issue is, an option is provided to toggle the sidebar. Upon clicking the sidebar collapses/opens however, the charts doesn't resize. Something similar to this: 

http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/

Appreciate if you could provide pointers to documentation or ways to handle this issue.

**Comment by jtblin** [comment]
I am not too sure, by default `responsive` is set to `true` so the chart should resize, they do on http://jtblin.github.io/angular-chart.js/ for me when I resize the browser window. I'd suggest providing a [repro case](http://jsbin.com/dufibi/3/edit?html,js,output) and looking into https://github.com/nnnick/Chart.js issues.

**Comment by devlanp** [comment]
Here is the JS Bin link:

http://jsbin.com/juyegujasa/1/edit?html,js,console,output

**Comment by devlanp** [comment]
Screenshots:
![sc1](https://cloud.githubusercontent.com/assets/10979563/7910903/195dde36-0876-11e5-87ac-7ff01cf33e4f.jpg)
![sc2](https://cloud.githubusercontent.com/assets/10979563/7910904/1964aa7c-0876-11e5-8ec1-1066b59734fe.jpg)

**Comment by marcosvega91** [comment]
Resize is made  by chart.js not by angular chart. Angular chart only set the responsive variable of chart.js

**Comment by reidlai** [comment]
can angular chart implement resize method?

**Comment by vchuquimia** [comment]
you have a way to use the resize method,  listening for the 'create' event (event, chart) then chart.resize().

```javascript
$scope.$on('create', function (event, chart) {
  console.log(chart);
});
```

**Comment by peio72** [comment]
Hello, any update on this issue , i encounter same problem using sidenav with angular material.

**Comment by hjzheng** [comment]
I have a solution, but it is just a template way.
you can find chart instance in object `Chart.instances`

```js
$timeout(function(){
    var keys = Object.keys(Chart.instances)
    Chart.instances[keys[0]].resize();
    Chart.instances[keys[0]].render();
}, 2000);
```

**Comment by jtblin** [comment]
@hjzheng you don't need to use `Chart.instances`, you can just listen to the `create` event as shown above by @vchuquimia and get the reference to the chart from here. Then you can call `resize` or `render` on the chart.

AFAIK you can only listen to the `resize` event on the window, not on individual DOM elements so there is no way to provide an automatic solution to resize the chart when its container dimensions change, short of checking the dimensions every 50ms or something, which I am not convinced it should be done in this library (I worry it could set too many `setInterval` killing performance and battery on mobile). That said maybe we could add an `autoresize` option and try and detect container size changes.

**Comment by hjzheng** [comment]
@jtblin OK, Thanks, I will try it.

**Comment by logicalin** [comment]
Might be a bit late to this party...  However, I'm working on Dashboard app that has a fluid layout, and the chart areas change frequently (and as a group).  This is my solution:

```javascript
$scope.$on('SIZE_CHANGE', function (e, d) {
                $timeout(function () {
                    window.dispatchEvent(new Event('resize'));
                }, 200)
            });
```
Chart.js is listening for window resize events when ```javascript responsive: true ```

**Comment by jtblin** [comment]
You can now emit a `$resize` event on scope on 1.x which will trigger the resize: aa2dc93

**Comment by anasanzari** [comment]
@jtblin when is this update going to be released ?

**Comment by jtblin** [comment]
It is released in 1.x

**Comment by lexyfeito** [comment]
@jtblin can please give an example of how to use the $resize event. Thanks

**Comment by jtblin** [comment]
Basic angular syntax e.g. `$scope.$emit('$resize')`

**Comment by lexyfeito** [comment]
I am doing that but it does not work for me, let me give you an insight of what i have. 

I have two charts inside a container, this container are showed depending of a flag. Whenever i hide any of the containers the other container takes the full window width, however the chart stays the same size. I have an event on the checkboxes controlling the containers like (ng-change="resize()") and the resize function does  $scope.$emit('$resize'). but this is not working

**Comment by lexyfeito** [comment]
@jtblin So digging more i set a break point on the angular-chart.js  where the scope.$on('$resize') is defined, on it is not being called and i already tried $scope.$emit('$resize') and $rootScope.$emit('$resize') and still is not calling it

**Comment by lexyfeito** [comment]
@jtblin so i just solved my issue. Instead of $emit i used $broadcast and i had to wrapped the $scope.$emit('$resize') inside of a $timeout in order to wait for the $digest to be done and the resize the chart. Thank you

**Comment by logicalin** [comment]
My work around for this; which may be pre-current versions, is the following:

From sub-directive, the function that is called to make the size changes, or that detects the size changes:

$scope.$broadcast('SIZE_CHANGE');

From the top-level controller:

$scope.$on('SIZE_CHANGE', function (e, d) {
                $timeout(function () {
                    window.dispatchEvent(new Event('resize'));
                }, 200)
            });

**Comment by mattbajorek** [comment]
@logicalin I have tried your workaround and it still is not working.

**Comment by logicalin** [comment]
The solution that I came up with was a result of needing to call a window resize to trigger the redraw in Chart.js to fit the new size of the chart container.

If I remember correctly, I needed to manually trigger the window resize event after the containers were at their new sizes.

For testing purposes, create a resize event function and call it manually after the scaling functions have completed leaving you with the issue you are seeing.  If this fix will work for you, you should see the chart correctly drawn on demand.  If it does work, then the proper place for auto-triggering needs to be determined.
