### ISSUE TITLE
Fonts are missing in the examples/ folder (breaks minification)

### ISSUE THREAD

**Issue by evdoks** [jtblin/angular-chart.js#119]
References to non-existing font files in `/examples/bootstrap.css`:
```
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

In my case it breaks the minification of angular-chart.js when installing it with bower and preparing static resources with Django's `collectstatic` command

The easy fix would be to simply add missing fonts to `examples/fonts/` directory

**Comment by jtblin** [comment]
Thanks for the report, it doesn't look like adding the fonts in example folder would work as the css is looking one level down (`../fonts/...`). I guess the best would be to remove the `examples` folder from bower using the `ignore` property as per https://github.com/bower/bower.json-spec#user-content-ignore

**Comment by evdoks** [comment]
That would be even better! There is no real need for having `examples/` when installing via bower.

**Comment by evdoks** [comment]
Should I make I pull request with the fix?

**Comment by jtblin** [comment]
That'd be awesome!
