### ISSUE TITLE
How can i change the chart colors

### ISSUE THREAD

**Issue by abomadi** [jtblin/angular-chart.js#120]
I was trying to do the following to change the chart colors but it keeps changing on every reload.
```
$scope.Colours = ["Red", "Green"];
```
and in the html element i add this attribute Colours = "Colours"

Also how possible to control the height and width of the chart, iv'e tried to user widht and height in the html but didnt work

Thanks

**Comment by jtblin** [comment]
You have to use hex colours, see example in the readme.

**Comment by abomadi** [comment]
The @jtblin  it did work, but how can i control the size of the chart ?
