### ISSUE TITLE
Compatibility with chart.js 2.0

### ISSUE THREAD

**Issue by krrokkx** [jtblin/angular-chart.js#123]
Not compatible with chart.js 2.0. Compatibility is needed since in chart.js there are significant performance improvements and fix of proper support for negative values in the bar chart.

**Comment by bischofs** [comment]
+1 Lack of simple things like multiple Y axis that are updated in Chart.js 2.0 would be very usefull in this directive. Can anyone create a fork to try to integrate the new Chart.js?

**Comment by Sljux** [comment]
+1

**Comment by gadeynebram** [comment]
+1

**Comment by jtblin** [comment]
2.0 is still alpha and only released 2 weeks ago: https://github.com/nnnick/Chart.js/releases/tag/2.0.0-alpha3. I'll probably start looking into it soon-ish, happy to consider a PR if someone is willing to. I haven't looked at what the breaking changes are yet.

**Comment by george3447** [comment]
+1

**Comment by adandan01** [comment]
+1

**Comment by Virti** [comment]
+1

**Comment by jtblin** [comment]
As per https://github.com/nnnick/Chart.js/tree/v2.0-dev, it isn't ready yet.

> Version 2.0 is in early alpha. We are changing the internal data model to reduce copying, increase performance and expose a more flexible API

**Comment by jtblin** [comment]
FYI I've started working on this last weekend and I will continue this one and push a branch with what I have then.

**Comment by jtblin** [comment]
Those interested into 2.0 support should try out [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0). Most of the homepage examples now work properly. I had to disable the realtime ticks chart as it was using too much cpu.

Some of the major and breaking changes:

* all options need to have `chart` prefix e.g. `chartData`. The other ones were deprecated for quite some time anyway.
* no more `legend` attribute as it is now a Chart.js option which is enabled by default so it can be disabled via `options.legend.display`
* `chartColours` have been renamed to `chartColors`.

You should be able to test the examples by opening `examples/charts.template.html`. Need to download Chart.js beta-2 and put it at the root of the directory.

I'd appreciate feedback and issues with this new version. Please prefix issues with `chartjs-2.0` in the title.

**Comment by thundo** [comment]
Good job @jtblin for supporting a beta version. Would it be possible to have an updated dist for this branch?

Thank you

**Comment by jtblin** [comment]
I've now updated the dist for the branch. Chart.js dependency is also updated in bower (not released to npm yet) so all dependencies can be retrieved via bower normally now.

Remaining items (non exhaustive):

- [ ] Fix the performance issue for the realtime ticks or open an issue on Chart.js
- [ ] Update the tests
- [ ] Update the stacked bar and other examples
- [ ] Remove hard-coding of `fill` cf. #309

**Comment by jtblin** [comment]
Opened https://github.com/nnnick/Chart.js/issues/2040 for tracking the realtime chart performance problem.

**Comment by jtblin** [comment]
> I've now updated the dist for the branch. Chart.js dependency is also updated in bower (not released to npm yet) so all dependencies can be retrieved via bower normally now.

However I recommend using the latest Chart.js in v2.0-dev branch for better performance and latest fixes: https://github.com/nnnick/Chart.js/blob/v2.0-dev/dist/Chart.js

**Comment by thundo** [comment]
Very nice, thank you for the dist and the direct improvement of the library. 
I'll give it a run to the bleeding edge branch in the next few days.

**Comment by jtblin** [comment]
All tests now pass with Chart.js 2.0 branch. I've now published a `1.0.0-alpha1` version, see https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0 for more info and breaking changes.

**Comment by PedroCassettari** [comment]
Hy dudes.

Is it possible combine bar chart and line chart with Chart.JS 1.0?

Thanks!!

**Comment by jtblin** [comment]
Not with Chart.js 1.0, it's possible with Chart.js 2.0 but not yet with angular-chart 1.0.0-alpha1. See https://github.com/jtblin/angular-chart.js/issues/336.

**Comment by niemyjski** [comment]
@jtblin can we merge this into master? 2.0 will be released shortly and all of there efforts are on 2.0 which means people should start the migration to 2.0. We can tag the current stable and release minor versions if we have to in a tag/branch for 1.x.

**Comment by jtblin** [comment]
@niemyjski until chart.js `2.0` is merged into master and published, there is no point doing so. The current deployed version of chart.js 2.0 beta dates from Dec-28 and there have been many changes since then so the version that will be picked by bower misses a lot of bug fixes, performance improvements, etc.

Moreover I may have more breaking changes that I want to release as part of `1.0`. For example I just removed the call to `scope.apply()` on mouse hover.

Latest version is published to npm as `1.0.0-alpha3`.

**Comment by niemyjski** [comment]
@jtblin Were working on getting it merged in.

**Comment by niemyjski** [comment]
@jtblin chartjs 2.0 has been released :)

**Comment by jtblin** [comment]
I've published a new version `1.0.0-alpha4` using latest Chart.js `2.0.0`. I still have one test failing in Travis that I'd like to fix but I should release as stable pretty soon.

- [ ] Fix travis ci build

**Comment by ramarro123** [comment]
Hi,

what about giving the option to better config all the params on dataset?

imagine making a chart with a filled line and a plain line, it will be
dataset[{fill:false,data:blabla},{fill:true,data:bubu}]


at the moment it's not possible to configure PER dataset attributes, just the global params via
chart-options

maybe adding another props like "datasetProps" that take an array of objects that will (at each index) extends the dataset? just wondering :)


i am thinking to all the various options, including mixing dashed chart with standard,  changing the tension (i have to chart a squared wave, and tension have to be 0 and an analog sin wave, with of coruse a bit of tension to make it nicer and smooth)

hope that you understand my shitty english guys ;)

**Comment by sankotm** [comment]
Hey,
thanks for making it compatible with Charts.js 2.0. Stacked Bar/Line graphs is what I needed. I have them almost running as I'd need. What I miss is a legend bellow showing names of series and their colors. Is it possible to show them ?

(on StackedBarExample, they are not there http://jtblin.github.io/angular-chart.js/examples/stacked-bars.html)

**Comment by sankotm** [comment]
Ah, found it:
```
$scope.options = {
    legend: {
        display: true,
        position: 'bottom'
    }
}

```

I couldn't find it in readme (there is just a note that chart-legend was removed). It may be handy to add a note there about how to enable it in options.

**Comment by istiti** [comment]
Hello, I use the last chartjs and the angular-chartjs 2.0 support but when  I resize my Chrome the chartLine is duplicated why this ? you can see here : http://g.recordit.co/s2w01tnCSB.gif

**Comment by alexcastillo** [comment]
+1

**Comment by jtblin** [comment]
@istiti please open separate issues with repro steps.

**Comment by nirre7** [comment]
@ramarro123 There is a PR in the works that should suit your needs #391

**Comment by jtblin** [comment]
- [ ] Review #391 PR and other data structure issues and ideas
- [ ] Add bubble chart

**Comment by jtblin** [comment]
I've now published [1.0.0-beta1](https://github.com/jtblin/angular-chart.js/releases/tag/1.0.0-beta1) which adds support for bubble charts and a few other things. That means I am not planning to do any major (breaking change) to the API for now. Given it has been in `alpha` for quite a while, I am not expecting the beta to last for too long before I merge to master. Probably just 1 or 2 weeks from now. Sorry it took way longer than expected.

**Comment by arjundevarajan** [comment]
Is the ability to adjust axes to nonlinear scales possible? (i.e. logarithmic, exponential, etc.)

**Comment by Olmer1st** [comment]
Hi,
what version of Chart JS supported?

**Comment by brunoserralheiro** [comment]
Error: Chart.js library needs to included, see http://jtblin.github.io/angular-chart.js/ 
It was working fine, and then this.

What is the matter, anyway?

**Comment by jtblin** [comment]
And then what? I don't understand you mate.

**Comment by mackelito** [comment]
When running bower install on "angular-chart.js": "1.0.1" it seems to lack Chart.js

**Comment by qiluo** [comment]
I ran into same problem when I was trying to load the page
```
ReferenceError: require is not defined
<anonymous>   chart.js:4

Error: Chart.js library needs to included, see http://jtblin.github.io/angular-chart.js/
<anonymous>   angular-chart.js:23
```

I installed angular-chart by bower
