### ISSUE TITLE
Graph fill bug with specific data

### ISSUE THREAD

**Issue by chelzwa** [jtblin/angular-chart.js#124]
With very specific data, the chart fill area does not display correctly. 
![image](https://cloud.githubusercontent.com/assets/10090103/8045330/6b544024-0de7-11e5-9cf7-60e8c5b3f219.png)

Javascript:
```javascript
angular.module("app", ["chart.js"]).controller("LineCtrl", function ($scope) {
  $scope.labels = ['6/5/15', '6/6/15', '6/7/15'];
  $scope.data = [
    [6000, 10000, 7000]
  ];
});
}
```

HTML:
```html
<canvas id="line" class="chart chart-line" data="data" labels="labels"></canvas>
```

This does not happen if you divide or multiply each data point by ten (and therefore still maintain the same graph curve), or subtract or add one from or all of the data points. Weirdly, when the graph first renders and animates, the fill is correct, but once the graph animation has finished, the chunk of fill in the top right-hand portion disappears.

**Comment by jtblin** [comment]
I think that would be an issue with chart.js itself, please open an issue in their tracker: https://github.com/nnnick/Chart.js/issues.

**Comment by chelzwa** [comment]
Will do, thank you.
