### ISSUE TITLE
create charts with ng-repeat with dynamic data

### ISSUE THREAD

**Issue by shaohaolin** [jtblin/angular-chart.js#127]
![html](https://cloud.githubusercontent.com/assets/6677092/8114942/1d270a7e-1046-11e5-896c-2d703bd24197.PNG)

Hello, first of all, great directive! Thank you.
My situation is:
I want to create charts based on the data I have binding to my model student with ng-repeat. Every student will have different data correspond to different charts. However, I am not able to use handler bar {{student.data}} to do so.

Is anyway I can achieve it?

**Comment by shaohaolin** [comment]
![issue4](https://cloud.githubusercontent.com/assets/6677092/8132794/30756e48-10f2-11e5-8c62-74072623b08a.PNG)
I am getting this error when I try to add handlebar to data attribute.
![issue5](https://cloud.githubusercontent.com/assets/6677092/8132806/4e26c4b4-10f2-11e5-9ac8-0aa8d40a8613.PNG)
![issue6](https://cloud.githubusercontent.com/assets/6677092/8132810/52f62ffc-10f2-11e5-8a00-5da855d2c3b4.PNG)

What I want to do here is to bind different data based on the index.

**Comment by jtblin** [comment]
Have you tried using an array instead? E.g. 

```js
$scope.data = [];
$scope.data[1] = 'bla';
```

```html
<canvas data="data[$index]" ... >
```

**Comment by shaohaolin** [comment]
Thank you. It helps a lot.

**Comment by youtalaoui** [comment]
Hello, is it possible to have the chart type also in the ng-repeat so i can have different charts depending on the variable binded ?

**Comment by Piraban** [comment]
Did you fix this issue? How did you fix the issue? I am facing same, but I couldn't sort out. Can you share pieces of code?
