### ISSUE TITLE
Resize problem with table

### ISSUE THREAD

**Issue by shaohaolin** [jtblin/angular-chart.js#128]
![issue2](https://cloud.githubusercontent.com/assets/6677092/8115545/28a84152-104a-11e5-8fed-409afd090aa7.PNG)

I am using ng-repeat to create my table, inside every tr has ng-show to show the chart if someone click it.
I am having the problem that some charts are resized properly.

**Comment by shaohaolin** [comment]
![issue3](https://cloud.githubusercontent.com/assets/6677092/8130853/0cbe53ce-10e4-11e5-999c-efcd9de12815.PNG)

First, I was trying to write ng-style in the canvas tag, which was not working. Because chart.js will overwrite the style responsively. 
Then I put the canvas in a div which as shown above, it fixed my problem.
So I assume that the canvas will fill in the space that it can to display the chart?

**Comment by jtblin** [comment]
Yes by default, it is responsive, so the canvas will take the dimensions of its container.

**Comment by jtblin** [comment]
For issues with resizing, please follow #118
