### ISSUE TITLE
Problem with Line chart and changing data

### ISSUE THREAD

**Issue by micha-09** [jtblin/angular-chart.js#129]
Hello,

i have a line chart. i want to set data, labels and series of this chart until i click one button. So i initialise at first like this, when angular controller starts:

$scope.series = [];
$scope.data = [];
$scope.labels = [];

so if buttons is clicked i do this in the method:
e.g:
$scope.series = ['First', 'Second'];
$scope.data = [[1,2,3],[4,5,6]];
$scope.labels = ['Label1','Label2','Label3'];

But nothing is change in graph... what is wrong?

Thanks for help

**Comment by micha-09** [comment]
Ok if i don`t hide the chart until data is available it runs ...

**Comment by jtblin** [comment]
Yes it's related to #29 and there is no easy fix for that but there are workarounds described there. Please follow the other issue.

**Comment by micha-09** [comment]
a easy fix for me was to use ng-if instead of ng-show / hide

So i able to hide the div and running charts correctly
