### ISSUE TITLE
Initializing charts with no data (for later loading via AJAX) could be simpler

### ISSUE THREAD

**Issue by bhasden** [jtblin/angular-chart.js#13]
When creating a chart with empty labels, data, series, etc. for later loading via AJAX, a Javascript exception occurs unless the data array is initialized as an array of an empty array (e.g. `[[]]`). I've included a fix below:

Broken Code:
`if (hasDataSets(type) && !newVal[0].length) return;`

Fixed Code:
`if (hasDataSets(type) && (!newVal.length || !newVal[0].length)) return;`

I'm working around this currently by initializing my data variable in the previously mentioned style (`[[]]`) and then clearing it and pushing the multiple series of data to the data array, so this isn't an urgent issue but is more of a nice to have if it doesn't cause other problems.

Thanks,
Brian

**Comment by IgoMedeiros** [comment]
\o/
