### ISSUE TITLE
Labels disappear after redraw the bar chart

### ISSUE THREAD

**Issue by victorarcasrios** [jtblin/angular-chart.js#130]
The bar chart is working great since I change the data of the model in $scope bar by bar. Then, the bars are well redrawed with the new values, but the labels disapepar. 
I compare the after and before data in the chrome console and both have the same format.

**Comment by jtblin** [comment]
Can you post a repro case e.g. jsbin (see readme for template)? There is a similar working example with labels (not disappearing) on the [demo](http://jtblin.github.io/angular-chart.js/) page.

**Comment by victorarcasrios** [comment]
I will try to post it. Now i'm at my job.

Btw, i fix the problem reasigning the data to the model after changing it using angular.copy()

**Comment by jtblin** [comment]
Please re-open with a repro case if you want.

**Comment by kiddy2910** [comment]
I also met this bug and cannot resolve. Here repo http://plnkr.co/edit/qAcvkiftpyj9RMznOvgB?p=preview
