### ISSUE TITLE
Getting fill-colors to the bar chart...

### ISSUE THREAD

**Issue by anthraxn8b** [jtblin/angular-chart.js#131]
Hi!
I am new to chart.js and especially angular-chart.js.
I am trying to do the following:

HTML:
```html
<canvas
   id="bar"
   class="chart chart-bar"
   data="charts.bar.data"
   labels="charts.bar.labels"
   colours="charts.bar.colours"
   options="charts.bar.options"
   width="100"
   height="50"
></canvas>
```
```javascript
$scope.charts.bar = {
   'labels' : [-6, -5, -4, -3, -2, -1, 0],
   'data' : [[65, 59, 80, 81, 56, 55, 40]],
   'colours' : ['#FFFFFF', '#FFFFFF'],
   'options' : {
      'showScale' : false,
      'showTooltips' : false,
      'responsive' : false,
      'maintainAspectRatio' : false,
      'pointDot' : false,
      'bezierCurve' : true,
      'datasetFill' : false,
      'animation' : false,
				
      'barShowStroke' : false,
      'barStrokeWidth' : 2,
      'barValueSpacing' : 1,
      'barDatasetSpacing' : 1,
				
      'fillColor' : 'rgba(220,220,220,0.9)'
   }
};
```
The line `'fillColor' : 'rgba(220,220,220,0.9)'` does not work.

In the chart.js documentation i saw another datastructure:
```javascript
var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.5)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [65, 59, 80, 81, 56, 55, 40]
        },
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};
```
This also does not seem to work.

Any Ideas?

**Comment by jtblin** [comment]
If you want to pass the different nuances for the colours, you have to pass the full colour objects in the `charts.bar.colours` instead of the hex codes i.e. 

```
{ // blue
      fillColor: 'rgba(151,187,205,0.2)',
      strokeColor: 'rgba(151,187,205,1)',
      pointColor: 'rgba(151,187,205,1)',
      pointStrokeColor: '#fff',
      pointHighlightFill: '#fff',
      pointHighlightStroke: 'rgba(151,187,205,0.8)'
}
```

**Comment by anthraxn8b** [comment]
This seems to work! THX!

Just one question left: What about the code from the documentation? Can I define datasets and use that approach?

**Comment by jtblin** [comment]
I don't understand the question. You can see different examples on the [demo page](http://jtblin.github.io/angular-chart.js/).

**Comment by mateutek** [comment]
But, this changes the color of all elements.
Is there a way to change color of specific object, like last bar for example ??

**Comment by Alain1405** [comment]
@jtblin what @mateutek and @anthraxn8b is shown [here](https://github.com/chartjs/Chart.js/blob/master/samples/timeScale/line-time-scale.html#L60). Instead of passing a `data` array of 3 parallel arrays, I pass a `dataset` array with 3 objects containing options and data for each dataset.

**Comment by jtblin** [comment]
Thanks @Alain1405, makes sense to have different options per series, I'll track the work in #370.

**Comment by troynsky** [comment]
Need help, I still don't understand what to do to fill-colors bar char from angular side. For example
$scope.chart = {
...
colors: [
                {
                    fillColor: 'rgba(213,226,255)',
                    strokeColor: 'rgba(213,226,254)',
                    pointColor: 'rgba(213,226,254)',
                    pointStrokeColor: '#fff',
                    pointHighlightFill: '#fff',
                    pointHighlightStroke: 'rgba(213,226,255)'
                },
                {
                    fillColor: 'rgba(185,223,147)',
                    strokeColor: 'rgba(185,223,146)',
                    pointColor: 'rgba(185,223,146)',
                    pointStrokeColor: '#fff',
                    pointHighlightFill: '#fff',
                    pointHighlightStroke: 'rgba(185,223,147)'
                }
]
...
};

in html : 
<canvas id="bar" class="chart chart-bar"
...
chart-colors = "chart.colors"
...>

Thx in advance!

**Comment by RPrzepio** [comment]
@troynsky  I think you have to override options. There is an attribute "chart-dataset-override" which you should use. 

here you have an example: 
http://plnkr.co/edit/bnbZFXVlq4pX1BL5slqR?p=preview

and here docs:
http://www.chartjs.org/docs/#doughnut-pie-chart-data-structure

**Comment by supergicko** [comment]
@troynsky if you using the new library with chart.js 2.0.x - there are some changes in the api of chart.js

**no need to override the datasets.**

for example: 

_fillColor_ is now **backgroundColor**
_strokeColor_ is now **borderColor**


my example colors for a bar chart:
`   colours: [
                    {
                        backgroundColor: '#A2DED0',
                        borderColor: '#A2DED0',
                        hoverBackgroundColor: '#A2DED0',
                        hoverBorderColor: '#A2DED0'
                    },
                    {
                        backgroundColor: '#65C6BB',
                        borderColor: '#65C6BB',
                        hoverBackgroundColor: '#65C6BB',
                        hoverBorderColor: '#65C6BB'
                    },
                    {
                        backgroundColor: '#1BBC9B',
                        borderColor: '#1BBC9B',
                        hoverBackgroundColor: '#1BBC9B',
                        hoverBorderColor: '#1BBC9B'
                    }
                ]
`

for more info (as @RPrzepio pointed out) : http://www.chartjs.org/docs/#doughnut-pie-chart-data-structure

**Comment by chedched** [comment]
@supergicko: I can't get your code to work - everything has the same color: http://plnkr.co/edit/1irEj30D9NfRX9qu9H12?p=preview. Can you please tell me what I'm missing here?

**Comment by tanveer12332** [comment]
same issue for me but i m fixed this is my pie chart function:
 this is html:
<canvas baseChart
          [datasets]="datasets"
          [labels]="pieChartLabels"
           [colors]="colorsOverride"
          [chartType]="pieChartType"
          (chartHover)="chartHovered($event)"
          (chartClick)="chartClicked($event)"></canvas>
------------------------
this is TS
import { ChartsModule, Color } from 'ng2-charts';
public color;
    public colorobj: Color = {
        backgroundColor : "green"
    };
  public pieChartLabels: string[] = [];
    public pieChartData: number[] = [];
public pieChartType: string = 'pie';

    public piechartlabel: string[] = [];
    public piechartvalue: number[] = [];
   public colorsOverride: Array<Color> =  [];
    this.nfData.forEach((e) => {
                this.pieChartLabels.push(e.InvestmentServiceName);
                this.pieChartData.push(e.HoldingValue);
                this.color = 'rgb(' + Math.floor(Math.random() * 200) + ', ' + Math.floor(Math.random() * 200) + ', ' + Math.floor(Math.random() * 200) + ')';
                this.colorobj.backgroundColor=this.color;
                this.colorsOverride.push(this.colorobj);
            }).then(res => {
            this.pieChartData = this.pieChartData.slice();
            this.colorsOverride = this.colorsOverride.slice();
        })

  datasets: any[] = [
  {
    data: this.pieChartData,
    backgroundColor: [
      this.colorsOverride,
     // "#36A2EB",
      //"#FFCE56"
    ],
    hoverBackgroundColor: [
      "#000",
      "#36A2EB",
      "#FFCE56"
    ]
  }];
you use  modified object for nfdata and then function to .
