### ISSUE TITLE
How to set max and min values for Y axis ?

### ISSUE THREAD

**Issue by yrshaikh** [jtblin/angular-chart.js#132]

**Comment by jtblin** [comment]
http://www.chartjs.org/docs/

**Comment by KaranSofat** [comment]
http://www.chartjs.org/docs/

**Comment by hinter1992** [comment]
`
                yAxes: [
                    {
                        id: 'y-axis-1',
                        type: 'linear',
                        position: 'left',
                        ticks: {
                            min: 0,
                            max:  100 ,
                        }
                    },
                ]
          `

**Comment by rajathms** [comment]
@hinter1992 can you be more descriptive.
I mean to which attribute i need to pass this

**Comment by rajathms** [comment]
**HTML**
```
<canvas id="bar" class="chart chart-bar" chart-data="vm.chartData" 
chart-labels="vm.cartLabel" chart-series="vm.chartSeries" 
chart-options="vm.chartOptions"> </canvas>
```
**Controller**
```
vm.chartOptions = {
      legend: {
        display: true
      },                                                                                             
      scales: {
        yAxes: [{id: 'y-axis-1', type: 'linear', position: 'left', ticks: {min: 0, max:100}}]
      }
    };
```

**Comment by Ratnadeep9** [comment]
@hinter1992 does the following code works with all type of charts?
yAxes: [ { id: 'y-axis-1', type: 'linear', position: 'left', ticks: { min: 0, max: 100 , } }, ]
cause I was trying to use the code for radar chart and it didnt worked!!! Could you please suggest how to set the max and min value for radar chart
