### ISSUE TITLE
How to use colours directive

### ISSUE THREAD

**Issue by jadjoubran** [jtblin/angular-chart.js#133]
Thank you for this great plugin!

How can we use the default colors available in Chart.js via the `colours=colours` & `$scope.colours` syntax

**Comment by youtalaoui** [comment]
if you dont define the attribute in the canvas(HTML) it will take the default one

**Comment by jadjoubran** [comment]
I did define the attribute in the HTML 
Can you give me an example of the Javascript code?

**Comment by jadjoubran** [comment]
I found an example in the repo:

      $scope.colours = [{ // red
      fillColor: 'rgba(247,70,74,0.2)',
      strokeColor: 'rgba(247,70,74,1)',
      pointColor: 'rgba(247,70,74,1)',
      pointStrokeColor: '#fff',
      pointHighlightFill: '#fff',
      pointHighlightStroke: 'rgba(247,70,74,0.8)'
    },
      { // green
        fillColor: 'rgba(70,191,189,0.2)',
        strokeColor: 'rgba(70,191,189,1)',
        pointColor: 'rgba(70,191,189,1)',
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: 'rgba(70,191,189,0.8)'
      }];


Now the question is: Would be possible to specify which colours to choose for this graph?

**Comment by jtblin** [comment]
You can also use hex code for colours fyi. Not sure I understand the question, if you set the colours for a graph, they will be used for this particular graph. You can also set the colours globally for all graphs.

**Comment by jadjoubran** [comment]
When you open the documentation: http://jtblin.github.io/angular-chart.js/
Series have beautiful pre-sets colours (to a maximum of 7 series, after that colours will be randomly generated). They can be overwritten using Chart.defaults.global.colours.
And you have: `Blue` `Light grey` `Red` `Green` `Yellow` `Grey` `Dark Grey`

So at first, I thought it was possible to specify 2 of these colors for a specific graph by just writing
`colours=colours`
`$scope.colours=['red','blue']`

I was able to make it work with the code sample above
Is it possible to select one of the pre-set colours by name?

Thanks!

**Comment by jtblin** [comment]
Got it. No it doesn't work with the colour names, you need to pass the hex
code.

**Comment by jadjoubran** [comment]
Okay thanks!
