### ISSUE TITLE
ng-repeat on graph type 

### ISSUE THREAD

**Issue by youtalaoui** [jtblin/angular-chart.js#134]
i am trying to dynamically draw different charts depending on binded data. it seems that the class attribute is not bindable. i tried with ng-class but no luck so far

here is an example of my issue http://plnkr.co/edit/j3QilQnfS2ny2vXNSUTd?p=preview

if you can get me some input that would be helpful

thank you

**Comment by jtblin** [comment]
You need to use `chart-base` class and set the type using `chart-type` attribute, see http://jtblin.github.io/angular-chart.js/#base-chart

Angular doesn't support setting directives with dynamic classes.
