### ISSUE TITLE
Problem in changing dimensions of the canvas

### ISSUE THREAD

**Issue by ibbatta** [jtblin/angular-chart.js#135]
Hi,

I have tried to add `width`and `height` markup html to a canvas but they got override probably by the javascript. 
Then I have tried to change dimension of the canvas via css and it works, but i got a hover problem.

![schermata 2015-06-19 alle 10 29 32](https://cloud.githubusercontent.com/assets/4375285/8249825/86d4ed5a-166e-11e5-8574-69aebc839f1b.png)
*(this is the screen of my css rules)*

**Comment by jtblin** [comment]
You need to set the responsive option to false.

**Comment by ibbatta** [comment]
Thanks, it works!
