### ISSUE TITLE
When adding segments[i].value in Legend, it doesn't update with the change in scope

### ISSUE THREAD

**Issue by nicolabortignon** [jtblin/angular-chart.js#136]
Every time the data change in the $scope the legends should change as well, especially if using the segments[i].value in the legend template.

**Comment by jtblin** [comment]
Yes it should be the case already, `setLegend` is called on chart create and update. See example here http://jtblin.github.io/angular-chart.js/#line-chart (series is changing but data should change as well).
Do you have a repro case (see jsbin link in readme)?

```
    function updateChart (chart, values, scope) {
     (...)
      if (scope.legend && scope.legend !== 'false') setLegend(elem, chart);
    }
```

**Comment by jtblin** [comment]
Hum, looks like this was only added locally but never pushed.
