### ISSUE TITLE
Can't show multiple chart in a single page

### ISSUE THREAD

**Issue by nil4you** [jtblin/angular-chart.js#139]
For demo purpose I was trying to put multiple chart in single page but failed to do it, only first chart is visible. Any solution of it ?

**Comment by jtblin** [comment]
Well look at the demo page, it's definitely possible:
http://jtblin.github.io/angular-chart.js/

**Comment by nil4you** [comment]
can  we do it by calling it in one controller, I can see only that difference in your code.

**Comment by jtblin** [comment]
Yes just make sure you set the data and options accordingly.

**Comment by nil4you** [comment]
I have set different data but reality is that you can not call multiple chart in single controller, can you provide the example ?

**Comment by jtblin** [comment]
Can you provide a reproduction case? There is a jsbin template URL in the
readme.

**Comment by nil4you** [comment]
great sure !!! wait while am creating.

**Comment by nil4you** [comment]
Ohh I look like silly it's working there, let me have a look in my code what causes the issue.

**Comment by nil4you** [comment]
here is the template
http://jsbin.com/zeqevowogu/edit?html,js,output

**Comment by jtblin** [comment]
Pie, polar area and doughnut charts use different data structure, see the readme and demo page. Hence why some of the charts don't show-up. Using the same data for all charts doesn't make sense anyway in real life.

**Comment by nil4you** [comment]
so it means if I change data then it will work ?

On Sat, Jun 27, 2015 at 11:58 AM, Jerome Touffe-Blin <
notifications@github.com> wrote:

> Pie, polar area and doughnut charts use different data structure, see the
> readme and demo page. Hence why some of the charts don't show-up. Using the
> same data for all charts doesn't make sense anyway in real life.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtblin/angular-chart.js/issues/139#issuecomment-115974827>
> .
>



-- 
With Regards,
Nirmal Bhagwani.
