### ISSUE TITLE
Stacked Area Chart 

### ISSUE THREAD

**Issue by marco-gagliardi** [jtblin/angular-chart.js#143]
Any chance to see a stacked area chart available soon?

**Comment by jtblin** [comment]
Look in the examples.

**Comment by marco-gagliardi** [comment]
Hey @jtblin , thank you for this feature.
What about a stacked area line chart, instead of bars? 
See: http://nvd3.org/examples/stackedArea.html

**Comment by jtblin** [comment]
This lib is just a wrapper around chart.js. you should check their site /
repo.
