### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by rebelholic** [jtblin/angular-chart.js#144]
Hi, I have some questions below:

* How I can add title with center align on canvas like "Last 2 months" title on my concept  below?

* How I can set red color just for last label text like "15 feb" on my concept below?

* How I can add just add a straight line like dot line with 100% as value on my concept below?

* How I can add percentage character (%) like 100%, 200% like my concept below and I already tried with this way ---> **$scope.data[0] = $scope.value + '%';** still no luck because got error message like *"Uncaught TypeError: Cannot read property 'draw' of undefined"*? 
![charts](https://cloud.githubusercontent.com/assets/6254876/8510320/958e03f8-2308-11e5-8eea-c51c8ac26321.jpg)

I hope you can help me to solve this problem. Thanks before.

**Comment by jtblin** [comment]
You should check the http://www.chartjs.org/ site, this lib is only a wrapper around it.
