### ISSUE TITLE
Unsafe eval Content-Privacy-Policy

### ISSUE THREAD

**Issue by fenos** [jtblin/angular-chart.js#146]
Hi guys, I'm having a sad news about this amazing plugin, when i setup the content-privacy-policy on my website Chart.js stop to work outputting this error:

<img width="1410" alt="screen shot 2015-07-08 at 16 35 05" src="https://cloud.githubusercontent.com/assets/4754064/8574604/78aacf26-258f-11e5-809a-bc7b0747179b.png">

I'm aware of this from the Chart.js repository referenced by this issue:
https://github.com/nnnick/Chart.js/issues/281

Can this plugin fix the issue or can you please suggest some solution to implement in a forked version or PR to fix this please. I heavily used this plugin in my app, it will be a huge disappointment to switch plugin for this. Any help will be hugely appreciated

**Comment by jantimon** [comment]
This plugin can't fix the Chart.js bugs it's only a wrapper.

**Comment by jtblin** [comment]
As @jantimon said, there is nothing we can do in this lib. You'd have to fork chart.js and remove / replace this bit. Sorry about that.
