### ISSUE TITLE
Angular-Chart.js Issues with Representing Chart Data For Memeory utilization

### ISSUE THREAD

**Issue by siddmegadeth** [jtblin/angular-chart.js#151]
Currently we cannot use Chartjs to show memory utilization
on the x axis there is a time in terms or Hrs with 15 min duration
and on the y Axis we have Consumption in terms of  m/sec

the problem here is that x axis should be equal to y axis and there are issues representing 
alphanumeric charecters in y axis.

Is there any solution to this issues. it would be great if we can have something  like this.
Please refer to the attached screenshots.

Also we do not see any documentation how to use Chartsjs settings and colors. Please help on that.
![memory](https://cloud.githubusercontent.com/assets/5025324/8674140/7ee10c10-2a59-11e5-99c2-e79a4eccaa53.png)

**Comment by jtblin** [comment]
I thin you should check chart.js doc for axis question, and look at the
readme and examples for the colors. You may also want to try StackOverflow.
