### ISSUE TITLE
Bind pie legend to checkbox

### ISSUE THREAD

**Issue by achurak** [jtblin/angular-chart.js#152]
Hello,

I'm trying to bind the legends parameter to a checkbox, so that when it's checked the legends would show up and disappear when it's unchecked, but it doesn't seem to work.

```html
<input type="checkbox" ng-model="ui.show_legend"> Show legend
<canvas id="some_id" class="chart chart-pie" legend="{{ui.show_legend}}"
        data="data" labels="labels" click="pie_click"></canvas>
```

Is this supposed to work and I'm just doing something wrong or it's not even going to work?

**Comment by jtblin** [comment]
No that wouldn't work as the `legend` option is only read when the chart is created. That would require watching the option and deleting / calling the `setLegend` function if you feel like submitting a PR for that.

**Comment by jtblin** [comment]
Something similar is implemented in Chart.js 2.0, see [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0).

I am going to close this issue as I won't implement it in the current version, as hopefully 2.0 should be out pretty soon.
