### ISSUE TITLE
cannot set line width of chart-line

### ISSUE THREAD

**Issue by artdias90** [jtblin/angular-chart.js#156]
Is there an option to set how large should the width of the line be?

**Comment by jtblin** [comment]
www.chartjs.org/docs/

**Comment by Deimos620** [comment]
Are there any way to set line width of chart line dynamically? For instance, I want to highlight series line if user click it. Is it something possible?

**Comment by Mogernetra** [comment]
To set width use borderWidth in datasets,  Ex: borderWidth: 5

**Comment by almgwary** [comment]
To set width use borderWidth

`
elements: {
      line: {
        borderWidth:1
      }
    }
`
