### ISSUE TITLE
Change colours and size

### ISSUE THREAD

**Issue by estvmachine** [jtblin/angular-chart.js#158]
Hi, i want to know how can i change the colours of the charts. I try something like these. :

```html
<canvas id="bar"
	    class="chart-bar"
		width="65" height="35"
		data="data"
		 labels="labels"
		colours='{ fillColor: "rgba(220,220,220,0.5)",
				  strokeColor: "rgba(220,220,220,0.8)",
				highlightFill: "rgba(220,220,220,0.75)"}'
		>
</canvas>
```

In the controller:

```javascript
    $scope.labels = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
    $scope.series = ['Series A'];

    $scope.data = [
      [65, 59, 45, 81, 56, 55, 40]
    ];

```
The size i changed using widht and height, but maybe exist a better way?

**Comment by jtblin** [comment]
Colours need to be an array and you can pass hex colours to make it simpler. 

If you want to set width and height yourself, you should set `responsive` to false as it is set by default.

**Comment by estvmachine** [comment]
Thanks for the response, work goods. But its not more understandable like object with the names parameters than a array, this way i dont have to access the wiki when i want a different behavior

**Comment by sean72kimo** [comment]
Hello,

About setting height attr in the canvas tag, is it documented in the [webpage](https://jtblin.github.io/angular-chart.js/#line-chart)? 

You mentioned that to set responsive = "false", is it an attribute in the canvas tag?
It is still responsive to me. I couldn't find the doc for this feature either.

Thanks,
Sean

**Comment by jtblin** [comment]
@sean72kimo I am not sure how your question is related to this issue. However the height is just a standard HTML attribute for the canvas tag so I don't think it needs to be specifically documented: https://developer.mozilla.org/en/docs/Web/HTML/Element/canvas
