### ISSUE TITLE
my chart cannot get response when page loads first time in Ionic

### ISSUE THREAD

**Issue by rebelholic** [jtblin/angular-chart.js#160]
I have a problem when making an ionic app about the chart cannot get response when page loads first time with "Item 1" and "New York" as initial selected option like my screenshot below: 
![screen](https://cloud.githubusercontent.com/assets/6254876/8797347/05df4644-2fc5-11e5-96c1-2b02324d81d3.jpg)

 **For controller js**

        .controller('DashCtrl', ['$scope', '$q', '$http', '$timeout', '$interval', '$state', '$filter', '$location',  'DOLLTYPE', 'REGION', function($scope, $q, $http, $timeout,  $interval, $state, $filter, $location,  DOLLTYPE, REGION) {
       $http
       .get('js/data2.json')
      .then(function(region) {

        var i = region.length -1;

        for (i; i >= 0; i--) {
            REGION.add(region[i]);
        };

    })
    .catch(function(error){
        console.log('Error fetching region data: ', error)
    })

    $http
    .get('js/data.json')
    .then(function(result) {

        var i = result.length -1;

        for (i; i >= 0; i--) {
            DOLLTYPE.add(result[i]);
        };

    })
    .catch(function(error){
        console.log('Error fetching doll data: ', error)
    })

     $scope.title = "Dashboard";
     $scope.dash = [];
     $scope.datas = [];
     $scope.avg = [];
     $scope.avgy = [];
     $scope.data = [[]];
     $scope.labels = [[]];
     $scope.date = [];
     $scope.place = [];
     $scope.ayv = [];

     $scope.dolltype = [];
     DOLLTYPE
       .all()
     .then(function(dolltype){ 
         $scope.dolltype    = dolltype;
         $scope.dash2       = $scope.dolltype[0];
     });

    $scope.regiontype = [];
    REGION
     .all()
     .then(function(regiontype){ 
        $scope.regiontype = regiontype;
        $scope.dash1      = $scope.regiontype[0];
     })

     $scope.change = function(dash1) {
     $scope.place = dash1;
      }

     $scope.change2 = function(dash2) {
     $scope.doll= dash2.id;
    }

    $scope.place.name = 'Please select';

    $scope.$watchCollection('[place, doll]', function(newVal, oldVal) {
     $scope.colours = [
      { // Blue
        fillColor: 'rgba(148,159,177,0)',
        strokeColor: 'rgba(47,64,200,1)',
        pointColor: 'rgba(67,43,177,1)',
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: 'rgba(148,159,177,0.8)'
      },
      { // Red
        fillColor: 'rgba(77,83,96,0)',
        strokeColor: 'rgba(200,15,9,1)',
        pointColor: 'rgba(190,50,11,1)',
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: 'rgba(77,83,96,1)'
      },
       { // Green
        fillColor: 'rgba(77,83,96,0)',
        strokeColor: 'rgba(18,177, 26,1)',
        pointColor: 'rgba(80,200,11,1)',
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: 'rgba(77,83,96,1)'
      }
    ];

      $http.get('js/data4.json').success(function(result) { 
       var deferred = $q.defer();
      $scope.dash.msg  = result.message;
      $scope.prices = result.data;
      deferred.resolve($scope.prices);
      angular.forEach($scope.prices,function(value,index){
      var values =  {
                  value : value.value,
                  date : new Date(value.created_at.replace(/-/g,"/"))
       };

     $scope.datas.push(values.value);
     $scope.dash.price = $scope.datas[2];
     $scope.date.push($filter('date')(values.date,'dd-MMM'));    
     $scope.date.splice(2); 
     return deferred.promise;       
      })}).error(function(data, status) {

     console.error('Error', status, data);
     }); //End get price value

     $http.get('js/data5.json').success(function(result) { 
     $scope.averageprice = result.data;
     angular.forEach($scope.averageprice,function(value,index){
      var avgvalue =  {
                    average: value.average,
                    date : new Date(value.created_at.replace(/-/g,"/"))
      };
      console.log (avgvalue);
      $scope.avg.push(avgvalue.average);
      })}).error(function(data, status) {

     console.error('Error', status, data);
      }); //End get average price value

      var deferred = $q.defer();
      $http.get('js/data3.json').success(function(result) { 
      $scope.averageyearprice = result.data;
      deferred.resolve($scope.averageyearprice);
     console.log ($scope.averageyearprice);
     $scope.avgy.push($scope.averageyearprice.yearly_average);
     return deferred.promise;
     }).error(function(data, status) {
    }); //End get average year price value

    $scope.data[0] = $scope.datas;
    $scope.data[1] = $scope.avg;
    $scope.data[2] =  $scope.avgy;

    $scope.labels = $scope.date;
    console.log ($scope.data[0]);

    $scope.series = [$scope.place.name, 'All (Average)', 'All (YTD Year)']; 
    console.log ($scope.series); // Add information for the hover/touch effect
 
     })

    }])

How I can fix it so the chart get response when page loads first time? For full source code [please check out my repo](https://github.com/rebelholic/ionic-chart-selection)

**Comment by jtblin** [comment]
Sorry but I'm not sure how this is related to this lib. You would probably have more luck asking the question on http://stackoverflow.com/.
