### ISSUE TITLE
multiple double Bar chart with same width of Bars

### ISSUE THREAD

**Issue by cyberkatze** [jtblin/angular-chart.js#162]
![capture](https://cloud.githubusercontent.com/assets/2271337/8850982/9f093658-314c-11e5-93ec-ead3b2a5c3b8.JPG)
is it possible to do this?

if i have 2 different bar-charts with different counts of items - width in this case will be different 1) 65px 2) 48px

how can i have on both charts same width of bars?

**Comment by jtblin** [comment]
I'm not sure, you should check the chart.js website.
