### ISSUE TITLE
Label Styling

### ISSUE THREAD

**Issue by LunarDevelopment** [jtblin/angular-chart.js#163]
Hello! 

I'm getting this rendering issue on your examples page and when I have the plugin installed locally, image below: 

![image](https://cloud.githubusercontent.com/assets/10709555/8854742/5fe1e878-3159-11e5-82fc-531d1b919bfa.png)

Any ideas on how to fix? 

I'm using bootstrap 3 as well.

**Comment by b-long** [comment]
I'm also looking for this, any luck figuring it out with CSS or JS?

**Comment by b-long** [comment]
Sorted this out, pass in options ( `myoptions` ) to your canvas.  Then, set a `myoptions` object on your `$scope`: http://jsfiddle.net/b_long/03po48vw/

**Comment by b-long** [comment]
@LunarDevelopment Any idea how to create a radar chart without the fill?  Something like this: https://github.com/bdargan/techradar/blob/master/README.md

**Comment by LunarDevelopment** [comment]
@b-long I'm afraid not, I'm new to the library and haven't had the time to read the APIs properly. Your JSFiddle doesn't seem to solve the rendering label issue, was it meant to?

**Comment by LunarDevelopment** [comment]
Looks to be an issue with Chart.Js, I'll close this and open the issue with them directly.

**Comment by jtblin** [comment]
Thanks!

**Comment by b-long** [comment]
@LunarDevelopment My apologies, I must have confused your issue description with something else I was reading at the time.  I thought you were looking for a way to customize the labels :smile:
