### ISSUE TITLE
Scale for Bar and Line Chart is not able to find lables

### ISSUE THREAD

**Issue by WeBaGeMyghty** [jtblin/angular-chart.js#164]
Hey there, I am experiencing some issue with the chart.js module.

The Problem I am facing is, the all charts which need a scale, for example the line or bar chart, can not be drawn since "labels" is undefined. I tried to dive a little bit inside chart.js and the angular-char.js module and figured out, that the angular-chart.js module only hands over an array of datasets. 

I used the directive for testing purposes like this:

```html
<canvas id="line" class="chart chart-bar" data="[10,20,30]"
                    labels="['Test','Test2','Test3']">
            </canvas>
```

But this generates the following data object which is handed over for initilizing the bar chart: (I stripped all those color parts...) 

```javascript
data:[ 
    {
        label: "Test",
        value: 10
    },
    {
        label: "Test2",
        value: 20
    },
    { 
        label: "Test3",
        value: 30
}
```

So if I understand the char.js documentation right, then now it is needed to hand over something like this:
```javascript
data:{
    labels: ["Label1", "Label2", "Label3"],
    datasets::[ 
    {
        label: "Test",
        value: 10
    },
    {
        label: "Test2",
        value: 20
    },
    { 
        label: "Test3",
        value: 30
    }
}
```

Or am I doing something totally wrong? Oo Using Chart.js 1.0.1 Since this is mentioned as supported on the homepage.

Best

Myghty

**Comment by milkmanjr** [comment]
@WeBaGeMyghty -- I was having a similar problem. I think the problem lies with your data. It should be an array in an array.

**bad**
```html
<canvas id="line" class="chart chart-bar" data="[10,20,30]"
                    labels="['Test','Test2','Test3']">
            </canvas>
```

**good**
```html
<canvas id="line" class="chart chart-bar" data="[[10,20,30]]"
                    labels="['Test','Test2','Test3']">
            </canvas>
```

**Comment by jtblin** [comment]
@milkmanjr is correct. Please read the docs.

**Comment by WeBaGeMyghty** [comment]
Ah, well, Thx, missed that second brace.
