### ISSUE TITLE
class vs ngClass

### ISSUE THREAD

**Issue by dec** [jtblin/angular-chart.js#165]
Hello. Probably this is not too interesting but I loss a half hour searching the reason why the Chart is not drawing correctly even when I use the right "chart-base" class in an "ng-class" AngularJS directive. 

I found the solution by adding to the Chart canvas an HTML class attribute with the "chart-base" value. Then for some reason the Chart doesn't take care about the "ng-class" or something else?

Anyway thanks very much for your work at angular-chart.js!

**Comment by jtblin** [comment]
Yeah that's the way angular directives work.

**Comment by dec** [comment]
Hello,
I can't understand @jtblin, do you say we can't use the "ng-class" directive in a Chart?

**Comment by jtblin** [comment]
You can use `ng-class` but it is not possible to use an `ng-class` to define the directive. If you want to define the chart type dynamically, use `chart-base` as the `class` and use the `type` attribute. That has nothing to do with this library, just the way Angular works.

**Comment by dec** [comment]
Thanks @jtblin. Now I understand we can't use ng-class to define a directive and here we use the "class" attribute to define it. Thanks again and sorry if waste your time.

**Comment by ruwhan** [comment]
seems related with this one: https://github.com/angular/angular/issues/4276
