### ISSUE TITLE
Add custom properties to data object

### ISSUE THREAD

**Issue by philippecarle** [jtblin/angular-chart.js#166]
I cannot figure out how to handle custom data properties in the directive, as the only properties passed are labels and values. What if in an onclick event, i want to access a 'token' property to generate an url with it, or whatever ? 

It could easily be done through a angular.isObject(data) which could allow to pass an object like { value: 99, customProp: "yeah"}, using value property as value and extending data object with all other properties, instead of just 99 ?

**Comment by jtblin** [comment]
Looks like a limitation of the chart.js library. You can have a look at what is supported at http://www.chartjs.org/docs/.
