### ISSUE TITLE
How to highlight a segment and show the tooltip when hovering a legend item?

### ISSUE THREAD

**Issue by voodinator** [jtblin/angular-chart.js#168]
I want to be able to highlight the corresponding segment and also show the tooltip/label when i hover the different legend items with my mouse. At the moment iam trying to solve this problem in a very non-angular hacky way. This is what i got:

```js
$scope.$on('create', function (event, chart) 
{
    $scope.chartReference = chart;
});

$('.legenditem').hover(function () 
{
    highlightSegment($( this ).index());
});

var highlightSegment = function(index) 
{
    var activeSegment = $scope.chartReference.segments[index];
    activeSegment.save();
    activeSegment.fillColor = activeSegment.highlightColor;
    $scope.chartReference.showTooltip([activeSegment]);
    activeSegment.restore();
};
```

This works so far but it is missing the "mouseout" event since i dont know how i can reset the color and hide the tooltip (i only found the showTooltip() function). I also dont like my approach so i hope somebody can help me out with a cleaner solution

**Comment by jtblin** [comment]
Did you have a look at #70? It seems similar. Perhaps you could ask on StackOverflow, you may get more help than here. The issue tracker should be kept for reporting bugs only.
