### ISSUE TITLE
ChartJS won't draw graph inside bootstrap tab until window resize

### ISSUE THREAD

**Issue by djabif** [jtblin/angular-chart.js#17]
I'm using bootstrap's tabs with chartjs charts inside every tab.

One problem that have occurred though is that the graph canvas wont be drawn until i resize the browser window. And this is happening in both latest Chrome and Firefox.

I'm having exactly the same problem described here: http://stackoverflow.com/questions/26178399/chartjs-wont-draw-graph-inside-bootstrap-tab-until-window-resize

Thanks!

**Comment by jamesjomuad** [comment]
jQuery('[data-js-tabs]').on('shown.bs.tab', function (e) {
                try {
                    window.dispatchEvent(new Event('resize'));
                } catch(err) {
                    console.log(err);
                }
            })

**Comment by zqillini4** [comment]
I know this is like 3 years old at this point, but I just came across the same issue (so it's still present).  Here's the only way I was able to "fix" it:

`setTimeout(function() {
		myChart.update();
	},1000);`

After calling the "update" statement on the chart after a 1 second delay, the charts loaded every time.

**Comment by ControlX** [comment]
Thanks @zqillini4 For me setInterval(function() { chart_obj.update(); console.log("in function")}, 1000); worked out.

**Comment by janbae** [comment]
Thank you @zqillini4, faced this problem in 2020 and this helped me a lot!!

**Comment by akbarali2019** [comment]
> Thanks @zqillini4 For me setInterval(function() { chart_obj.update();}, 1000); worked out.

Exactly in which part of the code, we can write this function?
