### ISSUE TITLE
error: chartBar is non-assignable!

### ISSUE THREAD

**Issue by estvmachine** [jtblin/angular-chart.js#170]
I got this error: Expression '[ "#ff4040","#ff4040","#ff4040"]' used with directive 'chartBar' is non-assignable!

![image](https://cloud.githubusercontent.com/assets/2062668/9045738/a59139ee-39f3-11e5-8c48-7032832f5890.png)

**Comment by jtblin** [comment]
Can you post a jsbin with your code? There is a template in the readme.

**Comment by estvmachine** [comment]
Thanks for the response, here is my jsbin: http://jsbin.com/jaxiruxube/1/edit?html,js

Im think i resolve the issue, the problem was the order of the depedencies, now i have this way and works:

```html
'public/lib/Chart.js/Chart.js',
'public/lib/angular/angular.js',
'public/lib/angular-chart.js/dist/angular-chart.js',
```

**Comment by estvmachine** [comment]
Sorry man, for three months all was good but now this error its back, i ask why this happen?
