### ISSUE TITLE
Is there a way to show the hover/click tooltip initially?

### ISSUE THREAD

**Issue by johannesjo** [jtblin/angular-chart.js#171]
Sorry if that's not the right place to ask, but I'm really struggling with this.

**Comment by jtblin** [comment]
Not sure what you mean by initially, but the readme shows how to add an onclick or onhover event. For how the tooltip work, see http://www.chartjs.org/docs/. If you mean having the tooltip showing without hovering I don't think this is possible but if it is it would be in chart.js doc.

**Comment by martinza** [comment]
This may be something to this feature. In #1861 there were a few comments asking for this, and I'm very interested as well. 

In a nutshell, I'd like to be to show a tool tip for any given data point at any given point in time. So, let's assume a few cases, 1) on startup, you may want to initially show a tool tip like johannesjo requested. or 2) you may want to show a tool tip on a mouse click/event in a different part of the app. 

Right now, the ability to show that tool tip is buried within the onHover event, but not easily accessible for further customization.

**Comment by martinza** [comment]
chart.showTooltip([chart.segments[0]], true);

This appeared to be valid in previous versions, but not in current version.

**Comment by jtblin** [comment]
@martinza you're commenting in the wrong repo, you should do that in Chart.js repo ;)
