### ISSUE TITLE
Am looking to have a single horizontal bar ..if you could add that instead of a stacked multi chart that will be great

### ISSUE THREAD

**Issue by pendliforu** [jtblin/angular-chart.js#172]
i have added the image of the chart am looking for , if you can help me out that will be great

![capture1](https://cloud.githubusercontent.com/assets/8366546/9145094/a7e35db0-3d1f-11e5-8e7e-996719305247.PNG)

**Comment by jtblin** [comment]
As per readme, you should ask that on chart.js repo.
