### ISSUE TITLE
browserfy + angular-chart.js throwing 'WARNING: Tried to load angular more than once.'

### ISSUE THREAD

**Issue by duvet86** [jtblin/angular-chart.js#173]
I'm creating a simple app with gulp + browserfy + angular and chart.js.
When I add the require('angular-chart.js'); angular is throwing 'WARNING: Tried to load angular more than once.'

```
(function() {
  'use strict';

  require('chart.js');
  require('angular');
  require('angular-route');
  require('angular-resource');
  require('angular-chart.js');

  angular.module('chartApp', ['ngRoute', 'ngResource', 'chart.js']).config(...

}());
```

**Comment by jtblin** [comment]
Angular is required for CommonJS so you don't need to require it yourself.
