### ISSUE TITLE
Chart not working with a single serie of data

### ISSUE THREAD

**Issue by AGrzes** [jtblin/angular-chart.js#174]
I was trying to get simple chart working but I noticed it is possible only when I'm supplying array of data series. 

Working code pen
http://codepen.io/AGrzes/pen/YXgZrG
Not working code pen
http://codepen.io/AGrzes/pen/OVqpbg
The only difference is that in the first one data="[[1,2,2,3,6,5]]" and in the second one data="[1,2,2,3,6,5]"

I see there is code for handling single array of data
```javascript
var data = Array.isArray(scope.data[0]) ?
    getDataSets(scope.labels, scope.data, scope.series || [], scope.colours) :
    getData(scope.labels, scope.data, scope.colours);
```
But if option with getData is chosen then the chart is not rendered at all and there is an error because this.scale is undefined in Chart.js.

**Comment by jtblin** [comment]
Yes it's by design and documented.
