### ISSUE TITLE
Making angular-chart.js responsive with UI-Grid

### ISSUE THREAD

**Issue by GreenOn** [jtblin/angular-chart.js#175]
Hello: I am trying to make the chart responsive with UI-Grid data as explained in my question: http://stackoverflow.com/questions/31946109/making-angular-chartjs-responsive-with-ui-grid.
I think the problem is UI-grid data is in JSON format and the line chart needs multi-dimensional array format. Is there any way to use JSON format directly without pushing into an array to make it responsive with UI-Grid?

**Comment by GreenOn** [comment]
Figured it out! 
Refer to http://stackoverflow.com/questions/31946109/making-angular-chartjs-responsive-with-ui-grid.

**Comment by jtblin** [comment]
Sweet :)
