### ISSUE TITLE
using ng-class directive is not rendering the charts 

### ISSUE THREAD

**Issue by PavithraSivaraj** [jtblin/angular-chart.js#176]
I am using  ng-class directives for creating class names dynamically within a for loop. Like below:

canvas ng-class="{'chart-doughnut':'type=doughnut'}" data="data" labels="label" legend="true" ng-if="temp.type=='doughnut'"

The chart is not rendering and when i am using the class name directly it is working.

Is there anyway to mention the chart type dynamically here?

**Comment by jtblin** [comment]
`ng-class` does not work to create directives dynamically, this is an angular limitation. Look at http://jtblin.github.io/angular-chart.js/#base-chart to see how to create charts dynamically.

**Comment by JobaDiniz** [comment]
I was doing the same error for dynamic chart types, :+1:
