### ISSUE TITLE
Cannot make it working in $http.post

### ISSUE THREAD

**Issue by Alplob** [jtblin/angular-chart.js#178]
Hello, 

Thanks a lot for this project, this looks awesome! I am testing it and I cannot make it working in a $http.post function, even with static data (only the legend is displayed). However it works perfectly when with the same static data.

Example, the code below does not work:

	(function(){
		angular.module('homepage', ['chart.js'])
			.controller('HomepageController', ['$http', '$scope', function($http, $scope){
				$http.post('./ajax/_homepage_display.php').success(function(json){
					$scope.labels = ['Download Sales', 'In-Store Sales', 'Mail-Order Sales', 'Tele Sales', 'Corporate Sales'];
					$scope.data_chart = [300, 500, 100, 40, 120];
					$scope.type = 'PolarArea';
				});
		}]);
	})();

The code below works perfectly:

	(function(){
		angular.module('homepage', ['chart.js'])
			.controller('HomepageController', ['$http', '$scope', function($http, $scope){
				$scope.labels = ['Download Sales', 'In-Store Sales', 'Mail-Order Sales', 'Tele Sales', 'Corporate Sales'];
				$scope.data_chart = [300, 500, 100, 40, 120];
				$scope.type = 'PolarArea';				
				$http.post('./ajax/_homepage_display.php').success(function(json){

				});
		}]);
	})();

Remark: I also tested through a factory and obtained the same results

Could you please tell me if it is normal, and if yes, how to solve this?

Thanks!

**Comment by Alplob** [comment]
Actually it works well with the master but not with 0.7.3 downloaded from http://jtblin.github.io/angular-chart.js/. Sorry and thanks again for your plugin!

**Comment by jtblin** [comment]
No worries, in master that is a fix for when the canvas is created in a hidden div, see #29. `$http.post` was probably just a red herring, I'll be pushing a new version very soon.
