### ISSUE TITLE
Cannot resize bar chart

### ISSUE THREAD

**Issue by chrisjensen** [jtblin/angular-chart.js#179]
Hi,
I've been fiddling with this for a few hours now and can't figure out how to resize my bar chart.

When the container it's in grows, I'd like to resize it accordingly.

I've tried the height properties of the canvas, but something is setting them back.
I've tried destroying the underlying chart object, calling resize and calling render but none of those seem to prevent it from reverting to the first height it was rendered at.

I've created a jsbin here: http://jsbin.com/juwakecaya/1/edit?html,css,js,output

Would appreciate any help.

**Comment by jtblin** [comment]
Sorry for the lag. I don't see anything specific in your jsbin, looks like the template, did you send the wrong link forget to save? Ironically, if you resize the right pane with the chart, the chart does resize. 

There is already #118 opened on the same topic with a repro, I'll close this bug, please follow on the other one.
