### ISSUE TITLE
Updating chart labels

### ISSUE THREAD

**Issue by oroalej** [jtblin/angular-chart.js#18]
hello, i want to change the label of the chart using jquery.

i already did this

$.get('/report', function(data) {
  $timeout(function () {
    $scope.data = data;
    $scope.series = ['test', 'test2'];
  }, 200);
});

but it's not working..

**Comment by furqan93** [comment]
Its not working. Can you please hep. I have done the following
$http.get('myUrl', { params: { CompanyID: $scope.selectedCompany } })
        .success(function (response) {
            $scope.typeLabel = response.type;
            $scope.typeData = [response.data];
            $scope.$apply;
        });

data is coming in correct format i have already checked it

**Comment by jtblin** [comment]
Hard to help without a repro case, you may want to post to StackOverflow with more details.
