### ISSUE TITLE
How to set the color of clicked bar only?

### ISSUE THREAD

**Issue by hopewise** [jtblin/angular-chart.js#180]
I have this setup:

    <canvas colours="theChart.colours" click="theChart.click" width="1000" height="500" id="bar" class="chart chart-bar" data="data" labels="labels"></canvas>

in the click:

     $scope.theChart={
                    colours:['#FF0000', '#FF00FF', '#FFFFFF', '#FF0000', '#FF0000', '#FF0000', '#FF0000'],
                    click : function (bar, evt) {

                        var c= ['#FF0000', '#FF0000', '#FF0000', '#FF0000', '#FF0000', '#FF0000', '#FF0000'];
                        
                        // set clicked bar to black:
                        c[$scope.labels.indexOf(bar.label)]= "#000000";
                        
                        $scope.theChart.colours= c;

                    }
                }

But, what I get is that all the bars turn black, isn't it possible to set the color of clicked bar?

**Comment by jtblin** [comment]
You should check the http://www.chartjs.org/docs/ site for this kind of questions or ask on http://stackoverflow.com/. Please use the issue tracker to report issues only.
