### ISSUE TITLE
Expression in data=""

### ISSUE THREAD

**Issue by idlyapp** [jtblin/angular-chart.js#183]
Hi I have tried using an expression inside the data attribute like this

          <div ng-repeat="item in item">
            <canvas data="getTheData(item.value)"></canvas>
         </div>

and in the controller

    var getData = {
        first: function(){ return angularFactory.getData() };
        second: function(){ return angularFactory.getData() };
    }

    $scope.getTheData = function(value){
      getData[value]().then(function(data){
          console.log(data);
        });
    };

the problem is this is resulting in [$rootScope:infdig] with a log that never stops even though I just have one item in the "item" list.

I might have gone about this completely wrong, so I would highly appreciate any other suggestion
if there is any other way for me to fire of certain functions based on ng-repeat data.

**Comment by jtblin** [comment]
This question is better suited to StackOverflow. Please use the tracker to report bugs only. This doesn't even seem related to this library.

**Comment by idlyapp** [comment]
Isnt it? The loop is because the execution of the expression from the
library, i dont get this problem if i put the expression somewhere else..
Try it yourself

lördag 22 augusti 2015 skrev Jerome Touffe-Blin <notifications@github.com>:

**Comment by jtblin** [comment]
`<canvas data="getTheData(item.value)"></canvas>` is not even related to the directives in this library, seems more like a basic angular issue?

**Comment by idlyapp** [comment]
So to get the data using an expression, shouldnt be possible?

lördag 22 augusti 2015 skrev Jerome Touffe-Blin <notifications@github.com>:

**Comment by idlyapp** [comment]
Actually i pass the whole item in the expression if that is what you meant,
i just typed it out wrong

lördag 22 augusti 2015 skrev Stellan Haglund <sh@idly.se>:

**Comment by jtblin** [comment]
No I mean that there is not even a class to trigger the chart directives...

**Comment by idlyapp** [comment]
I didnt think i needed to show all the other parts in the example to prove
my point.. because those are not the problem and since the chart are
rendering its working but the chart is executing the expression all the
time.

<canvas id="line" class="chart chart-line" data="getTheData()" labels="labels"
    legend="true" series="series" click="onClick"></canvas>


Is it an issue now?


lördag 22 augusti 2015 skrev Jerome Touffe-Blin <notifications@github.com>:

**Comment by jtblin** [comment]
Not really. As I said above

> This question is better suited to StackOverflow. Please use the tracker to report bugs only.

I don't think what you try to do is possible, it's a basic angular question so I think you'll get more help from SO than here. 

>  I didnt think i needed to show all the other parts in the example to prove my point.. 

If you think it's a bug with the library, as per the readme provide with a jsbin to repro the issue. I don't have the bandwidth to provide help for all questions and issues people have using angular et al hence why I'm suggesting to ask on SO as I think it's just basic usage of angular directives. Not trying to be mean but you obviously didn't take the time to read the readme and I honestly don't have bandwidth to provide individual support to everyone.

**Comment by idlyapp** [comment]
I hear you I will post on SO, and just to let you know I've read the readme
over and over again, but in the readme there is nothing about a more
dynamic setup where I can load only the data needed for the charts the user
has active.

Here is a jsbin just to show you what I mean...
http://jsbin.com/zaxevevedi/edit?html,js,console,output



2015-08-24 11:46 GMT+02:00 Jerome Touffe-Blin <notifications@github.com>:
