### ISSUE TITLE
Create More <chart-legend> in ie 8

### ISSUE THREAD

**Issue by shenshaohui1991** [jtblin/angular-chart.js#188]
there are more than 1 chart-legend below the chart when it works in ie8

**Comment by mcanzerini** [comment]
+1 
--> I had to remove the chart's legend

**Comment by BabysbreathJJ** [comment]
@shenshaohui1991   The IE can't  show my chart in IE8, even though I have 
    <script src="bower_components/ExplorerCanvas/excanvas.js"></script>
    <script src="bower_components/es5-shim/es5-shim.min.js"></script>

and I  also specify the canvas' width and height, do you know why?

**Comment by BabysbreathJJ** [comment]
@shenshaohui1991   The IE can't  show my chart in IE8, even though I have 
    
and I  also specify the canvas' width and height, do you know why?

**Comment by BabysbreathJJ** [comment]
+1

**Comment by jtblin** [comment]
You may need to declare the new element for ie6. Closing as ie6 support is not a priority.
