### ISSUE TITLE
Opacity is not configurable

### ISSUE THREAD

**Issue by neilff** [jtblin/angular-chart.js#189]
I'm trying to create a line graph that has a filled opacity of 1, however I'm not seeing this as a configurable option. I've noticed the values are hard coded to `0.2`:

```
  function getColour (colour) {
    return {
      fillColor: rgba(colour, 0.2),
...
```

Is there a way to configure this value?

**Comment by jtblin** [comment]
You can pass the entire colour object instead so you can control exactly every aspects.
