### ISSUE TITLE
Chart Legend Colours do not show with Ionic

### ISSUE THREAD

**Issue by cgathergood** [jtblin/angular-chart.js#190]
When setting ```legend=true ``` on any chart with ionic, the chart labels show but the associated colour does not. 

It looks like the span containing the colour is set to 0x0 when it should be 20x20. 

Here's a codepen of the issue: http://codepen.io/VeldMuijz/pen/RPRaQb
add legend=true to line 25 to reproduce.

Apologies if this is an issue with Ionic instead of Angular-Chart. Thanks!

**Comment by jtblin** [comment]
@cgathergood, it doesn't look like it's an issue with angular-chart.js, you can see example of the legend colours showing up here: http://jtblin.github.io/angular-chart.js/. Sorry but you'll have to ask some ionic experts or on SO.

**Comment by srend42** [comment]
Ensure that you are importing `angular-chart.css`/`angular-chart.min.css` file in your `index.html` - fixed it for me
