### ISSUE TITLE
请问chart支持滚动条吗？

### ISSUE THREAD

**Issue by coolara** [jtblin/angular-chart.js#192]
如果横轴数据多了。显示不下 支持横向滚动吗？

**Comment by jtblin** [comment]
Sorry I don't speak Chinese, you'll have to ask in English, maybe look at http://stackoverflow.com/.

**Comment by coolara** [comment]
How to set the width of chart?

**Comment by jtblin** [comment]
Well `width` but that's basic html stuff, please google it and use stackoverflow.
