### ISSUE TITLE
CDN: Add non-minified CSS and name the CSS files properly

### ISSUE THREAD

**Issue by sanketsaurav** [jtblin/angular-chart.js#193]
The latest version v0.8.1 lacks a non-minified version of the CSS file on the CDN. Also, `angular-chart.css` is actually minified. This leads to confusion.

**Comment by jtblin** [comment]
Waiting on https://github.com/jsdelivr/jsdelivr/pull/6726.

**Comment by jtblin** [comment]
Done.
