### ISSUE TITLE
Line chart - Start line from a non-zero point on X-axis

### ISSUE THREAD

**Issue by nvme978** [jtblin/angular-chart.js#196]
I'm trying to create a multi-line chart. X-axis has dates and Y-axis is percentage. 
I want to show today's percentage as a point on the chart and a line for the previous 6 days. 

The problem is that the 2nd line (chart point for today) is rendered at the beginning of X-axis. I want it to be rendered at the end. 

![screen shot 2015-09-01 at 12 01 29 pm](https://cloud.githubusercontent.com/assets/13456525/9597674/c9841258-50a1-11e5-9bda-b2013027e163.png)

Activation percent for today should be rendered on 01-Sep.

**Comment by jtblin** [comment]
Well without code to repro, I don't know you think anyone can really help you ;) Anyhow it seems more like a generic chart.js question so I'd advise you ask it on stackoverflow where more people can help you.
