### ISSUE TITLE
Is it possible to skip labels in a line chart if i have a large amount of data (>500 values) ?

### ISSUE THREAD

**Issue by Gaikan** [jtblin/angular-chart.js#201]
I have over 500 data points to show in a line chart. But there is not enought space to show a label for each data point. The labels are sorted dates or numbers and I need a option that defines to show only each 2nd, 3rd, ... label on the x-axis. But for each data point the tooltip should show the correct and full label and value.

**Comment by jantimon** [comment]
Afaik this is not possible - however this is probably not an issue which angular-chart.js can solve.
Please open an issue for the underlying Chart.js module: https://github.com/nnnick/Chart.js
