### ISSUE TITLE
Question : how to disable transition on data update

### ISSUE THREAD

**Issue by hugsbrugs** [jtblin/angular-chart.js#203]
Hello and thank you for this great portability of charts.js !

I'm wondering if there is any options I could play with to disable transition when updating my data collection. I agree this is nice to have thoses transitions by default but in my use case this is an inconvenient ...

thanks for you suggestions

Hugo

**Comment by jtblin** [comment]
I think you'd want to use `animation: false` in the `chart-options` attribute.

**Comment by hugsbrugs** [comment]
Thanks jtblin !

I've tried : 
```javascript
chart-options="{animation:false}"
chart-options="animation:false"
```

But didn't work, works without "chart-" prefix which is strange because it is recommended to add it ...
This works :
```javascript
options="{animation:false}"
```

**Comment by jtblin** [comment]
`chart-options` works for me with the same.
