### ISSUE TITLE
Using JSPM to load angular-chart.js.

### ISSUE THREAD

**Issue by gillyd12** [jtblin/angular-chart.js#204]
I used the NPM registry:

jspm install npm:angular-chart.js

and when attempting to import angular-charts.js:

import chart from 'angular-chart.js';

I get the following:

WARNING: Tried to load angular more than once.

At this point I am not sure if JSPM is resolving the dependencies correctly - will look at other options.  Anyone else having issues trying to use JSPM for angular-chart?

**Comment by gillyd12** [comment]
OK I have loaded both chart.js and angular-chart.js by using jspm install angular-chart=github:jtblin/angular-chart.js and jspm install chart.

I am no longer getting the Warning: tried to load angular more than once.

**Comment by circlingthesun** [comment]
It appears that if you install something from npm, all it's dependencies will be fetched from npm despite it already being installed from github. Angular-chart.js lists angular as a dependency in package.json. This basically forces you to install it from github or find yourself loading angular twice. I've been bitten in the ass by this several times. Surely there dependencies in package.json should first be resolved from existing sources?

**Comment by jtblin** [comment]
This sounds like an issue with JSPM, not this library. No need for this kind of language here, please go vent your frustration somewhere else.

**Comment by circlingthesun** [comment]
I was under the impression that I was in the JSPM bugtracker. Apologies.
