### ISSUE TITLE
Chart is not redrawn when data is empty.

### ISSUE THREAD

**Issue by Yogeshk25** [jtblin/angular-chart.js#205]
chart is not redrawn when we change scope variable let's say
$scope.data = [[1,2,3]]
to
$scope.data = [[]] 

but is redrawn when we change to
$scope.data = [[1,4,6]] 
or
$scope.data = [[1,5,3,6,7]]

does anyone else is also facing this issue?

**Comment by kowsheek** [comment]
Yup, experiencing this issue. I've tried to force a redraw but no luck.

**Comment by jtblin** [comment]
You need to pass `null` or `0` values to "redraw" the chart in this case. chart.js doesn't know how to draw a chart if there are no values.
