### ISSUE TITLE
Legend template not working

### ISSUE THREAD

**Issue by igorissen** [jtblin/angular-chart.js#210]
Hi,

I try to set a legend template to my line chart without success.
Any idea how to set a legend template ?

This is the option that I use for my line chart :

```js
var options = {
    bezierCurve: false,
    datasetFill: false,
    scaleGridLineColor: "#3E434E",
    legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
}
```

Thanks.

**EDIT**:

I also add a listener for the `create` event on the scope to check if the legend template is correctly set.

```js
/* @ngInject */
function Controller($rootScope, $scope, logger, request) {
    var vm = this;
    ...
    ...
    $scope.$on("create", function (event, chart) {
        console.log(chart);
        console.log(chart.generateLegend());
    });
}
```

In the output I can find the legendTemplate in chart options but when I generate the legend HTML I don't have the correct HTML (always your template).

Is this a bug that the option property legendTemplate isn't working ?

**Comment by igorissen** [comment]
Ok my bad.

Didn't notice that you use the same template but you had style to it.

Sorry about that and thank you for your work!

**Comment by jtblin** [comment]
No worries. You shouldn't need to style it if you add the css as well, see the readme.

**Comment by zymr-keshav** [comment]
Kindly provide the proper example for this. I am unable to produce the template as it always add 
`<span  style="background-color:#A2D9CE,#A2D9CE,#A2D9CE,#A2D9CE,#A2D9CE,#A2D9CE">`

**Comment by jtblin** [comment]
@zymr-keshav this is outdated, the new version of this lib does not handle the legend anymore, you can set chart.js one directly, see their docs for information.
