### ISSUE TITLE
possible to create bar chart with one set and multiple colours

### ISSUE THREAD

**Issue by mattiLeBlanc** [jtblin/angular-chart.js#211]
Hi,

I was wondering if it is possible to create a bar chart with multiple colours, but only one dataset.
Something like in this question:
http://stackoverflow.com/questions/29999963/how-can-i-set-different-colours-for-each-bar-in-angular-chart-js

In this package I am not sure if I can extend the Bar chart?

**Comment by jtblin** [comment]
No, it isn't. You'd have to modify the source of [chart.js](github.com/nnnick/Chart.js) library.

**Comment by jtblin** [comment]
Have a look at the [stacked bar example](http://jtblin.github.io/angular-chart.js/examples/stacked-bars.html) ([code](https://github.com/jtblin/angular-chart.js/blob/master/examples/stacked-bars.html)), maybe you can have 7 datasets, one per day per colour.

**Comment by mattiLeBlanc** [comment]
is it desirable to change the source of a package like chart.js? Or do you mean extending in the case.
I think I read that some peeps actually altered the source of chartjs. Something I wouldn't do unless I fork it and ask for a merge.

**Comment by jtblin** [comment]
No I don't think it's a good practice, but that's how it was solved in the SO question. Otherwise you can try the stacked bar suggestion maybe.

**Comment by mattiLeBlanc** [comment]
I will have a play with ChartJS. There might be a way to legally extend a chart type and add in the changes in a non destructive way. Thanks for your response!
