### ISSUE TITLE
Multiple values shown on hover chart

### ISSUE THREAD

**Issue by gerbsen** [jtblin/angular-chart.js#212]
hey, maybe i'm doing something wrong, or is this how it should be? 

![screenshot 2015-09-18 15 18 56](https://cloud.githubusercontent.com/assets/1186245/9960081/c22d8c30-5e18-11e5-9e68-b9d1782a1413.png)

**Comment by jtblin** [comment]
Repro?

**Comment by praveendath92** [comment]
@jtblin I have a similar issue too. Especially on mobile devices. For repro, you may try [this][1] on mobile phones or super zooming on browser.

[1]: https://coursestats.de/#/course/1

**Comment by jtblin** [comment]
@praveendath92 how do you hover on a mobile device?

**Comment by praveendath92** [comment]
Clicking on the points on curve. Hmm, that's a different callback but you see the bug. Alternatively, if you would like to see it on desktop with hover, you could try a smaller canvas for the graph - zooming in on that link should do the trick.

**Comment by stefanlorenz85** [comment]
+1, same issue here

http://jsbin.com/yetodol/edit?html,js,output

**Comment by xtingray** [comment]
Stefan, I edited your example and I could display an accurate graphic:
```javascript
var app = angular.module("jsbin", ["chart.js"]);
app.controller("ChartCtrl", ['$scope', function ($scope) {
   $scope.labels = ["01", "02","03"];
  $scope.series = ["A", "B"];
    $scope.data = [
      [65, 59, 80], [10, 20, 30]
    ];
    $scope.onClick = function (points, evt) {
      console.log(points, evt);
    };
}]);
```
I noticed two things:
1. If you define two series, you must include 2 arrays inside the data array.
2. You can't use too much data if your canvas is too small

**Comment by stefanlorenz85** [comment]
solved by setting the detection radius in the chart.js options:

js:
```
$scope.options = {
      pointHitDetectionRadius : 0.1, //amount extra to add to the radius to cater for hit detection outside the drawn point
};
```

html:
```
<canvas id="line" class="chart chart-line" data="data" labels="labels" legend="true" chart-options="options" click="onClick" series="series"></canvas>
```

http://jsbin.com/wevaro/edit?html,js

**Comment by jtblin** [comment]
Thanks for following up @stefanlorenz85
