### ISSUE TITLE
Unable to display 2d Array

### ISSUE THREAD

**Issue by hasbulhadi** [jtblin/angular-chart.js#213]
HTML
![image](https://cloud.githubusercontent.com/assets/14356473/9974525/b1fdbda0-5ec5-11e5-80b0-2fa3356f47c3.png)

Controller

![image](https://cloud.githubusercontent.com/assets/14356473/9974530/0320736c-5ec6-11e5-8dad-402a56c11756.png)

It wont display anything. It shows Typeface error: Line is undefined.

After i changed the html into this
![image](https://cloud.githubusercontent.com/assets/14356473/9974544/49c502ba-5ec6-11e5-8a18-79b7e7f0a965.png)

Now it show all the data. Is it possible to show just one of the array per chart

![image](https://cloud.githubusercontent.com/assets/14356473/9974554/be48d5b2-5ec6-11e5-9428-7ce463504829.png)

**Comment by jtblin** [comment]
Yes, just set only one series i.e. only set `data[0]`. This kind of question is better for stackoverflow.com.
