### ISSUE TITLE
Colours polar chart

### ISSUE THREAD

**Issue by cskiwi** [jtblin/angular-chart.js#215]
hi,

I can't seem to set the colours of the polar-area chart, the other charts work just fine:

example plnkr: http://plnkr.co/edit/CH4z9UyBkvv8G9UpGg4j?p=preview

**Comment by jtblin** [comment]
You need to use hex code for colours not colour names, and either pass them as strings e.g. `"F7464A"` or as full objects e.g.
```
    { // red
      fillColor: "rgba(247,70,74,0.2)",
      strokeColor: "rgba(247,70,74,1)",
      pointColor: "rgba(247,70,74,1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(247,70,74,0.8)"
    }
```
