### ISSUE TITLE
Dynamic chart type seems  to be broken with bar,line

### ISSUE THREAD

**Issue by ravitez** [jtblin/angular-chart.js#216]
Dynamic chart type doesn't seem  to be working with bar,line..throws `TypeError: (intermediate value)[type] is not a function` Or Am I missing anything ?
Here's the fiddle 
https://jsfiddle.net/ravitej/4Lzc2cr7/

**Comment by mikedevita** [comment]
seems to be broken for doughnut too :(

http://plnkr.co/edit/hdjO6CFY6aHmqR4dXICY?p=preview

**Comment by danwellman** [comment]
+1 any news on this? Seeing the same issue in an ng-repeat

**Comment by mikedevita** [comment]
I think this boiled down to a data issue for me.

**Comment by danwellman** [comment]
I'm pretty sure it's not data, I'll post some actual code later, but by changing the class from chart-base to chart-doughnut, and moving it out of the ng-repeat, the chart worked as expected

**Comment by mikedevita** [comment]
Ah yes you are corrrect. I was mistaken.

**Comment by danwellman** [comment]
After some testing, I find this works and produces the desired graph:

`<div class="chart" ng-repeat="chart in charts">
     <canvas id="charts[$index].type" 
                   class="chart chart-doughnut" 
                   chart-data="charts[$index].data" 
                   chart-labels="charts[$index].labels">
    </canvas>
</div>`

But this *doesn't* work:

`<div class="chart" ng-repeat="chart in charts">
    <canvas id="charts[$index].type" 
                  class="chart chart-base" 
                  chart-type="charts[$index].type"
                  chart-data="charts[$index].data"
                  chart-labels="charts[$index].labels">
    </canvas>
</div>`

The latter snippet results in the following console error:

> TypeError: (intermediate value)[type] is not a function

**Comment by draconteus** [comment]
Got the same error message.
I figured out, that the types stat with capital letters and it worked after that.

**Comment by danwellman** [comment]
Great, thanks for the  info!

**Comment by jtblin** [comment]
As @draconteus said, the chart type is case sensitive.

**Comment by brunoserralheiro** [comment]
Still does not seem to fix with capital letter.

**Comment by dnadrshin** [comment]
use https://github.com/gor181/react-chartjs-2 for chart v2.0
