### ISSUE TITLE
StackedBar chart not updating when data has the same number of elements, but different values. 

### ISSUE THREAD

**Issue by jjbskir** [jtblin/angular-chart.js#219]
Hey, the StackedBar chart is not updating when the data has the same number of elements, but different values. I made a jsfiddle example - http://jsfiddle.net/jd9mborr/1/

Let me know if there is any other way I can help!

**Comment by jtblin** [comment]
Thanks for the repro case, I stepped in the code and the data is updated correctly for stacked bar charts on my side, and `chart.update()` is called properly but the chart doesn't update. So it seems it's an issue with the stacked bar char lib, relevant issue is https://github.com/Regaddi/Chart.StackedBar.js/issues/43. Please follow-up with upstream directly.

**Comment by jjbskir** [comment]
Ok awesome, I will follow up there. In case any one needs a quick fix I was able to manually update the Chart.js object and then call update() on it. http://jsfiddle.net/918sr5yw/1/
