### ISSUE TITLE
Is it possible to use angular-charts with Chart.Scatter.js?

### ISSUE THREAD

**Issue by tonylampada** [jtblin/angular-chart.js#221]
[Chart.Scatter.js](http://dima117.github.io/Chart.Scatter/) is a plugin for ChartJS that allows drawing Scatter graphs, that is, line graphs with arbitrary X values.

Is it possible the use that without modifying angular-charts? 

If you could provide an example that would be super. Thanks! :-)

**Comment by jtblin** [comment]
There is an example for [stacked bar](https://github.com/jtblin/angular-chart.js/blob/master/examples/stacked-bars.html). I guess it would be similar for scatter chart.

**Comment by axeMaltesse** [comment]
Sorry, but I could not understand solution that you have provided above. 
I am using angular and chart.js to get data from JSON object and display it on charts. My problem is that I don't know how can I match the month and xAxis month. 
Is it possible to display a full year on the xAxis and assign values from JSON somehow?

**Comment by uazure** [comment]
Answer is unclear and not helpful. So is it possible to use scatter plot?
