### ISSUE TITLE
How can I show y axis labels in bar chart

### ISSUE THREAD

**Issue by ashishkhanna** [jtblin/angular-chart.js#223]
How can I show y axis labels in bar chart

**Comment by jtblin** [comment]
Check www.chartjs.org/docs/

**Comment by mcakar1993** [comment]
Use google chart or
Use css text rotate to execute this

**Comment by MaxChamps** [comment]
The correct link for the Y axis labelling: http://www.chartjs.org/docs/latest/axes/labelling.html
