### ISSUE TITLE
Negative values on Bar chart

### ISSUE THREAD

**Issue by pantera160** [jtblin/angular-chart.js#225]
When you enter negative values into the Bar chart these values are not shown nicely.
I know this feature was not included in Chart.js v1.0 on which angular-chart.js is based but since this should be included in Chart.js v2.0 I was wondering if anyone might have gotten a fix for this.

Simply using chart.js v2.0 instead of v1.0 does sadly not work (for me anyway).

Thanks in advance!

**Comment by jtblin** [comment]
You can follow #123 for chart 2.0. It's still in alpha so probably a while before I can port this library to use 2.0.

**Comment by KeweiCodes** [comment]
Hey @pantera160 , it seems that there is a way this could work with chartv1.0.2 as shown here: https://jsfiddle.net/ahrex/jy8nnaem/ But I'm still having trouble getting this to work with angular-chart :disappointed:

**Comment by davidsheart02** [comment]
The chart version bundled with angular chart doesn't include the barbeginatorigin property. That's why it works in the fiddle but not with angular-chart. Even though they both are labelled as chartv1.0.2 the property is missing from angular-chart.

**Comment by jtblin** [comment]
That's weird, it should pick up 1.0.2 if you install with bower or npm.

**Comment by davidsheart02** [comment]
The chart.js used by the fiddle appears to be a specific pull from a specific commit. The conversation here mentions a pull request that I believe contains the extra property: https://github.com/nnnick/Chart.js/issues/9

I think angular-chart.js is doing the picking up the right version according to the bower specs and the one in the fiddle is using a chartv1.0.2 with the special property added. Looking at the git repo for Chart.js, the barbeginatorigin property doesn't exist in the current master branch nor in the chart.js under the v1.0.2 tag.
