### ISSUE TITLE
not able to show vertical legend and in pie chart

### ISSUE THREAD

**Issue by anupcs0017** [jtblin/angular-chart.js#227]
not able to show vertical legend and in pie chart

**Comment by AJ1985** [comment]
Hi @jtblin , 

is it possible to show vertical legend in pie chart?

**Comment by greatromul** [comment]
Hello, @AJ1985 !
Did you try right or left position for legend?

```
ctrl.options = {
	legend: {
		display: true,
		position: 'right'
	},
};
```
This settings force directive to draw vertical legend to the right of pie.
