### ISSUE TITLE
Tooltip formatting not working with one series!

### ISSUE THREAD

**Issue by gslezynger** [jtblin/angular-chart.js#231]
Hy there, 

When working with the chart I noticed that the tooltip formatting works for graphs with more than one series: 

<img width="300" alt="screen shot 2015-10-21 at 6 41 38 pm" src="https://cloud.githubusercontent.com/assets/8821314/10649535/6c0e09ae-7823-11e5-8fe9-1920440b8db5.png">

But does not work with one series charts: 

<img width="295" alt="screen shot 2015-10-21 at 6 42 51 pm" src="https://cloud.githubusercontent.com/assets/8821314/10649574/91efa9e8-7823-11e5-81d0-588184a66a14.png">

Hope you can help!

Thanks ,

**Comment by jtblin** [comment]
That would be an issue with Chart.js, please check in their repo / tracker: https://github.com/nnnick/Chart.js
