### ISSUE TITLE
require('Chart.js') fails in case-sensitive file systems

### ISSUE THREAD

**Issue by toostn** [jtblin/angular-chart.js#235]
In commit a72a515335c276d0f0e83056d8a9a172b77f9af3, the chart.js depedency has been changed to use uppercase C.

`angular-chart.js:5
module.exports = factory(require('angular'), require('Chart.js'));`

However, the module name for chart.js uses a lowercase c.

This change makes compilation fail when imported via e.g. browserify on case-sensitive file systems. 

Maybe you've mistaken the module name for the actual .js file it exports?

**Comment by LuckY1** [comment]
I don't know if it's related but I'm trying to import angular-chart.js with jspm:

import chart from "chart";
import ngChart from "angular-chart.js";

which fails with: GET http://localhost:8080/Chart.js 403 (Forbidden)

**Comment by jtblin** [comment]
@toostn the change was made by @soladk because it was apparently needed for bower. See https://github.com/jtblin/angular-chart.js/pull/226 for explanation. I will add a `try/catch` block and try each spelling...
