### ISSUE TITLE
How do I change the chart values using an array of objects.

### ISSUE THREAD

**Issue by hespada** [jtblin/angular-chart.js#238]
Hi,

Every time I change the chart values gives me this error: "uncaught TypeError: Cannot read property 'draw' of undefined".

I have an initial array that everything works fine. But when I change the values in my select always gives me error.

Can someone help me?

Thanks

My controller:

  $scope.labels = ["January", "February", "March", "April", "May", "June", "July", "August",     "September", "October", "November", "December"];

  $scope.test = [
        {
            id: 1,
            label: 'test 1',
            data: [[62, 12, 77, 88, 42, 51, 12, 45, 23, 57, 11, 22]]
            },
        {
            id: 2,
            label: 'test 2',
            data: [[65, 59, 80, 81, 56, 55, 40, 32, 30, 25, 15, 5]]
            },
        {
            id: 3,
            label: 'test 3',
            data: [[23, 15, 42, 24, 94, 19, 67, 82, 54, 76, 5, 55]]
            }
];

  $scope.selectedOption = [[62, 12, 77, 88, 42, 51, 12, 45, 23, 57, 11, 22]];

And my HTML:

    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-6 col-md-12 col-xs-12 margin-top-md-10 margin-top-xs-10">
                <div class="apps-title-h1">TEST</div>
            </div>
            <div class="col-lg-6 col-md-12 col-xs-12 margin-top-md-10 margin-top-xs-10">
                <div class="form-group">
                    <select class="form-control" ng-model="selectedOption">
                        <option ng-repeat="option in test" value="{{option.data}}">{{option.label}}</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-xs-12 margin-top-40 margin-bottom-40">
            <canvas id="line" class="chart chart-line" chart-data="selectedOption" chart-labels="labels" chart-legend="false">
            </canvas>
        </div>
    </div>

**Comment by jtblin** [comment]
It looks ok to me, I'm not sure... This kind of question is best suited for stackoverflow.
