### ISSUE TITLE
Simple doughnut chart example

### ISSUE THREAD

**Issue by lewma** [jtblin/angular-chart.js#239]
Hello

Does anyone have a simple doughnut chart example ?  I've tried many ways to get a doughnut to display but nothing ever shows.  line and bar charts are fine, just the doughnut does not display.  If someone can point me to an example I'm sure I can figure it out.

thanks!

**Comment by jtblin** [comment]
http://jtblin.github.io/angular-chart.js/#doughnut-chart

**Comment by lewma** [comment]
Sorry, I mean't to say I was using AngularJS.  Got some of those examples ?
