### ISSUE TITLE
View blows up if the canvas is used with ng-repeat

### ISSUE THREAD

**Issue by SarasArya** [jtblin/angular-chart.js#241]
The scenario is similar to many issue but not exactly the same. There is a question asked by me on StackOverflow you can see that [here](http://stackoverflow.com/questions/33642163/how-to-destroy-and-recreate-canvas-in-angularjs). 
The problem is with using canvas to load chart and ng-repeat. ng-repeat I believe recretes the chart on the canvas without destroying it. How would I destroy the canvas while using chart.js . One solution provided was to use windows.location.reload() But I wouldn't recommend doing that as in Angular you create a single page apps and with a reload the whole page reloads which essentially leads to loss of data.

**Comment by jtblin** [comment]
Your question is for another library "tc-chartjs-bar".
