### ISSUE TITLE
Chart legend does not get updated

### ISSUE THREAD

**Issue by codyrigney92** [jtblin/angular-chart.js#243]
Upon removing/adding series, the legend does not update.  I am currently working around it like so:

First include $element in the controller that's on the chart
```
$scope.$on('create', function(event, chart) {
    var oldLegend = $element.find('chart-legend');
    var newLegend = '<chart-legend>' + chart.generateLegend() + '</chart-legend>';
    if(oldLegend.length) {
        oldLegend.replaceWith(newLegend);
    }
});
```

**Comment by jtblin** [comment]
This jsbin shows example of legend being updated when adding series: http://jsbin.com/voguni/2/edit?html,js,output.

Please provide a repro case.

**Comment by codyrigney92** [comment]
Thanks for the template.  Here is the repro case: http://jsbin.com/pumeniyaqi/edit?html,js,output
