### ISSUE TITLE
JSON usage

### ISSUE THREAD

**Issue by ahsanbagwan** [jtblin/angular-chart.js#244]
This is a question and not an issue. How do I use this in case of JSON data? 

I have my structure like:

{data:[["2015-05-31",5.7377049180328],["2015-04-30",5.7851239669421],["2015-03-31",6.2761506276151]]} with thousand of such entries.

How do I figure out how to set labels. Is it manual? I'm really confused.

**Comment by zurez** [comment]
create two arrays . label and data 
push data[i][0] to label, and data[i][1] to data 
then do 
$scope.data = data;
$scope.labels= label;

**Comment by jtblin** [comment]
As @zurez said, you can use `map` to easily create new arrays from an existing array.
