### ISSUE TITLE
Line Chart get cut off

### ISSUE THREAD

**Issue by littleFF** [jtblin/angular-chart.js#247]
The problem is when i create a new line chart, sometimes the line chart is slightly cut off. Anybody has idea?
![download](https://cloud.githubusercontent.com/assets/1897878/11295952/f5088caa-8fa9-11e5-9b91-2fe7aab6f9f2.png)

**Comment by Batleth** [comment]
This problem occurs also in the original chart.js library.
There is a workaround by adding a space in front of the y-axis scale.
https://github.com/nnnick/Chart.js/issues/729

**Comment by littleFF** [comment]
Thanks a lot.
