### ISSUE TITLE
Legends do not update

### ISSUE THREAD

**Issue by jonathansampson** [jtblin/angular-chart.js#25]
It appears as though the legend is not being updated along with the rest of the data. Not much code needed to repro the issue; setup a basic chart:

```html
<canvas class="chart chart-doughnut" data="points" labels="labels" legend="true"></canvas>
```

After a short delay, change the labels as well as the data. Legend is not updated.

I'm seeing this issue in both Chrome and Internet Explorer, so it doesn't appear to be browser-related.

**Comment by jtblin** [comment]
Done, I had to watch the labels as well and destroy and re-create the chart on change.
