### ISSUE TITLE
Show percentage in pie chart 

### ISSUE THREAD

**Issue by mkelley82** [jtblin/angular-chart.js#256]
I can't seem to figure out how to display a percentage used.... I only want to display one value as a percentage. So for example, if i had a data value of 75 (or say .75) i would want it to fill 75% of the pie chart.  How can I do this with the pie chart?

**Comment by mkelley82** [comment]
Ok I figured out how to do this... it wasn't super intuitive but maybe that's because I'm dumb =] ...


    var item = { Balance: 50, Total: 200 }
    var chartdata =
     {
        data: [{
            x: "Remaining",
            y: [(item.Balance / item.Total) * 100], // this will be 25
            tooltip: '% Remaining'                        
        },
        {
            x: "Used",
            y: [(1 - (item.Balance / item.Total)) * 100], //  this will be 75
            tooltip: '% Used'
        }]
    };

**Comment by malikperang** [comment]
Hi are there any demo?
