### ISSUE TITLE
ReferenceError: Can't find variable: Chart

### ISSUE THREAD

**Issue by rbarman** [jtblin/angular-chart.js#257]
According to the README, the cdn for dependencies are :

`//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js
//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css`

I have the following in the index.html of my angular app :
`<link href ="//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css">`
` <script src = "//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js"> </script>`

However when I load my app, I get the error : 
`angular-chart.min.js:11ReferenceError: Can't find variable: Chart`

Am I incorrectly getting the dependencies?

**Comment by rbarman** [comment]
I needed to also include Chart.js
     `<link href ="//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css">`
` <script src ="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" </script>`
`<script src = "//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js"> </script>`

**Comment by slchorne** [comment]
You need to seriously update the docs on http://jtblin.github.io/angular-chart.js/ to reflect this

**Comment by jtblin** [comment]
The dependencies are indicated at the top of this page, feel free to send a
PR to improve the example, it's in `examples/charts.template.html` in
`master` branch.
