### ISSUE TITLE
Different options for every line?

### ISSUE THREAD

**Issue by ignaciohita** [jtblin/angular-chart.js#260]
Hello,

I want to use this cool feature of Chart.js that specifies different visualization options for every line in a chart.

![picture 2015-12-03 10_46_13](https://cloud.githubusercontent.com/assets/11271674/11557085/17d2946e-99ab-11e5-9e52-870dffe089ae.png)

For example, I want to have a line with no dots but I want to display dots in the other, can this be possible using angular-chart? I can't find an example of this, all of them are using chart-data with simple arrays and options for all the chart and all the lines.

Thanks!

**Comment by purpleferret** [comment]
Maybe my comment from another issue https://github.com/jtblin/angular-chart.js/issues/258#issuecomment-161558898 can help you.
There I'm using the option to set Chart.js specific options.

**Comment by ignaciohita** [comment]
Hi Pulpleferret,

Thanks for your reply, but I can't see how can I do what I want with that, I want to change options for one serie inside the chart, and what you say in your comment is to specify options for the whole chart, is not that?

**Comment by jtblin** [comment]
What's the difference between the 2 datasets in your example? I can only
see different colours which can be done.

**Comment by ignaciohita** [comment]
Sorry, actually I didn't explain myself properly, I understand is possible to define different colors, series, options and labels, but what I want to do is to set different property inside one Line. For example, I want to have pointed dots in one Line but not in the other. This should be done this way in pure Chart.js:

```javascript
var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            pointDot: false,
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [65, 59, 80, 81, 56, 55, 40]
        },
        {
            pointDot: true,
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};

var myLineChart = new Chart(ctx).Line(data, options);
```

But I have no idea how to do it with angular-chart.js, according to what you say should be something like this:

    ChartJsProvider.setOptions('Line', {
        options: [{
            pointDot: false
        }, {
            pointDot: true
        }]
    });

Or this:

    ChartJsProvider.setOptions('Line', {
        pointDot: [false, true]
    });

But it's not working, I can do this:

    ChartJsProvider.setOptions('Line', {
        pointDot: false
    });

But is removing the pointed dots for both lines, and I want pointed dots in one and not in the other.

Thanks for your help!

**Comment by jtblin** [comment]
I see. No sorry it's unfortunately not possible at this time.

**Comment by jtblin** [comment]
See options available in Chart.js 2.0: https://github.com/nnnick/Chart.js/blob/v2.0-dev/docs/02-Line-Chart.md. All the options available there should work with the next version of angular-chart, see [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0).
