### ISSUE TITLE
Uncaught TypeError: Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by shyamg91** [jtblin/angular-chart.js#264]
I'm trying to replicate the example graphs shown on the website.
    $scope.data = [[154, 31, 17, 4, 1]];
    $scope.labels = ["A", "B", "C", "D", "E"];

    <canvas id="line" class="chart chart-line" chart-data="data" chart-labels="labels" chart-click="onClick">
      </canvas>

I'm using chart.js 1.0.2 version. I keep hitting this error. What am i doing wrong?

**Comment by jtblin** [comment]
Not sure but same works on the demo page so there must be something else. Try posting on stackoverflow.com with a complete [repro case](http://jsbin.com/dufibi/3/edit?html,js,output) maybe.

**Comment by shyamg91** [comment]
http://jsfiddle.net/HB7LU/20813/

This is a fiddle which shows it doesn't draw. I've done this before, i have no idea why it isn't working.

**Comment by jtblin** [comment]
Ok, obviously not an issue with the library, good luck with troubleshooting.

**Comment by shyamg91** [comment]
Sorry about that ! Thanks .
