### ISSUE TITLE
Chart floating outside container

### ISSUE THREAD

**Issue by stibay** [jtblin/angular-chart.js#265]
Graph container is not respecting the padding from parent div. As you can see from the screenshot this graph is beeing viewed inside a simple boostrap collapse panel http://getbootstrap.com/javascript/#collapse

See screenshots.
http://imgur.com/a/WnfcE

**Comment by jtblin** [comment]
Not sure what you mean, there is no specific style applied to the container.

**Comment by stibay** [comment]
Tried to illustrate it better here: http://imgur.com/4QVArk0
Seems like it was the margin: 20px 5px 10px 10px style on the canvas that was causing it. Just added margin: 0px to it and it looks good.

**Comment by jtblin** [comment]
Glad you found the issue, this library doesn't add any styling to the container nor the canvas, there are only optional styles for the legend, here's the entire style (`less`) as of today:

```
.chart-legend, .bar-legend, .line-legend, .pie-legend, .radar-legend, .polararea-legend, .doughnut-legend {
  list-style-type: none;
  margin-top: 5px;
  text-align: center;
  /* NOTE: Browsers automatically add 40px of padding-left to all lists, so we should offset that, otherwise the legend is off-center */
  -webkit-padding-start:0; /* Webkit */
  -moz-padding-start:0; /* Mozilla */
  padding-left:0; /* IE (handles all cases, really, but we should also include the vendor-specific properties just to be safe) */

  li {
    display: inline-block;
    white-space: nowrap;
    position: relative;
    margin-bottom: 4px;
    border-radius: 5px;
    padding: 2px 8px 2px 28px;
    font-size: smaller;
    cursor: default;

    span {
      display: block;
      position: absolute;
      left: 0;
      top: 0;
      width: 20px;
      height: 20px;
      border-radius: 5px;
    }
  }
}
```
