### ISSUE TITLE
Chartjs 2.0

### ISSUE THREAD

**Issue by youtalaoui** [jtblin/angular-chart.js#268]
Hello, 

Was wondering if you have any plan to start looking for Chartjs 2.0, they released 2 beta so far. 

https://github.com/nnnick/Chart.js/releases

Thank you for your good job.

**Comment by jtblin** [comment]
Yes, I've started working on it last weekend. I will continue this weekend and will push a branch then. There is already #123 if you want to follow when it becomes available.
