### ISSUE TITLE
angular $filter interpolation for scalelabel, legend and tooltips values.

### ISSUE THREAD

**Issue by uxtx** [jtblin/angular-chart.js#269]
Hi, I'd been using the lib a bit and it works great! One question I had was if it's currently possible to expose value for use with angular filters... it'd be nifty to be able to do something like  `'scaleLabel': '$<%=value | filter:'currency' %>' `...or something like that.

Right now, I'm just calling out to a global lib (for instance accounting.js) and doing something like this:
```
    'scaleLabel': '<%=accounting.formatMoney(value) %>',
```
Has anyone found a good solution for this?

**Comment by mbuttu** [comment]
@uxtx you can do

```javascript
scaleLabel: function(valuePayload) {
  // currencyFilter is injected
  return currencyFilter(valuePayload.value);
}
```

**Comment by uxtx** [comment]
Great! This is what I needed! Thanks @mbuttu
