### ISSUE TITLE
Graph not drawn unless window is resized.

### ISSUE THREAD

**Issue by michaelsund** [jtblin/angular-chart.js#27]
Im doing a post to a database via my angular service, 1 of 10 times the graph loads, but 9 out of 10 times it only shows up when i resize the window.

Im guessing that the graph is drawn before the data is populated from my service, allthough from the documentation the graph data could be empty and update when populated (reactive)?

Heres ,my example
```html
<canvas id="line" class="chart chart-line" data="data" options="options" labels="labels" series="series"></canvas>
```
```javascript
GraphService.fetchSensorLogs(sensortofetch, function(response) {
	$scope.series = ['Measurement'];
	$scope.labels = response.labels;
	$scope.options = { animation: false, showScale : true, showTooltips : false, scaleShowLabels: true, pointDot: true, scaleShowGridLines : false};
	$scope.data = response.data;
});
```

**Comment by jtblin** [comment]
The graph should update when you modify the data. Could you try to wrap your data update in a `scope.$apply`?

```
GraphService.fetchSensorLogs(sensortofetch, function(response) {
  scope.$apply(function () {
    $scope.series = ['Measurement'];
    $scope.labels = response.labels;
    $scope.options = { animation: false, showScale : true, showTooltips : false, scaleShowLabels: true, pointDot: true, scaleShowGridLines : false};
    $scope.data = response.data;
  });
});
```

**Comment by michaelsund** [comment]
Working flawlessly on osx with chrome, gonna do some more testing and cache clearing on chrome with windows before i resort to $scope.$apply();
Thanks for the tip!
