### ISSUE TITLE
how to set option for hiding the y axis?

### ISSUE THREAD

**Issue by lonelysun** [jtblin/angular-chart.js#270]
I use the chart-line,but i can't set option.I want to hide the Y axis,so i tried to use chart-options,but it's not work.So,i need help.
Thanks!

**Comment by uxtx** [comment]
according to chart.js docs... it doesn't look like you can hide the y axis, but if you want to hide the other vertical lines, you should be able to do so by  adding an options object with this value:

``` $scope.myChartOpts = {
    'scaleShowVerticalLines' : false

}```

and referencing it with your chart object like so:

```
<canvas id="doughnut" class="chart chart-doughnut" chart-data="myChart.data" chart-labels="myChart.label" chart-legend="true" chart-options="myChartOpts" chart-colours="reportColors"></canvas>
```

**Comment by lonelysun** [comment]
hi uxtx.
Thanks for your reply.
I tried your suggest, I hide the vertical lines but except Y axis ,but i just want to hide the y axis.
as your reply,the chart.js doesn't support to hide the y axis.

**Comment by ykyuen** [comment]
The latest chart.js support hiding the axes.

To hide the y-axis only, you can set the following chart option
```
{
  'scaleShowLabels': false,
};
```

if you want to hide both x and y axes and the grid lines, just set
```
{
  'showScale': false,
};
```

[Chart.js Documentation - Chart options](http://www.chartjs.org/docs/#line-chart-chart-options)

**Comment by jtblin** [comment]
If you want to use Chart.js 2.0, try this branch out: https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0

**Comment by nigelkong** [comment]
Under the options object:
`
scales: {
  yAxes: [{
    display: false
  }]
}
`

**Comment by zymr-keshav** [comment]
@jtblin  link provided by you is not found :  https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0
