### ISSUE TITLE
Minimum Pie slice size

### ISSUE THREAD

**Issue by zhurni-man** [jtblin/angular-chart.js#272]
How would I set a minimum slice size for a pie chart? I have a data with wide ranges. One data point can be in the hundreds, and another can be as small as 2. When displaying in a pie chart, really small data points can barely be seen.

I tried using scaleOverride and it's options but it doesn't seem to apply to pie charts.

**Comment by jtblin** [comment]
The [Chart.js tracker](https://github.com/nnnick/Chart.js) or StackOverflow is probably a better place to ask this kind of question.
