### ISSUE TITLE
Add support for Chart.Scatter.js

### ISSUE THREAD

**Issue by jabaa** [jtblin/angular-chart.js#276]
I read in a closed issue, that it could be possible to use angular-chart.js for Chart.Scatter.js but I wasn't able to achieve this. As far as I could realize the data structures of most Chart.js types and Chart.Scatter.js are too different to use angular-chart.js. The "data"-field of Chart.js is an array of arrays but Chart.Scatter.js uses an Array of Objects. I think a third type of  "getData"-function is necessary. If I'm  misleading and it is possible to use Chart.Scatter.js with angular-chart.js, I'd be glad to learn, how to do this.

**Comment by jtblin** [comment]
The data structure seems to different to allow support for this kind of chart. That said, I think scatter charts are coming to Chart.js 2.0 so this library will support that once 2.0 is out.

**Comment by darrachequesne** [comment]
For future readers, if you are locked with angular-chart.js < 1.x, it does seem possible to use `Chart.Scatter.js`: http://jsbin.com/munuditute/edit?html,js,console,output

A new directive was added:
```js
  return angular.module('chart.js', [])
    .provider('ChartJs', ChartJsProvider)
    .factory('ChartJsFactory', ['ChartJs', '$timeout', ChartJsFactory])
    .directive('chartBase', ['ChartJsFactory', function (ChartJsFactory) { return new ChartJsFactory(); }])
    .directive('chartLine', ['ChartJsFactory', function (ChartJsFactory) { return new ChartJsFactory('Line'); }])
    // [...]
    .directive('chartScatter', ['ChartJsFactory', function (ChartJsFactory) { return new ChartJsFactory('Scatter'); }]);
```

And it can be used with:
```js
app.controller("ChartCtrl", ['$scope', function ($scope) {
    $scope.labels = ["January", "February", "March", "April", "May", "June", "July"];
    $scope.series = ['Series A', 'Series B'];
    $scope.data = [
      [{ x: 0, y: 0}, { x: 1, y: 1 }, { x: 0, y: 1 }],
      [{ x: 1, y: 0}, { x: 0, y: 1 }, { x: 2, y: 0 }]
    ];
    $scope.onClick = function (points, evt) {
      console.log(points, evt);
    };
}]);
```
