### ISSUE TITLE
Bar chart negative values?

### ISSUE THREAD

**Issue by acidmk** [jtblin/angular-chart.js#277]
When i pass array which have negative values it won't scale it right

![untitled123](https://cloud.githubusercontent.com/assets/12675793/12048440/63cb731c-af05-11e5-8ff1-8d97ec887b69.png)

Is it possible to draw negative values like here http://www.highcharts.com/demo/column-negative

**Comment by jtblin** [comment]
Not with this version of chart.js but I think next version will allow it.

**Comment by Saschafeldmann** [comment]
Do you mean in this way (see attached image) - Its possible with option ""scaleBeginAtZero":false	".

![negative-value](https://cloud.githubusercontent.com/assets/15728010/12547462/ed93bc30-c350-11e5-860f-e3d4f58910ba.jpg)

**Comment by jtblin** [comment]
I stand corrected, thanks @Saschafeldmann.

**Comment by acidmk** [comment]
@Saschafeldmann, no i mean like in highcharts example. With "scaleBeginAtZero:false" option it will start drawing bars from it's minimum value lie it is shown in the picture.

![untitled1234](https://cloud.githubusercontent.com/assets/12675793/12694493/844259e0-c75a-11e5-95f3-b378d7cff25a.png)

 And i want it to draw like in example where it's growing from zero value up or descending down. 

![untitled1234a](https://cloud.githubusercontent.com/assets/12675793/12694505/a902d6c4-c75a-11e5-983d-1de30621ec55.png)

**Comment by acidmk** [comment]
Ok. I've adapted angular-chart-js for chart.js version 2.0 and it's drawing negative values. [link](https://github.com/acidmk/angular-chart.js/blob/master/dist/angular-chart.js)

**Comment by jtblin** [comment]
You can check out [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0).
