### ISSUE TITLE
Angular-chart stacked bar chart is showing the graph upside down

### ISSUE THREAD

**Issue by pacificeyes** [jtblin/angular-chart.js#278]
I'm using angular-chart and chartjs + stackebarchart.js in combination to create the stacked bar chart. It works perfectly fine most of the cases but when I pass values like (0,9 [0 for fail and 9 for pass]), it shows the graph upside down. Please let me know the resolution of this weird issue.

**Comment by jtblin** [comment]
No idea, you should check with the creator of the stacked chart extension.
