### ISSUE TITLE
Line example uses wrong class

### ISSUE THREAD

**Issue by ulikoehler** [jtblin/angular-chart.js#279]
At https://jtblin.github.io/angular-chart.js/, the line example code shows this markup:
```html
<canvas id="bar" class="chart chart-bar"
  chart-data="data" chart-labels="labels"> chart-series="series">
</canvas>
```

However, `char-bar` is wrong here, it needs to be `chart-line`, so the markup needs to be changed to

```html
<canvas id="bar" class="chart chart-line"
  chart-data="data" chart-labels="labels"> chart-series="series">
</canvas>
```

Thanks for fixing!

**Comment by jtblin** [comment]
It looks good to me, maybe you're confusing with the next chart:

<canvas id="line" class="chart chart-line" chart-data="data"
  chart-labels="labels" chart-legend="true" chart-series="series"
  chart-click="onClick" >
</canvas>

**Comment by ulikoehler** [comment]
Oops, sorry, I indeed confused it. I was thinking the tabs *below* the line chart were related to it, but in fact the code for the line chart is to the right.
