### ISSUE TITLE
Font icons as labels

### ISSUE THREAD

**Issue by lucasbeef** [jtblin/angular-chart.js#280]
Hi, I have been able to load custom fonts with pointLabelFontFamily, but not to display the icons. 
I've seen it work on Chart.js, but does angular-chart support it ?

Thank you

**Comment by jtblin** [comment]
How do you do that on Chart.js? You should be able to pass the same options as for Chart.js.

**Comment by lucasbeef** [comment]
I tried it again and managed to make it work.

The thing is to set the font in the graph's options with `pointLabelFontFamily : "'fontello'",`
and as labels use the codes formated like so `"\ue823"`
