### ISSUE TITLE
datasetFill option not implemented

### ISSUE THREAD

**Issue by lucasbeef** [jtblin/angular-chart.js#281]
The datasetFill option does not seem to be implemented for line and radar charts. I think it would be a nice addition.

It could take an array of bools (one per serie) so that we can display both a filled serie and one with only the stroke visible. For me it would be usefull to show how one user is positioned compared to an average.

**Comment by mrunion** [comment]
I don't think it's a problem with The Angular Chart JS code. For example, if you set values for pointDot or pointDotRadius in the chart-options attribute, they will affect the chart. If you set datasetFill to true or false, the chart ignores it. I have looked into the code for Angular Chart JS and it is passing the datasetFill option to the ChartJS creation call. It seems the error is on ChartJS's side. I need to dig more, though.

**Comment by mrunion** [comment]
Yup, ChartJS has the issue. See http://stackoverflow.com/questions/30350865/radar-charts-for-chartjs-always-stay-filled.

**Comment by mrunion** [comment]
If you rebuild ChartJS this option will work as expected, so this is not an Angular Chart JS issue.

**Comment by lucasbeef** [comment]
Thanks !
I'm sorry I really thought the param wasnt sent to Chart.js
I found the related discussion on a Chart.js PR : https://github.com/nnnick/Chart.js/pull/1127
