### ISSUE TITLE
chart-hover redraws

### ISSUE THREAD

**Issue by holtc** [jtblin/angular-chart.js#282]
When I pass a function to chart-hover, even just an empty function stub that does nothing, the chart redraws the first time I move the mouse over the chart, but every time after that, the behavior works properly, and the chart does not redraw.  Any clue as to why this would happen?

EDIT1: Have done some debugging and found that the $scope.$apply() call at line 241 in the getEventHandler method starting at line 232 calls $scope.$digest, which calls resetChart for some reason.

EDIT2: This only happens when the chart is in a collapsible panel that is being opened for the first time, and then it redraws on the first hover, but does not redraw after that.  The chart does not redraw on hover at any other point.

**Comment by jakehasler** [comment]
@holtc Are you still having this issue? When I reset my data object that is being used in the graph, it displays correctly, but then when I hover, it flashes (redraws) back to the original dataset that it had to begin with. Is there any other config items that I need to adjust so that this doesn't happen?

**Comment by jtblin** [comment]
@jakehasler it looks more like #187 if you see the original dataset, which was fixed in `0.9.0`. Are you sure you are using the latest version?

**Comment by jakehasler** [comment]
@jtblin That solved it! Thanks so much - Sorry for not digging deeper into the issues. All is great and thanks for the awesome library!

**Comment by jtblin** [comment]
No worries, thanks for the feedback and glad it helps! :+1:

**Comment by jtblin** [comment]
@holtc, I've removed the call to `$scope.$apply()` in the 1.0 branch published to npm as `1.0.0-alpha2`. I will not change this in the 0.x branch as it's a breaking change.
