### ISSUE TITLE
chart-colours vs chart-colors

### ISSUE THREAD

**Issue by gkampjes** [jtblin/angular-chart.js#283]
It seems against best practice to use "colours" rather than "colors" for `chart-colours`.

Generally it's best to use the Americanised spelling, as much as it irritates me as a fellow commonwealth resident to do so, it makes for consistent code, rather than having half my code having "color" and the other half having "colour", especially since JS uses the American spelling, as well as chart.js itself.

Seems like aliasing `chart-colors` to `chart-colours` could be a good idea, and a way to reduce coding errors and increase consistency.

**Comment by KarlPurk** [comment]
+1 agree completely (also a fellow commonwealth resident)

**Comment by jtblin** [comment]
Yeah agreed, it was a mistake in the first place. That will change in the
next major version.

**Comment by jtblin** [comment]
This is now done in the [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0) which will be released when Chart.js 2.0 is released. Closing this issue.
