### ISSUE TITLE
Question: Reload/Redraw canvas chart

### ISSUE THREAD

**Issue by fmiboy** [jtblin/angular-chart.js#285]
I wonder if there is redraw or refresh/reload functionality so that I can access it from controller?

I saw this following

*If you want to reload the canvas send a broadcast using:
$scope.$broadcast("$reload", {});
This wil repaint the charts (for example when a chart became visible)*

in https://github.com/leonetnl/angular-chart.js

**Comment by fmiboy** [comment]
Further checking showed that only line 130 has this extra maybe can be considered in future releases if no alternative available now?!

>          scope.$on('$reload', function () {
>              if (chart) chart.update();
>          });

**Comment by johannesjo** [comment]
I'm also wondering how to do this. It's possible to do this in a hacky way with ng-if, but an actual redraw trigger would be nice.

**Comment by jtblin** [comment]
You can get a reference to the chart using the `create` event so you can call `chart.update()` when you would normally broadcast the reload event. I'll consider that for a next release.

**Comment by JobaDiniz** [comment]
+1

**Comment by JobaDiniz** [comment]
+1
I don't see any API docs on how to get the *chart reference* to be able to call `chart.update()` afterwards

**Comment by jtblin** [comment]
https://github.com/jtblin/angular-chart.js#events

**Comment by JobaDiniz** [comment]
+1 and *sorry* for deleting comments

**Comment by JobaDiniz** [comment]
I set `responsive=false` and `mantainAspectRatio=false`, and I calculate the *width* and *height* myself (because I'm using [Gridster](https://github.com/ManifestWebDesign/angular-gridster)).
Apart from the *legend* being cut off, it works.

However, when I change the width of the *gridster item* I then reset the *width*/*height* of the chart:
```
var chart;
var debounceResize = debounce(3000, onGridsterResized);
scope.$on('gridster-item-resized', debounceResize);
scope.$on('create', onChartCreated);

function onChartCreated(event, newValue) {
                chart = newValue;
            }

function onGridsterResized(event) {
                if (chart) {
                    $timeout(function () {
                        scope.chart.height = $('.panel-body', element).height();
                        scope.chart.width = $('.panel-body', element).width();
                        chart.resize();
                    });
                }
            }
```
**Template**
```
<div class="panel panel-default panel-shadow">
    <div class="panel-heading">
        <div class="panel-title">{{widget.Title}}</div>
    </div>
    <div class="panel-body">
        <canvas height="{{chart.height}}" width="{{chart.width}}"
                class="chart-base"
                chart-type="chart.type"
                chart-data="chart.data"
                chart-labels="chart.labels"
                chart-series="chart.series"
                chart-options="chart.options"
                chart-legend="true"></canvas>
    </div>
</div>
```
I'm calling `chart.resize()` however the chart disappears and only when I click in its area, then it is shown. Why is that happening?

**Comment by jtblin** [comment]
What are the values of `scope.chart.height` and `scope.chart.width`? Maybe you need to add `px` to the markup element?

**Comment by JobaDiniz** [comment]
I tried:
```
chart.resize(function(){
  chart.reflow();
  chart.render();
});
```
This *kinda* works... 
When resizing, and calling the above code, chart gets a little messed up.
The only way I get it to work was to remove `<canvas>` DOM completely and insert a new one with the new width/height.

**Comment by jtblin** [comment]
Can you post a jsbin?

**Comment by cmrenus** [comment]
Im checking for the create event in my code but it never happens. Is it not implemented? Im using 1.0.0-alpha6 and chartjs version 2.1.5

**Comment by jtblin** [comment]
Event is called `chart-create` in `alpha6`.

**Comment by cmrenus** [comment]
Thanks. I remember seeing that in some threads now that everything is "chart-". You should emphasize that more within documentatino. Spent real long time trying to figure that out. Also I don't know if this is something that you or chart.js should do, but an actual drilldown funcitionality like highcharts has would be so good

**Comment by jtblin** [comment]
Well you just have to read the beginning of the readme...

![image](https://cloud.githubusercontent.com/assets/1388974/16109913/8c4173a0-33ee-11e6-9272-d4604ea35000.png)

Plus more in the readme...

![image](https://cloud.githubusercontent.com/assets/1388974/16109925/983ab4be-33ee-11e6-9507-e6c90b93fd7f.png)

https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0

**Comment by cmrenus** [comment]
ah my apologies. I was looking probably at old README and most threads have the old version info. Quick irrelevent question, is there a way to set the chart-click attribute within the js when creating a new chart?

**Comment by jtblin** [comment]
It's the `chart-click` option.

**Comment by jtblin** [comment]
You can now emit a $resize event on scope on 1.x which will trigger the resize: aa2dc93. Chart is automatically updated when data or other options change. Closing this issue.

**Comment by prashasti4** [comment]
My chart data not updating
$scope.$on('chart-update',function(evt, chart){
chart.update();
})

is not working

**Comment by DurgpalSingh** [comment]
on window resize event chart-update and chart-create event not fired. Any solution
