### ISSUE TITLE
label a pie chart, not legend

### ISSUE THREAD

**Issue by aparna1591** [jtblin/angular-chart.js#288]
Is there a setting/option to always display the label and data on the pie chart? Instead of displaying the legend on hover that is. Also notice that pie charts are accepting a maximum of three data items. Can that also be changed? It is ignoring the 4th data onwards.

**Comment by gkampjes** [comment]
Pie and Doughnut charts can be of any size, not sure what you've done to limit them to only 3 items, you're possibly not putting the data in the right format?

The data should be in the format:

```javascript
$scope.data = [1, 2, 3, 4, 5];
$scope.labels = ["a", "b", "c", "d", "e"];
```

By always display the data and label, do you mean have the tooltips always showing, like [this](http://stackoverflow.com/questions/25661197/chart-js-doughnut-show-tooltips-always)? If that's what you want, then add this to your options:

```javascript
$scope.chartOptions = {
        onAnimationComplete: function () {
            this.showTooltip(this.segments, true);
        }
}
```

Your html should now look something like this:

```html
<canvas id="doughnut" class="chart-doughnut" chart-data="data" chart-labels="labels" chart-options="chartOptions" chart-legend="false">
</canvas>
```

**Comment by jtblin** [comment]
Thanks @gkampjes for the explanation.

@aparna1591 for options, check http://www.chartjs.org/docs/.

**Comment by R4ZuL** [comment]
I tried to show the tooltips permanently for a pie chart but the following code did not work:

```
// pieChart.controller.js
class PieChartController {
    constructor() {
        var self = this;
        self.labels = ['Download Sales', 'In-Store Sales', 'Mail-Order Sales'];
        self.data = [300, 500, 100];
        self.options = {
            tooltipEvents: [],
            tooltipCaretSize: 0,
            showTooltips: true,
            onAnimationComplete: function() {
                self.showTooltip(self.segments, true);
            }
        }
    }
}

export default PieChartController;

```

```
//pieChart.component.js
import template from './pieChart.tmpl.html';
import controller from './pieChart.controller.js';

let pieChartComponent = {
    scope: {},
    template,
    controller
};

export default pieChartComponent;
```

```
// pieChart.tmpl.html
<div>
    <canvas id="pie"
            class="chart-pie"
            chart-data="$ctrl.data"
            chart-labels="$ctrl.labels"
            chart-options="$ctrl.options">
    </canvas>
</div>
```
