### ISSUE TITLE
Coordinating colors on multiple charts.

### ISSUE THREAD

**Issue by jondthompson** [jtblin/angular-chart.js#289]
So I have several charts that are showing different slices of the same data at once through several API calls for different slices. The collections of data that I get back don't necessarily have the same label information in them, which causes a UI issue where the color in one chart represents one data point, and in another represents another data point.

Ways I've though of solving it is to put all data into a dictionary that would aggregate the labels together as 0 value, then parse each again with each api call to set the values that I need to be set. However, that seems really inefficient.

Is there a way to sync colors between graphs?

**Comment by jtblin** [comment]
There is no way that I know to map colours and labels, you will have to maintain the mapping on your side.
