### ISSUE TITLE
Bar chart legend color issue

### ISSUE THREAD

**Issue by imornar** [jtblin/angular-chart.js#291]
I use different kinds of chart displays (line, bar, radar)  with custom colors to display data.
All charts are displayed with colors correctly, but I have legend issue with bar display, where legend has some kind of opacity on it.

other legends
 ![line](https://cloud.githubusercontent.com/assets/9463015/12354957/c9b54e1e-bb99-11e5-9aaf-7ec6eade937f.png)
bar legend 
![bar](https://cloud.githubusercontent.com/assets/9463015/12354967/dcdf5318-bb99-11e5-8221-9e1f7b91a03c.png)

**Comment by jtblin** [comment]
I believe this is an issue with upstream (Chart.js).
