### ISSUE TITLE
chart-legend does not work with functions like other fields

### ISSUE THREAD

**Issue by djwagner-cbc** [jtblin/angular-chart.js#292]
the bar chart attribute chart-legend does not work with functions like other fields.

line 201 of angular-chart.js v0.8.5 has this:
```javascript
if (scope.legend && scope.legend !== 'false') setLegend(elem, chart);
```

It would be more useful to allow functions so the chart legend can be shown when there are more than one series.

This would allow someone to do:
```javascript
chart-legend="getResults().ShowLegend"
```

**Comment by gkampjes** [comment]
I've noticed this myself as well.

**Comment by jtblin** [comment]
In 1.x, there is no more chart legend attribute as this is handled entirely by Chart.js now so closing as "Won't fix" as I will only be doing bug fixes in the `0.x` series from now on. You can try out the new version at https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0.
