### ISSUE TITLE
Custom tooltip

### ISSUE THREAD

**Issue by maketroli** [jtblin/angular-chart.js#294]
I am working with the Line Chart from [ChartJS](http://www.chartjs.org/docs/) and with [the Angular extension](http://jtblin.github.io/angular-chart.js/) for that Plugin.

I am having difficulties trying to edit the tooltip so according to the Docs I need to create a custom template in order to achieve what I need

Here is what I have so far

[![enter image description here][1]][1]

as you see there is the tooltip but it is not displaying what I need, I need to display something like this: 

>$AMOUNT (total) 

so in this case it should be:

>$150 (1)

got it ?

See my code

          $scope.labels = Object.keys(data);
          $scope.seriesConv = ["amount"];
          $scope.dataConv = $scope.seriesConv.map(function(serie) {
            return $scope.labels.map(function(label) {
              $scope.trafficSource = Object.keys(data[label])[0];
              $scope.chartOptions = {
                tooltipTemplate: "<%= '$' + value %>",
              };
              return data[label][$scope.trafficSource].conversions.amount;
            });
          });

and html

       <canvas id="line" class="chart chart-line"
               height="100" chart-options="chartOptions"
               chart-data="dataConv" chart-labels="labels">
       </canvas>

This is the data I am receiving

    {
      "12-15-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 8,
            "real": 1
          }
        }
      },
      "12-16-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 18,
            "real": 1
          }
        }
      },
      "12-17-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 1,
            "amount": 22
          },
          "clicks": {
            "total": 12,
            "real": 1
          }
        }
      },
      "12-18-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 6,
            "real": 1
          }
        }
      },
      "12-19-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 12,
            "real": 1
          }
        }
      },
      "12-20-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 10,
            "real": 1
          }
        }
      },
      "12-21-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 1,
            "amount": 22
          },
          "clicks": {
            "total": 1,
            "real": 1
          }
        }
      },
      "12-22-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 1,
            "amount": 150
          },
          "clicks": {
            "total": 1,
            "real": 1
          }
        }
      },
      "12-26-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 4,
            "real": 1
          }
        }
      },
      "12-28-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 1,
            "real": 1
          }
        }
      },
      "12-29-2015": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 1,
            "real": 1
          }
        }
      },
      "01-03-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 2,
            "real": 1
          }
        }
      },
      "01-04-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 3,
            "real": 1
          }
        }
      },
      "01-05-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 6,
            "real": 1
          }
        }
      },
      "01-06-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 6,
            "real": 1
          }
        }
      },
      "01-10-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 1,
            "real": 1
          }
        }
      },
      "01-11-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 2,
            "real": 1
          }
        }
      },
      "01-14-2016": {
        "55f6de98f0a50c25f7be4db0": {
          "conversions": {
            "total": 0,
            "amount": 0
          },
          "clicks": {
            "total": 22,
            "real": 1
          }
        }
      }
    }

for now I am just playing with the `"conversions : {}` part of the Object, which contains `total` and `amount`

so according to the Docs of those links, what do you think I should do in order to achieve what I want?

  [1]: http://i.stack.imgur.com/8akSz.png

**Comment by ZhukV** [comment]
+1

**Comment by jtblin** [comment]
This really is a question for upstream (http://www.chartjs.org/), probably better suited for stackoverflow.

**Comment by maketroli** [comment]
But you are not supporting this, I mean, you don't anything in this framework to cover that part. So maybe you can think on adding a new feature :+1:

**Comment by gkampjes** [comment]
If the data on the x axis is unique, you can make an dictionary with the required data, and then have the x axis values as the keys.

Then in your custom tooltip, you have something like (excuse the coffeescript instead of JS, I'm sure you can figure it out):

```coffee
      tooltipTemplate: (point) ->
        "$" + $scope.data[point.label].amount + " (" + $scope.data[point.label].total + ")"
```

It looks like with a small amount of work, you'll be able to use the data as it comes, and not even make a new dictionary.
