### ISSUE TITLE
Problems with script includes - where is /Chart.js/Chart.min.js?

### ISSUE THREAD

**Issue by richnsoos** [jtblin/angular-chart.js#295]
Hi Team. Trying to following the installation instructions posted here: http://jtblin.github.io/angular-chart.js/. Instructions say to the only include needed is ```<script src="bower_components/angular-chart.js/dist/angular-chart.js"></script>``` but I was not able to get the pie chart to dispaly without *also* adding a ```Chart.min.js``` include but I cannot find this anywhere in the package I downloaded (angular-chart.js-master.zip) so I'm temporarily using: http://cdn.rawgit.com/nnnick/Chart.js/master/Chart.min.js and the chart dispalys as expected. Love the charts btw, but where can I get the official copy of /Chart.js/Chart.min.js? Thanks in advance for any help you can provide.

**Comment by jtblin** [comment]
You need to install it yourself or use npm or bower which should install dependencies.
