### ISSUE TITLE
Any idea when to support Chart.js 2.0.0 (and showXLabels option) ?

### ISSUE THREAD

**Issue by JonasWestAlro** [jtblin/angular-chart.js#296]
Hi,

I really need this feature: https://github.com/nnnick/Chart.js/pull/897 and it looks like it's going to be in version 2.0.0 of Chart.js. Does Angular-chart.js have any plans of supporting this any time soon? :-)

**Comment by kamyarg** [comment]
+1

**Comment by mannb1** [comment]
+2 - I was wondering as well if there are plans to support Chart.js 2.0 and if so an approximate ETA of when that might be available.  We enjoy using your package and are making plans to upgrade to Chart.js 2.0 and need to know if we will be able to move along with your package or find an alternate solution to upgrade.  Thanks

**Comment by jtblin** [comment]
Yes, subscribe to #123 for changes and see `chartjs-2.0` branch. I was on annual leave in January so didn't make any progress but will start looking into it again.

**Comment by acidmk** [comment]
You can try this [version](https://github.com/acidmk/angular-chart.js/blob/master/dist/angular-chart.js) for chart.js 2.0 support. But seems chart.js 2.0 doesn't support showXLabels option yet.

**Comment by jtblin** [comment]
Work is well advanced in [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0), I suggest using it instead...
