### ISSUE TITLE
Any idea on how to use a line and bar chart together in angular-chart.js?

### ISSUE THREAD

**Issue by KnightNight07** [jtblin/angular-chart.js#297]
I'm currently working on getting this http://fiddle.jshell.net/leighking2/898kzyp7/ to work inside of angular-chart, but it only gives me the bar chart.  Here is my example canvas tag

       <canvas id="base" class="chart chart-base" chart-type="'LineBar'" chart-data="data2" chart-labels="labels2" width="361" height="543"></canvas><br>

The "LineBar" comes from the fiddle above.  Wondering if this is possible to do or if anyone has done this before?

**Comment by jtblin** [comment]
No it isn't, each directive is for one chart type only.
