### ISSUE TITLE
PieChart show old datas after update

### ISSUE THREAD

**Issue by TheNemus** [jtblin/angular-chart.js#298]
Hi,

this is my chart directive:

`<canvas id="pie"
                    class="chart chart-pie"
                    data="sources_piechart.data"
                    labels="sources_piechart.labels"
                    legend="true"
                    colours="chartColors">
   </canvas>`

`chartColors` and `sources_piechart.labels` once initialized are immutables. Then, when I change `sources_piechart.data` the chart apparently update well (the "update" event is fired). But when I go with the mouse all over the chart, it shows me the old datas: usually this happens when I point to the with space between the pie slices.

Thank you

Rick

**Comment by gkampjes** [comment]
This is going to be fixed in the next version.

Related to #186, #187.

**Comment by loona70** [comment]
This is also the case with the Line Chart.
Thanks
Arnold

**Comment by gkampjes** [comment]
Head to further #187 for further discussion.

Cheers.
