### ISSUE TITLE
Height

### ISSUE THREAD

**Issue by bluee** [jtblin/angular-chart.js#30]
It seems like if passing the parameter height it is ignored and not passed on?

eg.
<canvas id="line" class="chart chart-line" data="data"
                                labels="labels" legend="false"
                                click="onClick" height="50"></canvas>

Rendered Height is then 205px

**Comment by WeHateNick** [comment]
+1

**Comment by jtblin** [comment]
Would you have a full example, preferably on jsbin or similar? This works for me using the line chart example in `examples/charts.html` and adding `height="50"` to the markup:

    <canvas id="line" class="chart chart-line chart-xl" data="data" labels="labels" legend="true" click="onClick" series="series" height="50"></canvas>

![image](https://cloud.githubusercontent.com/assets/1388974/5773659/091f3050-9d65-11e4-8823-7a2d814e47d6.png)

**Comment by jtblin** [comment]
Here is a jsbin template for convenience: http://jsbin.com/dufibi/3/edit?html,js,output.

**Comment by bluee** [comment]
It does indeed seem to work fine in the example, I need to find out what's causing it to behave differently in my code. Feel free to close this issue until I can find the cause. Thanks.

**Comment by coffeeDanny** [comment]
Canvas set height, width lateral tagging part will be truncated.How to solve this question?
