### ISSUE TITLE
How to set y-axis label

### ISSUE THREAD

**Issue by patrickrioux** [jtblin/angular-chart.js#300]
Hi,

Is there any option to set a y-axis label. This option is supported in chartjs but I have no clue how to set in the angular-chart.js implementation. Sounds like not available. Any idea?

**Comment by gkampjes** [comment]
You mean a label as in a name for the axis? Or label as in the numbers on the scale?

**Comment by patrickrioux** [comment]
Label as in a mame indicating the type for the points rendered in the chart.

**Comment by gkampjes** [comment]
That's a ChartJS 2.0 feature I'm fairly sure, it's not in the docs for ChartJS 1.

**Comment by jtblin** [comment]
You can try the [2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0).
