### ISSUE TITLE
PieChart created twice

### ISSUE THREAD

**Issue by TheNemus** [jtblin/angular-chart.js#301]
Almost everytime I load new data, chart is initialized twice. After some debug I realize that this is caused by the `createChart` function, which assign to the `$scope.colours` the result of the `getColours()` functions. Being `$scope.colours` under watch, causes a new call to the `resetChart` that subsequentially call `createChart` function again in the next digest.

chart v 0.8.8
angular v 1.4.8

**Comment by jtblin** [comment]
Thanks for the report, would you have a code example, especially regarding how your colours are set, ideally with a [jsbin](http://jsbin.com/dufibi/3/edit?html,js,output)? There was some similar report in the past but it was impossible to repro.

**Comment by gkampjes** [comment]
I think I've noticed the same thing. The create event is fired twice, it destroys the first one though, as it should. It's not really a major, but it could be a performance problem in certain cases (not that chart.js is particularly slow, except for animations).

**Comment by TheNemus** [comment]
I'll provide you some code on this we

**Comment by TheNemus** [comment]
Unfortunatly I didn't get to reproducible case. However I made some screenshot of my webapp while the bug is appearing.

in every screenshot there are two print of the colours array (`$scope.mycolours` is defined in my ctrl):
```
{{::mycolours}}
{{mycolours}}
```

So I can see how the` $scope.mycolours` value change from the beginning

1. this is the directive boot. Data, lables and colours are now availables (they were taken from aRESTApi). `$scope.mycolours` is an hex array
![c_bug01](https://cloud.githubusercontent.com/assets/9430669/13223776/fa968fac-d985-11e5-86a4-d0d87c3886da.png)

2. Still in the same call. scope.getColors build the colors array object and assign it to the directive`scope.colors` properties
![c_bug03_5](https://cloud.githubusercontent.com/assets/9430669/13224097/477bb6a2-d987-11e5-991a-5f60483ab0bc.png)

3. Chart is built. `$scope.mycolours` is still an hex array
![c_bug02](https://cloud.githubusercontent.com/assets/9430669/13223795/07d6e072-d986-11e5-9d1f-6dd1cfcc8a84.png)

4. Next `dygest `phase (triggered by a page scroll), `createChart` is called, maybe triggered by the `scope.colors` watch
![c_bug03](https://cloud.githubusercontent.com/assets/9430669/13223829/2db0cda8-d986-11e5-80c8-63b406244821.png)

5. Chart is rebuilt. Now `$scope.mycolours`is an object array as `scope.colors`
![c_bug04](https://cloud.githubusercontent.com/assets/9430669/13223834/328d0472-d986-11e5-873f-763a4f003f7e.png)


This is a slowmo of what is happening in my app. Hope helps

**Comment by jtblin** [comment]
Thanks for the detailed report @TheNemus. I've changed the behaviour to avoid mutating the scope colours, unless it is really necessary (i.e. not enough colours to display the chart). I will port this to 1.x branch as well.
