### ISSUE TITLE
Breaks when using in minified file

### ISSUE THREAD

**Issue by chrillewoodz** [jtblin/angular-chart.js#302]
No charts appear to work when using[ grunt-contrib-uglify ](https://github.com/gruntjs/grunt-contrib-uglify), when the charts directives are inside the minified file then I get this error:

```Unknown provider: aProvider <- a <- chartBarDirective```

I got the same for my own directives when forgetting about the array annotation, but after fixing those I still get these. But I don't know how to fix it for the charts, are you not using array notation? I can't really see what's going on because of the way it's written with exports and stuff. 

Please help.

**Comment by langdonx** [comment]
@chrillewoodz You manage to fix this?
