### ISSUE TITLE
Series not showing when there is only one

### ISSUE THREAD

**Issue by fjompen** [jtblin/angular-chart.js#303]
Is this a known bug? Anyone knows how to fix it?

**Comment by jtblin** [comment]
Only one what? Point? If yes then yes it's s known limitation of Chart.js. Mathematically a line needs 2 points.

**Comment by fjompen** [comment]
NO. When there is oboy one strunt in the Series Array.

**Comment by fjompen** [comment]
NO. When there is only one string in the Series Array.

**Comment by jtblin** [comment]
Ok not sure what you mean, I'd suggest you post some code example on stackoverflow.
