### ISSUE TITLE
Series label not showing when there is only one value. 

### ISSUE THREAD

**Issue by fjompen** [jtblin/angular-chart.js#304]
$scope.labels = ['2013-01-01', '2013-01-02'];
$scope.series = ['Project A'];
$scope.data = [52, 53];

I'm having an issue. When there is only one string in the Series array the string isnt displayed in the chart. See picture.

![namnlos](https://cloud.githubusercontent.com/assets/10205517/13041787/9b80367e-d3ba-11e5-8fd9-837a27ead5d9.png)

Anyone who got any ideas/knowledge on how to fix this? It works fine as soon as I have two series.

**Comment by jtblin** [comment]
Your data doesn't seem to be correct anyway, it should be something like `$scope.data = [[52, 53]];` and even that would be only one series, not two. The picture obviously doesn't correspond to the code. I'd suggest you follow the markup example on http://jtblin.github.io/angular-chart.js/#bar-chart, and send a [jsbin](http://jsbin.com/dufibi/3/edit?html,js,output) to repro. That said, it's possible that to display 2 series, well you need to have 2 series both in the data and series labels. Stackoverflow.com may be a better place for this kind of questions.
