### ISSUE TITLE
chartjs-2.0: bower dependencies and dist folder

### ISSUE THREAD

**Issue by gadeynebram** [jtblin/angular-chart.js#305]
Hi,

Great work on chart.js 2.0! 

I just wanted to point out some documentation / set-up problems. 

I have this bower config:
`"dependencies": {
    "angular-chart.js": "chartjs-2.0",
    "Chart.js": "2.0.0-beta2"
},"resolutions": {
    "angular": ">=1.4.0 <1.5",
    "Chart.js": "2.0.0-beta2"
  }`

This currently resolves to angular 1.4.9.

The resolution for Chart.js was necessary because it resolved to version 1.0.2.

I also first used the angular-chart.js version that was in the dist folder. However this is probably an older version because this gave some errors.

with kind regards

**Comment by jtblin** [comment]
Thanks, I've updated bower.json and pushed the change. Chart.js 2.0.0-beta2 has not been pushed to npm yet so this is not changed.
