### ISSUE TITLE
Updating data doesn't clear old chart

### ISSUE THREAD

**Issue by corientdev** [jtblin/angular-chart.js#306]
Updating data doesn't clear old chart.

It actually shows old chart on hover.

any way to completely clear old chart

**Comment by gkampjes** [comment]
Known issue, see  #187 and try some of the fixes there. Please comment there for further discussion.

The problem is that in certain cases (usually changing the size of the data) when it recreates the chart, it doesn't delete the old one.

A fix is being worked on.
