### ISSUE TITLE
chartjs-2.0 Hardcoded property "fill" in getDataSets

### ISSUE THREAD

**Issue by courchef** [jtblin/angular-chart.js#309]
The property fill is hardcoded to true in function getDataSets
```
    function getDataSets (labels, data, series, colors) {
      return {
        labels: labels,
        datasets: data.map(function (item, i) {
          return angular.extend({}, colors[i], {
            label: series[i],
            data: item,
            fill: true
          });
        })
      };
    }
```

Is it possible to convert this into an option?

**Comment by courchef** [comment]
In my cshtml file, I added a tag named chart-fill
```
<canvas id="primary" class="chart chart-line" chart-fill="false"></canvas>
```

In the ChartJsFactory, I added the property in the scope:
```
        scope: {
          getColour: '=?',
          chartType: '=',
          chartData: '=?',
          chartLabels: '=?',
          chartOptions: '=?',
          chartSeries: '=?',
          chartColors: '=?',
          chartFill: '=',
          chartLocale: '=?',
          chartClick: '=?',
          chartHover: '=?'
        },
```

And in method getDataSets, I use the scope property instead of the hardcoded value:
```
    function getDataSets (labels, data, series, colors) {
      return {
        labels: labels,
        datasets: data.map(function (item, i) {
          return angular.extend({}, colors[i], {
            label: series[i],
            data: item,
            fill: scope.chartFill
          });
        })
      };
    }
```

What do you think?

**Comment by jtblin** [comment]
Thanks. Agreed it should not be hardcoded. Looking at the 2.0 docs, it is possible to set the value via standard Chart.js options  and it already defaults to `true` so I've just removed it.

https://github.com/nnnick/Chart.js/blob/v2.0-dev/docs/00-Getting-Started.md

**Comment by courchef** [comment]
I removed all my modifications, updated to your last commit and set fill: false in default options of Chart.js

Many thanks for your work!

**Comment by jtblin** [comment]
:+1:

**Comment by seralf** [comment]
Hi the correct link seems to be:
https://github.com/chartjs/Chart.js/blob/master/docs/00-Getting-Started.md
