### ISSUE TITLE
chartjs-2.0: double y axis

### ISSUE THREAD

**Issue by gadeynebram** [jtblin/angular-chart.js#311]
Hi,

In chart js 2 it should be possible to show 2 y-axis. As far as I can see this is done by setting a yAxisID value for the second series.

Is it possible to do this with angular-chart.js?

**Comment by jtblin** [comment]
Yes all options supported by chartjs should be available, see https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0. Please post a repro case if you find something that doesn't work properly.

**Comment by gadeynebram** [comment]
Hi,

I've managed to get this working but I had to change something in the code.

What I did was pass this to the options

`options={
      scales: {
            yAxes: [
                 {type:"linear","id":"y-axis-1",display:true, position: "left"},
                 {type:"linear","id":"y-axis-2",display:true, position: "right"}
            ]
      }
}`

In [data-structure](http://nnnick.github.io/Chart.js/docs-v2/#line-chart-data-structure) they mention that you should add yAxisID as a property to the dataset. However in angular-chart.js in the function getDataSets this will not be added since (as far as I can see) only the properties label, data and fill are set. Zo I change the code to this:

`function getDataSets (labels, data, series, colors) {
      return {
        labels: labels,
        datasets: data.map(function (item, i) {
        	var dataset=angular.extend({}, colors[i], {
                label: series[i],
                data: item,
                fill: true,
                yAxisID: "y-axis-"+(i+1)
              });
          return dataset;
        })
      };
    }`

**Comment by jycouet** [comment]
I was looking exactly for this.
But, it's not working when you don't set these **yAxes** in options/scales (when you don't have multiple axes for instance)
Maybe, it's better to add a **chartYaxes** directive? (And when this is set, attach yAxisID)

**Comment by pane-e-design** [comment]
I add the chartYaxes directive and pass it on getDataSets call:

```js
getDataSets(scope.chartLabels, scope.chartData, scope.chartSeries || [], scope.chartColors, scope.chartYAxes);
```
And add yAxisID if chartYAxes is true:
```js
      function getDataSets (labels, data, series, colors, yaxis) {
          return {
              labels: labels,
              datasets: data.map(function (item, i) {
                  var dataset =  angular.extend({}, colors[i], {
                      label: series[i],
                      data: item,
                      fill: true
                  });

                  if (yaxis) {
                      dataset.yAxisID = "y-axis-" + (i+1)
                  }

                  return dataset;
              })
          };
      }
```
Send a pull request?

**Comment by jtblin** [comment]
Yes please :+1: I'll have a look at it this weekend.

**Comment by ramarro123** [comment]
hi, any update for that? will it be published on the library?

**Comment by jtblin** [comment]
Yes, it will. You can follow https://github.com/jtblin/angular-chart.js/pull/327. if @pane-e-design doesn't have the time to do the changes asked in the PR, I'll probably look at integrating it as-is this weekend.

**Comment by pane-e-design** [comment]
I update the pull request, @jtblin check in #327

**Comment by ramarro123** [comment]
just tested, work for me, but i suggest to change
                    chartYAxes: '@'
into
                    chartYAxes: '=?'

in that way it will be possible to pass the config of the chart with a model. i don't know if it's
better approach in angular to write it with a simple =? or with a ng-if or with an {{}} signature, still too new for me :)

**Comment by pane-e-design** [comment]
@ramarro123 i change into '=?' but when you change the model you also change the options removing the other yAxes.
I test this changing the options and the model for chartYAxes and it worked. See change on #327.

**Comment by ramarro123** [comment]
great, and, it's expected that if i change it the chart will redraw himself :)

**Comment by rafaellop** [comment]
It seems that the directive is not working if the options contains yAxes definition. For example, I've got a linechart canvas with `chart-y-axes="false"` and the options contain:

`$scope.intakeChartOptions = {
        scaleShowGridLines : true,
        pointDot : true,
        legend: false,
        maintainAspectRatio: true,
        responsive: true,
        scales: {
            yAxes: [
                {
                    id: "y-axis-0",
                    type: "linear",
                    display: true,
                    position: "left"
                },
                {
                    id: "y-axis-1",
                    type: "linear",
                    display: true,
                    position: "right"
                }                
            ]            
        }
    }
    `

The chart always shows the right Y scale. No matter of the `chart-y-axes` directive is true or false. The scale is a bit weird by the way because it is from -0.1 through 0.0 to 1.0 for data which are far from this range.

**Comment by jtblin** [comment]
It kind of makes sense I guess. By adding the y-axis in the options, you're telling `chart.js` to display a right Y axis. But because no series are attached to the axis, it doesn't have any value to set the scale properly hence the weird -0.1 through 0.0 to 1.0. 
I don't see what we can do in this library about this, I suggest to open an issue here https://github.com/nnnick/Chart.js/issues so that they don't display the axis if no series attached to it.

**Comment by jtblin** [comment]
Btw `1.0.0-alpha2` is published in npm so closing this issue. In case of issues with the y-axis feature, please open separate issues. Thanks @pane-e-design for implementing this!

**Comment by rafaellop** [comment]
Sorry, but the series are attached in the canvas. I thought it's obvious.

`<canvas chart-chart-data="intakeChartData" chart-labels="intakeChartLabels" series="intakeChartSeries" chart-options="intakeChartOptions" ... >`

In the controller's `$scope` there are series available and even I try to change them later with a timeout the yaxis remains the same -1..1. It may be related to the chart.js itself, but I think it can also be related to the order of initialization in the angular module. Just guessing.
