### ISSUE TITLE
chartjs-2.0: cvs.getContext is not a function

### ISSUE THREAD

**Issue by jycouet** [jtblin/angular-chart.js#312]
I think that I have the right chart.js 2.0 and angular-chart.js 2.0, but when I try I have an error:
`cvs.getContext is not a function`

I think that this part is the same then in 1.0... so why is it not working?
Thanks for your help

**Comment by jtblin** [comment]
Hard to say with so little information... Please add a repro case.

**Comment by jycouet** [comment]
Hi @jtblin I'm quite new in this js, git, angular, chart... And I think I mixed up everything!
I managed to checkout the 2.0 branch and it's working well! So I close the issue.

**Comment by jtblin** [comment]
Great, glad to know.

**Comment by sadiesh** [comment]
Am also getting the same issue

**Comment by sadiesh** [comment]
angular.js:14236 TypeError: cvs.getContext is not a function
    at createChart (angular-chart.js:184)
    at watchData (angular-chart.js:156)
    at n.$digest (angular.js:17462)
    at n.$apply (angular.js:17781)
    at l (angular.js:11815)
    at H (angular.js:12113)
    at XMLHttpRequest.u.onload (angular.js:12331)
