### ISSUE TITLE
$scope vs this

### ISSUE THREAD

**Issue by heyahharissa** [jtblin/angular-chart.js#313]
We're using controller as and this.scope = {} in our directive, is this compatible?

Curious to see if anyone has any workarounds because I cant for the life of me get it to work with this.

**Comment by Pdrevland** [comment]
It works, remember to use your controller alias and your data object in 
`<canvas chart-data="yourCtrl.scope.data>`

**Comment by heyahharissa** [comment]
Do you have a codepen or jsfiddle of this I could check out? Im using the controller allias and the data shows up in the template if I print it out but a graph never draws

**Comment by heyahharissa** [comment]
ahh nvm it was a dependency issue I was having, thank you for the quick help though :)
