### ISSUE TITLE
Bar chart colours do not work

### ISSUE THREAD

**Issue by danwellman** [jtblin/angular-chart.js#314]
When using a pie chart, I can set global colours like this:

`Chart.defaults.global.colours = ['#FF69B4', '#BADA55', '#C0FFEE', '#101CA7', '#E22025'];`

This works great, the pie segments take these colours. With a bar chart however, only the first colour is used for all bars, and also the bars have some crazy alpha setting making them semi-transparent which on white background just makes them look washed out. Here is the bar config in my controller:

    $scope.bar = {
        data: [100, 200],
        labels: ['Something', 'Something else'],
        opts: {
            barShowStroke: false,
        }
    };

Here is the mark-up:

    <canvas id="bar" class="chart chart-bar" width="250" height="255"
                  data-chart-options="bar.opts"
                  data-chart-data="bar.data"
                  data-chart-labels="bar.labels">
    </canvas>

I've also tried configuring the colours for the bar chart by adding a colours property to the 'bar' object in the scope:

    $scope.bar = {
        colours: ['#FF69B4', '#BADA55', '#C0FFEE', '#101CA7', '#E22025']
        data: [100, 200],
        labels: ['Something', 'Something else'],
        opts: {
            barShowStroke: false,
        }
    };

And adding the colours attribute to the mark-up:

    <canvas id="bar" class="chart chart-bar" width="250" height="255"
                  data-chart-colours="bar.colours"
                  data-chart-options="bar.opts"
                  data-chart-data="bar.data"
                  data-chart-labels="bar.labels">
    </canvas>

This doesn't work at all, it just uses the Chart.js default colours (not even the overridden defaults I set!). After looking at the chart,js site, I changed the colours property on my scope object to this:

     colours: [{  fillColor: #FF69B4 }, { fillColor: '#BADA55' }],

In this format, only the first colour is used for all bars in the chart.

Perhaps it's not a bug, but from  the docs on angular-chart or Chart.js it's not obvious how to specify a different colour for each bar in the chart.

Please advise

**Comment by danwellman** [comment]
Actually, I found the problem, in my `data` I should have specified it like this:

    data: [[100], [200]],

In this case, I see the different colour bars. Apologies

**Comment by danwellman** [comment]
one thing I notice is if I specify the data like this:

    data: [[100], [200]],

Then in this case, I see the different colour bars. However, now my two bars are very thin and are squeezed right next to each other, so I guess they are data within the same series?

I just want a simple bar chart, with a single series, with different coloured bars, is this possible?

**Comment by gkampjes** [comment]
It's possible in chart.js 2.0, but not in chart.js 1.

I'm not sure if it's possible on the chart.js 2.0 branch of angular-chart.js though.

**Comment by danwellman** [comment]
OK cool, I'll take a look at the 2.0 branch

**Comment by jtblin** [comment]
If it's 2 bars in the same series you should use `data: [[100, 200]]`.

**Comment by danwellman** [comment]
In this format the chart doesn't even render and there are no errors in the console. Maybe i'm using the wrong terminology, but compared to the example bar chart on the angular-chart homepage, I just want one bar for each value at the bottom, e.g. just the blue bars, but i want each bar to be a different colour.

**Comment by jtblin** [comment]
I cannot repro your issue. If you use [this example](https://github.com/jtblin/angular-chart.js/blob/master/examples/charts.template.html#L456) and change `chart-line` to `chart-bar` in the markup and open the page in your browser you will see it uses the colours properly. I'd recommend you a jsbin if you want to re-open the issue: http://jsbin.com/dufibi/3/edit?html,js,output
