### ISSUE TITLE
Getting "number" of current bullet

### ISSUE THREAD

**Issue by kasperrt** [jtblin/angular-chart.js#315]
In a linechart, is it in any way possible to get the index of the bullet you're currently hovering over?
Or or have another dataset that isn't being shown as bulletpoints and shown in the graph, only as tooltips?

**Comment by gkampjes** [comment]
If your chart x axis data is unique (i.e. no 2 points have the same x axis label), then you can just reach into your controller/viewmodel and use indexOf to find the index in the chart labels.

When chart.js builds tooltips, the point is passed into the toolTipTemplate function (which can be set in your chart-options), this point contains the label (x axis label), dataSetLabel (label of the data set), and the value.
