### ISSUE TITLE
legend colours not working properly

### ISSUE THREAD

**Issue by Nsab31** [jtblin/angular-chart.js#317]
The legend colours are not shown as square with corresponding colours.It was shown as bullets and the colours are given as background for the label. 

While I look into the html, the label  should be out of <span> element.but in my case it was generated by the library inside the <span>. how to fix this ? Please help.

![image](https://cloud.githubusercontent.com/assets/13604477/13324395/275f435c-dba3-11e5-93bc-37d5016bdc6e.png)

My code are given below

![image](https://cloud.githubusercontent.com/assets/13604477/13325030/d4386b4c-dba5-11e5-8a51-484bdbbde107.png)

CSS
.pie-legend {
  list-style-type: block;
  list-style:circle;
  margin-top: 5px;
    font-size : 16px;
  -webkit-padding-start: 0;
    -moz-padding-start: 0;
    padding-left: 0;
}
.pie-legend li{
  color : black;
  white-space: nowrap;
  position: relative;
  margin-bottom: 4px;
  border-radius: 5px;
  padding: 2px 8px 2px 8px;
  font-size: 16px;
  cursor: default;
}
.pie-legend li span{
  position: absolute;
  left: 0;
  top: 0;
  border-radius: 5px;
  padding: 2px 8px 2px 8px;
  width : 140px;
 }

![image](https://cloud.githubusercontent.com/assets/13604477/13325007/bd9ec188-dba5-11e5-85b3-142be2c23bc7.png)

**Comment by jtblin** [comment]
Have you included the css from the repo as per the README?

```
<head>
  <link rel="stylesheet" href="bower_components/angular-chart.js/dist/angular-chart.css" />
<head>
```
