### ISSUE TITLE
Dynamically change scale label

### ISSUE THREAD

**Issue by mazzimi** [jtblin/angular-chart.js#318]
Hello,

Inside my angular application, I fetch new data from the server via ajax and then I update the chart.
It happens that the user can change the scale of the values, by multiplying them by 1000, so that the scale should change accordingly.
The probblem is that I can set the "scaleLabel" using the "chart-options" in the canvas, but I did not find any way to change it dynamically.

Is it possible to do that?

Thank you,
Michele

**Comment by jtblin** [comment]
The chart will be automatically if you change the options. Make sure you pass the options in the markup and change the corresponding option in the scope when needed.

**Comment by mazzimi** [comment]
Hello,

I can confirm it works properly; I was using a wrong format for "option" valiable.
I was adding a double quote ", around the json variable.

Thank you
