### ISSUE TITLE
Line Chart Example label and serie variable values do not match the chart label series values

### ISSUE THREAD

**Issue by rajangdavis** [jtblin/angular-chart.js#319]
![chart example](https://cloud.githubusercontent.com/assets/8786035/13333846/e895feca-dbbd-11e5-9954-88047d8fe038.JPG)
 
See attached image; I looked at the code and saw a setTimeout function to change the values for the Line Chart example, so I think all you have to do is remove the function or at least reflect this function in the example code. Not a huge issue, just really confusing.

**Comment by jtblin** [comment]
This is by design to simulate updating the chart dynamically by changing its data.

**Comment by rajangdavis** [comment]
That's fine and all, but in the javascript code, this change is not reflected. The result is working off of a different set of code than what is in the example.

If you want, I can update this and submit a pull request; I am only griping because I did not know that the chart was _supposed to _dynamically change without reading the page source.
