### ISSUE TITLE
Error: function(ChartJsFactory) is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by MihaiDinculescu** [jtblin/angular-chart.js#320]
This issue can be easily reproduced by adding `ngStrictDi` alongside `ngApp`.

`<div ng-app="ngAppStrictDemo" ng-strict-di>`

Adding this directive helped me investigate an issue in production (AngularJS served by RoR). The given error is very generic and didn't help at all 
`Error: [$injector:unpr] Unknown provider: eProvider <- e <- chartRadarDirective`.

I will make a PR with the fix.

**Comment by jtblin** [comment]
You need to use the files in the `dist/` folder to avoid this error. The annotations are added automatically by the `gulp-annotate` plugin, see `gulpfile.js`. That said, this trips a lot of people so I think it's better making that explicit, but should remove the stuff from the `gulpfile` and dependency.

**Comment by MihaiDinculescu** [comment]
Please excuse my ignorance, I had no knowledge of the existence of `gulp-annotate`.

I would like to point out however that it's not a good idea to include in the package a 'broken' version of the library.

Shall I go ahead and update the PR with the removal of `gulp-annotate`?

**Comment by jtblin** [comment]
> However, I would like to point out that it's not a good idea to include in the package a 'broken' version of the library.

It isn't the package, it's the non compiled source... Anyhow I agree that it's better to remove. Thanks for taking the time to do that :+1:

**Comment by MihaiDinculescu** [comment]
It's done.
Build seems to be failing for some reason, but I don't see how it can be from my modifications.

The source file is included in the bower package.
In RoR we don't usually include specific JS files, we reference the bower package instead. Based on naming conventions, `sprockets` then searches and includes the files needed.

**Comment by jtblin** [comment]
> The source file is included in the bower package.
In RoR we don't usually include specific JS files, we reference the bower package instead. Based on naming conventions, sprockets then searches and includes the files needed.

Well `sprockets` should include the file indicated by `bower` in the `main`array so you should open a bug with `sprockets`.

```
{
  "name": "angular-chart.js",
  "version": "0.8.8",
  "main": [
    "./dist/angular-chart.js",
    "./dist/angular-chart.css"
  ],
(...)
```

Looking at the errors, it might be due to angular 1.5. Let's keep the rest of the conversation in the PR.

**Comment by MihaiDinculescu** [comment]
Normally `sprockets` does that but in this case the dot in `angular-chart.js` makes it bug out so I erroneously updated the reference to 

`//= require angular-chart.js/angular-chart`

instead of 

`//= require angular-chart.js/dist/angular-chart`

**Comment by jtblin** [comment]
No worries :)
