### ISSUE TITLE
Overlapping Legend Text

### ISSUE THREAD

**Issue by ChewingPencilLines** [jtblin/angular-chart.js#322]
My pie chart's legends are overlapping.

I have tried displaying my pie chart in different sizes, i.e. half the screen's width and the entire screen's width, but both showed tightly packed legend labels that overlap. 

![screenshot from 2016-02-29 09 14 45](https://cloud.githubusercontent.com/assets/5270350/13383454/ffd17b64-dec4-11e5-95a5-4ce93b686958.png)

**Comment by ChewingPencilLines** [comment]
Found something odd when inspecting elements.

I found this: <span style="background-color:rgba(151,187,205,1)">Download sales</span>.

Seems like the proper HTML would have been: <span style="background-color:rgba(151,187,205,1)"></span> Download sales.

Any idea why mine is coming out oddly?

**Comment by ChewingPencilLines** [comment]
I have resolved the issue by changing `Chart.js`.

**Comment by otaviodecampos** [comment]
This does not occur in Chart.js 1.0.2
