### ISSUE TITLE
chartjs-2.0: Why in the latest commit "dist/" dir doesn't have the minified css file?

### ISSUE THREAD

**Issue by pane-e-design** [jtblin/angular-chart.js#323]
I'm trying to download the plug-in with bower, in your bower file there are these dependencies, but css file isn't in dist/:
```js
  "main": [
    "./dist/angular-chart.js",
    "./dist/angular-chart.css"
  ],
```

**Comment by jtblin** [comment]
There is no css needed anymore but I forgot to update bower.json file.
