### ISSUE TITLE
Drawing line graph, slow performances when a lot of points to draw

### ISSUE THREAD

**Issue by vagusae** [jtblin/angular-chart.js#324]
Hi,
I hope I am creating in the right category this comment.
It is a question more than an issue.
I could integrated successfully angular-charts, using the Line chart into an AngularJS/Ionic application. I am getting from Database a huge number of points to draw, around 3000. So when I try to draw the line graph, it takes some time to render the whole graph. In fact it draws section by section and it difficult a lot the usability in terms of performances.
I tried to used some config options, but is there any options to be configured to increase performances or something to consider on the code?
Thanks for the support

**Comment by gkampjes** [comment]
Have you tried disabling animation?

This is a chart.js issue, more than an angular-chart.js specific issue. I'd suggest asking over on the chart.js repo: https://github.com/nnnick/Chart.js

**Comment by jtblin** [comment]
+1 to disabling animation. This is how the realtime ticks chart is rendered without performance problem on http://jtblin.github.io/angular-chart.js/

**Comment by vagusae** [comment]
Thanks a lot! I checked the options for the line-chart but I did not see there were also global options.
