### ISSUE TITLE
Pie chart updating , only after select box value changed twice

### ISSUE THREAD

**Issue by catalystweb** [jtblin/angular-chart.js#326]
Hi,

I'm new to all this, been trying to learn angular as I go.  I'm a pretty shit dev at the best of times, so my code probably looks like shit.

Anyways, I have a select box (id = searchInput) when the user selects an option from it, the jquery change function is fired, and then an each loop for the array of objects totalData.

I had another if statement but I removed it as it was similar to this one, looking for a null value in searchInput, which subsequently ran different conditions.  Due to the jquery change function firing everytime searchInput changes, I wanted to ensure that the arrays data and labels were clear everytime, so I set their length to zero.

As crap as my code might be, it works first time the page is loaded and the console log shows that the data and labels arrays are being updated with the pushed data.

However if I select a different value from the select, the pie chart does not update until the value has been changed for a 3rd time.

Example:   

1. if I select HSBC from drop down, pie chart loads:
2. After HSBC chart loaded, if I select Aspen, nothing happens.
3. If I then select IAG, pie chart updates showing the Aspen data.

This happens everytime after 1st load.  I could select IAG , then HSBC and then the IAG data will load.  Hope this makes sense.

I'm also having an issue where if I select a value from the select on page load, the change function will not fire until the select loses focus, but this is a jquery issue I think.

Anyway, here is the code.  I hope all this made sense, any help would be appreciated. 

Thanks,

```
controller('dataCtrl', ['$scope',function($scope) {   
    
        //static array values //
        $scope.fieldNames = [{ type1: 'EDM', type2: 'SMS', type3: 'BOUNCE', type4: 'UNSUB', type5: 'CLICK' }];
        $scope.totalData =  [{ name: 'HSBC', edm: 1100, sms: 400, bounce: 95, unsub: 320, click: 300 },
                             { name: 'Westpac', edm: 800, sms: 300, bounce: 70, unsub: 75, click: 100 },
                             { name: 'Aspen', edm: 550, sms: 100, bounce: 50, unsub: 30, click: 220 },
                             { name: 'IAG', edm: 230, sms: 50, bounce: 30, unsub: 90, click: 75 }                               
                            ];   


        //css to view based on scope select value//
        $('#searchInput').on('change', function() {
              
              var select1 = $("#searchInput").val();                           
              

                    $.each($scope.totalData, function(key,value) {               

                        if (value.name == select1 ) {

                            $scope.data.length = 0
                            $scope.labels.length = 0                      
                            
                              $("#allView").fadeOut("fast", function () {
                                  $("allView").css({display:"none"});
                                  $("#singleView").fadeTo("fast",1);

                                  $.each($scope.fieldNames, function(i,x) {                    
                                                                        
                                      $scope.labels.push(x.type1, x.type2, x.type3, x.type4, x.type5);
                                  })

                                      console.log ("Name: " + value.name);
                                      console.log ("Select: " + select1);

                                      $scope.data.push(value.edm, value.sms, value.bounce, value.unsub, value.click); 

                                      console.log ("Data: " + $scope.data);
                                      console.log ("Labels: " + $scope.labels);

                                      $('#singleGraph').html($("#searchInput").val()); 
                                      $("#searchInput").css("margin-right","30px"),
                                      $("#compInput").css("display","block");  
                                                                 
                                      
                                })                      
                                  
                        }  

                })    

          }); 
  }]);
```

**Comment by jtblin** [comment]
Sorry mate, it isn't really the best place to ask this kind of questions. I'd recommend you go to http://stackoverflow.com/ and post your question there where people will be more likely to help you.

Just at high level, in general I'd avoid mixing up jQuery and Angular, when the dropdown selection changes you could just use angular `ng-change` to retrieve the data and update the chart dynamically, see https://docs.angularjs.org/api/ng/directive/select for example.
