### ISSUE TITLE
Pie chart is not getting destroyed if data is set to null

### ISSUE THREAD

**Issue by sandeeproop** [jtblin/angular-chart.js#328]
Hi,
I am trying to hide the pie chart if i don't have data but when i pass chat-data="null". It doesn't do any thing.
It is probably because of following line.

    if (! newVal || ! newVal.length || (Array.isArray(newVal[0]) && ! newVal[0].length)) return; 

In my opinion it should destroy existing chart.
Request you to please let me know if there is some work around already available.

**Comment by gkampjes** [comment]
Use ng-hide/ng-show to hide the chart when it's got no data.

**Comment by jtblin** [comment]
You can pass 0 values to remove the data from the chart. I may look into destroying the chart when null values or empty array are passed later as it isn't the first time someone raises this as an issue.

**Comment by agaskell** [comment]
@sandeeproop this should be fixed in 0.9.0. See issue #334.
