### ISSUE TITLE
Format Values on Tooltips

### ISSUE THREAD

**Issue by WeHateNick** [jtblin/angular-chart.js#33]
Cannot figure out how to format values on tooltips. For instance, I would like a pie chart to display a value as "$4,500" instead of "4500". Is this functionality currently available?

**Comment by jtblin** [comment]
This can be done using Chart.js `multiTooltipTemplate` (for tooltips) and `scaleLabel` (for labels) functions, see https://github.com/nnnick/Chart.js/issues/411 and http://jsbin.com/jihadu/1/edit?html,js,output for example implementation.

```
Chart.defaults.global.scaleLabel = function (label) {
    return label.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
};

Chart.defaults.global.multiTooltipTemplate = function (label) {
    return label.datasetLabel + ': ' + label.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
}; 
```

**Comment by WeHateNick** [comment]
That did it for me! Thanks a lot!

**Comment by Ehesp** [comment]
What happens if you have multiple charts on a single page, where you need to format the values differently for each chart?

**Comment by jtblin** [comment]
You can use the chart options:

```html
    <canvas id="line" class="chart chart-line" data="data"
      labels="labels" legend="true" series="series"
      click="onClick" options="options">
    </canvas>
```

```js
  $scope.options = {
   multiTooltipTemplate : function (label) {
    return label.datasetLabel + ': ' +    label.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
   } 
  };
```

**Comment by Ehesp** [comment]
@jtblin Thanks but I can't seem to get that working. Would you mind doing an example somewhere?

It just shows the default still.

**Comment by jtblin** [comment]
Here you go: http://jsbin.com/vupejayoro/1/edit. Make sure you add the `options` to the markup and set the options before the data (I might have to watch if `options` change and redraw the chart on change if that was the issue, lmk.

**Comment by Ehesp** [comment]
@jtblin Seems it doesn't work if I want to nest my objects.... http://jsbin.com/huqodobisu/1/edit?html,js,output

Basically I'm trying to get a % option in there, but I have multiple chart objects within my `charts` object.

**Comment by jtblin** [comment]
Oh for doughnut, pie i.e. charts with only one data series, you need to use `tooltipTemplate` not `multiTooltipTemplate`. The label property is also now `label` not `datasetLabel`, there are several inconsistencies in Chart.js API unfortunately, see https://github.com/nnnick/Chart.js/blob/master/Chart.js#L167.

Updated [jsbin](http://jsbin.com/puwayajobi/3/edit)

**Comment by Ehesp** [comment]
Cheers, works a treat now.

**Comment by alexcosmin** [comment]
I wanted to do the same as @Ehesp . Thanks @jtblin !

**Comment by SamiTriki** [comment]
You can also use angular filters or create your own to help you with the formatting 
```javascript
// put this in your controller or your app's run block
function (label) {
    // example with angular's build in currency filter
    return $filter('currency')(label.value);
}
```

**Comment by hyperreality** [comment]
For those using Chart.js >2.1, I used the following code to get formatted tooltips on a pie chart:

    $scope.labels = ['A', 'B', 'C'];
    $scope.data = [40, 30, 30];
    $scope.options = { 
      legend: { 
        display: true 
      },
      tooltips: {
        enabled: true,
        mode: 'single',
        callbacks: {
          label: function(tooltipItem, data) {
            var label = data.labels[tooltipItem.index];
            var datasetLabel = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
            return label + ': ' + datasetLabel + '%';
          }
        }
      },
    };

**Comment by cgountanis** [comment]
Can this be done with a global option using the ChartJS 2.2+ version, having lots of issues with old examples not working. All I want to do is a simple comma in Y AXIS and tooltip labels,

**Comment by MilindDivre** [comment]
How can we disable tool tips on hover and  get  the value by default

**Comment by AmarKoli** [comment]
@hyperreality - the callback for the tooltip works fine, can you guide me on how to format the labels on the yAxes/xAxes. 
it would be a great help, actually i am new to angularjs.

**Comment by lschneiderman** [comment]
@hyperreality's solution works great! You can also add a comma formatter:

[options: {
				tooltips: {
				enabled: true,
				mode: 'single',
				callbacks: {
				  label: function(tooltipItem, data) {
					var label = data.labels[tooltipItem.index];
					var datasetLabel = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
					return label + ': ' + addCommas(datasetLabel) ;
				  }
				}
			  }
			}

function addCommas(nStr)
{
   nStr += '';
    x = nStr.split('.');
    x1 = x[0];
    x2 = x.length > 1 ? '.' + x[1] : '';
    var rgx = /(\d+)(\d{3})/;
    while (rgx.test(x1)) {
        x1 = x1.replace(rgx, '$1' + ',' + '$2');
    }
    return x1 + x2;
}](url)

**Comment by vikas379** [comment]
@hyperreality @lschneiderman the solution works great for single graph what if i need to show more than one graphs data in a single tooltip.
![image](https://cloud.githubusercontent.com/assets/16378824/21254581/3fbbc336-c38c-11e6-9164-4733503def6c.png)


as you can see in the above graph when i hover mouse on a single point the tooltip shows details of all four  graphs simultaneously for that month also see the graph colors in sequence. 

i tried this
options: {
                tooltips: {
                enabled: true,
                mode: 'nearest',
                callbacks: {
                  label: function(tooltipItem, data) {
                    var label = data.labels[tooltipItem.index];
                    var datasetLabel = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
                    return label + ': ' + addCommas(datasetLabel) ;
                  }
                }
              }
            }

but it is not working.
suggestions please

**Comment by dhanraj-infyom** [comment]
> @hyperreality's solution works great! You can also add a comma formatter:
> 
> ```
> options: {
>                 tooltips: {
>                 enabled: true,
>                 mode: 'single',
>                 callbacks: {
>                   label: function(tooltipItem, data) {
>                     var label = data.labels[tooltipItem.index];
>                     var datasetLabel = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
>                     return label + ': ' + addCommas(datasetLabel) ;
>                   }
>                 }
>               }
>             }
> 
> function addCommas(nStr)
> {
>    nStr += '';
>     x = nStr.split('.');
>     x1 = x[0];
>     x2 = x.length > 1 ? '.' + x[1] : '';
>     var rgx = /(\d+)(\d{3})/;
>     while (rgx.test(x1)) {
>         x1 = x1.replace(rgx, '$1' + ',' + '$2');
>     }
>     return x1 + x2;
> }
> ```

it's working fine.
