### ISSUE TITLE
[chartjs-2.0] legend + colours

### ISSUE THREAD

**Issue by frlinw** [jtblin/angular-chart.js#333]
Thanks for your work for support chartjs 2.0

There are some little issues
default legend display is true and even if I use chart-legend="false" legend is displayed.
chart-colours seems to be ignored as well

**Comment by frlinw** [comment]
Bug spotted

In your doc you still say "chart-colours"
But it seems to be "chart-colors" now

**Comment by jtblin** [comment]
Yes it uses "colors" now, similarly there is no `chart-legend` attribute anymore as legend is controlled via an option in Chart.js 2.0 now. I'll fix that in the docs, thanks for pointing out.
