### ISSUE TITLE
chartjs 2.0 support mixed type

### ISSUE THREAD

**Issue by ramarro123** [jtblin/angular-chart.js#336]
hi,

as per this example

https://github.com/nnnick/Chart.js/blob/v2.0-dev/samples/combo-bar-line.html

now chartjs2.0 support mixed type, so it will be nice to have line + bar in the same chart as for this example.

it's not possible now (yet) to add this using the angular directive, do you think that can be planned?

**Comment by ChrisBirchUZ** [comment]
Support for mixed types would be great, is it likely this will be integrated any time soon?

**Comment by jtblin** [comment]
It is now possible to override individual datasets options with #418. Published `1.0.0-alpha8` with this change.

See [this mixed type chart example](https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/examples/dataset-override.html).
