### ISSUE TITLE
Bower warnings with Angular 1.5.0

### ISSUE THREAD

**Issue by Philio** [jtblin/angular-chart.js#338]
As the bower dependency currently requires Angular 1.4.x it's necessary to fix interactively or specify resolutions to use the library with Angular 1.5.0. Would be nice if the dependency could be updated to be a little more flexible to avoid this.

**Comment by sos0** [comment]
just when i needed to integrate too :')

**Comment by jtblin** [comment]
I fixed the test that was having issue with `1.5.x` and updated bower and npm files. Published `0.10.2`. This shouldn't be an issue anymore.
