### ISSUE TITLE
chartjs-2.0 Error: Chart.js - Moment.js could not be found! You must include it

### ISSUE THREAD

**Issue by Tokix** [jtblin/angular-chart.js#340]
First of all thanks a lot for the awesome integration you provide. 
I'm not sure if it is worth mentioning, but after the steps, described in the install process (https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0) Chart.js gave me the error above.

Current configuration: 
Bower Entry: 
`"angular-chart.js": "~1.0.0-alpha1"`

Solution: 

1. Install moment:
`bower install moment --save`
                             
2. and add the script definition in index.html above the chart.js part:
`<script src="bower_components/moment/moment.js"></script>`

Just in case someone has the same issue

**Comment by Tokix** [comment]
Sorry my mistake forgot to run 
`npm install --save angular-chart.js`
which is already provided in the Install-Guide

**Comment by jtblin** [comment]
I don't have the issue on my side. I think it depends on the type of scale that you use, as the message says you need to include it yourself. As it is not required for all types of charts, I assume this is why it is not included automatically to keep the size small. WDYT?

**Comment by skarthik333** [comment]
I was facing a similar issue with a chart.js addon for Vaadin. When Vaadin upgraded to the newer npm packaging from bower packaging, I got this error. Adding the import specifically as mentioned resolved the issue. Thanks!
