### ISSUE TITLE
Dotted line?

### ISSUE THREAD

**Issue by im1dermike** [jtblin/angular-chart.js#341]
I'm trying to figure out how to implement a line chart where one of the series is a dotted line.  I found some articles referencing `borderDash` and `lineDash`, but I'm unable to get it to work.

**Comment by jtblin** [comment]
Not sure, I never tried that. Are you sure it's for Chart.js? 

http://www.chartjs.org/docs/

Version 1 or 2?

**Comment by im1dermike** [comment]
It seemed like it was possible...

http://stackoverflow.com/questions/31426195/can-we-draw-a-line-chart-with-both-solid-and-dotted-line-in-it

http://stackoverflow.com/questions/34240595/how-can-i-draw-dotted-line-using-chartjs

http://stackoverflow.com/questions/34517573/dotted-lines-using-chart-js

**Comment by jtblin** [comment]
Looks like `borderDash` is for Chart.js 2.0 version. Check the [2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0).
