### ISSUE TITLE
Error loading chart.js using browserify

### ISSUE THREAD

**Issue by kentonbmax** [jtblin/angular-chart.js#344]
When loading the web page which was working with Bower I am seeing the following weird error. 
![image](https://cloud.githubusercontent.com/assets/15804484/13950950/55555614-f004-11e5-9bf9-c57817490aa1.png)

app.js 
![image](https://cloud.githubusercontent.com/assets/15804484/13950966/6f141338-f004-11e5-8d37-108d213ae0d2.png)

my bundle.js is generated without errors and the type-chart uses angular-chartjs. I also get the error below. 

![image](https://cloud.githubusercontent.com/assets/15804484/13951059/ff33308e-f004-11e5-8b4e-69e2489ec014.png)

**Comment by jtblin** [comment]
Not sure, I don't use `browserify` personally but it should work with it. I see you are requiring `chart.js` two times but I don't think that would cause this error.

**Comment by hut8** [comment]
Did you ever find a solution to this? I'm facing the same issue.

**Comment by hut8** [comment]
Ah, it looks like you can't do `require("chart.js")` in the angular module dependencies directly because it doesn't return the name of the module. Instead, I did `require('angular-chart.js')` before the Angular module definition, then just used `'chart.js'` in the dependency list.

**Comment by jtblin** [comment]
@hut8 This (module name) is now fixed on [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0) and will be published soon.

I've also added an example for webpack with CommonJS.
