### ISSUE TITLE
Cannot read property 'defaults' of undefined RequireJS

### ISSUE THREAD

**Issue by anthony-pinskey** [jtblin/angular-chart.js#347]
I have the following in my path in the requirejs config:

```
        chart: 'lib/angular-chart/Chart',
        'angular-chart': 'lib/angular-chart/angular-chart'
```

The angular-chart module appears to load, but it doesn't seem that Chart.js is being pulled in as I get the following error below in the console.

` Cannot read property 'defaults' of undefined`

Which starts on the 18th line of angular-chart module

`Chart.defaults.global.responsive = true;`

Any idea what's causing this?

**Comment by anthony-pinskey** [comment]
I believe I fixed it by adding the following to my shim object

```
        chart: {
            exports: 'Chart'
        }
```

**Comment by jtblin** [comment]
Cool. Here's a different example as well: https://github.com/jtblin/angular-chart.js/blob/master/examples/amd.js
