### ISSUE TITLE
Set fillColour on the Doughnut Chart

### ISSUE THREAD

**Issue by kotmatpockuh** [jtblin/angular-chart.js#348]
### Overview

I want to set custom colour for doughnut segment (rgba), but something is wrong...

- [x] Use latest version of the library
- [x] Make sure you've included all the dependencies e.g Chart.js, angular, css file
- [x] Include a repro case, see below.

### Step to reproduce

http://jsbin.com/kigoqeqama/1/edit?html,js,output

**Comment by jtblin** [comment]
What's wrong exactly? rgba(0, 0, 0, 0.14) is black no? http://www.color-hex.com/color/000000
