### ISSUE TITLE
Module 'chart.js' not found error

### ISSUE THREAD

**Issue by rekibnikufesin** [jtblin/angular-chart.js#35]
Hi,
I'm using the mean.io template. I've installed chart.js using "bower install angular-chart.js --save".
I have verified that it installed and is available in bower_components.
I have added "bower_components/angular-chart.js/angular-chart.js" to config/assets.json
And declared it as a dependency in my module:
angular.module('mean.posts', ['ngSanitize', 'angularFileUpload', 'infinite-scroll', 'chart.js'])

Upon running my app, I get the error "Error: [$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

I've used the same process to add other dependencies without error (such as angularFileUpload and infinite-scroll). I'm not sure how to resolve the error. 
Any suggestions?
Thanks!

**Comment by garytalmes** [comment]
I was able to figure this out. This angular module has a dependency on the Chart.js package (separate from this angular module). If you install this module via Bower then that dependency gets installed also, but you need to link to that file your code. Make sure you put this BEFORE the link to this module. So your script links should look something like this:

<script src="/bower_components/Chart.js/Chart.min.js"></script>
<script src="bower_components/angular-chart.js/angular-chart.js"></script>

(Adjust paths as needed.)

Gary

**Comment by rekibnikufesin** [comment]
Awesome- that was it!
Thanks @garytalmes

**Comment by Ehesp** [comment]
Just ran into this, thanks @garytalmes - should probably be documented somewhere....

**Comment by jtblin** [comment]
Thanks for raising, updated the readme accordingly.

**Comment by alexcosmin** [comment]
Ran into this as well. Maybe it would be a good idea to also include it [here](http://jtblin.github.io/angular-chart.js), under **Installation**.

**Comment by fabrikate** [comment]
I am running into this issue. As advised I bower installed angular-chart.js --save. I have put the chart.js script before the angular-chart script ( and css link ). I verified in the console that the Chart.js is being loaded before angular-chart. However I get the same error as rekibnikufesin did. Any suggestions?

**Comment by gjrwebber** [comment]
I am also seeing this.

**Comment by fabrikate** [comment]
I found a way around this by using a CDN. Try your program in this jsbin that @jtblin supplied.

http://jsbin.com/cucoqe/1/edit?html,js,output

**Comment by sibaspage** [comment]
Same issue i am facing using cdn. Any solution?

**Comment by StephenMeehan1996** [comment]
ran into the same issue, after a hour I found this. Thank you!
