### ISSUE TITLE
How to pass in custom config options into the graphs?

### ISSUE THREAD

**Issue by jakehasler** [jtblin/angular-chart.js#350]
Hey there,

Love these graphs, and they have been working very well for me. I'm just wondering how to pass in options into the graphs? I've done it with standard javascript Chart.js, but wondering how to do it with Angular. Specifically the `onAnimationComplete()` function as seen below.

```
  var options = {
    onAnimationComplete: function() {
        var ctx = this.chart.ctx;
        ctx.font = this.scale.font;
        ctx.fillStyle = this.scale.textColor
        ctx.textAlign = "center";
        ctx.textBaseline = "bottom";

        this.datasets.forEach(function (dataset) {
            dataset.bars.forEach(function (bar) {
                ctx.fillText(bar.value, bar.x, bar.y + 15);
            });
        })
    }
  }

var chart = new Chart(ctx).Bar(data, options);
```

Thanks in advance!

**Comment by jtblin** [comment]
Yes it is possible, use `chart-options` to pass native Chart.js options.

**Comment by comlaterra** [comment]
Did you consider on creating a small example to use `onAnimationComplete`? I would really create it but I can't manage to make it work.

Thanks!
