### ISSUE TITLE
Filling in chart when area is above a certain value

### ISSUE THREAD

**Issue by im1dermike** [jtblin/angular-chart.js#351]
Is there any way to fill in a chart when the area is above a certain value?  For instance, take this:

<a href='http://postimg.org/image/qpwaxzskh/' target='_blank'><img src='http://s8.postimg.org/qpwaxzskh/Capture.jpg' border='0' alt="Capture" /></a>

I have a line chart with two series: the first is actual data and the second (in red) is a sort of "limit" line.  When the data series is above the "limit" series, I would like for the area to be filled in.  In the edited screenshot, I've done this with red dots.

Is this possible?

**Comment by jtblin** [comment]
I don't think so, you should check http://www.chartjs.org/docs/.
