### ISSUE TITLE
Change PIE chart stroke color

### ISSUE THREAD

**Issue by akilah007** [jtblin/angular-chart.js#352]
How to change PIE chart stroke color

### Overview

Describe the issue. What is the issue and what did you expect?

Please make sure to review and check all of these items:

- [ ] Use latest version of the library
- [ ] Make sure you've included all the dependencies e.g Chart.js, angular, css file
- [ ] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent.** 
Here is a [jsbin template](http://jsbin.com/dufibi/3/edit?html,js,output) for convenience.

**Comment by jtblin** [comment]
https://github.com/jtblin/angular-chart.js/blob/master/test/fixtures/51-pie-update-colours.js#L10
