### ISSUE TITLE
Make bar chart labels clickable

### ISSUE THREAD

**Issue by beeches** [jtblin/angular-chart.js#359]
#Is there a way to make the labels of a bar chart clickable like the bars itself?

I tried using the chart-click directive, which does only return an empty points array when clicking outside an actual bar.

Thanks!

**Comment by beeches** [comment]
Found a solution here: http://stackoverflow.com/questions/34918750/add-link-to-x-label-chart-js

**Comment by akandach** [comment]
Can you please share the working example?

**Comment by beeches** [comment]
Unfortunately I can't since the project was not ported to Angular 2.
