### ISSUE TITLE
Extended Line, Bar or Radar charts get incorrect parameters passed to constructor

### ISSUE THREAD

**Issue by Haewk** [jtblin/angular-chart.js#36]
Replicating the issue is fairly easy:

```
Chart.types.Line.extend({
    name: "LineAlt",
    initialize: function(data){
        Chart.types.Line.prototype.initialize.apply(this, arguments);
    }
});
```

The "data" parameter is all wrong. The problem seems to be in the following code:

    function hasDataSets(type) {
        return ['Line', 'Bar', 'Radar'].indexOf(type) > -1;
    }

The extension will have a different name and hasDataSets will return false which in turn will result in a non-dataset formatted parameter being supplied to the chart constructor.

**Comment by jtblin** [comment]
I changed the detection of the datasets, it should work now as long as you follow the Chart.js convention for the datasets i.e. line chart extension should use multidimensional array.
