### ISSUE TITLE
Options, Series, Colours?

### ISSUE THREAD

**Issue by egidiocs** [jtblin/angular-chart.js#361]
Hi, your work is fantastic.
I can't change legend position, and apply a single colour schema...
What am I missing?

![image](https://cloud.githubusercontent.com/assets/1933529/14550275/a741d2c6-029d-11e6-8508-de80d28caba9.png)

`<canvas id="bar" class="chart chart-bar" 
chart-options="tasksData.options" 
chart-legend="true" 
chart-series="tasksData.series" 
chart-data="tasksData.values"
chart-labels="tasksData.labels" 
chart-colours="tasksData.colours"></canvas>`
```

$scope.tasksData = {
                                       
series: ['Tasks'],
  colours:[ {
  fillColor: 'rgba(151,187,205,0.2)',
  strokeColor: 'rgba(151,187,205,1)',
  pointColor: 'rgba(151,187,205,1)',
  pointStrokeColor: '#fff',
  pointHighlightFill: '#fff',
  pointHighlightStroke: 'rgba(151,187,205,0.8)'
 }],
 labels: ["2016-01", "2016-02", "2016-03", "2016-04", "2016-05", "2016-06", "2016-07"],
values: [19, 26, 43, 40, 66, 42, 35]
}
```

Thank you again for your work!

**Comment by jtblin** [comment]
So you want to use the same colour for each bar iiuc? You should use `getColour` attribute with a function that always returns the same colour:

```
$scope.tasksData = {

series: ['Tasks'],
  getColour: function () {
    return {
      fillColor: 'rgba(151,187,205,0.2)',
      strokeColor: 'rgba(151,187,205,1)',
      pointColor: 'rgba(151,187,205,1)',
      pointStrokeColor: '#fff',
      pointHighlightFill: '#fff',
      pointHighlightStroke: 'rgba(151,187,205,0.8)'
     }
  },
 labels: ["2016-01", "2016-02", "2016-03", "2016-04", "2016-05", "2016-06", "2016-07"], 
values: [19, 26, 43, 40, 66, 42, 35]
}
```

I'm actually surprised that this code even works as `values` should be a bi-dimensional array. I guess what's happening is that it treats your code as 7 series hence why there are 7 colours. If you use a bi-dimensional array, I believe it would use the same colour for the series with your existing code so just try this out:

```
$scope.tasksData = {

series: ['Tasks'],
  colours:[ {
  fillColor: 'rgba(151,187,205,0.2)',
  strokeColor: 'rgba(151,187,205,1)',
  pointColor: 'rgba(151,187,205,1)',
  pointStrokeColor: '#fff',
  pointHighlightFill: '#fff',
  pointHighlightStroke: 'rgba(151,187,205,0.8)'
 }],
 labels: ["2016-01", "2016-02", "2016-03", "2016-04", "2016-05", "2016-06", "2016-07"],
values: [[19, 26, 43, 40, 66, 42, 35]]
}
```

For the legend, I'm afraid I don't think that's possible, however it should show below the chart. Make sure you include the `css` file.

Glad that you liked the library, thanks for the kind words.

**Be aware that I'm going to merge the 2.0 branch into master very soon which has a lot of breaking changes. I'd start looking at the 2.0 branch now if I were you. Chart.js 2.0 includes more options for the legend so you may want to look at http://www.chartjs.org/v2/docs/**

**Comment by egidiocs** [comment]
Hi, thank you for your time replying my "issue"!! It worked as expected, I've rewrote to `[[serie1]]` .
