### ISSUE TITLE
Window need to be resized for Chart to follow parent/container width

### ISSUE THREAD

**Issue by karjac14** [jtblin/angular-chart.js#363]
My bar chart used to show correctly. But ever since I made the containing `<div>` to have dynamic bootstrap col width, like below in the first line:

```
<div class="elements-pane col-xs-{{bar.wf.xs}} col-sm-{{bar.wf.sm}} col-md-{{bar.wf.md}} col-lg-{{bar.wf.lg}}">
      <div class="inner-elements-pane">
        <h4 class="pane-title">{{bar.name}}</h4>
        <div id="bar-select">
          <canvas id="performance-bar" class="chart chart-bar" chart-labels="bar.labels" chart-legend="true" chart-series="bar.seriesname" chart-data="bar.seriesdata">
          </canvas>
        </div>
      </div>
    </div>
```

I started to experience an issue  when the `<canvas>` elements expands across the page with even the parent has `col-md-6` or 50% width.

See photo:
![image](https://cloud.githubusercontent.com/assets/8317978/14645371/6743e9f0-0623-11e6-987f-42b7318261d1.png)

I noticed I had to resize the window so that the chart will follow the width of its parent.

Any help will be appreciated. Thanks!

**Comment by digitalinfamy** [comment]
I've got the same issue using the flex component in angular-material

**Comment by enderdickerson** [comment]
Similar issue here using flex with angular-material. Any solutions?

**Comment by alvachien** [comment]
I got the same issue here. I am using ui.router.
When it reach the first view contains the chart, the size is correct;
Whenever the second view contains the chart got hit, the size was not correct unless resize the window. 

Any comment?

**Comment by jtblin** [comment]
Need full repro steps.

**Comment by jtblin** [comment]
Chart.js only listens to the window resize event AFAIK as it is the only resize event that is available. If only part of the page is resized or just the parent container, you need to send a resize event normally using `$resize` e.g. `$scope.$emit('$resize')`.
