### ISSUE TITLE
Presence of a canvas makes angular-ui typeahead field forever visible

### ISSUE THREAD

**Issue by villasv** [jtblin/angular-chart.js#364]
When I included a doughnut chart in my page, the text field using ui-typeahead started showing a blank rectangle. Apparently the class of the input field no longer gets updated.

Form:
```
<input class="form-control"
    type="text"
    autocomplete="off"
    ng-model="vm.newAssetName"
    uib-typeahead="asset.name for asset in vm.assets | filter:$viewValue"/>
```

###### Empty Input (correctly invisible)
```
<input class="form-control ng-pristine ng-valid ng-empty ng-touched" aria-expanded="false" aria-owns="typeahead-3-1998" aria-autocomplete="list" type="text" ng-model="vm.newAssetName" autocomplete="off" uib-typeahead="asset.name for asset in vm.assets | filter:$viewValue">
```
###### Empty Input (Incorrectly visible)
```
<input class="form-control ng-pristine ng-untouched ng-valid" aria-expanded="false" aria-owns="typeahead-3-6413" aria-autocomplete="list" type="text" ng-model="vm.newAssetName" autocomplete="off" uib-typeahead="asset.name for asset in vm.assets | filter:$viewValue">
```

Because the removal of `<canvas>` fixes the problem, It can't be CSS as I thought before. I don't know what else could cause this.

**Comment by jtblin** [comment]
Canvas is a standard HTML element. Why are you opening the issue here? Is it happening only with the angular-chart.js directive or any type of canvas? I'd open the issue on ui-typeahead project.

**Comment by villasv** [comment]
The canvas tag is not the problem. The incorrect behavior manifest as soon as I put the chat-* class on it. I'll open the issue on ui-bootstrap as well.

I'll try to reproduce in a plunk later on.

**Comment by jtblin** [comment]
Please reopen when a repro case is provided.
