### ISSUE TITLE
Horizontal bar chart

### ISSUE THREAD

**Issue by baio** [jtblin/angular-chart.js#37]
Hi! Please add support for horizontal bar charts, it is often prefered way to display chart on mobile devices

**Comment by jtblin** [comment]
Horizontal bar charts would need to be implemented in Chart.js for me to include it in the directives. According [this issue](https://github.com/nnnick/Chart.js/issues/73), this is not in scope for the moment but it seems to have been implemented in some old fork of Chart.js.

Even if you manage to add this extension to Chart.js, there would still be some work to be allow it in this project as per #20 and #36 unfortunately.

**Comment by jtblin** [comment]
#36 is fixed and #20 show how to use an extension. If you get the code for the extension you should be able to use the horizontal bart chart with this lib following the instructions in #20.

**Comment by jtblin** [comment]
Example of integration of stacked bar chart: http://jtblin.github.io/angular-chart.js/examples/stacked-bars.html
