### ISSUE TITLE
Update StackedBar chart through '$scope.data = []' is not working 

### ISSUE THREAD

**Issue by llee** [jtblin/angular-chart.js#371]
### Overview

I am using Chart.StackedBar.js. It works for initial creation of the stacked chart, but I couldn't update the chart data through setting "$scope.data". I expect the stacked bar chart will redraw with updated data.

### My code looks like this:

`<canvas class="chart chart-base" chart-type="type" data="data" labels="labels"></canvas>`

`app.controller('StackedBarCtrl', function ($scope) {`
`    $scope.labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];`
`    $scope.type = 'StackedBar';`
`    $scope.data = [`
 `     [65, 59, 90, 81, 56, 55, 40],`
 `     [28, 48, 40, 19, 96, 27, 100]`
`    ];`
`  });`

// The following code is not working
`$timeout(function () {`
     `       $scope.data = [`
  `              [165, 159, 190, 181, 156, 155, 140],`
         `       [218, 148, 140, 119, 196, 127, 100]`
   `         ];`
  `      }, 3000);`

**Comment by cschoenfeld** [comment]
Same issue — and I went a step further. I captured the chart object as follows: 

`    			$scope.$on('create', function (event, chart) {
					$scope.chart = chart;
				});
`

And after updating $scope.data, I tried forcing the chart to refresh:
`$scope.chart.render();`

That didn't have any effect, either.

**Comment by surfjedi** [comment]
+1

**Comment by jtblin** [comment]
You should look at using Chart.js 2.x with angular-chart.js 1.x, there is native support for stacked bar charts now in chart.js 2.0. Otherwise please post a jsbin for repro.
