### ISSUE TITLE
Caching issue when loading new data

### ISSUE THREAD

**Issue by loykianos** [jtblin/angular-chart.js#374]
I use angular-chart.js to represent some results that I have stored in my database. When those results change in the database, even after refreshing the charts stay the same until I erase all cache, or if I open the console in cache-free mode. 

In order to clarify, I have different states and show multiple kinds of charts, which works fine. The only issue is that the data requests seem to get cached, so even if the response has different data, the charts stay the same.

Is there a way to keep the charts cache free?

**Comment by jtblin** [comment]
That has nothing to do with angular-chart.js, I'd guess maybe look at `$http` doc: https://docs.angularjs.org/api/ng/service/$http#caching although it says it's disabled by default. Maybe default cache headers on your http server?
