### ISSUE TITLE
List of options

### ISSUE THREAD

**Issue by marcgetqd** [jtblin/angular-chart.js#375]
Where do I find a list of options eg:

    $scope.options = {
      animation: false,
      showScale: true,
      showTooltips: true,
      pointDot: true,
      datasetStrokeWidth: 2,
      bezierCurve : false
    };

In the charts.js documentation there is no "datasetStrokeWidth" or "bezierCurve" etc. so just wondering where these are coming from.

**Comment by jtblin** [comment]
Where do the options come from? Maybe they're for Chart.js 1.x and the docs on Chart.hs site are for 2.0?

**Comment by Manningham** [comment]
Here are the docs for version 1.1.1 of chart.js: https://github.com/chartjs/Chart.js/tree/v1.1.1/docs

Howerver, I'm having some issues getting the options to work using angular 1.5.  Specifically, the charts only appear if the `responsive` option is set to `false`, and even then I am unable to change any other options from their defaults...
