### ISSUE TITLE
Horizontal Bar Chart Support

### ISSUE THREAD

**Issue by mtholdefer** [jtblin/angular-chart.js#376]
Chart.js just recently supported horizontal bar charts in their latest release ([https://github.com/chartjs/Chart.js/releases/tag/2.1.0]), could you add support for this feature?

**Comment by jtblin** [comment]
Done.

**Comment by emok032** [comment]
For some reason Horizontal-bar chart is the only chart not working. Can't find it in the library file(s) either. The documentation also looks off (see screenshot). The markup tab is showing the Pie Chart controller. Any ideas?

<img width="1269" alt="Screen Shot 2020-07-29 at 11 47 48 AM" src="https://user-images.githubusercontent.com/17553357/88822512-f0e19480-d191-11ea-91f9-426537a69c01.png">
<img width="1313" alt="Screen Shot 2020-07-29 at 11 47 42 AM" src="https://user-images.githubusercontent.com/17553357/88822515-f17a2b00-d191-11ea-83a7-275a72dbc7dc.png">
