### ISSUE TITLE
Duplicate charts showing in android 4.3 native browser.

### ISSUE THREAD

**Issue by akaradhey** [jtblin/angular-chart.js#377]
A duplicate charts are showing in android's native browser in android 4.3.

**Comment by jtblin** [comment]
Please provide repro.

**Comment by glauberataide** [comment]
I had the same problem using Angular Chart in my Ionic application. I solved it by removing some wrapping divs and using instead only Ionic tags. Here's my final code:

`<ion-content>
		<ion-item class="card item item-text-wrap">					
			<canvas id="pizza" class="chart chart-pie" chart-data="data" chart-labels="labels" chart-legend="true">
			</canvas>								
		</ion-item>
</ion-content>`
