### ISSUE TITLE
Support v2 of chart.js

### ISSUE THREAD

**Issue by kustnodi** [jtblin/angular-chart.js#378]
### Overview

Angular-chart.js doesn't support v2 of chart.js

Please make sure to review and check all of these items:

- [X ] Use latest version of the library
- [X ] Make sure you've included all the dependencies e.g Chart.js, angular, css file
- [X ] Include a repro case, see below.

### Step to reproduce

[Here's a plunk](http://plnkr.co/edit/7Khl0Q0bfbZY33qkbh50?p=preview) trying to use Chart.js v2.1.2.  In the console there's an error: "TypeError: (intermediate value)[type] is not a function on line 197 of angular-chart.js
`chart = new ChartJs.Chart(ctx)[type](data, options);`

Apparently the type property was removed from the Chart object

If you change the line
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.2/Chart.min.js"></script>`  in index.html to 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.min.js"></script>`
the chart displays correctly

**Comment by rhuanbarreto** [comment]
Please reopen!!! How to solve this???

**Comment by jtblin** [comment]
Man, have you taken the time to read the 2nd paragraph of the readme???

**Comment by rhuanbarreto** [comment]
Yes. It works now. But it's not too obvious how to do this. You could put on master branch 2 js files. One for chartJs 1.1.x and another for 2.0.x
