### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by tonik** [jtblin/angular-chart.js#38]
The demo page does not work.

Also I cant get a line chart working it says undefined field data.datasets my chart code looks like this:  

<cjs-line dataset="allreports" autofit="true"></cjs-line>

	$scope.allreports = {
											labels : [ "Jun", "July",
													"Aug"],
											datasets : [ {
												fillColor : "rgba(151,187,205,0.5)",
												strokeColor : "rgba(151,187,205,1)",
												pointColor : "rgba(151,187,205,1)",
												pointStrokeColor : "#fff",
												data : [1, 2, 3]
											} ]
										};

All it says is: "Error: data is undefined" WHy.

**Comment by Ehesp** [comment]
Demo page works fine, also line does here..

What does your HTML/Directive look like?

**Comment by jtblin** [comment]
Demo page works fine for me too. What is not working for you exactly and with which browser / OS?

As also pointed out by @Ehesp, what does your markup looks like? It'd be great to have a jsbin to repro the issue, see [template](http://jsbin.com/dufibi/3/edit?html,js,output). Looking at your js code, I don't think it can match what is required. Have you actually looks like at the examples and chart options as per the [readme](https://github.com/jtblin/angular-chart.js) or [examples](http://jtblin.github.io/angular-chart.js/) e.g. the colours and the data should probably be separated.
