### ISSUE TITLE
Disable line chart fill for 2.0

### ISSUE THREAD

**Issue by emcniece** [jtblin/angular-chart.js#383]
Can't quite figure out how to disable the fill under lines for the `chartjs-2.0` branch. What is the correct option?

http://plnkr.co/edit/UESf8uly1vI0QnCRgTua

**Comment by jtblin** [comment]
```
elements: {
        line: {
                fill: false
        }
}
```

**Comment by emcniece** [comment]
Beautiful - thank you so much!
