### ISSUE TITLE
Pie Chart lines overlap

### ISSUE THREAD

**Issue by jpike88** [jtblin/angular-chart.js#384]
Using angular-chart 2.0 alpha, using latest build of angular material

Pie chart looks like this:

![screen shot 2016-05-14 at 9 51 27 am](https://cloud.githubusercontent.com/assets/9585787/15264694/8358f60e-19b9-11e6-9c75-31e2b0fd45b3.png)

**Comment by jtblin** [comment]
Post a repro

**Comment by jpike88** [comment]
You shouldn't need a repo, it's present in the example files (chart.html for example).

Using Mac OS X El Capitan Safari

**Comment by jtblin** [comment]
Yes it needs a repro as there is no problem with the pie chart example, and there are integration tests verifying that as well. The issue template indicates how to post a repro, you chose to ignore it and open an issue that I cannot reproduce hence why I close the issue. Feel free to reopen it once you add a repro case.

![image](https://cloud.githubusercontent.com/assets/1388974/15266372/1001d9f0-19e6-11e6-8725-6e1f36d2174e.png)

**Comment by jpike88** [comment]
Look at the image you posted! There's overlapping lines in the centre, just like the one I originally put in!

**Comment by jpike88** [comment]
I just took this screenshot of the pie chart on the stable branch, straight from the website. It looks different to all of the images posted in this thread so far. Why are you insisting on a repro... look at the images.

![screen shot 2016-05-14 at 3 14 55 pm](https://cloud.githubusercontent.com/assets/9585787/15266394/f59c34ec-19e6-11e6-9dd6-dba0d4ae899e.png)

**Comment by jtblin** [comment]
It wasn't clear what was the issue, your original pie chart seems to be truncated. Anyhow that would be an issue with Chart.js lib: https://github.com/chartjs/Chart.js

**Comment by jpike88** [comment]
Nope that's me just cropping the image poorly. I'm referring to the middle of the chart where lines aren't lining up well, it may just be that they're too thick.
