### ISSUE TITLE
dist folder of 0.10.2

### ISSUE THREAD

**Issue by cemo** [jtblin/angular-chart.js#385]
I think that there is a mistake in dist folder of 0.10.2 (maybe in other versions as well). It display that there is not change since 0.9.0 for js files. Is this expected?

https://github.com/jtblin/angular-chart.js/tree/0.10.2/dist

**Comment by jtblin** [comment]
I think that's correct, the latest changes to `angular-chart.js` code itself were in March. The changes on 0.x have only been to upgrade the version of Chart.js, css changes, and dependencies changes.
