### ISSUE TITLE
Cannot display chart because of "display:none"

### ISSUE THREAD

**Issue by LujunWeng** [jtblin/angular-chart.js#386]
I would like to use a button to hide and show the chart. It worked at first. But I didn't want the chart being showed when the page is first loaded. So I added `display:none` to the related element and it did not work. 

Check this out (`panel-heading` is the button to show and hide the chart):
http://jsbin.com/nosavu/edit?html,css,js,output

I use jQuery to implement show and hide the chart. 
I also set width and height attributes in `<canvas>`. But I found this did not affect this problem.
As I deleted the `display:none`, it worked again.

**Comment by jtblin** [comment]
I don't recommend mixing angular and jquery. You'd better use something like ng-show to achieve the same effect, you can see some examples of that in `examples/tabs.html`. I'd suggest you post this type of question on StackOverflow.

**Comment by LujunWeng** [comment]
Thank you! You are right, it is because of I using jQuery. I should have test it first without jQuery. I thought it might be a library's problem, so I posted it here. Sorry. :smile:
