### ISSUE TITLE
update chart on window resize with debounce

### ISSUE THREAD

**Issue by niemyjski** [jtblin/angular-chart.js#388]
```js

    function link(scope, element, attrs, ctrl) {
      var chart;

      var debouncedUpdate = debounce(function() { updateChart(chart)}, 150);
      var window = angular.element($window);
      window.bind('resize', debouncedUpdate);

      scope.$on('$destroy', function () {
        window.unbind('resize', debouncedUpdate);
        destroyChart(chart, scope);
      });
    }
```

It would be nice if

**Comment by jtblin** [comment]
You haven't completed your sentence, what do you want exactly? :)

**Comment by niemyjski** [comment]
The chart should be throttled resized on window change, there's currently no way to trigger an update or I'd do this code myself.

**Comment by jtblin** [comment]
Not sure what the `debounce` function is supposed to accomplish. Moreover, not sure why we'd call `updateChart` on a `resize` event, the chart will only be redrawn if  values change.

**Comment by jtblin** [comment]
I am looking a bit more into that. My understanding was that Chart.js was already listening to `resize` events and resizing the canvas on change when `responsive` is set to true which is the default for this lib.

https://github.com/chartjs/Chart.js/blob/959b4eedf6f504cadcff97d8a84bf39dd9386c67/src/core/core.js#L54

Let me know if I'm misunderstanding something.

**Comment by jtblin** [comment]
@niemyjski please feel free to reopen if you have more details, it's unclear to me what you want to achieve here.
