### ISSUE TITLE
Click event doesn't apply scope changes afterwards

### ISSUE THREAD

**Issue by bhasden** [jtblin/angular-chart.js#39]
The click event doesn't apply scope changes afterwards, so any changes to data or any other scope changes don't take effect. The easy fix for this issue to add a call to scope.$apply() after the call to the click event handler.

```javascript
if (scope.click) {
    cvs.onclick = function (evt) {
        var click = chart.getPointsAtEvent || chart.getBarsAtEvent || chart.getSegmentsAtEvent;

        if (click) {
            var activePoints = click.call(chart, evt);
            scope.click(activePoints, evt);
            scope.$apply() // Add this line
        }
    };
}
```

If you'd like to me to submit a pull request or if you need any more information please let me know.

Thanks.

**Comment by jtblin** [comment]
Thanks for the report, done in `0.3.16`.
