### ISSUE TITLE
angular-chart.css file is missing

### ISSUE THREAD

**Issue by ranbuch** [jtblin/angular-chart.js#390]
after running:
> npm install --save angular-chart.js

I don't have this file in my "node_modules" directory:
angular-chart.js/dist/angular-chart.css

right now I'm using this CDN:
> //cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css

so no big deal . . .

**Comment by jtblin** [comment]
Which version of angular-chart.js did npm install? There is no more css in the latest 1.x-alpha series.

**Comment by edohkodjo** [comment]
I don't have the css file me too.
The chart is not displayed in my html page. I don't know if it is related to the missing of css file or something else.
my code: index.html

      <script src="/lib/chart.js/dist/Chart.min.js"></script>
      <script src="/lib/angular-chart.js/dist/angular-chart.min.js"></script>
      ....
      <canvas id="line" class="chart chart-line" chart-data="data"
      chart-labels="labels" chart-series="series" chart-options="options"
      chart-dataset-override="datasetOverride" chart-click="onClick">
      </canvas>


I include 'chart.js' module in my app.js and this is the code of my controller:

    $scope.labels = ["January", "February", "March", "April", "May", "June", "July"];
	$scope.series = ['Series A', 'Series B'];
	$scope.data = [
	   [65, 59, 80, 81, 56, 55, 40],
	   [28, 48, 40, 19, 86, 27, 90]
	];
	$scope.onClick = function (points, evt) {
	   console.log(points, evt);
	};
	$scope.datasetOverride = [{ yAxisID: 'y-axis-1' }, { yAxisID: 'y-axis-2' }];
	$scope.options = {
	    scales: {
	     	yAxes: [
	       		{
	         		id: 'y-axis-1',
	         		type: 'linear',
	         		display: true,
	         		position: 'left'
	       		},
	       		{
	         		id: 'y-axis-2',
	         		type: 'linear',
	         		display: true,
	         		position: 'right'
	       		}
	     	]
	   	}
	 };


Maybe, there is something I did wrong. How to solve it and display the chart?

**Comment by andymurakami** [comment]
@edohkodjo I have the same issue.. do you fix this ?

**Comment by jtblin** [comment]
There hasn't been a CSS file required since a very long time.
