### ISSUE TITLE
Chart.js version

### ISSUE THREAD

**Issue by sergiofigueras** [jtblin/angular-chart.js#392]
Hello guys,

I'm in a problem with line chart using angular-charts. Basically, when I create a stacked linechart with multiple series, it seems that the fill color just is with some kind of opacity that I don't want. I've tested it with Chart.js 2.1.3 and it was ok at http://codepen.io/anon/pen/MydZVB

In fact, I would like the blue session in a deep blue as the line is, the green one too, and all the others. But some kind of opacity is being displayed.
Here's the result:

<img width="522" alt="captura de tela 2016-05-17 as 20 03 26" src="https://cloud.githubusercontent.com/assets/1733227/15354400/d0595e64-1cc3-11e6-9253-c92dc15720c1.png">

Here's my chart config:

```
        vm.defaultChartOptions = {
            legend : {
                position: 'bottom', display: true
            },
            elements: {
                point : {
                    radius: 5
                }
            },
            tooltips: {
                mode: 'label',
            },
            hover: {
                mode: 'label'
            },
            scales: {
                xAxes: [{
                    gridLines: {
                        lineWidth: 0,
                        color: "rgba(255,255,255,0)"
                    }
                }],
                yAxes: [{
                    stacked: true,
                    gridLines: {
                        lineWidth: 0,
                        color: "rgba(255,255,255,0)"
                    },
                    "ticks": {
                        "min": 0
                    }
                }]
            }
        };
```

As a workaround, how can I change manually the version of charts.js from 2.0.2 to 2.1.3 (newest one)?

**Comment by jtblin** [comment]
The latest `alpha6` uses `2.x` as a dependency so just running `npm install` or `bower install` should bring the latest charts.js , e.g. https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/package.json#L60
