### ISSUE TITLE
angular-chart.js tickmark issue

### ISSUE THREAD

**Issue by dmitriy-reisys** [jtblin/angular-chart.js#394]
Is there a way to change the number of tick marks on the Y axis? I have about 17 of them, and I need to shrink that number to about 5 or 7.
![image](https://cloud.githubusercontent.com/assets/15931210/15505116/0fdcda9a-2190-11e6-910d-cad5e31370b9.png)

**Comment by jtblin** [comment]
Check Chart.js options.
