### ISSUE TITLE
Legend positions on charts

### ISSUE THREAD

**Issue by AJ1985** [jtblin/angular-chart.js#395]
Hi Jtblin,

I am using chart js (version 1.1.1) with angular -chart.js. By default the chart-legend position is below the chart. As per my requirements I need this legend to be on the right hand side of the chart. 

I tired different options combinations as well Chart.defaults.global.legend.position but nothing worked. 
Could you please suggest how it can be achieved.

Ajay

**Comment by jtblin** [comment]
You can get a handle of the chart by listening to the `create` event on the chart, then call the `generateLegend` and position it where you want.
