### ISSUE TITLE
Gauge directive

### ISSUE THREAD

**Issue by james-bell** [jtblin/angular-chart.js#396]
I hacked together a directive for a gauge display by modifying the doughnut chart.  I thought I'd share.  This works for me but it's one of my first stabs at directives, I'm sure someone can make it better.  This is for the Chart.JS **2.0** branch.
![gauge](https://cloud.githubusercontent.com/assets/7467130/15576984/92368ec0-2328-11e6-9487-5957ed30fef6.PNG)

Directive:
```javascript
app.directive("doughnutGauge",function()
{
  return 
  {
    restrict: "E",
    scope: 
    {
      gaugeSize: '@', //size in px
      gaugeOptions: '=',
      gaugeColors: '=',
      gaugeValue: '@', //value displayed 0-100
      valueSuffix: '@', //optional suffix, e.g. '%'
      gaugeTitle: '@', //large title under gauge
      subTitle: '@',  //smaller text under title
    },
    link: function($scope, $element, $attrs) { 
      $attrs.$observe('gaugeValue', function(value) {
        if (value) {
          $scope.gaugeData=[value,100-value]; 
        }
      });
      $scope.gaugeLabels=["Score",'']; 
    },
    template: 
    '<div ng-if="gaugeSize" style="text-align:center;">'+
    '<canvas class="chart chart-doughnut" height="{{gaugeSize}}" width="{{gaugeSize}}" '+
    'chart-legend="true" chart-options="gaugeOptions" chart-colors="gaugeColors" '+
    'chart-data="gaugeData" chart-labels="gaugeLabels">'+
    '</canvas> '+
    '<div style="margin-top:{{(-gaugeSize/2.2)}}px; font-size:{{(gaugeSize/6)}}px; font-weight:bold;">{{gaugeValue}}{{valueSuffix}}</div>'+
    '<div style="font-size:{{(gaugeSize/7.5)}}px;">{{(gaugeValue)?gaugeTitle:\'No Data\'}}</div>'+
    '<div style="font-size:{{(gaugeSize/10)}}px;">{{subTitle}}</div></div>'
  }    
});
```

Javascript:
```javascript
$scope.stats = {AVG_SCORE:80.3, SCORED:4101};
$scope.doughnutColors=['#8C9EFF','#DDDDDD'];
$scope.doughnutOptions = 
{
  responsive:false, 
  responsiveAnimationDuration:500, 
  maintainAspectRatio:true, 
  cutoutPercentage:60, 
  circumference:Math.PI, 
  rotation:(-1 * Math.PI), 
  legend:{display:false} 
};
```

HTML:
```html
<doughnut-gauge gauge-size="150" gauge-options="doughnutOptions" gauge-colors="doughnutColors"
  gauge-value="{{stats.AVG_SCORE}}" gauge-title="Average Score" sub-title="({{stats.SCORED}} scores)">
</doughnut-gauge>
```

Bummers:
Negative margins are an ugly hack
Fixed size and non-responsive
Different colors based on the value would be nice (e.g. red for less than 50% full)
Hovering on the grey area attempts to display the "unfilled" value

**Comment by jtblin** [comment]
Thanks @james-bell. Do you want to send a PR with this directive in the `examples/` directory and a sample html file demonstrating its use? That could be useful for other people and I don't think I'll want to keep the issue opened forever ;)

**Comment by james-bell** [comment]
Made something that probably looks like the worst PR ever, hopefully you can fix it.  I'm an old school guy that hand rolls everything: no idea what this new-fangled Git or Gulp stuff is.  (And: get off my lawn!)

**Comment by adamtaylor13** [comment]
Hey, I love this idea. I've used some of the options you've got to design my own gauge. One thing I notice, however, is that this gauge only fills halfway at "max" value.

i.e. For 10 out of 10, I get this: 
![image](https://user-images.githubusercontent.com/2922753/30709259-4041cbea-9ec7-11e7-9cd8-718bbf97ff9f.png)

What did you do to get around that?
