### ISSUE TITLE
angular-chart.js cannot find module chart.js

### ISSUE THREAD

**Issue by rajeevfaya** [jtblin/angular-chart.js#397]
while installing angular-chart.js user bower i am getting an error as **cannot find module chart.js**. but at angular-chart.js => dist  => angular-chart.js(line no 7) i changed require('chart.js') to require('Chart.js') and it works fine. i am using webpak to load modules.. please give me a solution for this.. thank you

**Comment by jtblin** [comment]
You should use npm with webpack and you won't have the issue, this is a problem with Chart.js lib that had different spellings in bower and npm...
