### ISSUE TITLE
Ticks min option not retained after update of data.

### ISSUE THREAD

**Issue by lonerzzz** [jtblin/angular-chart.js#398]
When the following 'min' option is set on a bar chart, it ensures that the minimum value of the chart is zero as expected when the chart is first rendered.

`					var costsBarChartOptions =
					{
						scale:
						{
							ticks:
							{
								min: 0
							}
						},
						tooltips:
						{
							callbacks:
							{
								label: $scope.getCostLabel
							}
						}
					};
`

However, once the 'costs' data is updated, the min value is no longer respected and the range is based on the minimum and maximum value from the dataset.

`<canvas class="chart chart-bar" chart-data="costs" chart-labels="barChartLabels" chart-options="costsBarChartOptions" style="width:100%; height:100%"></canvas>
`

**Comment by jtblin** [comment]
Please provide repro steps as per the issue template.
