### ISSUE TITLE
Add check Data has been defined

### ISSUE THREAD

**Issue by bryanrscott** [jtblin/angular-chart.js#40]
When a dataset is defined as an attribute of a json object (eg myObject.data) and labels are defined, sometimes the console can display the following error until the json is resolved.

TypeError: Cannot read property '0' of undefined 

Adding a check for data corrects.   

<pre>
function getData (labels, data, colours) {
    colours = colours || Chart.defaults.global.colours;
    if (data) {
        return labels.map(function (label, i) {
          return {
            label: label,
            value: data[i],
            color: colours[i].strokeColor,
            highlight: colours[i].pointHighlightStroke
        };
        });
    } else {
        return [] ;
    }
</pre>

**Comment by jtblin** [comment]
Thanks, added a fix for this in `0.3.17`.
