### ISSUE TITLE
Please add JSBin template for latest 2.0 branch

### ISSUE THREAD

**Issue by lonerzzz** [jtblin/angular-chart.js#400]
Before submitting my last bug, I attempted to create a JSBin against the latest branch but was only getting internal angular-chart errors which provided no indication as to the problem. As such, I submitted the bug without the the JSBin to reproduce and it was immediately closed. Please add a template for supporting the new Chart.js 2.0 branch in JSBin to make it straightforward to reproduce.

**Comment by jtblin** [comment]
Done, updated the README.md in each branch and the issue template.

http://jsbin.com/rodunob/edit?html,js,output
