### ISSUE TITLE
Chart reloads when $scope.data get more elements

### ISSUE THREAD

**Issue by dilumn** [jtblin/angular-chart.js#403]
Every 5 second my chart gets more data to show in the chart, that means there will be a new object for `$scope.labels` & `$scope.data[i].push(newValue)` 

Because of I add more data to show, the chart reloads every time I get a new set of data.

So is there any solution for this type of scenario?

**Comment by adrogon** [comment]
Hi @dilumn,

Your chart gets redrawn because it is animated by default.

Simply turn off the animation should achieve what you intend.

```
$scope.options = {
  animation: false
};
```

Here is an example : https://plnkr.co/edit/hJqG8SSdG7Clospryv4T?p=preview

**Comment by dilumn** [comment]
Thanks @adrogon `plnkr` example is same kind of implementation what I want.
I think it can't work with animations because in that `output.jsbin.com` example they are not adding new elements.
