### ISSUE TITLE
Tooltip not working with 0 values

### ISSUE THREAD

**Issue by SaSH17** [jtblin/angular-chart.js#406]
Please look at following Plunker - The bar with label A shows no Tooltip in IE11.
http://plnkr.co/edit/p0bepcBrfQ31EoZsrtso?p=preview

I created the same chart only with chart.js library and it was working.

Anybody know why or any solutions ?

**Comment by jtblin** [comment]
Works for me (it displays bars):

![image](https://cloud.githubusercontent.com/assets/1388974/15856586/b90efbb0-2cf9-11e6-851b-655a91903cf7.png)

**Comment by SaSH17** [comment]
yes the bars are working, but the tooltip for A is not working...

**Comment by jtblin** [comment]
Yeah realised afterwards... I don't use Windows...

**Comment by SaSH17** [comment]
But any idea why the chart has this behavior ? Cause I have also the issue, when I have a bar with a high value and a bar with low value, then the tooltip is also not showing...

**Comment by jtblin** [comment]
No idea. Probably an issue with Chart.js as there is nothing this lib does with specific about tooltops. Please provide repro steps or post your question to StackOverflow.
