### ISSUE TITLE
How to get instance of chart to refresh it?

### ISSUE THREAD

**Issue by djleonskennedy** [jtblin/angular-chart.js#409]
Have issue, after chart loaded and data updated asynchronously, charts **freezes**, they're updating after mouse hover or click only, seems like instance should be refreshed or any solutions?

**Comment by AndriiDidkivsky** [comment]
Have same issue.

**Comment by RuslanaGRA** [comment]
I have the same problem((

**Comment by jtblin** [comment]
I don't understand the problem, can someone post a repro case? Haven't look
at the demo site and examples/ for sync refresh examples.

**Comment by djleonskennedy** [comment]
Problem is when data updates. Chart couldn't refresh, it's refreshes when i hover over it
Can I refresh chart instance manually?

**Comment by djleonskennedy** [comment]
Here the code example, 


```
  vm.data = [];
  vm.labels = [];
  vm.total = 0;
  
  function render() {
    statisticsService.topGroup(vm.dateFrom, vm.dateTo, vm.separator)
      .then(
      ({ chartData }) => {
        vm.data = chartData.map(x => x.data);
        vm.labels = chartData.map(x => x.label);
        vm.total = chartData.reduce((a, c) => a + parseInt(c.data), 0);
      },
      error => {
        const message = `MANTU STATISTIC MODULE ERROR: ${error.reason}`;
        notify.error(message);
        throw new Error(message)
      }
    );
  }
```

**Comment by jtblin** [comment]
As you can see from the [demo](http://jtblin.github.io/angular-chart.js/), the chart refreshes automatically. This is not a repro case, please post a repro case using plunkr or jsbin.

**Comment by djleonskennedy** [comment]
Seems like it is not issue for this repo, Thank you that took the time
