### ISSUE TITLE
Is there any way to set the values on the y-axis?

### ISSUE THREAD

**Issue by jseminck** [jtblin/angular-chart.js#41]
Hi,

I've been trying to figure this out but couldn't get to it... have no experience with Chart.js either. Is there any way to set the values on the y-axis in a line chart? E.g. my chart runs between 80 and 95, but I want the values on the y-axis to be between let's say 0 and 120. This way my chart doesn't start straight from the bottom but starts already somewhere above the middle and the swings between values don't look as too big jumps.

I assume this should be possible but really can't find the function for it.

Thanks,

**Comment by jtblin** [comment]
It doesn't seem to be possible on a line chart: http://www.chartjs.org/docs/#line-chart-chart-options.

On [bar chart](http://www.chartjs.org/docs/#bar-chart-chart-options) `scaleBeginAtZero` may be similar to what you need but I'm unsure. 

You may want to open a feature request on [Chart.js](https://github.com/nnnick/Chart.js/issues).

**Comment by afraz-ahmad** [comment]
scales: {
                      yAxes: [{
                        id: 'A',
                        type: 'linear',
                        position: 'left',
                        scaleLabel: {
                               display: true,
                               labelString: 'Amount'
                             }
                      }, {
                        id: 'B',
                        type: 'linear',
                        position: 'right',
                        ticks: {
                          max: max_value,
                          min: min_value
                        },
                        scaleLabel:{
                            display:true,
                            labelString:'Date'
                        }
                      }]
                    }

**Comment by ghizoulo** [comment]
Hello, 
Is there a way to do it in angular 4 @afraz-ahmad ?
