### ISSUE TITLE
legend not displayed for radar Angular-chart.js

### ISSUE THREAD

**Issue by mnaouali** [jtblin/angular-chart.js#412]
### Overview

Describe the issue. What is the issue and what did you expect?

Please make sure to review and check all of these items:

- [x] Use latest version of the library
- [x] Make sure you've included all the dependencies e.g Chart.js, angular, css file
- [x] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent.** 
Here is a [jsbin template](http://jsbin.com/dufibi/3/edit?html,js,output) for convenience.

**Comment by mnaouali** [comment]
I'm trying to create a radar chart using angular-chart js and chartjs 2.1. I was able to display the graph but not the legend. would you help me to display it. here is a [plunker](http://plnkr.co/edit/09WSHD?p=preview) for what I've done

**Comment by jtblin** [comment]
You need to set the options and series, see http://plnkr.co/edit/386pA8?p=preview.

```
$scope.options = { legend: { display: true } };
  $scope.series = ["Series A", "Series B", "Series C", "Series D"];
```
