### ISSUE TITLE
tooltip label block color shows only the border without fill

### ISSUE THREAD

**Issue by D4NH** [jtblin/angular-chart.js#414]
When hovering over a multiLine graph, the tooltip displays the labels where the blocks only have colored borders.

<img width="1095" alt="screen shot 2016-06-14 at 11 14 36" src="https://cloud.githubusercontent.com/assets/6664547/16037526/33dbac40-3221-11e6-9220-8cff75af7c4b.png">

The example from ChartJS shows them filled.

![screen shot 2016-06-14 at 11 15 19](https://cloud.githubusercontent.com/assets/6664547/16037562/544c5970-3221-11e6-9cb2-e7d5978f94b0.png)

### Step to reproduce

http://plnkr.co/edit/dGKEKzNbk5YIXtkqM9oH?p=preview

Is there any setting to have them filled as the same color of the linegraph?
Seems like the blockcolor in the tooltip fade away after loading the graph.

**Comment by D4NH** [comment]
found it at line 248, will try creating a Pull Request.

instead of:

`pointHoverBackgroundColor: '#fff',`

should be:

`pointHoverBackgroundColor: rgba(color, 1),`

**Comment by D4NH** [comment]
for some reason I can't commit my changes, getting: 

> Authentication failed for 'https://github.com/jtblin/angular-chart.js.git/'
Pushing to https://github.com/jtblin/angular-chart.js.git
2016-06-15 09:30:54.909 git-credential-sourcetree[30939:8511127] Error (internetKeychainItemForServer:withUsername:path:port:protocol:) - The specified item could not be found in the keychain.

must be an issue in my system

**Comment by jtblin** [comment]
You need to fork the repo to send pull requests, you can't push to the repo
directly.

**Comment by D4NH** [comment]
yes I did, but I cant push it:

<img width="675" alt="screen shot 2016-06-15 at 10 06 38" src="https://cloud.githubusercontent.com/assets/6664547/16072397/f2b1007e-32e0-11e6-92f7-680a01605767.png">

**Comment by jtblin** [comment]
It looks like you're trying to push to my repo directly:

> Pushing to https://github.com/jtblin/angular-chart.js.git

See https://help.github.com/articles/using-pull-requests/.

**Comment by jtblin** [comment]
Merged, thanks for the PR.
