### ISSUE TITLE
Canvas Line chart not supporting less then 0 float value in data

### ISSUE THREAD

**Issue by vijaypatoliya** [jtblin/angular-chart.js#415]
$scope.line2 = {
        labels: result.days,
        data: [
                result.data,
          **['0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.90']**
                ],
        colours: [{
            "fillColor": "rgba(61, 177, 255, 0.4)",
            "strokeColor": "rgba(0, 153, 255, 0.8)",
            "pointColor": "#B1E0FF",
            "pointStrokeColor": "#rgba(0, 153, 255, 0.8)",
            "pointHighlightFill": "#fff",
            "pointHighlightStroke": "rgba(0, 153, 255, 1)"
            },
          {
            "fillColor": "rgba(255, 51, 51, 0.4)",
            "strokeColor": "rgba(255, 51, 51, 0.8)",
            "pointColor": "#FFCCCC",
            "pointStrokeColor": "#rgba(255, 51, 51, 0.8)",
            "pointHighlightFill": "#fff",
            "pointHighlightStroke": "rgba(255, 51, 51, 1)"
                }]
      } 

Its not working. If any one value is greater then 1 then works. But all value less then 0 then its loading and not rendering chart.

I used "angular-chart.js": "~0.5.2" version.

**Comment by jtblin** [comment]
It's a known chart.js limitation, fixed in 2.0 I think so you'll need to upgrade.
