### ISSUE TITLE
How do I specify the colors of each segment

### ISSUE THREAD

**Issue by increos** [jtblin/angular-chart.js#42]
I would like to specify the color of a segment in a Doughnut chart based on the type of data. Any direction is much appreciated. Thank you.

**Comment by jtblin** [comment]
What do you mean by based on the type of data? You can specify the colours you want using the `colours` attribute, they will be applied with the same order.

**Comment by increos** [comment]
Sorry I wasn't very clear

I created an array 
$scope.colors = ['#FD1F5E','#1EF9A1','#7FFD1F','#68F000'];
in the markup specified colours="colors"

All the segments show up as black. I am sure I am doing something wrong..

**Comment by jtblin** [comment]
The colours need to be an object as follow (you don't need to use `rgba` colour, html colour is fine too):

```
{ // blue
      fillColor: "rgba(151,187,205,0.2)",
      strokeColor: "rgba(151,187,205,1)",
      pointColor: "rgba(151,187,205,1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(151,187,205,0.8)"
    }
```

I'll probably make a change soon to accept a string and construct a default object soon.

**Comment by increos** [comment]
Thank you. That works!!  It will be nice however to be able specify strings but not a showstopper. Kind of like the way it is specified in the Chart.js docs, but through the attribute way i.e the way you have implemented, data / legend/seres. which I found to be more elegant than the other angular chart.js libraries. Keep up the great work

```
var data = [
    {
        value: 300,
        color:"#F7464A",
        highlight: "#FF5A5E",
        label: "Red"
    },
    {
        value: 50,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Green"
    },
    {
        value: 100,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Yellow"
    }
]
```

**Comment by jtblin** [comment]
Done, you can now pass hex strings as per your example ;)

    $scope.colors = ['#FD1F5E','#1EF9A1','#7FFD1F','#68F000'];
