### ISSUE TITLE
Chart.js was not loading + when finally loaded it has Error: [$injector:unpr] Unknown provider: $compileProvider Isue

### ISSUE THREAD

**Issue by sandnath** [jtblin/angular-chart.js#420]
First I had issues with loading Chart.js. My bower was this...
 "angular-chart.js": "0.10.2",
 "Chart.js": "2.1.6",
And it says the module cannot be found even though I added 'Chart.js' in my module list

Then I modified my bower...added this...
"angular-chart.js": "0.10.2",
 "Chart.js": "2.1.6",
"Chart-js": "2.1.6"

- WHICH ITSELF IS WEIRD... but anyway.. I can accept it if it works... BUT I have other issues 
Now it loads and I checked in angular.js that moduleFn now is the Chart.js module .....
 
```
try {
        if (isString(module)) {
          **moduleFn** = angularModule(module);
          runBlocks = runBlocks.concat(loadModules(moduleFn.requires)).concat(moduleFn._runBlocks);


```

moduleFn is NOT undefined 

But then it has this issue...
"[$injector:unpr] Unknown provider: $compileProvider
http://errors.angularjs.org/1.5.6-build.4807+sha.9355aea/$injector/unpr?p0=%24compileProvider"

I checked the moduleFn._invokeQueue and it shows array of 9 with compileProvider entries of 7 of them and they are...
chartBase 
chartLine
chartBar
chartRadar
chartDoughnut
chartPie
chartPolarArea

I am not sure but all these are not present in the Chart.js\src\charts\

That location only has ...

Chart.Line.js
Chart.Bar.js
Chart.Radar.js
Chart.Doughnut.js

Chart.PolarArea.js

Chart.Bubble.js
Chart.Scatter.js

Is that the reason for this error or something else? Someone please help - I am pulling my hair on this..

Thanks
San D

**Comment by jtblin** [comment]
Please use stackoverflow for this type of question.

**Comment by sandnath** [comment]
Thanks jtblin. I saw others coming with issues to get them resolved here. 
But anyways, appreciate your special treatment to me!

**Comment by jtblin** [comment]
Well you completely discarded the issue template, delete the questions and checkboxes, didn't provide a jsbin template so you obviously do not care. As said in the issue template if you had taken the time to read it, I may close this kind of issues immeditely. Moreover you didn't even try to search for similar issues which would have brought a few similar closed ones in this tracker, let alone Google or Stackoverflow. Last this is a basic "I don't know how to use Angular" question so it is not an issue with the lib and therefore better suited to StackOverflow.

I honestly don't have time for this...

**Comment by sandnath** [comment]
Sorry, I did not discard the template - I checked many questions with no template answer - suddenly there is rule only for me...  And btw I searched Google or stackoverflow enough, This is not a angular question... all my other libraries are working except yours... anyways - I resolved it myself - I do not need your library - as I just got another much better charting library working for me... so thank you!
