### ISSUE TITLE
Line tension

### ISSUE THREAD

**Issue by mkamioner** [jtblin/angular-chart.js#421]
Hi,

I am using the beta 1.0.0. 

How can I get line tension on my line graphs? I need the graph to be straight lines but the lines always seemed to be curved. I tried adding `lineTension: 0` into the options but it doesn't seem to change anything...

Thanks in advance (and for the AWESOME module)!
~Mo

**Comment by jtblin** [comment]
According to [chart.js docs](http://www.chartjs.org/docs/) it'd be `line.tension`.

**Comment by mkamioner** [comment]
`line: {tension: 0}` does not work either :-/

I found the lineTension concept here: http://www.chartjs.org/docs/#line-chart-data-structure

**Comment by bezineb5** [comment]
Did you put it into the "elements" object? It seems that `elements: { line: {tension: 0} } `works.

**Comment by ravishan110** [comment]
i am using `elements : { line : { tension:0}}` , still the lines are not straight.

In Ejs template
`<canvas class="chart chart-line" chart-data="lineData" chart-labels="lineLabels" chart-series="lineSeries" chart-options="lineOptions" chart-click="onClick"></canvas>`

In Angular App
`$scope.lineOptions ={ elements : { line : { tension : 0 } } };`

Kindly suggest any solution.

**Comment by akshitj** [comment]
+1 for what @ravishan110 said.  I just added 
elements: {
        line: {
          tension: 0
        }
}
to $scope.options and rest of the code is same as given in the "getting started" line chart example. Can anyone help please

**Comment by akshitj** [comment]
hey @ravishan110 so this is how I solved my problem. I don't know if you have a simillar issue. I used bower to install this package so it installed the latest stable version ie. 10.0.2 which uses chart.1.x but tension is maybe chart.2.x fun. So I installed latest package(beta) by command 
`bower install --save angular-chart.js#1.0.0-beta1`
This solved my problem.

**Comment by ravishan110** [comment]
@akshitj Thanks!!! . That solved my issue.

**Comment by jtblin** [comment]
@akshitj @ravishan110 fyi the latest is `1.0.0`, not `1.0.0-beta1`. I've now merged into master.
