### ISSUE TITLE
Bower update to latest Chart.js

### ISSUE THREAD

**Issue by sweety-wo** [jtblin/angular-chart.js#422]
I use bower to install angular-chart.

Please update the bower to have latest Chart.js lib, as it is not compatible 
with "angular-chart.js": "~0.10.2" and Chart.js v1.1.1

if I replace Chart.js v2.1.6, I'm able to set colors with it, and many of the issues has been fixed.

Thanks....

**Comment by jtblin** [comment]
Can you point to the `1.0.0-beta1` version for now at https://raw.githubusercontent.com/jtblin/angular-chart.js/chartjs-2.0/dist/angular-chart.min.js which is compatible with Chart.js 2.x? Otherwise it should be published by end of the week.

**Comment by sweety-wo** [comment]
Ok.

How can I set "barValueSpacing" so that bar-chart has no in-beetween spacing,
also can I set other properties that are described in Chart.js  (http://www.chartjs.org/docs/)

**Comment by jtblin** [comment]
You can pass options using the `chart-options` attributes. Just follow the [chart.js docs](http://www.chartjs.org/docs/). Have a look at the examples in `examples/app.js` and http://jtblin.github.io/angular-chart.js/.
