### ISSUE TITLE
Bar Chart Not Showing All xAxes Labels

### ISSUE THREAD

**Issue by cpitzak** [jtblin/angular-chart.js#423]
I made a jsfiddle here of the issue: https://jsfiddle.net/gnns7wbn/1/

I'm using:

angular 1.5.0
angular-chartjs 1.0.0-alpha8
chart.js 2.1.6

note: I'm using 1.0.0-alpha8 only because I don't see an 1.0.0-beta cdn that can be used. In the code on my computer I'm using 1.0.0-beta and the same issue is there.

The issue:

Not all the xaxes labels are being shown. If you reduce the length of the xaxes labels then they will all show.

Hopefully this is a user error. If so, how can I show all the xaxes labels without reducing their length?

**Comment by jtblin** [comment]
This is weird, the tooltip does show the label so it's passed correctly, see 
![image](https://cloud.githubusercontent.com/assets/1388974/16712833/36d2a86c-46d6-11e6-8eb6-2e451f7980e2.png)

I believe this is due to the size of the labels, because if I make them a bit smaller everything show correctly

![image](https://cloud.githubusercontent.com/assets/1388974/16712841/763f5f9a-46d6-11e6-9e8c-70fca380f5cf.png)

I'd recommend opening an issue with Chart.js (or see if there is one opened for that) as this is not an issue with this library.

**Comment by chrismbarr** [comment]
@cpitzak @jtblin - was a fix for this ever found?  I am having the exact same issue today.

**Comment by favisan** [comment]
I'm facing the same issue. :/
I'm using chart.js within ionic. Is there any workaround?

**Comment by ferdynator** [comment]
There seems to be a configuration option (see [chartjs/Chart.js#2801](
https://github.com/chartjs/Chart.js/issues/2801)). Adding 

    
              ticks: {
                  autoSkip: false
              }

to the options of an axis helped me.

**Comment by notmunique** [comment]
Just to add to @ferdynator anwser:

```
ticks: {
    autoSkip: false
}
```

has to be add to xAxes option, not just yAxes.

**Comment by w3sleader** [comment]
options: {
                        scaleShowValues: true,
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }],
                            xAxes: [{
                                ticks: {
                                    autoSkip: false
                                }
                            }]
                        }
                    }

**Comment by halloei** [comment]
Won't work for me. In my case, months on the x-axis are still hidden. Please check my fiddle: https://jsfiddle.net/fcg1wp18/1/

**Comment by dasAnderl** [comment]
see https://github.com/chartjs/Chart.js/issues/2801

**Comment by halloei** [comment]
Thanks, but the problem persists: https://jsfiddle.net/fcg1wp18/3/

**Comment by dasAnderl** [comment]
thats not a bar chart....seems impossible to print all x labels since its too many. the solution works fine for bar charts though. i dont know about line charts

**Comment by syed-haroon** [comment]
Same as @w3sleader 's answer but just formatted (indented).
```
options: {
  scaleShowValues: true,
  scales: {
    yAxes: [{
      ticks: {
        beginAtZero: true
      }
    }],
    xAxes: [{
      ticks: {
        autoSkip: false
      }
    }]
  }
}
```

**Comment by GermanAngarita** [comment]
Thanks @syed-haroon this works for me

**Comment by Ahmed3rab** [comment]
@syed-haroon 's solution worked perfectly, thanks.

**Comment by thaioai01** [comment]
@syed-haroon  it'works for me

**Comment by lucashenriqueteixeira** [comment]
Thanks @syed-haroon this works for me

**Comment by tautau** [comment]
worked for me thanks :+1:  @syed-haroon

**Comment by jonjie0317** [comment]
@notmunique You save the day 👍

**Comment by rockfight** [comment]
> ```
> options: {
>   scaleShowValues: true,
>   scales: {
>     yAxes: [{
>       ticks: {
>         beginAtZero: true
>       }
>     }],
>     xAxes: [{
>       ticks: {
>         autoSkip: false
>       }
>     }]
>   }
> }
> ```

Perfect !

**Comment by ClaireToulouse** [comment]
@syed-haroon it wirked for me too, maybe the "scaleShowValues: true". woohoo !

**Comment by Jagadhissh** [comment]
thnak you it worked for me

**Comment by dyonis** [comment]
Doesn't work for me ((
https://jsfiddle.net/7mLz26we/2/

**Comment by ayalonbnc** [comment]
Once autoSkip is set to false make sure that your limit is also not set too small

        ticks: {
          maxTicksLimit: 15
        },

**Comment by AcidRogue** [comment]
Seems like autoSkip shows all labels no matter what. If you have a lot of labels though, they become way too crammed and don't look good. I've found another way of doing this without autoSkip. 'autoSkipPadding' is basically the distance between labels, so if you set it to a negative number for example -40, it will show more than the default, but not all so it doesn't look crammed. 

`
options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
                xAxes:[{
                    ticks:{
                        beginAtZero: true,
                        autoSkip: true,
                        autoSkipPadding: -40 //Try changing this to different values to see what works best for you
                    }
                }]
            },
            legend: {
                position: 'bottom'
            }
        }
`

**Comment by frederikheld** [comment]
Adding `source: 'date'` to the axis definition did the trick for me \o/. After that the labels stayed visible even on small screens.

Another thing that worked is `ticks.minRotation: 90` but then all labels are turned by 90 degrees no matter how wide your viewport is. So the second option is not optimal...

`autoSkip: true` didn't work for me at all.

My setup:

    "chart.js": "^2.9.3",
    "chartjs-adapter-moment": "^0.1.2",
    "chartjs-plugin-annotation": "^0.5.7",

With NodeJS 12.18.3.
