### ISSUE TITLE
Css file missing

### ISSUE THREAD

**Issue by edohkodjo** [jtblin/angular-chart.js#424]
My css file is missing.
The chart is not displayed in my html page. I don't know if it is related to the missing of css file or something else.
my code: index.html

      <script src="/lib/chart.js/dist/Chart.min.js"></script>
      <script src="/lib/angular-chart.js/dist/angular-chart.min.js"></script>
      ....
      <canvas id="line" class="chart chart-line" chart-data="data"
      chart-labels="labels" chart-series="series" chart-options="options"
      chart-dataset-override="datasetOverride" chart-click="onClick">
      </canvas>

I include 'chart.js' module in my app.js and this is the code of my controller:

    $scope.labels = ["January", "February", "March", "April", "May", "June", "July"];
	$scope.series = ['Series A', 'Series B'];
	$scope.data = [
	   [65, 59, 80, 81, 56, 55, 40],
	   [28, 48, 40, 19, 86, 27, 90]
	];
	$scope.onClick = function (points, evt) {
	   console.log(points, evt);
	};
	$scope.datasetOverride = [{ yAxisID: 'y-axis-1' }, { yAxisID: 'y-axis-2' }];
	$scope.options = {
	    scales: {
	     	yAxes: [
	       		{
	         		id: 'y-axis-1',
	         		type: 'linear',
	         		display: true,
	         		position: 'left'
	       		},
	       		{
	         		id: 'y-axis-2',
	         		type: 'linear',
	         		display: true,
	         		position: 'right'
	       		}
	     	]
	   	}
	 };

Maybe, there is something I did wrong. How to solve it and display the chart?

**Comment by jtblin** [comment]
There is no css file in the 1.x series anymore. Can you post a full jsbin template, there's one in the issue template.

**Comment by edohkodjo** [comment]
i downloaded the repo using npm command. And the version used is 1.0.0-alpha8.
Sorry, but I don't know if i answered your question.

**Comment by jtblin** [comment]
There is no css anymore in 1.x series. Please create a repro using the [jsbin template](http://jsbin.com/rodunob/edit?html,js,output) if you want some help troubleshooting why your chart doesn't display.

**Comment by edohkodjo** [comment]
I understand now. I will do it.
Firstly i am comparing your code in the jsbin template with mine.

**Comment by edohkodjo** [comment]
It is working now.
Instead of 
    
    <canvas id="line" class="chart chart-line" chart-data="data" chart-labels="labels" chart-    click="onClick" series="series"></canvas>

I followed your jsbin template and i wrapped the canvas tad in the `div panel id` tag like this:

    <div class="panel-body">
        <canvas id="line" class="chart chart-line" chart-data="data" chart-labels="labels" chart-click="onClick" series="series"></canvas>
      </div>

It is working perfectly now. Thank you for the help!

**Comment by jtblin** [comment]
Huh, interesting, that shouldn't be the case. Was your canvas directly in the body?

Btw, `series` attribute should be `chart-series`.

**Comment by edohkodjo** [comment]
Yes, my canvas are in the body. 
I still have another problem. I have noticed that when i used `chart-dataset-override="datasetOverride"`, the chart is not displayed. But when I remove it, the chart is displayed. So I am unable to use the mixed type chart. Do you know how I can solve it?

**Comment by jtblin** [comment]
Can't help without a repro case mate. Look at the mixed type chart in
examples/app.js as well.

**Comment by edohkodjo** [comment]
Whenever I put my code on JsBin, the chart is displayed even the mixed type. But with my app there is something wrong. It is amazing that the only option `chart-dataset-override` prevents the chart to be displayed.
Isn't another way to display simultaneously the line and the bar chart without using the `dataset-override` option because so far my app can display in different figures the line and the bar chart. I would like to combine both of them on the same figure.

**Comment by jtblin** [comment]
No. Is there any error displayed in the console etc.? If it works in the jsbin, there is obviously another issue with your code... Maybe try to submit the question on stackoverflow with more details.
