### ISSUE TITLE
Fill area from lower value

### ISSUE THREAD

**Issue by sweety-wo** [jtblin/angular-chart.js#425]
angular-chart v0.10.2
ChartJS v2.1.6
How to fill/start from min value ?

![angular chartjs app demo](https://cloud.githubusercontent.com/assets/14175105/16707409/d9337548-45e9-11e6-9b72-36be340a4834.png)

**Comment by jtblin** [comment]
ChartJS v2.1.6 requires angular-chart v1.x. You should start by reading Chart.js docs then open your question on StackOverflow.
