### ISSUE TITLE
Line chart from axes in Mixed bar-line chart.

### ISSUE THREAD

**Issue by sweety-wo** [jtblin/angular-chart.js#426]
Is there a way to achieve the line chart start from y-axes-1 and should end to y-axes-2
in mixed bar-line chart.

![angular chartjs app demo](https://cloud.githubusercontent.com/assets/14175105/16707992/5ec23a76-4600-11e6-84df-d4654349414e.png)

**Comment by jtblin** [comment]
You should start by reading Chart.js docs then open your question on StackOverflow.
