### ISSUE TITLE
Data not rendering using ng-repeat

### ISSUE THREAD

**Issue by deepakc147** [jtblin/angular-chart.js#43]
Hi I'm trying to create Bar-Charts using ng-repeat, but the data is not getting rendered. Please Help.

Plunker : http://plnkr.co/edit/DAUkixDSOvjBKGhYjAu3?p=preview

**Comment by jtblin** [comment]
I don't see anything related to angular-chart.js in your plunker so I'm not sure how I can help here.

**Comment by deepakc147** [comment]
I apologize for providing a wrong link. I am extremely sorry for wasting your time. Anyways I have sorted out the issue. And appreciation for your support.

**Comment by jtblin** [comment]
No worries, glad it's solved.

**Comment by dbaines48** [comment]
Hey! How did you solve the issue? I would appreciate the help.
