### ISSUE TITLE
Chart options doesn't work fill=False

### ISSUE THREAD

**Issue by christopher-abastar** [jtblin/angular-chart.js#430]
Sorry, not sure how to use it but i'm trying to add a linechart without the area filled. seems to be not working on the chart-options?

http://jsfiddle.net/176gdxer/

**Comment by RussMax783** [comment]
change your options too.
```
$scope.options = {
    datasetFill: false,
}
```

https://github.com/chartjs/Chart.js/blob/v1.1.1/docs/01-Line-Chart.md

**Comment by christopher-abastar** [comment]
thanks! that makes sense

**Comment by jwhitmarsh** [comment]
This fix doesn't seem to work anymore - how do I disable fill?

**Comment by frederickayala** [comment]
@jwhitmarsh your options object should look like:

$scooe.line_options = { elements:{ line: {fill:false}}};

<canvas id="line_1" class="chart chart-line" chart-options="line_options" ...></canvas>

**Comment by h1nson** [comment]
> @jwhitmarsh your options object should look like:
> 
> $scooe.line_options = { elements:{ line: {fill:false}}};
> 
> Then just set chart-options="line_options" in your canvas element

thanks,it works correctly
