### ISSUE TITLE
[v2] Stacked on Y axis is broken ?

### ISSUE THREAD

**Issue by frlinw** [jtblin/angular-chart.js#431]
Hi !

I tried to stack dataset on Y axis but I don't know why my second set is empty.

X stacked : everything is fine
![12](https://cloud.githubusercontent.com/assets/11896237/16816141/0d6f7d56-493d-11e6-9f6f-549b9bf62d61.JPG)

X stacked + Y stacked : second dataset is empty, tooltips don't work
![13](https://cloud.githubusercontent.com/assets/11896237/16816138/0ab68f78-493d-11e6-9216-4cc0b1c3bcf9.JPG)

I have to change the data format or something ?

**Comment by jtblin** [comment]
Difficult to help without any repro... Maybe ask on StackOverflow? And Chart.js repo if it's possible?

**Comment by frlinw** [comment]
I tried in jsfiddle and everything was fine so... I found my mistake. 
My data are converted into string with .toFixed() and I used them as is.

In Chartjs, "string" data works fine with :
- xAxis stacked: false + yAxis : stacked: false
- xAxis stacked: true + yAxis : stacked: false
But only the first dataset works if :
- xAxis stacked: true + yAxis : stacked: true

Anyway it's close

**Comment by frlinw** [comment]
In addition, this problem is fixed in 2.2.0 rc2

**Comment by jtblin** [comment]
Thanks for the info.
