### ISSUE TITLE
Need a quick example for modify y-axes scale.

### ISSUE THREAD

**Issue by Rliao1992** [jtblin/angular-chart.js#432]

**Comment by jtblin** [comment]
https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/examples/app.js

**Comment by Rliao1992** [comment]
hey, thank you for your response, but I try to modified the y-axes based on your example:
<img width="535" alt="screen shot 2016-07-14 at 12 22 36 pm" src="https://cloud.githubusercontent.com/assets/8837435/16852636/c5311df2-49bd-11e6-9688-c7ebb9d23688.png">
<img width="659" alt="screen shot 2016-07-14 at 12 23 51 pm" src="https://cloud.githubusercontent.com/assets/8837435/16852694/ef0ab0fc-49bd-11e6-9aae-66cd173abfcd.png">
but the y-axes scale still be 0.1 step:
<img width="334" alt="screen shot 2016-07-14 at 12 25 39 pm" src="https://cloud.githubusercontent.com/assets/8837435/16852758/392d1ab2-49be-11e6-99c1-4f2bfa655252.png">
Do you mind give me a hand with this? 
Thank you

**Comment by jtblin** [comment]
You should ask on StackOverflow.
