### ISSUE TITLE
Small Installation doc mistake

### ISSUE THREAD

**Issue by lenanex** [jtblin/angular-chart.js#433]
### Overview

In the installation manual, one mistake : 

<script src="node_modules/angular-chart.js/dist/angular-chart.min.js"></script> -> appearing twice, should be removed as the order is useful.
<script src="node_modules/chart.js/Chart.min.js"></script>  -> 
<script src="node_modules/angular-chart.js/dist/angular-chart.min.js"></script> 

Nothing major, but could help other to install it.

Thanks,
Nanex

**Comment by jtblin** [comment]
Duplicate of #428
