### ISSUE TITLE
How to set the "pointDot" option for the Line charts

### ISSUE THREAD

**Issue by dec** [jtblin/angular-chart.js#435]
Hello there!

First of all, many thanks for your work. This is not exactly an issue, since, trying to answer the subject question, we can use the below Javascript code:

`
Chart.defaults.Line.pointDot = false;
`

But how I can achieve the same using the Chart options of your AngularJS directive? It's possible?

Thanks very much in advance for your help!

**Comment by jtblin** [comment]
You can set options, please read the readme, demo site and chart.js options.
