### ISSUE TITLE
How to remove pie chart stroke / border

### ISSUE THREAD

**Issue by peteringram0** [jtblin/angular-chart.js#437]
Is there a way to remove the stoke / border from the pie chart?

**Comment by jtblin** [comment]
Have a look at http://www.chartjs.org/docs/

**Comment by peteringram0** [comment]
This doesnt really answer my question. I have the following: 

`
        vm.labels = ["Download Sales", "In-Store Sales", "Mail-Order Sales"];
        vm.Chartdata = [300, 500, 100];
        vm.colours = ['#35c98c','#e14a56','#a084ff'];

<canvas class="chart chart-doughnut" chart-data="vm.Chartdata" chart-labels="vm.labels" chart-colors="vm.colours"></canvas>
`

It seems from the docs chart-data can be an object but only seems to want to take an array. Please can you provide an example at all? 

Thanks,

**Comment by jtblin** [comment]
You can pass any option that Chart.js supports via `chart-options` so
generally the best is to look at Chart.js docs to see which option you need
to use. For colors you can pass the full color oblect so you can control
the border, etc. as well. Example for 0.x series is
https://github.com/jtblin/angular-chart.js/blob/master/examples/app.js#L131,
there should be a similar one in the 1.x branch (which I'm about to merge
into master anyway).

**Comment by philecom** [comment]
Please how did you solve this issue @peteringram0
