### ISSUE TITLE
Chart doesn't work with only one series.

### ISSUE THREAD

**Issue by davidssonarnor** [jtblin/angular-chart.js#44]
Chart doesn't work with only one series constantly gives errors.

        $timeout(function () {
        $scope.labels = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
        $scope.series = ['Series A'];

        $scope.data = [
          [65, 59, 80, 81, 56, 55, 40]
        ];
        }, 1000);

**Comment by jtblin** [comment]
What type of chart?

**Comment by mmirold** [comment]
I had the same problem (with angular-chart 0.4.2 and Chart 1.0.1) for a line chart. I get the error 

> "Uncaught TypeError: Cannot read property 'draw' of undefined" 

in Chart.js:2763 when I use the following scope assignment:

    $scope.data = [154, 31, 17, 4, 1];
    $scope.labels = ["A", "B", "C", "D", "E"];

However, if I write

    $scope.data = [[154, 31, 17, 4, 1]];
    $scope.labels = ["A", "B", "C", "D", "E"];
    $scope.series = ["dummy"];
    
everything is normally drawn.

**Comment by mmirold** [comment]
It seems that the Chart API has changed. I was able to fix my local installation of angular-chart with 
```
--- a/angular-chart.js
+++ b/angular-chart.js
@@ -224,14 +224,13 @@

   function getData (labels, data, colours) {
     colours = colours || Chart.defaults.global.colours;
-    return labels.map(function (label, i) {
-      return {
-        label: label,
-        value: data[i],
-        color: colours[i].strokeColor,
-        highlight: colours[i].pointHighlightStroke
-      };
-    });
+    var dataSet = angular.copy(colours[0]);
+    dataSet.data = data;
+
+    return {
+      labels: labels,
+      datasets: [ dataSet ]
+    };
   }
```

Not sure if this breaks anything.

**Comment by jtblin** [comment]
@mmirold this is a different problem. OP says it doesn't work with **only one** series, you say it doesn't work where there is **no** series so it would have been better to open a different issue.

Moreover, you use a simple array for the data whereas the line chart requires a multidimensional array. I'd recommend that you read the examples on the demo site: http://jtblin.github.io/angular-chart.js/. In your examples for a line chart, it should be:

```
$scope.data = [[154, 31, 17, 4, 1]];
$scope.labels = ["A", "B", "C", "D", "E"];
```

@davidssonarnor 

I cannot repro your issue with a line chart with the same code example. Closing the issue. Feel free to re-open if you encounter the issue again with the chart type, the error details, and a jsbin.

![image](https://cloud.githubusercontent.com/assets/1388974/6144954/e8b15556-b230-11e4-9892-5634c135100c.png)

**Comment by trendy-weshy** [comment]
doesn't work in my pie chart as well getting this error 
![screenshot from 2016-07-16 14-38-43](https://cloud.githubusercontent.com/assets/11578670/16894572/11568e32-4b63-11e6-89fa-b97abac50d53.png)
