### ISSUE TITLE
Argument 'module' is not a function(For whom might have similar situation like me)

### ISSUE THREAD

**Issue by w4-steve** [jtblin/angular-chart.js#440]
From 1.0.0-beta, when you 'require' module, it exports name directly.
So if you wrote code like this before with alpha version:
```
angular.module('something', [
  require('angular-chart.js').name,
]);
```
Your code may work well before updating your node packages, but will break in CI or next update.
So plz make sure remove '.name' and update package.js to 1.0.0
I visited npm every single day to check if it becomes beta, but suddenly it turns to release version :)
Though I woke up since CI was broken(actually it is my fault that I used alpha version in production), I really appreciate the project owner's effort. I hope someday I could distribute even a small code.
Thanks!

p.s I am so newbie to open source world and also github, do not know how to write an article for other people. If it is not right place to write, so sorry. But it could be an open issue since you need to announce what module exports from now not like before.

**Comment by jtblin** [comment]
Apologies, I actually released 1.0.0-beta1 one month ago but it looks like I forgot to push to npm :(
Sorry it broke your build, the breaking change is documented in the readme.
