### ISSUE TITLE
HTML Markup Issue

### ISSUE THREAD

**Issue by EvanBurbidge** [jtblin/angular-chart.js#444]
In the examples provided the markup for the html has all attributes using the notation ""chart-data, chart-label"" etc. etc. I found that this did not work and removing the ""chart-"" from attributes did. Could you update the documentation, or is this a new feature that has been introduced?

**Comment by jtblin** [comment]
You must be using a very outdated version of the library, the attributes have been prefixed with `chart-` and the ones without have been deprecated since August 2015, see #181.

The attributes without `chart-` have been entirely removed since 1.x has been released.
