### ISSUE TITLE
Horizontal Stacked Bar Produces NaN

### ISSUE THREAD

**Issue by jewkesy** [jtblin/angular-chart.js#445]
Turning off all the labels on a horizontal stacked bar chart produces a label 'NaN' to appear in the top-left (cropped on the canvas)

Screenshot as example: -
![screen shot 2016-07-25 at 14 23 57](https://cloud.githubusercontent.com/assets/1673570/17102922/a79a83fa-5273-11e6-82e0-e2ddc704e9df.png)

controller.js
```
$scope.chtLabels = ["Alpha", "Beta", "Gamma"];
$scope.chtSeries = ['Category A', 'Category B', 'Category C'];
$scope.chtShowLegend = true;
$scope.chtOptions = {
  scales: {
    xAxes: [{
      stacked: true
    }],
    yAxes: [{
      stacked: true
    }]
  }
 }
 $scope.chtData = [
    [65, 59, 80],
    [28, 48, 40],
    [7, 6, 7]
  ];
```

template.jade
```
canvas#chtDemo.chart.chart-horizontalBar(chart-data='chtData', chart-labels='chtLabels', chart-series="chtSeries", chart-legend="chtShowLegend", chart-options="chtOptions")
```

**Comment by jtblin** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps as described in the issue template. Check this element's CONTRIBUTING.md for an example.

**Comment by noah-ubf** [comment]
There are reproducible steps. In my case they are:
1) create a chart with 2 Y axes, some data series bind to 1 axis, some to second one;
2) Turn off all 2-nd axis series by clicking on the legend
Result - NaN appears in top left corner

**Comment by happy257** [comment]
This issue is still open. I don't see a resolution in the above comments.

**Comment by jtblin** [comment]
@happy257 feel free to provide repro steps following the jsbin template.

**Comment by Delijentry** [comment]
got the same issue using ng2-charts
but in this pen used original chart.js - http://codepen.io/jamiecalder/pen/NrROeB
in options need to set  
```
legend:{
  display:true
}
```
hide all labels, in the left corner displayed NaN :(
