### ISSUE TITLE
Run on Docker

### ISSUE THREAD

**Issue by brunoserralheiro** [jtblin/angular-chart.js#447]
This fails when trying to run gulp
docker run --rm -i -v $(pwd)/coverage/:/src/coverage/ -v $(pwd)/test/:/src/test/ -v $(pwd)/angular-chart.js:/src/angular-chart.js angular-chart.js

npm run docker-test

> angular-chart.js@1.0.0 docker-test D:\DEVELOPMENT\lab\angularjs\angular-chart.js
> docker run --rm -i -v $(pwd)/coverage/:/src/coverage/ -v $(pwd)/test/:/src/test/ -v $(pwd)/angular-chart.js:/src/angular-chart.js angular-chart.js

docker: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'docker run --help'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "docker-test"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! angular-chart.js@1.0.0 docker-test: `docker run --rm -i -v $(pwd)/coverage/:/src/coverage/ -v $(pwd)/test/:/src/test/ -v $(pwd)/angular-chart.js:/src/angular-chart.js angular-chart.js`
npm ERR! Exit status 125
npm ERR!
npm ERR! Failed at the angular-chart.js@1.0.0 docker-test script 'docker run --rm -i -v $(pwd)/coverage/:/src/coverage/ -v $(pwd)/test/:/src/test/ -v $(pwd)/angular-chart.js:/src/angular-chart.js angular-chart.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-chart.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker run --rm -i -v $(pwd)/coverage/:/src/coverage/ -v $(pwd)/test/:/src/test/ -v $(pwd)/angular-chart.js:/src/angular-chart.js angular-chart.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-chart.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-chart.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\DEVELOPMENT\lab\angularjs\angular-chart.js\npm-debug.log

D:\DEVELOPMENT\lab\angularjs\angular-chart.js>npm bugs angular-chart.js
npm ERR! not a package D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
npm ERR! addLocal Could not install D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "angular-chart.js"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! path C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\DEVELOPMENT\lab\angularjs\angular-chart.js\npm-debug.log

npmdebug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'bugs',
1 verbose cli   'angular-chart.js' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 silly fetchPackageMetaData angular-chart.js
5 silly fetchOtherPackageData angular-chart.js
6 silly cache add args [ 'angular-chart.js', null ]
7 verbose cache add spec angular-chart.js
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'angular-chart.js',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'angular-chart.js',
8 silly cache add   spec: 'D:\\DEVELOPMENT\\lab\\angularjs\\angular-chart.js\\angular-chart.js',
8 silly cache add   type: 'local' }
9 silly addLocalTarball shasum (computed) 84f87d4527e3ff5bf2d98bca8f7885f23fd34b3f
10 verbose addTmpTarball D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js not in flight; adding
11 verbose correctMkdir C:\Users\Bruno Serralheiro\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
12 verbose addTmpTarball validating metadata from D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
13 verbose tar unpack D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
14 verbose tar unpacking to C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17
15 silly gentlyRm C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17 is being purged
16 verbose gentlyRm don't care about contents; nuking C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17
17 silly gunzTarPerm modes [ '777', '666' ]
18 error not a package D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
19 error addLocal Could not install D:\DEVELOPMENT\lab\angularjs\angular-chart.js\angular-chart.js
20 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
20 silly fetchPackageMetaData     at Error (native)
20 silly fetchPackageMetaData  error for angular-chart.js { Error: ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
20 silly fetchPackageMetaData     at Error (native)
20 silly fetchPackageMetaData   errno: -4058,
20 silly fetchPackageMetaData   code: 'ENOENT',
20 silly fetchPackageMetaData   syscall: 'open',
20 silly fetchPackageMetaData   path: 'C:\\Users\\BRUNOS~1\\AppData\\Local\\Temp\\npm-9260-63ff8b89\\unpack-3a031c17\\package.json' }
21 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
21 verbose stack     at Error (native)
22 verbose cwd D:\DEVELOPMENT\lab\angularjs\angular-chart.js
23 error Windows_NT 10.0.10586
24 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "angular-chart.js"
25 error node v6.2.1
26 error npm  v3.9.3
27 error path C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json
28 error code ENOENT
29 error errno -4058
30 error syscall open
31 error enoent ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
32 error enoent ENOENT: no such file or directory, open 'C:\Users\BRUNOS~1\AppData\Local\Temp\npm-9260-63ff8b89\unpack-3a031c17\package.json'
32 error enoent This is most likely not a problem with npm itself
32 error enoent and is related to npm not being able to find a file.
33 verbose exit [ -4058, true ]

**Comment by jtblin** [comment]
Looks like a problem with your docker engine given the error message "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //./pipe/docker_engine".

I'm not familiar with running Docker on Windows but googling this error message leads to issues like https://github.com/docker/docker/issues/22338. Maybe your docker machine is not started?

**Comment by brunoserralheiro** [comment]
Thanks for the quick response. 
I only posted it to try to help you on bug tracking. The example did not run, but angular-chart.js now works fine with bar line chart within the app I am currently working. Exactly what I need! 

Thank you so much! 
![image](https://cloud.githubusercontent.com/assets/9983600/17194187/a80620b0-544e-11e6-94ee-d717d503c9cd.png)

**Comment by brunoserralheiro** [comment]
Just to get it over with, I am not used to windows either, but yes the docker-machine star default command was used and it was up and running.

![image](https://cloud.githubusercontent.com/assets/9983600/17194355/86663890-544f-11e6-9165-b8e71f01bb13.png)
