### ISSUE TITLE
Global configuration override v1.x

### ISSUE THREAD

**Issue by frlinw** [jtblin/angular-chart.js#449]
Hi,

Options defined with ChartJSProvider.setOptions are overridden by chart type default properties

Example:
Set tooltips mode = single for bar chart
- If you don't use 'tooltips' in chart option, mode = single
- If you override a property in tooltips (callback for example), mode = label

https://jsfiddle.net/zpq0x4yt/1/

**Comment by jtblin** [comment]
Thanks, I can see the issue. I guess all global options should be passed as standard options instead like https://github.com/jtblin/angular-chart.js/blob/master/angular-chart.js#L65.

**Comment by frlinw** [comment]
It's maybe because of angular.extend ?

with these data :
```
var globalOptions = {
    tooltips: {
        fontFamily: 'Comic sans MS',
        fontColor: '#000'
   }
};

var localOptions = { 
    tooltips: {
        fontSize:  50
    }
};
```

angular.extend({}, globalOptions, localOptions) result is :
```
 {
    tooltips: {
        fontSize:  50
    }
}
```

when angular.merge({}, globalOptions, localOptions) result is :
```
{
    tooltips: {
        fontFamily: 'Comic sans MS',
        fontColor: '#000'
        fontSize:  50
   }
}
```

**Comment by jtblin** [comment]
This issue should now be fixed, see https://github.com/jtblin/angular-chart.js/pull/498

**Comment by frlinw** [comment]
Thanks for the PR, I tested it and it works fine.

But... it doesn't work for global font settings
defaultFontColor
defaultFontFamily
defaultFontSize
defaultFontStyle
Maybe they need a particular treatment

https://jsfiddle.net/1fd07wad/2/

**Comment by jtblin** [comment]
It's the same issue as #512
