### ISSUE TITLE
How do you put the legend on the right-hand-side?

### ISSUE THREAD

**Issue by tawani** [jtblin/angular-chart.js#45]
How do you put the legend on the right-hand-side?

**Comment by jtblin** [comment]
You will have to listen to the `create` event to get a handle on the char and generate the legend using the  `generateLegend` function, then place the legend html in a div or other element on the right of the chart, see http://www.chartjs.org/ for some example.

```
$scope.$on('create', function (chart) {
  var legend = chart.generateLegend();
  // put the html in the DOM
});
```

**Comment by tylerITP** [comment]
The event returned from $on('create') does not have the generateLegend function

You need to have a legitimate example.  http://www.chartjs.org/ does not even have examples of what you are saying.

**Comment by tylerITP** [comment]
The proper use of the function is
```
$scope.$on('create', function (event, chart) {
  var legend = chart.generateLegend();
  // put the html in the DOM
});
```

**Comment by bes1002t** [comment]
does this also work with angular-chartjs 1.1.1? for any reason my console.log is not triggered inside that function but I get no error or something.

```
$scope.$on('create', function (event, chart) {
    var legend = chart.generateLegend();
    console.log(JSON.stringify(legend))
});
```
