### ISSUE TITLE
How can I set different colours for each bar in angular-chart.js v1.0.0?

### ISSUE THREAD

**Issue by jesussaad** [jtblin/angular-chart.js#451]
Could you please answer this ask?
http://stackoverflow.com/questions/38618158/how-can-i-set-different-colours-for-each-bar-in-angular-chart-js-v1-0-0

**Comment by frlinw** [comment]
It's related to Chartjs, not angular-chart.
Chartjs doesn't allow this because 1 color = 1 dataset = 1 legend item (and sadly, you can't get a rainbow for one legend item)
If you want to achieve this, edit the source code or try to create a chartjs plugin (or find a nice guy to do it).

**Comment by frlinw** [comment]
I'm back with a trick if you don't want to wait for a cleaner thing.

- Use one dataset for each bar
- Set all data to 0 for the dataset except the data you want to show
- Custom color for each dataset
- BorderWidth = 0 to hide empy data and stacked = true on X axe
- Custom tooltip callback to hide empty dataset

https://jsfiddle.net/3qas1ar8/2/

**Comment by jesussaad** [comment]
Perfect solution!
Thank you so much!

Contributing...
Adding this code to options, show bar labels:

animation: {
    onComplete: function() {
        var chartInstance = this.chart;

        var ctx = chartInstance.ctx;
        ctx.textAlign = "center";
        ctx.textBaseline = 'bottom';

        Chart.helpers.each(this.data.datasets.forEach(function(dataset, i) {

            var meta = chartInstance.controller.getDatasetMeta(i);

            Chart.helpers.each(meta.data.forEach(function(bar, index) {

                if (index == i && dataset.data[index] > 0) {

                    var add = bar._model.base - bar._model.y >= 10 ? 12 : 2;

                    ctx.fillStyle = '#000000';
                    ctx.fillText(dataset.data[index], bar._model.x, bar._model.y + add);
                }
            }), this)
        }), this);
    }
},
