### ISSUE TITLE
Chartjs 2.2.0 dependencies 

### ISSUE THREAD

**Issue by frlinw** [jtblin/angular-chart.js#452]
There is no more "dist" folder in Chartjs github repository since v2.2.0
Dependencie in bower.json should be removed

**Comment by wwarby** [comment]
This fix isn't included when I pull angular-chart.js from bower. Appreciate it was only committed yesterday but wondering when it might be included in the release?

**Comment by frlinw** [comment]
It's an exotic dependencie and bower don't know about bower-npm-resolver syntax so it won't be explicit that bower-npm-resolver is missing if someone try to bower install angular-chart.
He will get an error like "npm:chart.js#2.x can't be found/is not a branch/whatever"

Maybe it's more clear to remove the dependencie and add instructions for Chartjs installation to the readme.
@navarroaxel thought

**Comment by navarroaxel** [comment]
Hi!

The instructions are in the README.md of my pull request.
But it's true what @frlinw is saying, you have to add the bower-npm-resolver in your project and it's rare.

Maybe the best is what angular does with a bower-angular repository, that's specific for the bower instalation. Doesn't make any sense if you can use the bower installation of something deprecated.

Options:
A) Use my pull request
B) Remove the Chart.js dependency and tell to the user that he has to add it in some special way.
C) Tell to the Chart.js team, or maybe @jtblin can do, if they can create an specific repository with the bower releases, and without the non-dist files.

I prefer the option C.

**Comment by jtblin** [comment]
I was considering removing bower support in 1.x. I moved all the dependencies internally to use npm instead. I think bower is pretty much dead and everybody should use npm now so I'm not going to follow-up with the Chart.js team about why they removed it. In the past, it created issues as they were using different casing or something like that so it might be the reason why. I'm happy to merge @navarroaxel 's PR for now, but if there were going to be more issues supporting bower later on, I might just remove support for it entirely.

**Comment by goseign** [comment]
bower install --save angular-chart.js
still pick Chart.js not chart.js
I noticed that downloaded bower.json is not the latest.

**Comment by navarroaxel** [comment]
@goseign yes, it's true. @jtblind should release a new version (maybe 1.0.1) with the new bower.json.

**Comment by dharitdesai** [comment]
getting this in the latest version
```
:~] bower install --save angular-chart.js            
bower angular-chart.js#*        cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#*      validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#*
bower chart.js#2.x           ENOTFOUND Package npm:chart.js not found
```

**Comment by navarroaxel** [comment]
Hey @dharitdesai, you need to add a .bowerrc file in your project with this config:
````JSON
{
  "resolvers": [
    "bower-npm-resolver"
  ]
}
````
and install this package:
```
npm install -g bower-npm-resolver
```

**Comment by dharitdesai** [comment]
@navarroaxel I added that in .bowerrc since not all packages has the mapper, its failing on regular bower update/install. any other way that I can use this ?

**Comment by dharitdesai** [comment]
damn it my bad.

**Comment by dharitdesai** [comment]
I am sorry y'all for spamming. @navarroaxel the inital comment was correct. since not all packages will have the mapper, `bower update` and `bower install` is failing. is there any other way that i can install this ?

**Comment by navarroaxel** [comment]
It's working for me
````
$ bower install angular-chart.js
bower angular-chart.js#~1.0.1   cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#~1.0.1 validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#~1.0.1
bower angular-chart.js#*        cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#*      validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#*
bower chart.js#2.x              cached npm:chart.js#2.2.0
bower chart.js#2.x            validate 2.2.0 against npm:chart.js#2.x
bower angular-chart.js#~1.0.1  install angular-chart.js#1.0.2
bower chart.js#2.x             install chart.js#2.2.0
[..................] \ :
angular-chart.js#1.0.2 bower_components\angular-chart.js
├── angular#1.5.8
└── chart.js#2.2.0

chart.js#2.2.0 bower_components\chart.js
````

Please check you need to use the version 1.0.1+ and the bower-npm-resolver is installed **globally** (with -g) with NPM.
Also you can try the [steps ](http://www.chartjs.org/docs/#getting-started-installation) to install charts.js using bower individually 

But this is an error in your end.

**Comment by GabLeRoux** [comment]
Had similar problem on debian, but I was getting the following error:

```
bower Chart.js#^2.2.1                                       error Arguments to path.join must be strings

Stack trace:
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at ResolveCache._readPkgMeta (/usr/lib/node_modules/bower/lib/core/ResolveCache.js:337:25)
    at ResolveCache.store (/usr/lib/node_modules/bower/lib/core/ResolveCache.js:108:51)
    at /usr/lib/node_modules/bower/lib/core/PackageRepository.js:190:35
    at _fulfilled (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:604:44

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
System info:
Bower version: 1.7.9
Node version: 0.10.46
OS: Linux 3.16.0-4-amd64 x64
```

Had same error using globally installed bower-npm-resolver.

Used solution from the following comment:
https://github.com/jtblin/angular-chart.js/issues/466#issuecomment-240708755

**Comment by dharitdesai** [comment]
thanks ya'll. actually problem was that my node_modules dir was created in the parent dir. moved it. and worked.
