### ISSUE TITLE
Issue setting option on chart

### ISSUE THREAD

**Issue by vanzylv** [jtblin/angular-chart.js#454]
Hi,

I've been bumping my head against this all morning.

http://jsbin.com/cutumigexa/1/edit?html,js,output

I cannot seem to set the lineTension (also tried tension) property on the line chart,I always get the bezier default lines.I basically need spiked lines.

Thanks

**Comment by vanzylv** [comment]
Silly me,needed this $scope.datasetOverride = [{lineTension: 0.001}];

**Comment by marcoskubis** [comment]
Same issue here. Can't set the `tooltipTemplate: function (){..}` and others options.

**Comment by marcoskubis** [comment]
I solve my problem:
```
    vm.options = {
        tooltips: {
            callbacks: {
    			label: function(tooltipItem, data) {
    				return data.labels[tooltipItem.index] + ': ' + tooltipItem.yLabel;
    			}
    		}
        }
    }
```

**Comment by marcoskubis** [comment]
@vanzylv try this:
```
    vm.options = {
        elements: {
			line: {
				tension: 0 // no bezier in radar
			}
		}
    }
```

**Comment by frlinw** [comment]
Because dataset-override is about datasets... 
Normally your jsbin is updated
http://jsbin.com/wijumeyaso/edit?html,js,output
