### ISSUE TITLE
show / hide data when clicking on legend

### ISSUE THREAD

**Issue by sean72kimo** [jtblin/angular-chart.js#455]
Hi, 
I am looking for the solution to hide series after clicking on legend. In[ issue#70](https://github.com/jtblin/angular-chart.js/issues/70), it said this feature will be included, but I only see this feature in bar chart. Will this feature also be available in line chart and pie chart as well as in chart.js?

Thanks,
Sean

**Comment by frlinw** [comment]
Since chartjs 2.0, you can do everything with "chart-option"
Define legend onClick function
http://www.chartjs.org/docs/#chart-configuration-legend-configuration

**Comment by jtblin** [comment]
Thanks @frlinw!
