### ISSUE TITLE
pointBorderColor hard-coded in angular-chartjs source lines 253-262 issue

### ISSUE THREAD

**Issue by bobbyfisher928** [jtblin/angular-chart.js#458]
Hello,

Using all the configurations defined in chartjs, I created a set of options that should be working properly. 

```
self.labels = ["January", "February", "March", "April", "May", "June", "July"];
  	self.series = ['Series A', 'Series B'];
  	self.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90]
  ];
  self.onClick = function (points, evt) {
    console.log(points, evt);
  };
  self.datasetOverride = [{ yAxisID: 'y-axis-1' }, { yAxisID: 'y-axis-2' }];
  self.options = {
  	maintainAspectRatio: false,
    scales: {
      	yAxes: [
        {
          	id: 'y-axis-1',
          	type: 'linear',
          	position: 'left',
	        ticks: {
		        display: false,
		        beginAtZero: true,
		        min: 0,
		        max:100,
		    },
		    gridLines: {
				tickMarkLength: 1,
				color: '#CFCFCF',
				zeroLineColor: '#CFCFCF'
		    }
        },
        {
          	id: 'y-axis-2',
          	type: 'linear',
          	position: 'right',
	        ticks: {
		        display: false,
		        beginAtZero: true,
		        min: 0,
		    },
		    gridLines: {
		    	tickMarkLength: 1,
		    	color: '#CFCFCF',
		    	zeroLineColor: '#CFCFCF'
		    }
        }
      	],
      	xAxes: [{
	        ticks: {
		        display: false,
		    },
		    gridLines: {
		    	tickMarkLength: 1,
		    	color: '#CFCFCF',
		    	zeroLineColor: '#CFCFCF'
		    }
      	}]
    },
    elements: {
    	line: {
    		fill: false,
    		tension: 0,
    		borderWidth: 5,
    		
    	},
    	point: {
    		radius: 4,
    		borderWidth: 0,
    		borderColor: ['#8CC63E','#46BFF3','#81C2F0','#7964A0','#F9ED37','#CE5A5A','#EEA444','#F93761','#C3AD74','#D9B600'],
    		backgroundColor: "#fff"
    	},
    }
  };
```

I have modified the [jsbin template](http://jsbin.com/cinofunika/edit?html,js,output) you provided to show that the options do not set the point border color using any of the defined methods described by chartjs. 

After digging in the source code for chartjs, this should work. So that lead me to dig into the angular-chart.js source. This lead me to this little snippet of code found on line 253:

```
function getColor (color) {
      return {
        backgroundColor: rgba(color, 0.2),
        pointBackgroundColor: rgba(color, 1),
        pointHoverBackgroundColor: rgba(color, 0.8),
        borderColor: rgba(color, 1),
        pointBorderColor: '#fff',
        pointHoverBorderColor: rgba(color, 1)
      };
    }
```
This is the only place I can change the border color for points. Unfortunately, I cannot reproduce this through jsbin because jsbin only pulls in the source and doesn't let me modify the source code from within... But I was able to do it on my own project. 

I was wondering if this was purposefully hard coded in for some reason? I attempted to change the value of '#fff' to 'rgba(color,1)' and that still didn't work. Please let me know if you need any more information. 

Best regards,
Bobby

**Comment by jtblin** [comment]
You can pass the full colors option if you want including the `pointBorderColor` property. It is "hardcoded" only when you only pass a hex value or similar. See https://github.com/jtblin/angular-chart.js/blob/master/examples/app.js#L179 for an example.
