### ISSUE TITLE
Draw additional chart after event on first chart?

### ISSUE THREAD

**Issue by davidmichaelkarr** [jtblin/angular-chart.js#459]
My app calls a REST service that gets a bunch of rows with a timestamp and some event counters at each timestamp.  I first display a graph that shows the numbers of those events during each hour of a day.  I have a series of four data points at each hour.

I want to be able to click one of the hour intervals, which would result in another graph being drawn that shows the detailed data during that hour, being the counters at each minute of the hour.

In my html, I just have this:
`	<canvas id="daily-chart" class="chart chart-bar" chart-data="dailyData" chart-labels="dailyLabels" chart-series="dailySeries"
			chart-options="dailyOptions" chart-click="dailyGraphClick"></canvas>
	<canvas id="hour-range-chart" class="chart chart-bar" chart-data="hourRangeData" chart-labels="hourRangeLabels" chart-series="hourRangeSeries"
			chart-options="hourRangeOptions" chart-click="hourRangeGraphClick"></canvas>
`

When I retrieve the data from the REST service, I build the fields for the "daily" graph.  This displays perfectly fine.  I can then click one of the hours, and I'm able to step through the code that sets the similar objects for the "hourRange" graph.  However, nothing ever shows up on the screen for the second graph.  I also note that I have the following that watches when the charts are created:
`			$scope.$on('chart-create', function(event, chart) {
				if (chart.chart.canvas.id == "daily-chart") {
					console.log("Creating daily chart.");
					$scope.dailyChart	= chart;
				}
				else {
					console.log("Creating hour range chart.");
					$scope.hourChart	= chart;
				}
			});
`

It never hits the "else" block.  I'm not sure of the expected chain of events here.

**Comment by davidmichaelkarr** [comment]
Er, I'm confused.  I'm now seeing the second chart.  It seems like it sometimes takes a long time before it actually appears.  It takes just a few seconds to draw the first chart, but it takes close to 30 seconds before I see the second chart.  There's more data to show in the second chart, but certainly not orders of magnitude larger.

**Comment by jtblin** [comment]
That doesn't sound right. Anyway, sorry but I don't have the time to provide individual support for this type of questions. This seems more appropriate for and you will get more help with [StackOverflow](angular-chart) tagged with _angular-chart_.
