### ISSUE TITLE
Text-labels do not work

### ISSUE THREAD

**Issue by feihan** [jtblin/angular-chart.js#461]
### Overview

When i use number labels, every label is shown, but when i switch to text labels, duplicate labels are not shown.

A second (not so important) bug is, that the number format does not work either.

### Step to reproduce

See following fiddle:
https://jsfiddle.net/j6ynkzqv/8/

**Comment by codyseibert** [comment]
I think this is a ChartJS issue, and not an angular-chartjs issue:
https://github.com/chartjs/Chart.js/issues/2994

**Comment by jtblin** [comment]
Apparently it works well in 2.1.6 (and below), until a fix is provided by the Chart.js team.
