### ISSUE TITLE
Change style legends

### ISSUE THREAD

**Issue by pconihout** [jtblin/angular-chart.js#463]
Hi,

I changed angular-chart.css adding a font & text-transform but it doesn't seems to work.
 
`.chart li,
.chart-legend li,
.bar-legend li,
.line-legend li,
.pie-legend li,
.radar-legend li,
.polararea-legend li,
.doughnut-legend li {
  display: inline-block;
  white-space: nowrap;
  position: relative;
  margin-bottom: 4px;
  border-radius: 5px;
  padding: 2px 8px 2px 28px;
  font-size: smaller;
  cursor: default;
  font-family: 'Montserrat', sans-serif !important;
  text-transform: uppercase !important;
}`

Any ideas ?

**Comment by jtblin** [comment]
Which lib version? Repro case?
