### ISSUE TITLE
How to get chart instance?

### ISSUE THREAD

**Issue by cankut** [jtblin/angular-chart.js#464]
I have the directive below and everything works fine.

```html
  <canvas class="chart chart-line" chart-data="settings.data" chart-labels="settings.labels" 
    chart-colors="settings.colors" chart-options="settings.options"
    chart-series="settings.series" chart-click="settings.onClick"></canvas> 
```

How can i get reference to this specific directive's Chart object?

My intention is to consume some methods on chart instance.

For example:

```javascript 
chartInstance.toBase64Image();
```

Thanks in advance.

**Comment by codyseibert** [comment]
You might just be able to listen for this message https://github.com/jtblin/angular-chart.js/blob/master/angular-chart.js#L182, but I'm not 100% on that.

**Comment by jtblin** [comment]
That's the correct way to retrieve the chart instance.

**Comment by cankut** [comment]
One more question,

![image](https://cloud.githubusercontent.com/assets/6057634/17744206/5f0b4ff4-64af-11e6-832b-f8264eec4177.png)

chart-created event is fired multiple times. any ideas what might be causing this?

**Comment by jtblin** [comment]
If options or other optional attributes are set after the data is set the
chart will be destroyed and recreated. This logic is what allows the chart
to be automatically updated everytime something changes in the chart
settings.

When that happens you should just update the reference on your side.

**Comment by wxjzeke** [comment]
I have 8 charts in one page, how can I distinguish them.

**Comment by firomero** [comment]
How can I listen to the fired event?

**Comment by jtblin** [comment]
Use separate controllers for each chart?

**Comment by nkoterba** [comment]
@jtblin Any way to get the ctx object associated with the chart instance? I have successfully grabbed the chart instance but `.ctx` as well as `.canvas` are both null and I'd like to draw something manually on the chart's canvas.

**Comment by maccer83** [comment]
@wxjzeke , in order to distinguish between charts, if you are listening to the 'chart-create' event, you could set a id of each chart canvas and access ut using `chart.canvas.id;`:
```
<canvas id="myChartId" class="chart chart-doughnut" ...></canvas>
```
```
$scope.$on('chart-create', function (event, chart) {
  let chartId = chart.canvas.id;
  if(chartId === 'myChartId') {
    console.log(chartId + " called!"); // Do something when your chart is found
  }
});
```
