### ISSUE TITLE
New release after fixing Bower support?

### ISSUE THREAD

**Issue by carlosafonso** [jtblin/angular-chart.js#465]
### Overview
In a recent commit (ef795b9) Bower support for ChartJS was restored. Since no release exists yet with this change, Bower users need to point to a specific commit in the `bower.json` file.

Would you consider creating a new minor/patch release so that us Bowerians can keep pointing to a stable version?

Thank you.

### Step to reproduce
Does not apply.

**Comment by jtblin** [comment]
Done: https://github.com/jtblin/angular-chart.js/releases/tag/1.0.1

**Comment by carlosafonso** [comment]
Thanks ;)

**Comment by TimmyParkwayd** [comment]
Thank you !!!!

**Comment by mackelito** [comment]
@carlosafonso did you manage to install it with this version?

**Comment by carlosafonso** [comment]
Just gave it a try now, I'm getting this:

```
ENOTFOUND Package npm:chart.js not found
```

**Comment by mackelito** [comment]
Same as me then :)

**Comment by carlosafonso** [comment]
Looks like a problem with Chart.js itself, I'll try to post an issue regarding this on that repo.
