### ISSUE TITLE
Option to remove curve from line chart

### ISSUE THREAD

**Issue by lvt1325** [jtblin/angular-chart.js#468]
I'm using line chart directive from Angular-Chart.js (at https://jtblin.github.io/angular-chart.js/#line-chart).
At above link, a line chart is curve. I don't want curve, I'd like straight line.
Is there any option/config to make the line is straight not curve.
If not, I think we should have one.

**Comment by ravishan110** [comment]
Try this:

In your HTML template
`<canvas class="chart chart-line" chart-data="lineData" chart-labels="lineLabels" chart-series="lineSeries" chart-options="lineOptions" chart-click="onClick"></canvas>`

In your Angular App controller
```
$scope.lineOptions ={ elements : { line : { tension : 0 } } };
//define other required variables as per your requirement.
```
if that doesnt solve your issue, try installing latest package(beta) using below command:
`bower install --save angular-chart.js#1.0.0`

This will solve your issue. Hoep it helps. :)

**Comment by lvt1325** [comment]
Thanks Ravi, It works.
Where do you refer that?

**Comment by jtblin** [comment]
@lvt1325 the library is just a wrapper for Chart.js, see http://www.chartjs.org/docs/ for the different options.
