### ISSUE TITLE
horizontal chart x axis title on alog with bar chart

### ISSUE THREAD

**Issue by ashwinipc** [jtblin/angular-chart.js#470]
I have a horizontal bar chart and I need to display the x axis values which comes on the tooltip along with the bar, is there any option available to get this effect.

Thanks for you help 

### Overview

Describe the issue. What is the issue and what did you expect?

Please make sure to review and check all of these items:

- [ ] Use latest version of the library
- [ ] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [ ] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent. Issues without repro steps may be closed immediately.** 

Here is a [jsbin template for 0.x version](http://jsbin.com/cucoqe/1/edit?html,js,output) and [one for 1.x](http://jsbin.com/rodunob/edit?html,js,output) for convenience.

**Comment by ashwinipc** [comment]
![capture](https://cloud.githubusercontent.com/assets/16604260/17927800/14586c2e-6a15-11e6-8256-516e4a8c5a78.PNG)


Please see the attached file, I need to have this value aligned to the bar

**Comment by jtblin** [comment]
You need to check http://www.chartjs.org/docs/, all the options over there can be used in this lib.
