### ISSUE TITLE
angular.merge is not a function

### ISSUE THREAD

**Issue by alijohn** [jtblin/angular-chart.js#472]
Hi,

I am using the latest angular-chart.js Version: 1.0.2, AngularJS v1.3.17 and Chart.js Version: 2.1.6. 

If I use the above with 'Mix Chart' example from the source all works file.

If I use the above with an application using following libraries I get error '_TypeError: angular.merge is not a function at angular-chart.js:303:21_'

- jquery.js
- bootstrap.js
- toastr.js
- angular-route.js
- angular-cookies.js
- angular-validator.js
- d3.min.js
- angular-gridster.min.js

Please help!

Thanks

Ali

**Comment by jtblin** [comment]
[angular-merge](https://docs.angularjs.org/api/ng/function/angular.merge) is part of angular core so not sure what the issue is here.

**Comment by alijohn** [comment]
Thanks.

Anyone run into this issue, please update Angularjs to version 1.4 at minimum.

**Comment by ccasalicchio** [comment]
or use the spread operator [... x]

**Comment by ccasalicchio** [comment]
https://stackoverflow.com/a/39465006/791245
