### ISSUE TITLE
Typo fix: Please fix the documentation

### ISSUE THREAD

**Issue by TheCodeDestroyer** [jtblin/angular-chart.js#473]
On your [page](https://jtblin.github.io/angular-chart.js/) where you have an example of dynamic charts.
You have a typo in javascript tab:

```js
$scope.type = $scope.type === 'PolarArea' ? 'Pie' : 'PolarArea';
```
Should be:
```js
$scope.type = $scope.type === 'polarArea' ? 'pie' : 'polarArea';
```

This is probably where people are getting these two errors:
```js
t.controllers[r.type] is not a constructor
```
or
```js
Chart.controllers[meta.type] is not a constructor
```
I know that this is the difference between chart v2.x and v1.x so maybe this could be added to FAQ or something.

**Comment by jtblin** [comment]
Thanks for reporting, this should be fixed now.

The difference for chart types casing is already indicated in the readme:

> chart types are in `camelCase` e.g. `line` and `polarArea`
