### ISSUE TITLE
how to set a template for y labels ?

### ISSUE THREAD

**Issue by webattitude** [jtblin/angular-chart.js#474]
### Overview

Describe the issue. What is the issue and what did you expect?
I'm looking for Yscales template equivalent, to be able to parse computed y labels with moment duration

Please make sure to review and check all of these items:

- [x] Use latest version of the library
- [ ] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [ ] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent. Issues without repro steps may be closed immediately.** 

Here is a [jsbin template for 0.x version](http://jsbin.com/cucoqe/1/edit?html,js,output) and [one for 1.x](http://jsbin.com/rodunob/edit?html,js,output) for convenience.

**Comment by jtblin** [comment]
Check http://www.chartjs.org/docs/#doughnut-pie-chart and maybe ask on Stackoverflow?
