### ISSUE TITLE
Chart does not refresh when adding/removing data items

### ISSUE THREAD

**Issue by myjupiler** [jtblin/angular-chart.js#479]
My chart is declared as following and updated by manipulating the chartModel object
< canvas class="chart chart-bar"
width="500" height="200"
chart-data="chartModel.data"
chart-series="chartModel.seriesLabels"
chart-labels="chartModel.xLabels"
chart-options="chartModel.options">

Updating options, xLabels, seriesLabels works fine as the chart gets updated.

When updating data, it is properyly updated if I change the y-axis values, for example, changing chartModel.data from [[1, 2, 3, 4, 5]] to [[5, 4, 3, 2, 1]]

but nothing happens when I remove/add a new x-axis value
from [[1, 2, 3, 4, 5]] to [[1, 2, 3, 4, 5, 6]]

chartModel.data is completely recreated, I don't push the new item into it.

If I change another property, then the new x-axis values are displayed.

**Comment by jtblin** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps as described in the issue template. Check this element's CONTRIBUTING.md for an example.
