### ISSUE TITLE
Installing with bower still not working...

### ISSUE THREAD

**Issue by mackelito** [jtblin/angular-chart.js#483]
I just cant get this bower install working :(

```
bower install --save angular-chart.js
bower angular-chart.js#*        cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#*      validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#*
bower chart.js#2.x           ENOTFOUND Package npm:chart.js not found
```
Would really love to change to NPM but it´s just not possible in this project...

**Comment by wiktorwojcikowski** [comment]
1. run `npm install -g bower-npm-resolver`
2. run `bower install --save angular-chart.js' 
2. for proper injection bower components add to bower.json
```"overrides" : {
    "chart.js": {
      "main": [
        "dist/Chart.bundle.min.js"
      ]
    }
  }```
3. have fun

**Comment by jtblin** [comment]
Thanks @wiktorwojcikowski. Which is pretty much what is described in the [readme](https://github.com/jtblin/angular-chart.js#bower)...

@wiktorwojcikowski  the bower `overrides` is now in [bower.json](bower.json), does it need to be in the bower.json of the project that requests angular-chart.js as well or it is enough to have it here? (asking in case docs need more updating).

**Comment by wiktorwojcikowski** [comment]
For gulp inject that I m using, it needs to be in bower.json of the project that requests angular-chart.js.

**Comment by mackelito** [comment]
Sorry but still doesn't work...
I have "npm install -g bower-npm-resolver"...
And then I get:

```
bower install --save angular-chart.js
bower angular-chart.js#*        cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#*      validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#*
bower chart.js#2.x           ENOTFOUND Package npm:chart.js not found
```

**Comment by mackelito** [comment]
So angular-chart.js is never added to bower.json file

**Comment by sarahsga** [comment]
Make sure you added `"resolvers": [
    "bower-npm-resolver"
  ]` in **.bowerrc** and **NOT bower.json**
I was getting exactly the same error, but i noticed i had put the resolver in bower.json instead of .bowerrc
