### ISSUE TITLE
"Unable to parse color from object" when clicking or hovering over a data point in a line chart

### ISSUE THREAD

**Issue by Lehonti** [jtblin/angular-chart.js#485]
### Background

I am developing a rough draft of a mobile app using the Ionic Framework and angular-chart. My code is based on the example directive found on the [angular-chart webpage](http://jtblin.github.io/angular-chart.js/).

### Problem

When clicking or hovering over any data point in a line chart, the JavaScript console reports an error. Notice that the error is repeated by moving the cursor inside the circle that represents the data point,, as shown in the picture.

`Chart.min.js:10 Uncaught Error: Unable to parse color from object ["rgba(151,187,205,1)","rgba(220,220,220,1)","rgba(247,70,74,1)","rgba(70,191,189,1)","rgba(253,180,92,1)","rgba(148,159,177,1)","rgba(77,83,96,1)","rgba(132,233,74,1)"]`

![charterror](https://cloud.githubusercontent.com/assets/17771375/18182559/1381d514-7056-11e6-9a81-c3e23b116d7d.png)

The expected behavior is, in this case, a tooltip popping up, like this.

![tooltip](https://cloud.githubusercontent.com/assets/17771375/18183176/c6ba178e-7058-11e6-825d-cdb6768e30fa.png)

I attach my markup and JavaScript, in case it is of any help to you.

[dashboard.zip](https://github.com/jtblin/angular-chart.js/files/450648/dashboard.zip)

To be fair, I only tested it on Chrome (**UPDATE**: I also tested in Firefox and got the very same error) and I don't really know if this is an issue with angular-chart or the chart.js core library, but I'm posting it anyway. If you find that the mistake is actually mine, by all means tell me.

**Comment by jtblin** [comment]
This is the same issue as #476 with RGBA not being supported. Please follow over there. There is also a PR #488 that I haven't had time to review yet.

**Comment by andreshg112** [comment]
This worked for me:
http://stackoverflow.com/questions/38239877/unable-to-parse-color-in-line-chart-angular-chart-js

Data must be on double array.

**Comment by EmilMoe** [comment]
If I use double array then no data is displayed

**Comment by nadeemkhoury** [comment]
same here, @EmilMoe did you find a solution ?

**Comment by nadeemkhoury** [comment]
@EmilMoe I followed @andreshg112  solution, and it worked for me. be sure to have data like this [[1,2,3]] not like this [[1],[2],[3]]. Cheers

**Comment by OnlyAGhost** [comment]
I got the same error running just regular chart.js (so may not be relevant) but the problem for me is that line charts cannot have an array of colors and must have a single non-array value for the color. Pie charts and bar charts obviously have multiple per dataset as each bar or slice of pie can have its own color, but a line chart cannot.

**Comment by adriel** [comment]
@OnlyAGhost Thank you! This was the issue I was having, and removing the array for colors fixed it.
Was also using regular chart.js

**Comment by somat** [comment]
I have the same issue with line type chart, and solve this issue with assigning backgroundColor as single value in datasetOverride.

```
        <canvas id="line" class="chart chart-line"
          chart-data="data" chart-labels="labels"
          chart-options="options" chart-colors="colors"
          chart-dataset-override="datasetOverride"></canvas>

    $scope.datasetOverride = {
        backgroundColor: "rgba( 0,203,254,0.3)"
    };

```

**Comment by rolljee** [comment]
@OnlyAGhost Thanks you for that, it's seems pretty obvious now...
