### ISSUE TITLE
How can i use chart.js all option ?

### ISSUE THREAD

**Issue by sohantandel** [jtblin/angular-chart.js#486]
I m <b>new to angularjs </b>and i get stuck to customize chart like want to<b> change bar color,</b> want to <b>remove grid line </b>, want to  <b>remove x-axis y-axis </b> etc..
I m using v1.0.2 , how can i use all option available in chart.js  
for example i want to use option like attached in file. How can i use such option using this library.
Thanks!
Sohan Tandel
![chart-js-options](https://cloud.githubusercontent.com/assets/5380049/18195769/20502a1a-710b-11e6-9f36-777e0b50afb5.png)

**Comment by jtblin** [comment]
By using the `chart-options` attribute.  Sorry I don't have the time to provide individual support for this type of questions. This question seems more appropriate for StackOverflow and you will get more help with [StackOverflow](angular-chart) tagged with _angular-chart_.
