### ISSUE TITLE
How do you set up a scatter line plot?

### ISSUE THREAD

**Issue by edgartheunready** [jtblin/angular-chart.js#492]
Hi All,
I created a stackoverflow question for this issue as recommended. I'd love to know how to do this, and I'll even update the docs once this is answered. 

Basicaly, I have a chart.js scatter plot working, but can't figure out how to pass that data to the line chart directive. Could you lend me a hand and answer my SO question?

[http://stackoverflow.com/questions/39356119/how-do-you-set-up-a-chart-js-scatter-line-chart-through-angular-chart-js](http://stackoverflow.com/questions/39356119/how-do-you-set-up-a-chart-js-scatter-line-chart-through-angular-chart-js)

**Comment by edgartheunready** [comment]
Maybe I'll try to debug it from here: https://github.com/jtblin/angular-chart.js/blob/master/dist/angular-chart.js#L294

**Comment by edgartheunready** [comment]
I still haven't figured this out. It looks like maybe angular-chart.js doesn't support sparse datasets? Is that true?

**Comment by jtblin** [comment]
`scope.data` should be an array not an object. Try something like below if it's based on a line chart:

```
$scope.data = [[{
        x: -10,
        y: 0
    }, {
        x: 0,
        y: 10
    }, {
        x: 10,
        y: 5
    }]
}]];
```

**Comment by Charles-BARDIN** [comment]
Hi @edgartheunready, 
I have the same issue and @jtblin code does not fix it. Have you found any solutions ?

Thanks

**Comment by edgartheunready** [comment]
I have not, and I haven't looked into it further yet. My work priorities shifted. I'll have to tackle this soon though. I might end up using chart.js directly or figure out how to update this wrapper to support sparse data.

**Comment by casanueva** [comment]
Hi @edgartheunready !

Please tell me how you resolved this, if you do. I need scattercharts to.

thanks

**Comment by Charles-BARDIN** [comment]
Thanks for you answer @edgartheunready.

@casanueva I did not succeed to create a scatterchart with angular-chartjs neither. Right now I don't have time to try to update angular-chart.js, so I'll just go with Chart.js.

**Comment by casanueva** [comment]
@jtblin Hey, have you made any shatter charts? could you show some example code on how one would do that in a Linechart?

**Comment by jtblin** [comment]
The code I pasted above just works, see http://jsbin.com/hejeyad/1/edit?html,js,output for example.
Make sure to read the docs: http://www.chartjs.org/docs/#line-chart-scatter-line-charts

**Comment by jtblin** [comment]
Also see http://jtblin.github.io/angular-chart.js/test/fixtures/scatter.html

**Comment by casanueva** [comment]
Cool thanks, didnt get it to work but ill try it out on monday!

Den 24 sep. 2016 05:21 skrev "Jerome Touffe-Blin" <notifications@github.com

**Comment by casanueva** [comment]
Woho! works like a chart(charm)! Dont know if thats the problem, but it
only worked if i put the options data in with the other info in the tag.

2016-09-24 20:40 GMT+02:00 jonathan casanueva willumsen <
jonathan.casanueva@gmail.com>:
