### ISSUE TITLE
Automatic resize of chart

### ISSUE THREAD

**Issue by jibax** [jtblin/angular-chart.js#493]
I have a basic chart with options.responsive = true, and I add data to this chart. However, even if only the chart wrapper width changes programmatically, the height of the chart changes too. This is a strange behavior of responsiveness. 

Is it another way to change only the width of the chart to keep the same space between bar chart ? 

angular chart : v1.0.0
Chart.js : 2.0.2

**Comment by jtblin** [comment]
Thanks for posting the answer to your issue @jibax
