### ISSUE TITLE
How to fill color for line chart?

### ISSUE THREAD

**Issue by hanigogo** [jtblin/angular-chart.js#495]
I try to set chart-colours, but it’s not working. 
I want to make an effect, which looks like the following picture

[http://imgur.com/a/PzNdB](http://imgur.com/a/PzNdB)

What should i do? 
Thanks. 

Code: 
https://codepen.io/hanigogo/pen/qadZkx?editors=1111

```
    <canvas id="line" class="chart chart-line" data="data"
      labels="labels" legend="true" series="series"
      click="onClick" chart-colours="colours">
    </canvas> 
```
```
  $scope.colours = [{
      fillColor: "rgba(151,187,205,1)",
      strokeColor: "rgba(151,187,205,1)",
      pointColor: "rgba(151,187,205,1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(151,187,205,0.8)"
  }];

```

**Comment by jtblin** [comment]
It's `chart-colors` since 1.x.

**Comment by devsubhajit** [comment]
I am using chart-colors but still not getting my mentioned color, its showing global random colors.
Any suggestions?
