### ISSUE TITLE
How to change series bar color 

### ISSUE THREAD

**Issue by zymr-keshav** [jtblin/angular-chart.js#496]
### Overview

I have created bar chart with 2 series , it's created succesfully but the color which bar is filled is very less opacity. I want it dark so i tried with various options but didn't find any satisfactory solution.

see[ this plunker](http://plnkr.co/edit/9WursX0JRkShso3Y9isP?p=preview) for the reference

what I have tried:

1.  trying to set default colors options in `.config()`   for bar 
```

        ChartJsProvider.setOptions('bar', {
          colours: [
                {
                  fillColor: "rgba(000,111,111,.5)",
                  strokeColor: "rgba(111,111,111,.5)"
                },
                {
                  fillColor: 'rgba(144, 185, 18, .5)',
                  strokeColor: 'rgba(47, 132, 71, .6)'
                }
            ]
        });
```

bit it does not affect anything :(

2.  setting inside controller with $scope.colors 

```
 $scope.bar.colors = [{
                      "fillColor": "rgba(224, 108, 112, 1)",
                      "strokeColor": "rgba(207,100,103, 1)",
                      "pointColor": "rgba(220,220,220, 1)",
                      "pointStrokeColor": "#fff",
                      "pointHighlightFill": "#fff",
                      "pointHighlightStroke": "rgba(151,187,205,0.8)"
                }];
and 

 <canvas height="270" id="bar" class="chart chart-bar" chart-data="bar.data" chart-labels="bar.labels" chart-series="bar.series" chart-options="bar.options" chart-colors ="bar.colors"></canvas>
```
This changes bar colors of one series ; i tried with two object  in `$scope.bar.colors` but than it does not change any bar colors.

and by using this bar color changes on every refresh with random color, which i do not want. i want constant color of bar .

3. using `chart-dataset-override` property

```
 $scope.bar.datasetOverride: [
                    {
                        fill: true,
                        backgroundColor: [
                       "#A2D9CE",
                       "#A2D9CE",
                       "#A2D9CE",
                       "#A2D9CE",
                       "#A2D9CE",
                       "#A2D9CE"
                        ]
                    },
                    {
                        fill: true,
                        backgroundColor: [
                        '#688091',
                        '#688091',
                        '#688091',
                        '#688091',
                        '#688091',
                        '#688091'
                        ]
                    }],
```

This fill the bar as pert my need but in this case I need to set color for every data , 

is there any short way to do this?

My version 

    "chart.js": "npm:chart.js#^2.2.1",
    "angular-chart.js": "^1.0.2"

**Comment by jtblin** [comment]
The color object has changed in Chart.js 2.x, see https://github.com/jtblin/angular-chart.js/blob/master/examples/app.js#L179 for example.

**Comment by MattGarnettWelsh** [comment]
Sorry to bring up an old issue, I haven't yet seen the third part of the OP's question answered anywhere. Is there any quick way to set the default colour for ALL bars within a singular Bar Chart? I noticed in multiple series bar charts they do set by default to a solid colour for each series of data but not when their is only one dataset.

Any help much appreciated.

**Comment by glenndilen** [comment]
> Sorry to bring up an old issue, I haven't yet seen the third part of the OP's question answered anywhere. Is there any quick way to set the default colour for ALL bars within a singular Bar Chart? I noticed in multiple series bar charts they do set by default to a solid colour for each series of data but not when their is only one dataset.
> 
> Any help much appreciated.

YES!

Enclose your dataset only, in another array.
