### ISSUE TITLE
global options being swiped when set options in data-option

### ISSUE THREAD

**Issue by sunkeyfong** [jtblin/angular-chart.js#499]
### Overview

@version : 1.0.2 ( from npm package).

When options set to chart in $scope , Global options set in provider config lost.

like : 

global
```javascript
options = {
    title : {
        display : true,
    },
}
```
chart
```javascript
options = {
    title : {
        text : 'hello',
    },
}
```
expect
```javascript
options = {
    title : {
        display : true,
        text : 'hello',
    },
}
```
infact
```javascript
options = {
    title : {
        display : false,   //the default value
        text : 'hello',
    },
}
```

It was suspected when options set, it was merged with the default value, not the value after global configed.

**Comment by jtblin** [comment]
Isn't that the same as #449 ?

**Comment by jtblin** [comment]
This issue should now be fixed, see https://github.com/jtblin/angular-chart.js/pull/498
