### ISSUE TITLE
Option to show VALUES on chart

### ISSUE THREAD

**Issue by lvt1325** [jtblin/angular-chart.js#501]
Is there any option to show values of bar in bar chart.
As bar chart at http://jtblin.github.io/angular-chart.js/#bar-chart
I want to show value at the top of each bar.
Thanks.

**Comment by jtblin** [comment]
Please check http://www.chartjs.org/docs/ for available options.

**Comment by jack100501** [comment]
I was trying to search how to show values on a top of bar chart, but unfortunately I didn't found how to do it. is it any option now available for that?
