### ISSUE TITLE
Bower install cannot file chart.js

### ISSUE THREAD

**Issue by SeanBerce** [jtblin/angular-chart.js#502]
The bower install is trying to install **chart.js#2.x** but the chart repo is listed as **chartjs-Chart.js#^2.2.2**

The error:

```
bower install angular-chart.js --save
bower invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-chart.js#*        cached https://github.com/jtblin/angular-chart.js.git#1.0.2
bower angular-chart.js#*      validate 1.0.2 against https://github.com/jtblin/angular-chart.js.git#*
bower chart.js#2.x           ENOTFOUND Package npm:chart.js not found
```

**Comment by joshhoffman** [comment]
I'm seeing the same thing. Works for me on v0.8.6, but I was trying to update this and Chart.js and now I get the ```ENOTFOUND Package npm:chart.js not found``` error

**Comment by jtblin** [comment]
Please follow the instructions in the readme.

**Comment by joshuaos** [comment]
I followed the instructions in the readme for bower installation and now i get:

`Error: Cannot find module 'chartjs-color' from '\bower_components\chart.js\src\core'`

**Comment by joshuaos** [comment]
The bower install on this is a mess. I had to spend several hours adding all the dependances using
`bower install nmp:<package> --save`

then checking and fixing many bower.json main properties.  Then had to figure out the correct requires needed.  FYI, it's this:

`require('angular-chart.js');
require('chart.js');
`

**Comment by ujvala-bhumi** [comment]
Following saved my day. Applying 
1. sudo npm install -g bower-npm-resolver (The resolver will match packages with npm: [prefix](https://github.com/mjeanroy/bower-npm-resolver) )
2. add "chart.js":"npm:chart.js#latest" to  bower.json
3. add "resolvers": [ "bower-npm-resolver" ] to  .bowerrc
Finally applying bower install worked well! :+1:

**Comment by bwyss** [comment]
@ujvala-bhumi Thx that worked as well for me
