### ISSUE TITLE
Change bars colors

### ISSUE THREAD

**Issue by hiniesta** [jtblin/angular-chart.js#503]
I will appreciate some help to know if its posible to change different colors for each bar in a chart-bar.

Hace tried something like this: [http://stackoverflow.com/questions/25594478/different-color-for-each-bar-in-a-bar-chart-chartjs](http://stackoverflow.com/questions/25594478/different-color-for-each-bar-in-a-bar-chart-chartjs) but nothing working

**Comment by jtblin** [comment]
Have you checked http://www.chartjs.org/docs/ for available options?

**Comment by ildefonso** [comment]
I think the option in chartjs is in DataSet structure : http://www.chartjs.org/docs/#bar-chart-dataset-structure

In background color option.

Is it posible with the actual code add them?

**Comment by jtblin** [comment]
Yes you can use `chart-dataset-override` attribute.
