### ISSUE TITLE
Data points and tooltips cropped when chart legend and axis labels are hidden

### ISSUE THREAD

**Issue by schamb34** [jtblin/angular-chart.js#504]
### Overview

I am trying to produce a chart without any legends or series labels (see attached image), but unfortunately, the chart data points and tooltips are being cropped in the canvas.

![croppedchart](https://cloud.githubusercontent.com/assets/22295149/18631825/36f35184-7e6c-11e6-93ee-206164562984.png)

### Step to reproduce

Apply this config (typescript):

   var chartData: LinearChartData = <LinearChartData>{
                labels: labels,
                datasets: [
                    {
                        label: 'Tracked Contacts',
                        backgroundColor: '#66BEB7',
                        type: 'line',
                        lineTension: 0,
                        data: dataPoints
                    }
                ]
            };

            var chartConfig: ChartConfig = {
                type: 'line',
                data: chartData,
                options: {
                    legend: {
                        display: false,
                        labels: {
                            boxWidth: 20,
                            fontSize: 10
                        }
                    },
                    scales: {
                        xAxes: [
                            {
                                stacked: false,
                                display: false
                            }
                        ],
                        yAxes: [
                            {
                                ticks: {
                                    fontSize: 10
                                },
                                display: false
                            }
                        ]
                    }
                }
            };

**Comment by jtblin** [comment]
Sorry I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
