### ISSUE TITLE
how to create dynamic charts in angular using json file? 

### ISSUE THREAD

**Issue by ChoudharyNikhil** [jtblin/angular-chart.js#508]
I am new to angular, please help. I want to create dynamic chartmeans my chart changes when I supply data from server by using json file? Can anyone explain how should I start from scratch.

**Comment by jtblin** [comment]
Sorry I don't have the time to provide individual support for this type of questions. This seems more appropriate for [StackOverflow](angular-chart), you can tag the question with _angular-chart_. You will get more help over there.
