### ISSUE TITLE
Set Colors of Charts - Wrong Docu

### ISSUE THREAD

**Issue by MartinBundschuh** [jtblin/angular-chart.js#515]
The Documentation of how to change/set the colors of the several charts is wrong.

"ChartJsProvider.setOptions({ colors : [ '#803690', '#00ADF9', '#DCDCDC', '#46BFBD', '#FDB45C', '#949FB1', '#4D5360'] });"
This is how it is described on the different pages/APIs.
 If you youse colors, chart-colors (attribute) it won't work at all.

The solution is simple. You need say colours with na OU not just an O.
Please correct the documentation. This is kinda missleading right now.

Regards

**Comment by jtblin** [comment]
You're looking at outdated code or using the old branch. This has changed in 1.x to chart-colors as per the README and the doc.
