### ISSUE TITLE
Stack horizontal bar NaN

### ISSUE THREAD

**Issue by shamrickus** [jtblin/angular-chart.js#516]
When using a stacked horizontalBar and hiding all of the data, NaN is displayed in the top left of the chart. To reproduce, just hide all of the data labels after setting up a stacked horizontalBar.

![013b4776588bcccb7a9757e8f84ba8b7](https://cloud.githubusercontent.com/assets/5377636/18938025/adb6ac92-85b2-11e6-9de7-73d7141f9b33.png)

JSBin: http://jsbin.com/mobabe/edit?html,js,output

 I noticed the issue was brought up in #445, but he/she decided not to follow up.

**Comment by jtblin** [comment]
Thanks for providing a jsbin, however it doesn't seem to have the issue that you mentioned:

![image](https://cloud.githubusercontent.com/assets/1388974/19019028/9163460a-88c2-11e6-866b-40eb8f659c5b.png)

**Comment by shamrickus** [comment]
It only occurs when you hide all off the labels, here is a gif showing it in action.

https://gyazo.com/ece1222b32e2069c26c2d7fa3fd2b00b

**Comment by jtblin** [comment]
Oh I see. It doesn't do that with standard bars e.g. on http://jtblin.github.io/angular-chart.js/

![image](https://cloud.githubusercontent.com/assets/1388974/19552650/757f4d1a-96fc-11e6-89f8-094185b706e7.png)

Anyhow that would be an issue with Chart.js itself. Could you post an issue on their issue tracker? https://github.com/chartjs/Chart.js
