### ISSUE TITLE
Time Scale Option

### ISSUE THREAD

**Issue by seetsy** [jtblin/angular-chart.js#517]
Is time scale supported? I've tried various config options to no avail and can't find any examples.

http://www.chartjs.org/docs/#scales-time-scale

**Comment by seetsy** [comment]
Never mind, adding the following did the trick:
xAxes: [
{
   type: 'time',
   display: true
}]

**Comment by vvdwivedi** [comment]
Can you please put up an example somewhere. I am not able to figure out how exactly can we use it.
