### ISSUE TITLE
Chart not working due to TypeError

### ISSUE THREAD

**Issue by b3h3rkz** [jtblin/angular-chart.js#519]
I get this error on the console when I try to run my app.
`Uncaught TypeError: Cannot set property 'mode' of undefined
angular.min.js:400

What do you think might be the cause?

PS: Using the line example from the docs`

**Comment by jtblin** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps as described in the issue template. Check this element's CONTRIBUTING.md for an example.
