### ISSUE TITLE
wanted to add double Y axis 

### ISSUE THREAD

**Issue by sagar-mindstix** [jtblin/angular-chart.js#52]
How can I add double Y axis in chart?

**Comment by jtblin** [comment]
Chart.js does not support this functionality, see https://github.com/nnnick/Chart.js/issues/17 (there is a $100 bounty on it), hence this wraooer doesn't either.

**Comment by sawajid** [comment]
https://github.com/nnnick/Chart.js/releases/tag/v2.0-alpha

alpha of chartjs version has these feature

**Comment by pavan66** [comment]
@sagar-k @jtblin @sawajid  http://jsfiddle.net/Lfmhcab3/4/ 
In above jsfiddle "My Second dataset" need to show on second y-axis...can someone help me with that
