### ISSUE TITLE
Help with setting bar chart label

### ISSUE THREAD

**Issue by steverob** [jtblin/angular-chart.js#521]
Here is a simple [fiddle](https://jsfiddle.net/vz4qhqpw/6/) of a bar chart setup using Angular Chart.js 

Now if you look at the tooltips we get on hover, they do not have any label for the values. I've tried multiple things but did not get the desired result. 

For instance I tried using 

```
$scope.series = ['# of votes'];
$scope.data = [28, 48, 40, 19, 86, 27, 90]
```

But this did not add any label. And then I tweak it such that the data is an array of arrays.

```
$scope.series = ['# of votes'];
$scope.data = [[28, 48, 40, 19, 86, 27, 90]];
```

Now all the bars were rendered in the same color which is not what I need. I am basically displaying results of a simple poll.

Would love some help with this!

**Comment by jtblin** [comment]
Sorry I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
