### ISSUE TITLE
Uncaught TypeError: Cannot set property 'mode' of undefined in angular chart js injection

### ISSUE THREAD

**Issue by devangptechuz** [jtblin/angular-chart.js#523]
I have included all dependencies about injection of angular chart js but still it through the error 
"Cannot set property 'mode' of undefined"

What should i do to solve this issue ,
Please help me,

Thanks in advanced

**Comment by adamk33n3r** [comment]
I found out that this is because the dependencies are listed as `chartjs: '2.x'` even though the angular-chart.js site explicitly says it requires `2.0.x`. The workaround is to uninstall chart.js and reinstall chart.js as version 2.0.x (which is 2.0.2).

**Comment by jtblin** [comment]
Nah it works with any 2.x version. Where did you see this mentioned, I will fix it.

**Comment by adamk33n3r** [comment]
It's on the website here http://jtblin.github.io/angular-chart.js/ at the top. I don't know, then, why this is an issue but downgrading chart.js solved it for me.
