### ISSUE TITLE
I do not see any option for scatter charts witch are supported by chartjs under line charts

### ISSUE THREAD

**Issue by RZeni** [jtblin/angular-chart.js#527]
Probably a feature suggestion but while playing with line charts and attempting to make it a scatter chart i was unable to find the options for this, such as per dataset options.  Support for scatter charts would be great.

Latest release of angular-js, chart js and appropriate version of angular as of 2016-10-24.

**Comment by jtblin** [comment]
http://jtblin.github.io/angular-chart.js/examples/scatter.html
