### ISSUE TITLE
How to Format the scaleLabel?

### ISSUE THREAD

**Issue by KarlStony** [jtblin/angular-chart.js#530]
Hi,
I'm tying to draw a line chart, and i'd like to format the value as '30%' instead of '30' at yAxis.
I try to add
`scaleLabel : "<%= Number(value) + ' %'%>"`
in options but it doesn't work.

I'm using angular-chart.js 1.0.0-beta1 and Chart.js 2.2.0-rc.1
Could somebody show me how to format the scaleLabel?
Thanks!

**Comment by KarlStony** [comment]
OK,finally figure it out.
add this in options.
```
scales: {
        yAxes: [
          {
            ticks:{
              callback: function (value) {
                return Number(value).toFixed(2)+"%"
              }
            },
          },
        ]
      }
```

**Comment by srinivas999** [comment]
Thank you its working for me also
