### ISSUE TITLE
how to set x y scale label

### ISSUE THREAD

**Issue by raneez88** [jtblin/angular-chart.js#533]
Hi buddy,

$scope.labels = ["AF", "AV", "CAB", "STR", "PNT", "NDT"];
$scope.series = ['FRM', 'CAP'];
$scope.data = [
                   [1600, 1300, 1400, 900, 2000, 700],
                    [1300, 1000, 2000, 1200, 2500, 500]
                  ];
$scope.options = {elements:{line:{tension:0}}};

Above code is using to plot line chart. I found some of the issue which already raised about axis labels. Mostly all solution tells that to configure in "chart-options" But i already using options to set line tension. 
I guess options wont take list items Please make me clear on this and give a solution.

Thanks in Advance 
Raneez

**Comment by erick2014** [comment]
@raneez88 http://stackoverflow.com/questions/39012925/angular-chart-js-make-line-chart-does-not-curve

**Comment by jtblin** [comment]
Options seem to be used properly as per SO Q&A. You can also have a look at the examples folder.
