### ISSUE TITLE
Responsive chart doesn't change size of container gets smaller

### ISSUE THREAD

**Issue by djleonskennedy** [jtblin/angular-chart.js#534]
global parameters:
    responsive: true,
    maintainAspectRatio: true,

layouts are `flex`
have several `div`s with charts, they all `flex 0 0 47.5%` 

When i'm resizing window to bigger scale all goes fine, but when i try to decrease size charts doesn't decrease size

Thank you

**Comment by jtblin** [comment]
jsbin for repro?
