### ISSUE TITLE
Customise legendTemplate templates?

### ISSUE THREAD

**Issue by asadsahi** [jtblin/angular-chart.js#538]
Just installed latest package of angular-chart.js (i.e Version 1.0.3). Trying to customise the legend template, but cannot find any resource, have tried every possible option on options object passed to canvas element, but legend template is not changing, position is changed, but not sure what is the option to customise legend elements.

Here is how it looks with default legends.

![image](https://cloud.githubusercontent.com/assets/3470892/19900694/57bcd2a2-a05c-11e6-80da-858f4fce5e52.png)

Html
```
<canvas id="doughnut" class="chart chart-doughnut" chart-data="$ctrl.data" chart-labels="$ctrl.labels" chart-options="$ctrl.options"
		chart-colors="$ctrl.colors">
	</canvas>
```

js:
```
$ctrl.options = {
                legend: {
                    display: true,
                    position: 'bottom',
                },
                legendCallback: function (chartInstance) {
                    console.log(chartInstance);
                }
            };
```

this [issue](https://github.com/jtblin/angular-chart.js/issues/210) seems to be and old one. so does not give any help.

Can someone please give any clue to customise legendTemplate?

**Comment by jtblin** [comment]
`legendCallback` seems to be a global option: http://www.chartjs.org/docs/

Also have a look at http://www.chartjs.org/docs/#chart-configuration-legend-configuration

**Comment by asadsahi** [comment]
Does global option mean that it cannot be set on options object when using angular-chart.js?

I have tried using this callback on the options object, but that doesn't seem to work. 

Can you please create plnkr/fiddle where legend is customised using this callback?

Thanks

**Comment by Estar1** [comment]
Please having this same issue, was anyone able to implement a solution in fiddle or a code fragment ?

Thanks
