### ISSUE TITLE
Pie chart hover and background color options not correctly used?

### ISSUE THREAD

**Issue by sabliao** [jtblin/angular-chart.js#539]
### Overview

Describe the issue. What is the issue and what did you expect?
I would expect the 'backgroundColor' option to be the fill color of the arcs and 'hoverBackgroundColor' to be the color of the arcs when hovered over, as explained [here](http://www.chartjs.org/docs/#doughnut-pie-chart-dataset-structure). However, if I do that, the fill color ends up being the default gray and when I hover over that piece, I get my background color. This then led me to try different combinations, and the way I was able to get my fill color and hover color to be those intended, I had to set my fill color to the 'pointBackgroundColor' option and my hover color to the 'backgroundColor' option.

Please make sure to review and check all of these items:

- [x] Use latest version of the library
- [x] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [x] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent. Issues without repro steps may be closed immediately.** 

Here is a [jsbin template for version 1.0.3](https://jsbin.com/betozapuya/1/edit?html,js,console,output).

**Comment by develmts** [comment]
Same for Doughnut charts

**Comment by harshajasti92** [comment]
I faced the same issue today with pie charts. Has there been a fix for this ?

**Comment by pradippatel1411** [comment]
```
backgroundColor: [ '#5cb85c', '#D74B4B', '#6685a4', '#f0ad4e', '#5bc0de', '#EE82EE' ],
                       
hoverBackgroundColor: ['#5cb85c', '#D74B4B', '#6685a4', '#f0ad4e', '#5bc0de', '#EE82EE'],
                        
```
