### ISSUE TITLE
Not enough colours (default or pre-defined) causes an array out of range exception

### ISSUE THREAD

**Issue by saorsa** [jtblin/angular-chart.js#54]
getData or getDataSeries loops through an array of colors with a possible array out of range exception(when data.length is > than scope.colours.length(or default colors length).
A possible (but ugly fix might be):
```
//Prevent an undefined compilation error
colours: '=?',
//Remove colour array assignment in getdata and getdata series
function createChart()
    scope.colours = scope.colours || Chart.defaults.global.colours;
		if(scope.colours.length < scope.data.length)
		{
			var itemsToAdd = scope.data.length - scope.colours.length;		
			for(var i=0; i<=itemsToAdd; i++)
			{
				var color = getRandomColor();
				scope.colours.push({
					fillColor: color,
					strokeColor: color,
					pointColor: color,
					pointStrokeColor: "#fff",
					pointHighlightFill: "#fff",
					pointHighlightStroke: "rgba(151,187,205,0.8)"
				});
			}
		}
```
getRandomColor() is a matter of a flavour.
Cheers!

**Comment by jtblin** [comment]
Nice suggestion. Will look into it. I like the idea of generating a random colour, just wondering if the library should not throw instead.

**Comment by saorsa** [comment]
or provide a getColor: =?
Well.. Maybe if explain the business case I will convince you not to throw.
We had an event with an unknown number of projects to be voted for.
We tested with a few and everything was great.
But the participants turned out to be more than expected and the chart crashed.
So from business perspective, maybe a $log will be great and a stability through randomColor (or a method provided by the developer) will be great. [:

**Comment by jtblin** [comment]
Got it. You know that you can pass colours already using the `colours` attributes, don't you?

I will add random colours in case not enough were provided, as you suggested. The "hard part" is probably going to be able to generate the difference nuances of the colours so that it doesn't look crap.

**Comment by jtblin** [comment]
Done and published as `0.5.0`. Thanks for the great suggestions, here how it looks with all random colours :)

![image](https://cloud.githubusercontent.com/assets/1388974/6096371/cbcf2568-afe1-11e4-902c-7318eb474065.png)

**Comment by saorsa** [comment]
Cheers, mate! [:

**Comment by nick-barth** [comment]
You are the man jtblin, thanks!
