### ISSUE TITLE
Passing additional Data into Chart attributes

### ISSUE THREAD

**Issue by snowyaaron1** [jtblin/angular-chart.js#541]
So what I am trying to accomplish is passing another piece of data into my charts so when I hover on the node I can then use a callback to display that as the label vs what I am currently feeding into the label.

Currently I am passing to chart-label and abbreviated label, and what I want to do is log the Long- field name somewhere else on the page

```
   <canvas id="{{'panel' + panelIndex + 'base'}}" class="chart-horizontal-bar" height="440px"
                            ng-show="detailModelsPanel[0].viz == 'hbc'"
                            chart-labels="detailModelsPanel[0].labels"
                            chart-data="[detailModelsPanel[0].data]"
                            chart-colours="['#0080C0']"
                            chart-hover="$root.hoverLongFieldName"
                            chart-legend="false"/>
```
js

```
$rootScope.hoverLongFieldName = function (points, evt) {
        try {
            console.log(points)
            $scope.index = points[0]['_index']
            $rootScope.placeHolderForLongFieldName = points[0]['_view'].label;
            $scope.$apply()
            console.log ($rootScope.test.sProfile[$scope.fieldName]['detail']['freq-histogram']['long-labels'][$scope.index]);
        }
        catch(e){
            console.log(e)

        }
    };
```
*** Please ignore the $rootScope use, that will be cleaned up!

See here, I am logging the label of the node(which is abbreviated) I want to be able to pass something else into the points object and reference like this:

` $rootScope.placeHolderForLongFieldName = points[0]['_view'].longLabel;`
Is there an attribute I can add to the html to allow adding data in? Or some other means? I am only looking for ways utilizing the chart.js library, nothing outside of it. I want to be able to pass it through to the "points" object.

**Comment by jtblin** [comment]
The points data is created by chart.js so I don't think you can do that. But maybe you could have a separate object where you store the long label and that you access using the short one maybe?

Closing as not really an issue, feel free to continue discussing here.
