### ISSUE TITLE
how to show label(tooltip) always inside each arc of pie chart using angular-chart.js and "chart.js": "2.3.0"

### ISSUE THREAD

**Issue by vinaynijhawan** [jtblin/angular-chart.js#543]
how to show label(tooltip) always inside each arc of pie chart using angular-chart.js and "chart.js": "2.3.0".
i am using your directive for chart.js

example:

http://jsfiddle.net/tk31rehf/

**Comment by jtblin** [comment]
Nice. It'd be great to have than as an example in /examples.

**Comment by westerncj** [comment]
How can we always show the tooltips with chart.js 2.x.x inside of angular chart for a pie chart?

**Comment by avihaym** [comment]
+1

**Comment by gitProject-kiran** [comment]
How we can display permanent tool-tip using angular-chartjs?

**Comment by dhc86** [comment]
that is a good question @gitProject-kiran, I am running into the same issue and still cannot find the answer. IF anyone has the answer please port it here! Thank you. I realized that angular-chartJS and chartJS have a few differences when rendering data. There are many solutions for chartJS, however for angular-chartJS those solutions do not work.
