### ISSUE TITLE
Base64 image is blank

### ISSUE THREAD

**Issue by nurgasemetey** [jtblin/angular-chart.js#544]
### Overview
Hello,
 
I wanted to take Base64 image of graph.
Shortly like this:

```
$scope.$on('chart-create', function(evt, chart) {
            console.log(chart);
            console.log(chart.toBase64Image());
            $scope.source = chart.toBase64Image();
        });
```
However it gives a blank picture.

### Step to reproduce

Here is the [jsfiddle link](https://jsfiddle.net/nurgasemetey/0bkttm3m/8/)

**UPDATE**: updated [jsfiddle link](https://jsfiddle.net/nurgasemetey/0bkttm3m/8/)

**UPDATE2**: It seems that *Chart.js*  works correctly as seen from [this jsfiddle](https://jsfiddle.net/nurgasemetey/dxo1jhu6/) . I guess that it breaks in *angular charts* part.
With regards

## SOLUTION

I solved this problem. You must add following to `options` :

```
animation: {
    onComplete: function(animation){
        console.log(animation.chartInstance.toBase64Image();//this gives the base64 image
    }
}
```

**Comment by hemant2018** [comment]
but the image is creating. only the upper half is visible
