### ISSUE TITLE
Radar chart - labels overflowed

### ISSUE THREAD

**Issue by pconihout** [jtblin/angular-chart.js#546]
Hi,

I'm having trouble with some of my radar chart, the labels on the bottom are hidden. I don't if it come from chart.js or the angular wrapper but i'd bet on the 2nd one.

As you can see on the screenshot, some letters of "Digital Marketing" are cut.

![capture d ecran 2016-11-07 a 17 59 58](https://cloud.githubusercontent.com/assets/16023563/20067070/0cbdf80a-a514-11e6-870d-780ce1f9da97.png)

Here a fiddle reproducing the bug.
https://jsfiddle.net/rvo8xL1z/

Regards.

**Comment by pconihout** [comment]
I found a temporary fix : adding one more label or removing one.

**Comment by jtblin** [comment]
The wrapper doesn't do anything from a display perspective so i'd think this is a chart.js issue.
