### ISSUE TITLE
Global config options not applying once built through cordova/ionic

### ISSUE THREAD

**Issue by Shadowstep33** [jtblin/angular-chart.js#552]
Using angular-chart.js v1.0.3
chart.js v2.4.0
ionic (tried 1.7.7 and latest 2.x build)

Not sure how to add a repro case because it seems to be specific with being run on cordova/ionic. I am using the following lines to globally config charts:

```
        chartJS.Chart.defaults.doughnut.cutoutPercentage = 80;
        chartJS.Chart.defaults.global.elements.arc.borderWidth = 0;
        chartJS.Chart.defaults.global.animation.easing = 'linear';
        chartJS.Chart.defaults.global.animation.duration = 300;
        chartJS.Chart.defaults.global.defaultFontColor = "#ffffff";
```

It works correctly in browser but as soon as the app is built they don't seem to apply.

**Comment by jtblin** [comment]
Try passing options via config. Closing if it's an ionic issue.

**Comment by Shadowstep33** [comment]
This was 100% my own fault. Had an:

```
if(cordova){
return;
}

//set config options
```
