### ISSUE TITLE
options are not changing, tried various example and is not working

### ISSUE THREAD

**Issue by piux** [jtblin/angular-chart.js#553]
im trying to add my own scale labels in angular chart js like in this issue https://github.com/jtblin/angular-chart.js/issues/33, the problem is that when i try that example, even with the same code that shows in the resolved issue it doesnt work, it wont take the options i assign in my scope.

since i have 4 states that will be the same, i was thinking i could make a function like this, but im having trouble even adding a simple option.
 

this is my controller code:

     $scope.options = {
       scaleLabel  : function (label) {
    	   
      if(Number(label)===1)    
    
    return 'State 1';
    if(Number(label.value)===2)    
    return 'State 2';
    if(Number(label.value)===3)    
    return 'State 3';
    if(Number(label.value)===4)    
    return 'State 4';
       } 
      };
    
    $scope.axis = [[1,2,3,3,4,2,1,2,3,4]];
    $scope.myLabels= [1,2,3,4,5,6,7,8,9];

this is my markup

    <br>
    <canvas id="line" class="chart chart-line" chart-data="axis"
    chart-labels="myLabels" chart-series="series"  chart-options="options"
    </canvas>

**Comment by hbastida** [comment]
Same here, only happens with global options to me.

**Comment by piux** [comment]
http://stackoverflow.com/questions/40646245/how-can-i-modify-scale-labels-in-angular-chart-js just fixed my problem, scale labels is only to name the axis, if you want to replicate what the other issue did you have to use ticks.
