### ISSUE TITLE
Chart Animation is Easing From 0 Value If X-Axis Value is Changed

### ISSUE THREAD

**Issue by 360disrupt** [jtblin/angular-chart.js#554]
In the beginning of the video (below) the animation is like in the example page. As soon as a value of the X-Axis changes the chart rebuilds from scratch. With changing the y-axis, this makes sense but not with the x-axis.  

https://youtu.be/G7E-JtebFFU

**Comment by dineshu07** [comment]
same problem here. can any help us?

**Comment by lstone** [comment]
me too.

**Comment by Snede** [comment]
Me 3.

**Comment by jtblin** [comment]
Sorry to answer so late: do you have the same number of items in the array? If you don't it will redraw the chart entirely. Otherwise please post repro steps and re-open issue.
