### ISSUE TITLE
Individual color per series

### ISSUE THREAD

**Issue by Gamester2097** [jtblin/angular-chart.js#555]
Hi,

Is it possible to set an individual color per series?

In Chart.js you can do that when creating a dataset object.

Great work by the way!

Best regards 
Markus

**Comment by DaveJarvis** [comment]
The "chart-dataset-override" attribute might help:

* http://plnkr.co/edit/bnbZFXVlq4pX1BL5slqR?p=preview
* http://www.chartjs.org/docs/#doughnut-pie-chart-data-structure

**Comment by Gamester2097** [comment]
Thanks Dave, helped a lot!
