### ISSUE TITLE
Function in directive's HTML tag

### ISSUE THREAD

**Issue by jaman1020** [jtblin/angular-chart.js#56]
I get an infinite digest loop when I try to put a function inside the "data" attribute of a doughnut chart (not sure if this happens for all of them. I'm using an ng-repeat to create multiple charts from a dataset. Like this - 

    <div ng-repeat="lesson in lessonStats">
    <canvas id="doughnut" class="chart chart-doughnut" data="dataForLesson(lesson)"</canvas>
    </div>

in controller - 

    $scope.dataForLesson = function(lesson){
      return [
        lesson["not_started"]["total"],
        lesson["in_progress"]["total"],
        lesson["completed"]["total"]
      ];
    }

If I manually put the array into the data tag it works, but I'd rather keep that logic out of my HTML. Am I doing something wrong?

**Comment by jtblin** [comment]
See detailed examples on http://jtblin.github.io/angular-chart.js/. You need to put the data in an attribute somewhere on your scope and only the reference goes into the markup.

**Markup**:

```html
<canvas class="chart chart-line" data="data"
  labels="labels" series="series">
</canvas> 
```

```js
$scope.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90]
  ];
```

Same for series, labels, etc.

**Comment by jaman1020** [comment]
I understand that part, but what I'm asking is if instead of using a static array like in your example I can make the attribute a function like in mine? 

So - 

    $scope.data = function(data) {
      return [formatted array]
    }

which triggers the infinite digest cycle loop

**Comment by jtblin** [comment]
Ah, it's the "but I'd rather keep that logic out of my HTML" part that confused me, the logic is already out of the HTML.

It isn't possible. That wouldn't work as the chart creation and update is triggered by the data changes. Passing a function to retrieve the data is not idiomatic AFAIK and functions are generally kept for actions, like the `onclick` event as it needs to be called by the directive.

**Comment by jugglingcats** [comment]
There is another use case which doesn't quite work (presumably for the same underlying reason) but which is more idiomatic IMO. This is using a filter to provide the data to the chart.

For example, I have the following:
```
current.data.value.facets[$index] | datagrid
```

This is giving me an error about recursive $digest cycles. In my case I can't easily put the correct data in a simple scope variable -- the datagrid filter is intended to 'format' the data correctly for the chart.

Thanks
