### ISSUE TITLE
Getting fill-colors to the bar chart

### ISSUE THREAD

**Issue by estvmachine** [jtblin/angular-chart.js#561]
Hi!
- [X] Use latest version of the library
- [X] Make sure you've included all the dependencies e.g Chart.js, angular, etc.

I want to produce a stacked chart where each bar have different palette of colors. The best i got using the options color.

![screen shot 2016-11-29 at 4 58 12 pm](https://cloud.githubusercontent.com/assets/2062668/20726629/35b4483e-b655-11e6-9f82-905a582a231c.png)

The other thing how i can change the color of lines of the graphic for default is black, i want white for example.

**Comment by ashutoshtyagi** [comment]
similar to this i guess, i would like to show no color below the line chart. this is analogous to the "fill" property of dataset in chartjs.

**Comment by estvmachine** [comment]
For change colour of the graph : 

`
Chart.defaults.global.defaultFontColor= 'rgb(255,255,255)';

ws.options = {
        scales: {
          xAxes: [{
            stacked: true,
            gridLines:{
              display: false
            }
          }],
          yAxes: [{
            stacked: true,
            ticks: {
                min: 0
            },
            gridLines:{
              color: 'rgb(255,255,255)',
              lineWidth: 1
            }
          }]
        }
      };
`
