### ISSUE TITLE
Pie chart hover colors

### ISSUE THREAD

**Issue by frlinw** [jtblin/angular-chart.js#564]
Hi,

Something is a bit wrong with auto generated hover color on pie chart. Colors are too light and they may look similar even if base colors are very differents.
Moreover, Chart.js 2.4.0 added the color in pie tooltips and it takes the hover color instead of the base color.

Chart.js:
https://jsfiddle.net/3w5bke8f/4/

angular-chart.js : 
https://jsfiddle.net/p31fjbwg/1/

**Comment by ronaldohoch** [comment]
+1

I need it too, hahaha

**Comment by suyalcinkaya** [comment]
+1

**Comment by davidamitchell** [comment]
@ronaldohoch and @suyalcinkaya not saying that this would be a permanent fix but you can control this by adjusting the `backgroundColor` key here: https://github.com/jtblin/angular-chart.js/blob/master/dist/angular-chart.js#L270

**Comment by davidamitchell** [comment]
so since that is a bad idea (editing the library code) what you can do instead is to pass an object to the colors array and set the `backgroundColor` to be whatever you want.

have a look at:
https://jsfiddle.net/qL49uzco/1/

notice the setting of the `alpha` value of the `backgroundColor` key.

**Comment by angherq** [comment]
+1
