### ISSUE TITLE
Plot 'straight line' charts with angler-chart.js?

### ISSUE THREAD

**Issue by mattjankowski** [jtblin/angular-chart.js#567]
### Overview
My goal is to make a plot with straight lines between data points. Looking through the chart.js documentation I should be able to set lineTension: 0, tension:0, bezierCurve:false to obtain straight lines between points on a chart.

Here is an example of what I want displayed in chartjs: http://codepen.io/mjankowski/pen/Ypvqev

### Step to reproduce

Here is my attempt to set lineTension:0, tension:0 and bezierCurve:false in the options on an angular-chart.js example:
https://jsfiddle.net/jank0003/bss3orL8/

You can see the lines between points remain curved. What do I need to do to obtain straight lines between the points? Thanks,
Matt

**Comment by frlinw** [comment]
https://jsfiddle.net/bss3orL8/1/

**Comment by mattjankowski** [comment]
Perfect! Don't know how I missed that. Thank you!
