### ISSUE TITLE
Hide legend if no value for particular series  doughnut chart

### ISSUE THREAD

**Issue by ghoshpradyot** [jtblin/angular-chart.js#568]
Hi, 

I want to hide or not display legend if the value supplied is 0 
![statistics](https://cloud.githubusercontent.com/assets/17972702/21001582/ccabdf36-bd53-11e6-9ae8-c2978629a805.png)

Is it possible. as i didn't get any solution for this.

**Comment by frlinw** [comment]
Try to override generateLabels
http://www.chartjs.org/docs/#chart-configuration-legend-configuration

**Comment by junbinku** [comment]
Any available solutions?

**Comment by NikeDotNet** [comment]
Same issue for me. Any solution on this??
