### ISSUE TITLE
Responsive Horizontal Scroll Issue with Bar Thickness

### ISSUE THREAD

**Issue by varunjayaraman** [jtblin/angular-chart.js#573]
### Overview

**Describe the issue. What is the issue and what did you expect?**

I understand that angular-chart.js (and chart.js transitively) is responsive by design, but I am having trouble getting the bars to maintain their thickness when implementing a horizontal scroll along the graph. An example is representing data weekly across multiple months, where a user might have to scroll a significant amount to see all the data. The bars become very small, even with the scroll.

I'm not sure if this is an angular-chart.js or chart.js issue, but I'm wondering how to both implement the horizontal scroll and get the library to maintain the bars' thickness. 

### Step to reproduce

Dependencies:
angular-chart.js v1.1.1
angular 1.5.8

With angular 1.5.8, we are using `controllerAs` syntax, which means that I'd like to avoid using `$scope` in any possible solutions (including avoiding `$scope`'s `$on` pub sub functionality).

To reproduce, I've created the following template for the graph (note: I'm using jade and stylus):

```
//- Graph
div.chart-wrapper
  //- Bar chart
  div.chart-area-wrapper
    div.chart-test
      canvas.chart.chart-bar(
        title="$ctrl.chartId"
        chart-data="$ctrl.events" 
        chart-series="$ctrl.cities" 
        chart-labels="$ctrl.labels"
        chart-click="$ctrl.onClickBar"
        chart-options="$ctrl.chartOptions")
```

Here is the `stylus` governing this:

```
.chart-wrapper
  width: 800px
  overflow: auto  
  canvas
    width: 100%
      
.chart-test
  width: 1200px !important
```

And I've configured my graph with the following config options:

```
 // composeChartService.createChartOptions function
function createChartOptions(options) {
  return {
      title: {
        display: true,
        text: options.title
      },
      legend: merge({ display: true }, options.legend)
  }
}

// configuration
 this.chartOptions = this.composeChartService.createChartOptions({
      title: ctrl.chartTitle,
      legend: {
        position: 'bottom'
      },
      responsive: true,
      maintainAspectRatio: true
    });
```

When the graph loads, however, it looks like this:

![screen shot 2016-12-21 at 11 41 59 am 2](https://cloud.githubusercontent.com/assets/9360603/21397978/c143c4ea-c773-11e6-8d8c-66332ce41136.png)

It scrolls horizontally, but smushes the graphs together as if the scroll weren't even there. I can't seem to find a solution that preserves bar thickness. Any ideas?

**Comment by jtblin** [comment]
You set the width to 800px so it will make the chart fit into that I guess. Have you tried disabling the responsive option and setting a larger width?
