### ISSUE TITLE
关于图像的单位

### ISSUE THREAD

**Issue by junhui75165** [jtblin/angular-chart.js#575]
这些表里面我没办法知道x和y坐标的单位，这里如何添加单位（unit）

**Comment by thigrand** [comment]
english?

**Comment by benlooi** [comment]
Translated:
I'm unable to know the x and y axes unit labels in the charts. How do i add them?

**Comment by benlooi** [comment]
Hi Junhui,
你可以直接在canvas上打字.自我所知， Chart.js没有 X and Y 坐标添加单位的功能. 
http://www.w3schools.com/tags/canvas_filltext.asp
