### ISSUE TITLE
Scrollable legend.

### ISSUE THREAD

**Issue by jansilva** [jtblin/angular-chart.js#576]
Hi friends! How are you. I hope you are fine.

So, I'm using angular-chart at work, and I have an specific chart with too many data. And I need to present these data into Legend. Do you know any way to adding scroll capability to legend?

Thanks for your help?

**Comment by frlinw** [comment]
You don't have to use the built-in legend. 
If you want a custom render, disable chart legend and make your own

**Comment by prashasti4** [comment]
Hi, 
In case of large dataset , legends are covering the chart, any suggestions?

**Comment by bdfulker2** [comment]
@frlinw can you provide a plunker for this example?
