### ISSUE TITLE
Using an Image for pointStyle throws a "maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by KerryRitter** [jtblin/angular-chart.js#577]
### Overview

Whenever the pointStyle dataset override is used for an image, a "maximum call stack size exceeded" error is thrown and there is a significant lag before rendering.

### Step to reproduce

1. Create a Line Chart
2. Set a pointStyle value for the chart-dataset-override value.

Here is a JSBin demonstrating the problem: http://jsbin.com/fifetuzefi/edit?html,js,output

**Comment by jtblin** [comment]
The lib is only passing all the option to chart.js so I would check there first.

**Comment by Babettestam** [comment]
I'm running into the exact same problem as Kerry. It doesn't seem to be a problem in the Chart.js library, see a working example here: https://codepen.io/bstam/pen/dzvgYN

Can this be reviewed again please?

**Comment by jbergfi** [comment]
Same issue here, the javascript just hangs when putting an image in pointStyle. I assume there's something about the Image object in the options that doesn't work well with angular-chart.js. It's the first non-primitive object I try to set.
