### ISSUE TITLE
How to show labels in bubble charts or any work around on tooltips for same

### ISSUE THREAD

**Issue by premrajnarkhede** [jtblin/angular-chart.js#578]
### Overview
This is more like stackoverflow question but I am not getting any help there. Can anyone tell me how can I put labels in bubble chart for all bubbles. Some workaround like always showing tooltips will also do.
Please advice

Premraj

Please make sure to review and check all of these items:

- [X] Use latest version of the library
- [X] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [X] Include a repro case, see below.

**Comment by jtblin** [comment]
Have a look at chart.js docs.
