### ISSUE TITLE
problem with type:'time'

### ISSUE THREAD

**Issue by blurry-code** [jtblin/angular-chart.js#579]
Hi,
I am using angular-chart.js in an mobile app. Whenever I change the settings for the chart (data, labels, datasetOverride) the change takes very long. Depending on the device it takes up to 5 seconds while the required data is available after milliseconds. 

I am not sure, but I believe it is caused by `type:'time'` on my x-axis. I tried to create a fiddle for testing/showing the delay. For some reason the fiddle is not working with type:'time'. Please have a look at my fiddle: [https://jsfiddle.net/blurry_code/fwpq1x5n/](https://jsfiddle.net/blurry_code/fwpq1x5n/) and try to uncomment the scale type in $scope.options.

Now fixing the fiddle is not the main objective here. But the mere fact that it's not working at all using type:'time' indicates that there's something wrong. (unless I have a typo somewhere).

I am using:
- AngularJS 1.6.1
- chart.js 2.4.0
- angular-chart.js 1.1.0

**Comment by jtblin** [comment]
You need to include moment.js for the time type. See message in console and
Chart.js docs

> Error: Chart.js - Moment.js could not be found! You must include it
before Chart.js to use the time scale. Download at https://momentjs.com
    at a.initialize (VM185 Chart.min.js:14)
    at a.t.Element (VM185 Chart.min.js:12)
    at a [as constructor] (VM185 Chart.min.js:12)
    at new a (VM185 Chart.min.js:12)
    at VM185 Chart.min.js:11
    at Object.o.each (VM185 Chart.min.js:12)
    at t.Controller.buildScales (VM185 Chart.min.js:11)
    at t.Controller.initialize (VM185 Chart.min.js:11)
    at new t.Controller (VM185 Chart.min.js:11)
    at new t (VM185 Chart.min.js:12)

**Comment by blurry-code** [comment]
Ah thanks!
I updated the fiddle: [https://jsfiddle.net/blurry_code/fwpq1x5n/10/](https://jsfiddle.net/blurry_code/fwpq1x5n/10/). 

Now on a computer the performance of switching the data is OK. But on a mobile device it is quite slow. Why is that?

And while we're at it. Why are there white stripes in the chart on a mobile device?

(I tested all of this using an iPod Touch 5th Gen)

**Comment by ohad-bpal** [comment]
I installed moment.js with bower, but I am still getting the same error

**Comment by jtblin** [comment]
@blurry-code dataset is pretty large, the js engine on mobile is probably struggling to draw that.

@ohad-bpal sorry but that's definitely the issue usually.
