### ISSUE TITLE
Occasionally getting "Uncaught TypeError: Cannot read property 'skip' of undefined"

### ISSUE THREAD

**Issue by kharris926** [jtblin/angular-chart.js#580]
Hello,
I creating my data based of an object selected from a dropdown. When the drop down is changed the chart is populated with the new data and displays correctly. However, occasionally when hovering over the graph I will get the error in the title, "Uncaught TypeError: Cannot read property 'skip' of undefined." When the error is triggered the charted information will not be displayed on hover. The odd thing is, as I said, this will not happen consistently with the same dropdown selections. 

Are there any suggestions on things to look for that may be causing this error to occur?

Thank you!

**Comment by benlooi** [comment]
Try doing a timeout before rendering the chart. Javascript is synchronous, so the data from your dropdown menu may not be available yet when the chart calls for it. Maybe a delay of half a sec or 500ms will do.

**Comment by darshantejani007** [comment]
+1 for the issue. I am facing the same issue. Timeout didn't work in my case.

**Comment by dirttech** [comment]
+1 for the issue. I am facing the same issue.

**Comment by jtblin** [comment]
I guess it's an issue in chart.js itself as there is no `skip` function in this library.

**Comment by darulAbror** [comment]
+1 for the issue, I am facing the same issue too

**Comment by 1-isus** [comment]
yea there is an issue in the code. I did find a work around though. In the chart.js folder locate the file core.interaction.js and on line 23 replace **if (!element._view.skip) {**     
   **if (!element.hidden) {**.....

**Comment by rswingler** [comment]
+1 for this issue. @1-isus 's solution works on v2.7.1. 

core/core.interaction.js lines 39 and 130 (v2.7.1)

I couldn't get tooltips to show on the chart, and this error was blocking proper execution. Thanks!
