### ISSUE TITLE
How change the colors of a individual circle of bubble chart

### ISSUE THREAD

**Issue by GiancarlosIO** [jtblin/angular-chart.js#581]
I want to change the background-color of a individual circle, something like this:
![maquetacion](https://cloud.githubusercontent.com/assets/17274950/21825058/28fdfb1e-d750-11e6-94cc-9cfe84a7d17f.png)

I combined the line chart and bubble chart for that:
![ss](https://cloud.githubusercontent.com/assets/17274950/21825136/7a10ac7c-d750-11e6-8fc6-8ddad44e22ed.png)

In my controller i have this:
`vm.colors = ['#7065E9', '#ff6384', '#ff8e72'];`  , but the bubble chart only get the first color for the all circles.
Is there any option to change the colors of each of the circles in a fusion of graphics?

Thanks.

**Comment by jtblin** [comment]
Sorry to answer so late, I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
