### ISSUE TITLE
Combine scatter and line chart

### ISSUE THREAD

**Issue by dem23step** [jtblin/angular-chart.js#585]
I want to combine scatter chart (dots only) and line chart.
The problem is I can't override `showLines` property for different charts. But it's necessary to make one chart be scatter and another one to be line.

Expecting result something like this:
![image](https://cloud.githubusercontent.com/assets/18378425/22174905/f7b68c48-dffa-11e6-8f1c-0cfafd92b276.png)

How can I override this property (or maybe there's another way to do such things)?

**Comment by jtblin** [comment]
Please check http://www.chartjs.org/docs/ for available options.
