### ISSUE TITLE
$scope variable do not respond to the onClick function

### ISSUE THREAD

**Issue by ycy233** [jtblin/angular-chart.js#586]
I bind the chart-click attribute to a function.  And hope that when I click in the chart, the onClick function will change the value of $scope.cateClicked and show which category has been clicked in a div. However, the display value of $scope.cateClicked do not change in the div, while in console, I can see this value has been changed by the function indeed.

I created a demo here: http://codepen.io/lyzy0906/pen/ggWqpJ

Please help me. Thanks a lot.

**Comment by ycy233** [comment]
It is solved.

**Comment by bhaktiprabhu** [comment]
Can You Please tell me, how did you solve the problem. I am facing the same issue.
