### ISSUE TITLE
Horizontal bar chart: x axis labels on different line as bar

### ISSUE THREAD

**Issue by blueskiedmorning** [jtblin/angular-chart.js#588]
Describe the issue. What is the issue and what did you expect?

I have some long labels and would like to have the x-axis labels on a separate row as the chart data. Putting a `<br>` or line break in the label doesn't render it. How would I go about doing this?

**Comment by jtblin** [comment]
Sorry to answer so late but this is probably a question for the chart.js repo or SO.
