### ISSUE TITLE
Question: Multiple charts on single page App?

### ISSUE THREAD

**Issue by hmfcriley** [jtblin/angular-chart.js#59]
Fairly new to Angular so I appreciate I may not be going about this the best way.

Scenario: I'm looking to use multiple charts on a single page app. Currently set up to use ng-show to determine which div is shown via a dropdown menu and, as such, what chart and controller is used. On switching charts I broadcast a message to pull in the correct data required.

When updating data alone it works fine and both charts are visible.... When adding extra values to series and data on one graph and then switching to a second graph and then back (i.e. from line to bar to line) the line chart is disappearing from the page with just the legend left behind. It appears to be hitting the destroy and reset functions multiple times due to the watch on data and series but the chart is no longer visible.

Any ideas what is causing the chart to disappear? Or how to better go about attempting this?

**Comment by rohanshar** [comment]
I have the same issue

**Comment by jamesadevine** [comment]
Can you confirm that none of the elements are left in the dom?

I had an issue where I would hide a chart, and then show it again, and because it 'adapted' to the hidden container height (which is 0), it wouldn't change back.

**Comment by jtblin** [comment]
@hmfcriley @rohanshar would you be able to post some minimum code that reproduces the issue? There is a jsbin template link in the readme to get started.

**Comment by idf** [comment]
By changing `ng-show` to `ng-if`, does it help? @hmfcriley
