### ISSUE TITLE
How to set origin in angular chart (for line chart)

### ISSUE THREAD

**Issue by tatsapp** [jtblin/angular-chart.js#592]
HI

 I need to manually set origin in angular chart. I want to set my origin as (0,-200) instead of (0,0).

 Can someone help me ?

**Comment by shafeerambatt** [comment]
Are those examples given in the site working for you? When i tried the same code nothing is shown on the page.

**Comment by tatsapp** [comment]
Are you speaking about below site ?
 http://jtblin.github.io/angular-chart.js/?

**Comment by shafeerambatt** [comment]
Yes. I copied and tried the same code for line chart. But no result

**Comment by tatsapp** [comment]
It's working for me. I have copied the same code which was provided in angular chart site and it's working fine.

**Comment by shafeerambatt** [comment]
Could you share the file please. I can't understand my issue

**Comment by tatsapp** [comment]
<canvas id="line" class="chart chart-line" chart-data="data" chart-colors="colors" chart-labels="labels" chart-series="series" chart-options="options">
      </canvas>

**Comment by tatsapp** [comment]
Find the code which I copied.

<canvas id="line" class="chart chart-line" chart-data="data" chart-colors="colors" chart-labels="labels" chart-series="series" chart-options="options">
      </canvas>

**Comment by shafeerambatt** [comment]
Sorry, i could not find any code.

**Comment by tatsapp** [comment]
<canvas
 id="line" class="chart chart-line" chart-data="data" chart-colors="colors" chart-labels="labels" chart-series="series" chart-options="options">
      </canvas>

**Comment by shafeerambatt** [comment]
Still can't see anything. Try copying and pasting as text if file attachment is not working.

**Comment by tatsapp** [comment]
`<canvas id="line" class="chart chart-line" chart-data="data" chart-colors="colors" chart-labels="labels" chart-series="series" chart-options="options">
      </canvas>`

**Comment by shafeerambatt** [comment]
Or send me the file to shafeerambatt@gmaill.com. thank you in advance.

**Comment by shafeerambatt** [comment]
@tatsapp I wanted the entire code that worked for you. Not only the part that you posted above

**Comment by tatsapp** [comment]
I sent it to your mail
