### ISSUE TITLE
Set Y axis max value dynamically based on the max value generated by angular chart for stacked bar chart

### ISSUE THREAD

**Issue by praveenkumararepalliGit** [jtblin/angular-chart.js#596]
Hi ,

I have a scenario where i need to set Y axis max value dynamically. Suppose assume
my Y axis values are generated by library is like , 0, 1, 2, 3, 4, 5. Here stepSize is 1

i want to change values to be 0, 1, 2, 3, 4, 5, 6 that means want to add one more value to axis

{
max : maxValueGenereatedByLibrary + stepSize ; // In this case i can get max values as 6
}

Is there a way to set it like that ?

**Comment by hexx870206helen** [comment]
@praveenkumararepalliGit  I have the same question..anyone can help?

**Comment by jtblin** [comment]
Can you just setup the options attributes?

**Comment by iNishant** [comment]
One way of doing it
```js
$scope.options = {
  scales: {
    yAxes: [
      {
        ticks: {beginAtZero:true,max:maxValue}
      }
    ]
  }
 }
```
`maxValue` can be anything you want
