### ISSUE TITLE
Please tell me how to show percentages on Pie/Doughnut chart slices, Best regards.

### ISSUE THREAD

**Issue by sangwin** [jtblin/angular-chart.js#597]
### Overview

Describe the issue. What is the issue and what did you expect?

Please make sure to review and check all of these items:

- [x] Use latest version of the library
- [ ] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [ ] Include a repro case, see below.

### Step to reproduce

**Ensure you add a link to a plunker, jsbin, or equivalent. Issues without repro steps may be closed immediately.** 

Here is a [jsbin template for 0.x version](http://jsbin.com/cucoqe/1/edit?html,js,output) and [one for 1.x](http://jsbin.com/rodunob/edit?html,js,output) for convenience.

**Comment by bes1002t** [comment]
just create a div which position is absolut to its parent and is the middle of the chart. You can calc the percentage value with the chart values. It's not cool because the chart framework should do that somehow but I also can't find another solution for this.

**Comment by jtblin** [comment]
Please check http://www.chartjs.org/docs/ for available options.

**Comment by victorhazbun** [comment]
http://stackoverflow.com/questions/28499475/inserting-percentage-charts-js-doughnut

**Comment by sangwin** [comment]
I want it like this. % in chart.

[https://d2wh20haedxe3f.cloudfront.net/sites/default/files/docs_190726c_pie_chart_en.gif](https://d2wh20haedxe3f.cloudfront.net/sites/default/files/docs_190726c_pie_chart_en.gif)

**Comment by ShadovvBeast** [comment]
I need the same thing, is there no option for it?

**Comment by bes1002t** [comment]
unfortunately not. You have to position the percentage manually.

**Comment by muhammad-ismaieel** [comment]
check the accepted answer at https://stackoverflow.com/questions/37257034/chart-js-2-0-doughnut-tooltip-percentages

**Comment by NeubauerJohannes** [comment]
@sangwin 

Check plugin: https://chartjs-plugin-datalabels.netlify.com/samples/index.html

Works for me like a charm. Here is the code I used to display percentages:
`
plugins: {
    datalabels: {
backgroundColor: function(context) {
return context.dataset.backgroundColor;
},
borderColor: 'white',
borderRadius: 25,
borderWidth: 2,
color: 'white',
display: function(context) {
var dataset = context.dataset;
return dataset.data[context.dataIndex] > 0;
},
font: {
weight: 'bold'
},
formatter: function(value, context) {								
var dataset = context.chart.data.datasets[context.datasetIndex];
var meta = dataset._meta[Object.keys(dataset._meta)[0]];
var total = meta.total;
var currentValue = dataset.data[context.dataIndex];
var percentage = parseFloat((currentValue / total * 100).toFixed(1));
return percentage + '%';
}
}
}
`
And here is how it looks like

![doughnut](https://user-images.githubusercontent.com/42164117/43754878-57720180-9a0d-11e8-98a7-905a1c2ed334.JPG)

**Comment by NeubauerJohannes** [comment]
@sangwin: If you are using chart.js like @muhammad-ismaieel mentioned you could check out https://github.com/chartjs/chartjs-plugin-datalabels

Could look like this with it (some javascript code for formatter required): 
![doughnut](https://user-images.githubusercontent.com/42164117/43754955-c8313da0-9a0d-11e8-894d-ab3350c2e774.JPG)

**Comment by kushika** [comment]
use plugins in options of chart.js

install by running: npm install chartjs-plugin-labels 

import 'chartjs-plugin-labels';

 plugins:{
        labels: {
          render: 'percentage',
          fontColor: ['green', 'white', 'red'],
          precision: 2,
          arc: true,
        }
      }

for more info and samples check:  https://emn178.github.io/chartjs-plugin-labels/samples/demo/ 

https://github.com/emn178/chartjs-plugin-labels

**Comment by bes1002t** [comment]
@kushika  I've checked the demos but the most important label was not shown, the percentage in the middle of the Doughnut
