### ISSUE TITLE
not working with ng-view container

### ISSUE THREAD

**Issue by idangozlan** [jtblin/angular-chart.js#60]
When using ng-view container on one-page app the chart is empty 0x0px, is there any known issue about that?

**Comment by jtblin** [comment]
It looks similar to #29. I guess this is due to the content being hidden at the beginning so the dimensions of the parent are 0px. Can you confirm by resizing the browser window?

**Comment by idangozlan** [comment]
Still 0*0 even after window resize :/

**Comment by jtblin** [comment]
Would you be able to share a bit of code in a jsbin to get me started? Here is a [jsbin](http://jsbin.com/dufibi/3/edit?html,js,output) template.

**Comment by idangozlan** [comment]
Oh, sorry, my bad. it's do rendering on windows resize.

**Comment by jtblin** [comment]
Ok. No worries, I'm going to close as duplicates, please follow status in #29.

**Comment by gangatharang** [comment]
ss

**Comment by gangatharang** [comment]
![image](https://user-images.githubusercontent.com/31310713/30002393-f8ef695a-90c5-11e7-8583-06c1ceef5257.png)
