### ISSUE TITLE
does  angular-chart.js  work with  ngRoute ??

### ISSUE THREAD

**Issue by ckuruvi** [jtblin/angular-chart.js#600]
### Overview

Describe the issue. What is the issue and what did you expect?
I'm unable to display charts on my home.html page using ngRoute. Attaching code snippets for 
the five files as well below.

Please make sure to review and check all of these items:

- [ ] Use latest version of the library
- [ ] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [ ] Include a repro case, see below.

### Step to reproduce

**Index.html**

<!DOCTYPE html>
<html ng-app="passportApp">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="vendors/bootstrap.min.css" media="screen" title="no title">
  <script src="vendors/angular.min.js" charset="utf-8"></script>
  <script src="vendors/angular-route.min.js" charset="utf-8"></script>
  <script src="vendors/Chart.min.js" charset="utf-8"></script>
  <script src="vendors/angular-chart.min.js" charset="utf-8"></script>
  <script src="scripts/login.controller.js" charset="utf-8"></script>
  <script src="scripts/home.controller.js" charset="utf-8"></script>
  <base href="/" />
</head>
<body class="container">
  <ng-view></ng-view>
</body>
</html>

**module.js**

var chartApp= angular.module('chartApp', ['chart.js']);
var myApp = angular.module('passportApp',['ngRoute','chartApp']);

**routerconfig.js**
myApp.config(function($routeProvider, $locationProvider) {
  $locationProvider.html5Mode(true);
  $routeProvider
    .when("/home", {
      templateUrl: "views/home.html",
      controller: "HomeController as home",
      authRequired: true
    })
    .otherwise({
      templateUrl: "views/login.html",
      controller: "LoginController as login"
    });

**home.html**
<button ng-click="home.logout()" >Logout</button>
<button ng-click="home.displayChart()" >Chart Display</button>
<canvas id="base" class="chart-bar"
  chart-data="home.data" chart-labels="home.labels" chart-colors="home.colors"
  chart-dataset-override="home.datasetOverride" >
</canvas>

**home.controller.js**

myApp.controller('HomeController', function($http, $location){

  ctrl.displayChart=function(){
    console.log('inside displayChart function');
    ctrl.colors = ['#45b7cd', '#ff6384', '#ff8e72'];

    ctrl.labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    ctrl.data = [
      [65, -59, 80, 81, -56, 55, -40],
      [28, 48, -40, 19, 86, 27, 90]
    ];
    ctrl.datasetOverride = [
      {
        label: "Line chart",
        borderWidth: 1,
        type: 'line'
      },
      {
        label: "Line chart",
        borderWidth: 3,
        hoverBackgroundColor: "rgba(255,99,132,0.4)",
        hoverBorderColor: "rgba(255,99,132,1)",
        type: 'line'
      }
    ];
}

});

**Ensure you add a link to a plunker, jsbin, or equivalent. Issues without repro steps may be closed immediately.** 

Here is a [jsbin template for 0.x version](http://jsbin.com/cucoqe/1/edit?html,js,output) and [one for 1.x](http://jsbin.com/rodunob/edit?html,js,output) for convenience.

**Comment by jtblin** [comment]
It should work.
