### ISSUE TITLE
Responsive issue while plotting bar graph

### ISSUE THREAD

**Issue by Seema85** [jtblin/angular-chart.js#602]
In my page, I am switching between Bar (using Chart.js) and Metric (Label showing aggregate count) on click of a button. But some time the chart is not getting plotted. Instead of bar chart , a compressed version like a box is appearing in the top left corner (image attached)

`        <div class="col-lg-12 col-xs-12 col-md-12">
            <i class="fa fa-line-chart " aria-hidden="true" ng-click="changeview('Line')" title="Bar View"></i>
            <i class="fa fa-calculator " aria-hidden="true" ng-click="changeview('Metric')" title="Metric View"></i>
        </div>
        <div class="col-lg-12 col-xs-12 col-md-12" ng-show="Showline">
            <canvas id="bar" class="chart chart-bar" chart-data="data" chart-labels="labels" chart-options="options"></canvas>
        </div>
        <div class="col-lg-12 col-xs-12 col-md-12" ng-show="ShowMetric">
            <div>
                {{ItemList.metricData}}
            </div>
        </div>`
**JAVASCRIPT**
`$scope.changeview = function (type) {
            if (type === "Line") {
                $scope.Showline = true;
                $scope.ShowMetric = false;
            } else if (type === "Metric") {
                $scope.Showline = false ;
                $scope.ShowMetric = true;
            }
        };`

Version: "angular-chart.js": "1.0.3"
"bootstrap": "3.3.6"
"jquery": "2.2.0"

### Step to reproduce

Navigate between Metric and Bar chart very fast.
![image](https://cloud.githubusercontent.com/assets/21954320/22964143/26cfb1e0-f37d-11e6-84aa-650567727cbe.png)

**Comment by jtblin** [comment]
Sorry to answer so late. Difficult to say without repro steps anyway. It will use the dimensions of the container that wraps the directive.
