### ISSUE TITLE
Line Chart draws a straight line from the start to end of a series 

### ISSUE THREAD

**Issue by guarilha** [jtblin/angular-chart.js#603]
Hello, everyone! 

I got this huge dataset (comparing to the examples I've seen on issues and the documentation) with 5 series of around 500 data points each. 

This is the error I'm getting:  

![image](https://cloud.githubusercontent.com/assets/902478/23068178/c0da2d78-f509-11e6-937b-4e38ed1f91bd.png)

As you can see, the straight line from start to end of all series are not expected at all. I'm struggling with this bug for the past two days and haven't found any issue that mentioned this behavior, so if there's another issue I apologize in advance for the duplicate. 

Here's a print with just one series: 

![image](https://cloud.githubusercontent.com/assets/902478/23068342/6998192a-f50a-11e6-97dc-fef740ff0f16.png)

If I try to add the fill, the results are worse: 

![image](https://cloud.githubusercontent.com/assets/902478/23069204/afed03ce-f50d-11e6-8fb5-21f580d9a3fa.png)

Other chart libraries were able to reproduce this data without all this weird behavior, so I think it's not a problem with the data itself. Here's an example: 

![image](https://cloud.githubusercontent.com/assets/902478/23069392/64943ac2-f50e-11e6-925c-d78b874a0f07.png)

The thing is that this particular library has a poor performance for my needs due to it's use of SVG charts. 

Any ideas? 

### Steps to Reproduce 

The data and code are on this JSbin: https://jsbin.com/nexugoz/edit?html,js,output

**Comment by jtblin** [comment]
Sorry to answer so late, but that looks like an issue with chart.js itself, please open an issue on https://github.com/chartjs/Chart.js.
