### ISSUE TITLE
Remove image comparison tests

### ISSUE THREAD

**Issue by gerardoepp** [jtblin/angular-chart.js#604]
Isn't weird comparing rendered graphs images for a module related with angular chart.js integration?, what's the point with this image comparison tests?, isn't it responsability of chart.js?, I think you should only test things related with angular integration. This tests should be remove in order to be able to update minor version of chart.js, it should be ^2.3.0 and not frozen on 2.3

**Comment by jtblin** [comment]
The image tests allow to find regressions. Unit tests are not enough unfortunately. 

Version is frozen to 2.3 because there was a breaking change in chart.js after 2.3 and I haven't had the time to fix that.
