### ISSUE TITLE
Only display fixed amount of dateTime-Labels

### ISSUE THREAD

**Issue by headyrules** [jtblin/angular-chart.js#607]
I am getting two arrays from my server, 7 Values and 7 corresponding labels which are timestamps.

The timespan between first and last label differs. My problem: I always want to have 7 labels on my xAxis (DD MMM), but when I, for example, set the unit of the xAxis to 'day' it displays any day between first and last label.

How can i get the chart to only display MY 7 days on the xAxis?

**Comment by jtblin** [comment]
Sorry to answer so late, I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
