### ISSUE TITLE
How to plot data from a table using this chart API ? 

### ISSUE THREAD

**Issue by shafeerambatt** [jtblin/angular-chart.js#608]
I want to plot the data from a table which is already there on the page. The data is received from a server and is dynamic live data. So please tell me the changes to be made in the examples charts given in the website to plot the data. I have included the html for the table in the txt file attached below.
[table.txt](https://github.com/jtblin/angular-chart.js/files/806924/table.txt)

**Comment by jtblin** [comment]
Sorry to answer so late, I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
