### ISSUE TITLE
Tooltip cut off by edge of chart-container

### ISSUE THREAD

**Issue by nick-barth** [jtblin/angular-chart.js#61]
Any known fix or workaround for this?  I have a small chart-container / chart, and fairly long tool tips, but they are cut off by the container.

**Comment by nick-barth** [comment]
Hey, after further digging, I found this wasn't an angular-chart.js error, but infact a chart.js error.  Here is the issue with a possible workaround.

https://github.com/nnnick/Chart.js/issues/622

**Comment by jtblin** [comment]
Thanks I was looking for it yesterday but couldn't find it.
