### ISSUE TITLE
How do I customize this？

### ISSUE THREAD

**Issue by suichukewan** [jtblin/angular-chart.js#613]
![qq 20170308152250](https://cloud.githubusercontent.com/assets/19454577/23694207/7cf7f022-0413-11e7-8885-f1d9dbe7ef7c.png)

**Comment by shyamg91** [comment]
Within the options configuration, you can customise the tooltip labels, check the callback documentation.
[http://www.chartjs.org/docs/#chart-configuration-tooltip-callbacks](url)

**Comment by ygorgasparin** [comment]
This page give me error 404.

I'm having trouble to customize my tooltip too. Maybe there is a problem with incompatible versions of angular-chart.js and chart.js?

Can you give and example and you can customize the tooltip? Thank you!

**Comment by greatsayan** [comment]
+1
