### ISSUE TITLE
How to do the scrolling chart on demo?

### ISSUE THREAD

**Issue by pjatinsight** [jtblin/angular-chart.js#617]
Hi,
Just looking at the page : http://jtblin.github.io/angular-chart.js/
The chart on the top of that page that scrolls along.. 
How do you do that one?
Is there a code example ?
Thanks

**Comment by krishnakanthpps** [comment]
Yes. I would like to have that as well. I have been trying for a long time to do that. I tried canvasjs but it is expensive to get just for one page.

**Comment by jtblin** [comment]
Have you guys checked the examples/ folder? It's all there. app.js is the main page, ticks.js is specifically the one you're asking about. It's basically just an array where you append a new value to the end of the data and remove the first one.

**Comment by pjatinsight** [comment]
Thanks,
Its not obvious from looking at app.js or ticks.js that this is what it does.
You have done some lovely work so maybe a little documentation or comments to say what each example does would be a good idea.
Thanks again for your help and your excellent directive.
PJ
