### ISSUE TITLE
How to change the line-through of the legend

### ISSUE THREAD

**Issue by richeric** [jtblin/angular-chart.js#619]
Hi !
Need help please. For needs of the design am using, I want my chart's legend to be disabled by changing color (gray for exemple) instead of the line-through style initially used. Thanks for your help

**Comment by jtblin** [comment]
Please check http://www.chartjs.org/docs/ for available options. Legend is disabled by default.

**Comment by bobhob314** [comment]
That is not what he meant. He wanted each individual legend **element** to be disabled by changing color instead of line-through, not the entire legend. Hence, the "Legend is disabled by default" does not apply. In the docs I couldn't find such an option so I'd like to reopen this.

**Comment by Kvarkas** [comment]
> Hi !
> Need help please. For needs of the design am using, I want my chart's legend to be disabled by changing color (gray for exemple) instead of the line-through style initially used. Thanks for your help

Perhaps this [helps](https://stackoverflow.com/questions/37949003/how-to-change-color-of-hidden-legend-item-instead-of-strike-through-in-chart-js)
