### ISSUE TITLE
Manually destroy chart 

### ISSUE THREAD

**Issue by zhangdanyangg** [jtblin/angular-chart.js#62]
Hi Jerome,

How to manually destroy a chart?

I am using `0.5.1` and using this snippet to get the chart in angular controller (vm is the controller reference): 
```javascript
        $scope.$on('create', function (chart) {
            console.log(chart);
            vm.chart = chart;
        });
```
Log:
```
Object {name: "create", targetScope: l, stopPropagation: function, preventDefault: function, defaultPrevented: false…}
```
But when I call this, an exception happens saying that `.destroy()` is undefined
```javascript
            if(vm.chart!==null) {
                vm.chart.destroy();
            }
```
```
 TypeError: undefined is not a function
```

**Comment by jtblin** [comment]
Looks like there was an issue with the example, the chart is the 2nd parameter of the event listener i.e.

        $scope.$on('create', function (event, chart) {
            console.log(chart);
            vm.chart = chart;
        });

I'll update the readme.
