### ISSUE TITLE
Right most column not being displayed

### ISSUE THREAD

**Issue by clipsett** [jtblin/angular-chart.js#622]
I tried creating a jsbin for this demo, but the link provided is not working.

![image](https://cloud.githubusercontent.com/assets/19802182/25292535/28fd77ca-269c-11e7-91bb-642333a31db1.png)

Here is a screenshot of the issue I'm seeing.

The basic issue appears to be the chart will only display 9 columns, even if 10 are supplied in the data array. I added the data array I'm attaching below the chart, and as you can see, the final 27 is not displayed on the chart.

I didn't see anything in other issues or from a google search that makes me think this has been addressed previously.

Thanks!

**Comment by clipsett** [comment]
Ping. Any suggestions on this? @jtblin

**Comment by jtblin** [comment]
I've fixed the [jsbin template](https://jsbin.com/rukiyis/edit?html,js,output), can you provide repro steps?

It looks like the chart is truncated on the right, is it overflowing or something?

**Comment by clipsett** [comment]
Thanks for the quick response. The chart is truncated and the data is overflowing. In my case, I didn't have a 10th label in my labels array and it looks like that was causing the issue. I guess I would have thought the 10th column would have displayed with no column label. 

Perhaps a simple documentation update would suffice?

**Comment by jtblin** [comment]
Glad to know. I think it's a chart.js behaviour, I can't document all that here, better refer to their docs: http://chartjs.org/docs
