### ISSUE TITLE
Module injection error in rails environment

### ISSUE THREAD

**Issue by iveskins** [jtblin/angular-chart.js#625]
### Overview

I added angular-chart.js to the application.js file as part of the rails asset pipeline. 
I added it after chart.js
I expected the modules to be loaded by angular.js when building a page and available to inject into a controller. 
But i got an injector error, chart.js can't be found. 

Please make sure to review and check all of these items:

- [ o] Use latest version of the library
- [ o] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
- [ ] Include a repro case, see below.

### Step to reproduce

Step1) build a ruby on rails environment
Step2) add dependencies and angular-chart.js to the rails app application.js file in the correct order.
Step3) make a rails view html and js file including angular-chart.js features. 
Step4) add chart.js to a angular controller in that js file. 
Step5) open the page. 

Here is a [jsbin template for 0.x version](http://jsbin.com/cucoqe/1/edit?html,js,output) and [one for 1.x](http://jsbin.com/rodunob/edit?html,js,output) for convenience.
Cant use rails pipeline on postbin sorry. 
 More details and a work around almost here

http://stackoverflow.com/questions/43407266/error-injectornomod-module-chart-js-is-not-available-rails-application-j

**Comment by jtblin** [comment]
Not sure why that would be an issue on R&R, and I can't really help if I can't repro.
