### ISSUE TITLE
Coustom legend to bar chart

### ISSUE THREAD

**Issue by Stefaneek** [jtblin/angular-chart.js#626]
I am trying to create custom legend to my bar chart. It's how i try to do it

                          generateLabels: function (chart) {
                          if (chart.data.labels.length && chart.data.datasets.length) {
                              return chart.data.labels.map(function (label, i) {
                                  var meta = chart.getDatasetMeta(0);
                                  var ds = chart.data.datasets[0];
                                  return {
                                      text: $scope.languagesOfCurrentSiteObject[i].localizedName,
                                      fillStyle: chart.data.datasets[0].backgroundColor[i],
                                      hidden: isNaN(chart.data.datasets[0].data[i]) || meta.data[i].hidden,
                                      // Extra data used for toggling the correct item
                                      index: i
                                  };
                              });
                          } else {
                              return [];
                          }
                      },  

It's create well but when i click on some text of my legend to hide clicked data I get such error 

> ncaught TypeError: Cannot read property '_meta' of undefined
    at 23.module.exports.Chart.Controller.getDatasetMeta

It occurs in them library method

    		onClick: function(e, legendItem) {
			var index = legendItem.datasetIndex;
			var ci = this.chart;
			var meta = ci.getDatasetMeta(index);

			// See controller.isDatasetVisible comment
			meta.hidden = meta.hidden === null? !ci.data.datasets[index].hidden : null;

			// We hid a dataset ... rerender the chart
			ci.update();
		},
in this line`var meta = ci.getDatasetMeta(index);` beacouse I can only use this method with index == 0.
If i set index = 0 then I get error in the next line couse dataSets also have only one element in the array and then inside elemenet of datas but only with values not propertis like hidden.

**Comment by jtblin** [comment]
Sorry I don't have the time to provide individual support for this type of questions. You will receive more help and this question seems more appropriate for [StackOverflow](angular-chart), tag the question with _angular-chart_.
