### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by stact** [jtblin/angular-chart.js#63]
Hi,

Can you provide a cdn please? It will be nice for lot of us

And I would add that you did a good job :)
Thank you for your feedback

**Comment by jtblin** [comment]
I can certainly look into adding free cdn hosting later. Will want to do #55 first.

* [JsDeliver](https://github.com/jsdelivr/jsdelivr)
* [cloudflare](https://www.cloudflare.com/plans)

**Comment by martellaj** [comment]
Still on your radar? A CDN or a npm module would be awesome.

**Comment by jtblin** [comment]
Good timing! Someone was kind enough to submit the project to JsDeliver so here are the links for the CDN versions:

* //cdn.jsdelivr.net/angular.chartjs/0.7.6/angular-chart.min.js
* //cdn.jsdelivr.net/angular.chartjs/0.7.6/angular-chart.min.js.map
* //cdn.jsdelivr.net/angular.chartjs/0.7.6/angular-chart.css
* //cdn.jsdelivr.net/angular.chartjs/0.7.6/angular-chart.css.map

Replace the version accordingly or use "latest" e.g. //cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css.

I'll update the README soon.

**Comment by stact** [comment]
Great job :)
