### ISSUE TITLE
applying chart-xs class on doughnut/pie-chart

### ISSUE THREAD

**Issue by gaspaonrocks** [jtblin/angular-chart.js#633]
Hi, 

as the title says, i don't know how to reproduce the sizing of the demo page for a pie chart...

When i look at the code, there's a chart-xs class that seems to do the trick, but I can find it anywhere...

I might be missing something...

I' ve added chart.js, angular-chart.js, bootstrap.js and jquery as dependencies, I also added bootstrap.css and the example app.css.

I don't really know where to look now...

Thanks !

**Comment by jtblin** [comment]
What version of Chart.js do you use? Unfortunately they decided to double the aspect ratio for pie (and family) charts so you'll need to set aspect ratio to 1 to avoid this. See https://github.com/chartjs/Chart.js/pull/4079

**Comment by gaspaonrocks** [comment]
Modifying chart.js in the node_modules folder like this : 
   ```
Chart.defaults.polarArea.aspectRatio = 2;
Chart.defaults.doughnut.aspectRatio = 2;
Chart.defaults.radar.aspectRatio = 2;
```

from 1 to 2 let it have the same size as the other chart types.

Thank you very much for pointing me to the link on chartjs page ;-).
