### ISSUE TITLE
Can't have a group of stacked Bar

### ISSUE THREAD

**Issue by ghizoulo** [jtblin/angular-chart.js#635]
Hi @jtblin,
I have tried my best to get a chart like this one but in vain:
[
![mwexn](https://cloud.githubusercontent.com/assets/13001134/26579927/7cee98bc-4525-11e7-8117-f8fb492bf6cf.png)
](url)

Here is my issue in stackOverFlow [https://stackoverflow.com/questions/44239952/how-to-create-a-group-of-stackedbar-using-angular-chart-js-duplicated](url)

Does this library support this type of chart?

U can find my plunker here : [http://plnkr.co/edit/MzcrykfcxplUZOyhU8wZ?p=preview](url)

Another issue of the same problem in StackOverFlow : [https://stackoverflow.com/questions/43188572/how-to-achieve-grouping-of-stacked-bars-in-angular-charts](url)

**Comment by jtblin** [comment]
Does something like that works for you? http://jtblin.github.io/angular-chart.js/examples/stacked-bars.html

![image](https://cloud.githubusercontent.com/assets/1388974/26582559/076fc560-4585-11e7-970c-3b12fd82811f.png)

Html in https://github.com/jtblin/angular-chart.js/blob/master/examples/stacked-bars.html and js code in examples/app.js.

**Comment by Sibiraj-S** [comment]
@jtblin. is there a way to pass options in data-override.

**Comment by ghizoulo** [comment]
@jtblin is not what I want, I need a group of stacked Bar,
Never mind, I fix it here is my solution : [http://plnkr.co/edit/MzcrykfcxplUZOyhU8wZ?p=preview](url)

Now I can display a group of stacked bar like this : [
![image](https://cloud.githubusercontent.com/assets/13001134/26588365/ad6f5192-4544-11e7-9ce0-b9a98a716cf5.png)
](url)

Yes @Sibiraj-S `data-override` did the thing :+1: 
```
$scope.data[$rootScope.indexOf] = [
                            [59, 80, 81, 56, 55, 40, 65],
    [65, 59, 90, 81, 56, 55, 40],
    [60, 59, 80, 81, 56, 55, 40],
 [59, 80, 81, 56, 55, 40, 65]
                        ];
                        $scope.datasetOverride = [
                            {
                                label: "Vital épargne: réalisé",
                                backgroundColor: "rgba(99,255,132,0.2)",
                                data: [59, 80, 81, 56, 55, 40, 65],
                                stack: 1
                            },
                            {
                                label: "Vital épargne: estimé",
                                backgroundColor: "rgba(99,255,132,0.2)",
                                data:  [65, 59, 90, 81, 56, 55, 40],
                                stack: 1
                            },
                            {
                                label: "Prévoyance groupe: réalisé",
                                backgroundColor: "rgba(99,132,255,0.2)",
                                data: [60, 59, 80, 81, 56, 55, 40],
                                stack: 2
                            },
                            {
                                label: "Prévoyance groupe: estimé",
                                backgroundColor: "rgba(255,99,132,0.2)",
                                data:  [59, 80, 81, 56, 55, 40, 65],
                                stack: 2
                            }
                        ];
```

**Comment by HughCoreGaming** [comment]
Couldn't get this to work with just stack1 and 2 options?
