### ISSUE TITLE
Violation messages in Chrome developer tool bar 

### ISSUE THREAD

**Issue by zymr-keshav** [jtblin/angular-chart.js#638]
using angular-chart js in my application  But when I load the page chrome gives below error multiple times

-  angular-chart.js": "^1.0.2", 
- chrome Version 58.0.3029.110 (64-bit)

> Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

How to fix this issue?

**Comment by jtblin** [comment]
No idea, there's no `touchstart` event in this lib.

**Comment by zymr-keshav** [comment]
This issue comes from  _Chart.budle.js_ which is being used by this library. Although I have fixed the issue by writing `{passive:true}` as 3rd argument in `addEventListener()` in **bower_components/chart.js/dist/Chart.bundle.js** but that is not a good way as one do `bower install` and get new set of files on his system.
