### ISSUE TITLE
Dont disable css class directives

### ISSUE THREAD

**Issue by jrmlstf** [jtblin/angular-chart.js#639]
I've spent few hours to fix a problem with angular-chart.js. I would like to share it with others.

My project was using angular-chart.js to display stats charts. Everything was ok but when it was build using my webpack config (angular-chart.js was installed using npm), the chartjs just didn't display. There was no webpack build errors nor angular errors.

The problem was that I disabled css class directives following angularjs documentation recommandation here : https://docs.angularjs.org/guide/production

Just **remove `$compileProvider.cssClassDirectivesEnabled(false);`**

It may also be useful to add a reminder to the documentation ?
Do you plan to replace css class directives with attribute directives ?

**Comment by jtblin** [comment]
It already supports attributes.
```
return function chart (type) {
      return {
        restrict: 'CA',
...
```
