### ISSUE TITLE
Question:  Any plans to wrap ChartNew.js

### ISSUE THREAD

**Issue by mannb1** [jtblin/angular-chart.js#64]
Any plans to wrap or support ChartNew.js?  I like your angular wrapper but there are some Chart.js limitations that are resolved in ChartNew.js.

**Comment by jtblin** [comment]
Hey, not really. Chart.js has gotten a bit of traction lately with the release of `1.0.0` although it's still a bit slow. What are the limitations that are solved in ChartNew.js, can they be moved to Chart.js?
I had the feeling ChartNew.js was also a pretty old fork of Chart.js.

**Comment by mannb1** [comment]
Hi Jerome,

Agreed.  I think Chart.js is the better product and I am sticking with it.
My main issue was labelling outside the doughnut and pie charts - it is not
easy to do and ChartNew.js did a nice job of it.  I worked around it by
adding labels external to the canvas for now.  Would be really nice if
Chart.js accounted for this.

Thanks

Blair

**Comment by jtblin** [comment]
Maybe suggest the ChartNew.js developer(s) to submit PRs to Chart.js for their improvements.

Cheers
Jerome
