### ISSUE TITLE
Chart blur on orientation change

### ISSUE THREAD

**Issue by mailtoamirjohn** [jtblin/angular-chart.js#640]
I am using this chart plugin for cordova mobile application(Bootstrap and Angular js).

 I loaded the chart in landscape mode its looking good but when it rotate to portrait mode its gets blur.

Vise versa in portrait mode to landscape mode .

Note: I am not setting resposive : true to my chart. (Is this cause an issue).

**Comment by jtblin** [comment]
Responsive is set to true by default. Difficult to know without repro steps.
