### ISSUE TITLE
Chartjs > 2.5.0: Cannot read property 'skip' of undefined when hover the chart on hover chart

### ISSUE THREAD

**Issue by pdorgambide** [jtblin/angular-chart.js#644]
With Chartjs 2.6.0 on hover the chart apperars the exception: 
 Cannot read property 'skip' of undefined when hover the chart on hover chart [https://github.com/chartjs/Chart.js/issues/3753](https://github.com/chartjs/Chart.js/issues/3753) 

With 2.5.0 seems to work fine.

**Comment by marcinn** [comment]
Same for me.

**Comment by RanganathaKR** [comment]
Same issue for me as well , can some one help me out on this please .

thanks in advance ..

**Comment by mattsnic** [comment]
You may want to check [this solution:](https://github.com/chartjs/Chart.js/issues/3753)
