### ISSUE TITLE
Custom legend templates

### ISSUE THREAD

**Issue by flithuge** [jtblin/angular-chart.js#649]
Hi, i start to use angular-chart (lastest version) for a new project and i want to customize the legend.
I tried some things from the ChartJS Documentation and this repositoty with no success. I m stuck with the method  "legendCallback" which seems not exist or not called.

There is a plunker with my code

https://jsbin.com/qamezafani/2/edit?html,js,output

There is other way to customize legend ? Thanks.

**Comment by flithuge** [comment]
Hi, after some try i can catch  the legendCallback function but it do not apply the new template to the legend. I must miss something.

https://jsbin.com/nunuhatavu/edit?html,js,output

**Comment by jtblin** [comment]
Probably better posting a question on StackOverflow or in Chart.js repo sorry.
