### ISSUE TITLE
angular-charts with ng-view doesnt resize

### ISSUE THREAD

**Issue by devlanp** [jtblin/angular-chart.js#66]
Not sure if this has already been discussed ! Observed that when the angular charts are used as a partial included through ng-resize, the chart doesn't resize to the viewport size. It remains of the same size even after the window is resized. Any fix or workaround would be helpful.

**Comment by jtblin** [comment]
Could you post a code example? There is a link to a jsbin template in readme.

**Comment by devlanp** [comment]
Hey thanks... I got it working with solution of Issue #29. :+1:  Quick question, any way in which we could get the values displayed on the chart than hover ?

**Comment by jtblin** [comment]
Have a look at the [options of Chart.js](www.chartjs.org/docs/). If it isn't available you can always create a feature request issue in their repo.
