### ISSUE TITLE
Chart bar don't show correct value

### ISSUE THREAD

**Issue by luciano-work** [jtblin/angular-chart.js#662]
I'm trying to work with  "chart-bar" using this configuration:

html:
<canvas id="bar" class="chart chart-bar" 
    chart-data="data" 
    chart-labels="labels">
</canvas>

Angular-Ctrl:
$scope.labels = ['2006', '2007', '2008', '2009'];
$scope.data = [
   [10, 5, 10, 10]
];

Problem: If I use equals values in data source, sometimes don't appear the chart bar

![chart](https://user-images.githubusercontent.com/12519008/31235976-30191360-a9c9-11e7-8930-b8d29cf2d483.png)

Examplo plnkr.co:
http://plnkr.co/edit/fs8BHPhGa3VXXBR7sQgE?p=preview

I'm doing something wrong or it's just a bug ?

Thankyou :)

**Comment by eugeneJava** [comment]
Your Y axes starts from min dataset value. Add beginFromZero option to your y axes options:
` $scope.options =  {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    };`

**Comment by luciano-work** [comment]
@eugeneJava Thank You very much :)
