### ISSUE TITLE
Chart is not working if I use ng-show

### ISSUE THREAD

**Issue by Rexota** [jtblin/angular-chart.js#67]
I added loaded variable to see a loading bar.

    $scope.loaded = false
    //things to load.... //chart options etc.
    $scope.loaded = true

Html:

    <div ng-show="loaded">
       <canvas id="line" class="chart chart-line" data="chartData" labels="chartLabels" legend="true" series="chartSeries"
	options="chartOptions"></canvas> 
    </div>

When`loaded` true, chart is not working.

**Comment by jtblin** [comment]
Angular digest cycle is not synchronous and the chart will not be created
right after setting the data. If you want to know when the chart is
created, I suggest you listen to the "create" event using

    $scope.$on('create', function () {
       $scope.loaded = true;
    });

**Comment by Rexota** [comment]
Thanks for suggestion, your advice is working for me but I also have to use `loaded` variable for showing a simple loading bar. I chart is still not working because I have to use ng-show.

**Comment by csheets** [comment]
If I am remembering correctly, I was seeing this at one point as well and it seemed to be that when ng-show was false then the canvas had no "size" or display:none (or something similar) and then the chart was never rendered which seems to be a common issue with ChartJS and so for me it seemed like this was a ChartJS issue: see https://github.com/nnnick/Chart.js/issues/512 for more info.

**Comment by Rexota** [comment]
Thanks! I'm looking to it now.

**Comment by jtblin** [comment]
Ok, this is the same issue as #29. Closing as duplicate.

The link posted by @csheets seems to have a workaround for the issue.

**Comment by IgorUzhviev** [comment]
@jtblin, even so that workaround worked it is not an angular way at all...

**Comment by gstrit** [comment]
IgorUzhviev is right. This is not the good way but I have no solution. I'm trying to use angularjs-chart with gridster but if have the same issue... Someone has a good solution ?

**Comment by tortik** [comment]
You can use ng-if instead ng-show/ng-hide. Works for me.

**Comment by LucasLazaro** [comment]
I had the same problem, but as @tortik said using **ng-if** will force a redraw of the container which also solves the issue.

**Comment by artdias90** [comment]
I lose the functionality of my preloading code when using ng-if instead of ng-show. Would be good if this is fixed so we can render the chart with ng-show / hide.
