### ISSUE TITLE
Stacked bar chart tooltip with total of each bar ?

### ISSUE THREAD

**Issue by vsundesha** [jtblin/angular-chart.js#672]
Is there anyway to get the tooltip to show the total of each bar ?
eg: In the image we can see that all has 2 stacks operational and not operational. Is there a way to add a total sum of both stacks in the tooltip as in total : 7640 ? 

Thankyou ! 
![image](https://user-images.githubusercontent.com/19426535/32554706-f6de47d6-c49a-11e7-9a30-c1e59c10db99.png)

**Comment by LucasKuhn** [comment]
Why was this closed? Is there a documented solution?
