### ISSUE TITLE
Docs need to refer to chart.js dependency

### ISSUE THREAD

**Issue by jkelleher** [jtblin/angular-chart.js#68]
As a new user of chart.js, can I suggest you mention the need for this:
```javascript
<script src="bower_components/Chart.js/chart.min.js"></script>
```
before this:
```javascript
<script src="bower_components/angular-chart.js/dist/angular-chart.js"></script>
```
Could throw a newbie (like me!)
Thanks, J

**Comment by jtblin** [comment]
Well, there was the code with the install of chart.js but I added some additional working.

**Comment by ronyef** [comment]
That what made my application throw module injection error until I found this post. Thanks jkelleher.
