### ISSUE TITLE
Pie Chart labels 

### ISSUE THREAD

**Issue by ebl22** [jtblin/angular-chart.js#69]
I would like to show labels (not tooltips) on the pie chart, which describe each slice of data.
Here is how I did it:

$scope.series = ['test1', 'test2', 'test3'];
$scope.pieLabels = ["a", "b", "c"];
$scope.pieData = [100, 300, 200];
$scope.pieColours = ['#5BC0DE', '#A9F5FF', '#18636B'];

<canvas id="pie" class="chart chart-pie" data="pieData" labels="pieLabels" colours="pieColours" series="series"></canvas>

but it's not working..

**Comment by jtblin** [comment]
Nope that is not the way Chart.js work, nothing I can do. You can display the legend instead by adding `legend="true"` to your markup e.g.

![image](https://cloud.githubusercontent.com/assets/1388974/6424117/0e673f5a-bf46-11e4-966a-91becdc3288f.png)

**Comment by ProdigyView** [comment]
Actually, Chart.js does offer this: http://jsfiddle.net/nCFGL/223/

**Comment by jtblin** [comment]
Interesting. Isn't it a new 2.0 feature (still alpha)? 

As you can see in the [docs](http://www.chartjs.org/docs/#doughnut-pie-chart), it doesn't work like this with the current stable version.

You can follow progress for 2.0 on #123.

**Comment by joshribakoff** [comment]
Here's what I see after adding legend="true":

![selection_339](https://cloud.githubusercontent.com/assets/4021306/13929788/2eeb08f8-ef59-11e5-9832-77857e6c35bf.png)

Looks broken (should not overlap!)

**Comment by c1moore** [comment]
Are labels with pie charts supported in the beta version now?

**Comment by jtblin** [comment]
Yes it has changed, see https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0#chartjs-20-and-100-beta-branch for breaking changes. Legend is now a Chart.js option, see [example](https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/examples/app.js#L65)

**Comment by indusbull** [comment]
I'm trying to show the legend at bottom as shown in pic by @jtblin in 2nd post. But I cannot get it to work with latest 1.0 .3. I tried both legend options -
1) With markup `chart-legend="true"`
2) Scope options 
`
	var pieChartDefaulOptions = {
        title: {
            display: true,
            text: 'Legend',
            position: 'bottom',
            padding: 5
        },        
        legend: {
	        display: true	        
	    }        
    };
		`

[Plnkr Example](https://plnkr.co/edit/1unhx1LO5JXc8rJJhCOj?p=preview)

Thank you.
