### ISSUE TITLE
show/hide line on legend click

### ISSUE THREAD

**Issue by benavern** [jtblin/angular-chart.js#70]
Hello,

First thank you for that directive that works perfectly!

I'd like to know if it's possible to be able to do something to be able toshow/hide a line (on line charts) when clicking on the corresponding label in the legend.
I tried multiple solutions (delete the corresponding array of data, change color for transparent one, customise legendTemplate ... ) but i always end up saying myself it's too durty...

That woul'd be owesome if you can give me some help or an entire solution ;)
Thank's in advance!

**Comment by benavern** [comment]
Hi, I kind of solved my problem.
The trick is to set every value of the array you want to hide by a null value.

If I have 2 datasets for exemple.
```javascript
$scope.chartData = [[1,2,3], [4,5,6]];
$scope.theChart = {
        "data" = [], 
        "series":["data1", "data2"], 
        "colors"=["#ff0000", "#00ff00"], 
        "labels":[1,2,3], 
        "options":{datasetFill:false}
    }
$scope.show = [true, true, true];
$scope.handleShow = function(){
	var output = [];
	angular.copy($scope.chartData, output);
	for(var i=0; i<output.length; i++){
		if ($scope.show[i] === false){
			for(var j=0; j<output[i].length; j++){
				output[i][j] = null
			}
		}
	}
	$scope.theChart.data = output;
}
$scope.handleShow()
```
now on the view :

```html
<canvas class="chart chart-line" 
		data="theChart.data" colours="theChart.colors"
		labels="theChart.labels" legend="false" 
                series="theChart.series" click="theChart.click" 
                options="bitrateChart.options"> <!-- legend false 'cause I recreate my own legend' -->
</canvas>
<div class="chart-legend">
	<ul class="line-legend">
		<li>
			<span ng-style="{ 'background' : ((show[0] === true) ? theChart.colors[0] : 'silver'), 'cursor': 'pointer'}" 
			title="Show/hide corresponding line on chart"
			ng-click="show[0] = !show[0]; handleShow()">
		        </span>
			{{ theChart.series[0] }} 
		</li>
		<li>
			<span ng-style="{ 'background' : ((show[1] === true) ? theChart.colors[1] : 'silver'), 'cursor': 'pointer'}" 
			title="Show/hide corresponding line on chart"
			ng-click="show[1] = !show[1]; handleShow()">
			</span>
			{{ theChart.series[1] }} 
		</li>
	</ul>
</div>
```

Here I deactivated the legend and rebuilt my own so that my functions work.

New data comes every 2 seconds for me, I call the $scope.handleShow function each time new data comes.

I think there can be better solutions but that's the only one I found for the moment. :)

**Comment by jtblin** [comment]
Nice :) you could probably dry that by using `map` instead of nested arrays in the js code, and by using a `ng-repeat` on the series in the html markup. Next step you could make this a directive and use all the time ;)

**Comment by benavern** [comment]
Uh!!
I'm maybe not used to javascript einough to be able to do that.
I don't know the  `map` function realy well, could you help me doing that please ?
will it be compatible with ie8 considering that I use `html5shiv` and `respond` that will enhance browsers compatibility?

**Comment by benavern** [comment]
Ok, I tried something, tell me if this can be improved:

directive : 
```javascript
.directive('chartsLegend', [function () { /*needs $scope.show to be defined...*/
        return {
            restrict: 'E',
            replace: true,
            templateUrl: 'partials/templates/charts-legend.html',
            scope:{
                chartdata:"=",
                show:"="
            }
        };
    }])
```
the template : 
```html
<div class="chart-legend">

	<ul class="line-legend">
		<li ng-repeat="item in chartdata.data track by $index"
			ng-click="show[$index] = !show[$index];"
			style="cursor: pointer;">
			<span 	ng-style="{ 'background' : ((show[$index] === true) ? chartdata.colors[$index].strokeColor : 'silver')}" 
					title="Show/hide corresponding line on chart">
			</span>
			{{ chartdata.series[$index] }} 
		</li>
	</ul>
	
</div>
```

and I use it like that, just under the canvas:
```html
<charts-legend chartdata="ipStatsChart" show="show" ng-click="handleShow()"></charts-legend>
```
I didn't change the `handleshow` function...

**Comment by jtblin** [comment]
Nice :+1: 

I'll have a look and maybe add this as an option later if you are OK with that?

**Comment by benavern** [comment]
no problem I'm ok, just don't forget to notice me so that I'll integrate your version in my project. 
Thank you ;-)

**Comment by sam2x** [comment]
Exactly what i'm looking for in the doc. 
Is that possible to add a "hide-onClick" option ?
I was reading http://canvasjs.com/docs/charts/how-to/hide-unhide-data-series-chart-legend-click/ for native chart.js, they managed to bind onClick event on the legend. But it's not possible via the directive.

So I was going to use the "options" parameter to pass "legendTemplate" with a ng-click handler to link anchor.

Not sure now, what's the best way. Waiting an update, implementing the solution above, or diving to the legendTemplate way (which allow me to keep the current legend).

Any suggestions ?  
Regards.

**Comment by AleksMeshkov** [comment]
@jtblin, Hi! Did you have time to look through it?

**Comment by grzegorzrazny** [comment]
+1. Are you planning to include this in nearest future?

**Comment by jtblin** [comment]
This is now possible with Chart.js 2.0 so I won't be implementing this in the current version. To try out the 1.x branch which works with Chart.js 2.0, please use https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0.
