### ISSUE TITLE
How to hide a Legend in the first load?

### ISSUE THREAD

**Issue by hukacode** [jtblin/angular-chart.js#708]
Hello,

Do we have an option to hide legend like this image in the first load?

Thanks in advance!

Best regards,
Huka

![image](https://user-images.githubusercontent.com/3462200/56845022-c2b53b00-68e4-11e9-8472-811fee67efa7.png)

**Comment by robertour** [comment]
You need to use the `chart-dataset-override` property. I just posted an answer here:

https://stackoverflow.com/questions/36846177/chart-js-how-to-set-a-line-chart-dataset-as-disabled-on-load/#answer-56772303

**Comment by hukacode** [comment]
Hi @robertour 

Thank you so much!
