### ISSUE TITLE
Bug: The charts animate twice on page load

### ISSUE THREAD

**Issue by gudh** [jtblin/angular-chart.js#71]
Hi, thanks for building this amazing directive.

I think I found the bug that the charts animate twice on page load instead of one, as show in the demo http://jtblin.github.io/angular-chart.js/#line-chart

Let me know if you need more info, thanks

**Comment by jtblin** [comment]
Thanks mate. It does that on the demo bc there is a timeout after a few
seconds changing the data. This is to show using async data / chart update.

Cheers
Jerome

**Comment by jtblin** [comment]
See `examples/app.js`:

```
app.controller('LineCtrl', ['$scope', '$timeout', function ($scope, $timeout) {
    $scope.labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July'];
    $scope.series = ['Series A', 'Series B'];
    $scope.data = [
      [65, 59, 80, 81, 56, 55, 40],
      [28, 48, 40, 19, 86, 27, 90]
    ];
    $scope.onClick = function (points, evt) {
      console.log(points, evt);
    };

    $timeout(function () {
      $scope.labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
      $scope.data = [
        [28, 48, 40, 19, 86, 27, 90],
        [65, 59, 80, 81, 56, 55, 40]
      ];
      $scope.series = ['Series C', 'Series D'];
    }, 3000);
  }]);
```

**Comment by gudh** [comment]
Oh I see

Thanks for the explanation, really appreciate it :)

Keep up great work!
