### ISSUE TITLE
Fail to resize manually

### ISSUE THREAD

**Issue by gudh** [jtblin/angular-chart.js#74]
Hi, thanks for building this directive

Here is the thing, I get the charts successfully with following code 
```javascript
        var charts = [];
        $scope.$on('create', function (event, chart) {
            charts.push(chart);
        });
```

Then I was thinking to resize the charts on button click with the code below
```
        $scope.resize = function() {
            charts.forEach( function(chart) {
                chart.resize();
            });
        }
```

However, the charts just goes blank.

Let me know if I am wrong. By the way, should I create plunkr demo for this?

**Comment by jtblin** [comment]
Thanks for the code, I've added that to the jsbin template (linked in the readme): http://jsbin.com/nacoge/1/edit?html,js,output. I can confirm the bug, will look into this later.

**Comment by akakwel** [comment]
I had the same issue but this worked for me :

```javascript
chart.resize(chart.render, true)
```

**Comment by jtblin** [comment]
Confirmed that this fixes the issue: http://jsbin.com/nacoge/3/edit

Thanks @akakwel!

**Comment by gudh** [comment]
@akakwel thanks for help, really appreciate it.

However, the charts are just render themselves, they still didn't resize. As showed in the following screenshot, the charts overflowed. 

![snip20150316_1](https://cloud.githubusercontent.com/assets/3378031/6661199/7f4ab032-cb7e-11e4-96b0-12886f6737d5.jpg)

**Comment by nvme978** [comment]
Hi @gudh I know this is an old issue. But did you find any resolution for your problem. I'm facing the same issue now.

Thanks

**Comment by jtblin** [comment]
@nvme978 can you post your code using a jsbin (see above)?

**Comment by Saschafeldmann** [comment]
Dear all - is there also a solution to resize/render a specific chart with this function above, when you have more then one ? Please have also a look to my question (with plunker):
http://stackoverflow.com/questions/34993764/angular-chart-js-how-to-animate-a-chart-per-click
