### ISSUE TITLE
Issues when using chart.js with leaflet

### ISSUE THREAD

**Issue by sebastialonso** [jtblin/angular-chart.js#75]
I'm using leaflet in my project, but not in this particular controller, where I am using `chart.js`.

If I use the `legend` attribute, this errors comes up

~~~
Error: [$compile:ctreq] Controller 'leaflet', required by directive 'legend', can't be found!
~~~
[link for the error](https://docs.angularjs.org/error/$compile/ctreq?p0=leaflet&p1=legend)

I believe it might be a naming conflict.

**Comment by jtblin** [comment]
Looks like it. Could you post a jsbin example? Setting `terminal` to `true` in angular-chart directive might solve the problem but I am not sure.

**Comment by sebastialonso** [comment]
Sorry for the delay, lots of work.

I've been trying to write a little plnkr, but I'm having issues making Angular work. I'll report any changes. Also, `terminal="true"` did not work.

**Comment by jtblin** [comment]
Feel free to re-open with a repro case.

**Comment by deancsmith** [comment]
I've just had the same issue - an apparent conflict over angular-chart.js and leaflet when trying to add legend="true" to a pie chat.

Setting terminal="true" has not fixed the issue.

Will work up a Plunkr.

**Comment by drobin** [comment]
There might be a conflict between angular-chart.js with angular-leaflet-directive:

http://plnkr.co/edit/eNfdtCkJDU0wuz9oinem

Removing the legend attribute will "fix" it...

**Comment by deancsmith** [comment]
My hacky workaround was to just generate the HTML using the Chart.js methods, and then inject the legend into the DOM in the correct place.


In the controller:
```
// Catch the chart creation event
$scope.$on('create', function (event, chart) {
    $scope.legend = $sce.trustAsHtml(chart.generateLegend());
});
```

In the view:
```
<span ng-bind-html="legend">{{ legend }}</span>
```

**Comment by svenstaro** [comment]
Got the exactly same problem. Seems like a legit problem.

**Comment by jtblin** [comment]
Just use `data-legend` instead of `legend` for the attribute. Angular will pick it up automatically and it won't conflict with leaflet directive. I should have been more careful with attributes and prefix them with `chart-` but that would be a breaking change now so that looks like the best option.

**Comment by svenstaro** [comment]
@jtblin That breaks for me sadly. What is the problem with adding `chart-` prefixes but keeping the current ones intact?

**Comment by svenstaro** [comment]
Can you reopen this for now? It does not appear fixed at least for me.

**Comment by jtblin** [comment]
I should have thought about that, if angular is able to pick up the attribute, it will work for a directive as well... I'll add the `chart-legend` sometimes soon.

**Comment by svenstaro** [comment]
Pretty please. :)

**Comment by Luxiyalu** [comment]
@jtblin still not added yet?

**Comment by jtblin** [comment]
Nope, I don't have time at the moment. If someone wants to take a stab at it, here are the specs:

* prefix all options by `chart-`
* set all options as `chart-<option> || <option>` for backward compatibility
* deprecate use of <option> via console.warn message
* update readme and examples
* add and update tests

I'll gladly accept PRs :)

**Comment by whummer** [comment]
Added PR #181, tests are passing, documentation is updated. Now we can use chart.js and leaflet directives in parallel. :) cheers
