### ISSUE TITLE
Pie Info not shown on mouse hover

### ISSUE THREAD

**Issue by devlanp** [jtblin/angular-chart.js#76]
When we load the chart without animation, for the first time the info displayed about the selected pie doesn't appear. However, when we move the mouse out of the chart and bring it back in the pie it pops up. 

JS:
<canvas id="pie" class="chart chart-pie chart-xs" data="data" labels="labels" legend="true" colours = "colors" click="onChartClick" options="{animationEasing : none, animateRotate : false}"></canvas>

Screenshots:
Attached.
![hover-1](https://cloud.githubusercontent.com/assets/10979563/6572445/576e2700-c738-11e4-80e8-b61a12c05297.png)
![hover-2](https://cloud.githubusercontent.com/assets/10979563/6572444/576e1602-c738-11e4-9118-e984faaba977.png)

**Comment by jtblin** [comment]
That looks like a browser issue or with Chart.js itself.
