### ISSUE TITLE
Mouseover / hover event over points

### ISSUE THREAD

**Issue by idangozlan** [jtblin/angular-chart.js#82]
Hi,

I think that it will be very useful to add feature of hovering point.

I'm using small charts and I handle info box outside the chart which I want to be influenced by the point that users hovering. today, I cant detect when point being hovered, and not getting its data.

Is there anyway use getPointsAtEvent function ?

Thanks.

**Comment by jtblin** [comment]
Published as `0.6.0`. Thanks!
