### ISSUE TITLE
Chart disappear when Changing Tabs in Ionic Framework

### ISSUE THREAD

**Issue by nishthanuj** [jtblin/angular-chart.js#85]
I am writing an application With Ionic Framework. I used 
Ionic Tabs template and I wanted to add a Chart using ChartJs. I use an 
Android device.

The Chart is working pretty good once the view appears, even when navigating through tabs without writing in input. But When:

I am in Tab1.
I try to change Tab to Tab2 that contains Input text.
then when the keyboard is appearing, i write or not.
I dismiss the keyboard (That's what cause the problem)
I go back to the Tab1
The Chart is disappearing and not reappearing until closing the application.
if i don't dismiss the keyboard the chart will appear
I am not using any extra code for handling the chart

i got following error
Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative. at line 1206 chart.js

**Comment by nishthanuj** [comment]
I got a hack to avoid this problem, and that is working fine for me, i used the 'options' attribute to set responsive to false.

**Comment by jtblin** [comment]
Same issue as #29. Yes setting responsive to false solves the issue, I also posted another workaround on the other issue.
