### ISSUE TITLE
Chart animation is very slow in Firefox 36.0.1

### ISSUE THREAD

**Issue by sgungormus** [jtblin/angular-chart.js#87]
I'm using Ubuntu / Firefox 36.0.1 and when opening charts animations are extremely slow. It hangs up for a second and continue. It is also same in demo page http://jtblin.github.io/angular-chart.js/
Is this a browser issue? By the way I tested standard chart.js and it works without a problem.

**Comment by jtblin** [comment]
It's a bit slow for me as well on the demo page with Firefox but that's because it's less optimised than Chrome I guess. I am not doing anything particular regarding animations so I don't see why there would be any difference with Chart.js for the same graph. Open an issue on Firefox?
