### ISSUE TITLE
IE8 compatibility issues

### ISSUE THREAD

**Issue by romain-ni** [jtblin/angular-chart.js#88]
The documentation says:
```
<head>
<!--[if lt IE 9]><script src="excanvas.js"></script><![endif]-->
<!--[if lt IE 9]><script src="es5-shim.js"></script><![endif]-->
</head>
```

However this did not fix all of my compatibility issues. Currently, the legend is displayed but the Chart (doughnut in my case) doesn't.
IE8 is throwing three "TypeError: Object doesn't support this property or method".

An example of IE8 compatible integration would be very helpful.

**Comment by romain-ni** [comment]
The main issues might come from the use of rgba() which is not supported by IE8

**Comment by jonathancohen4221** [comment]
Hi,

I have an issue angular-chart plugin. It doesn't work in IE8. No charts display. I add excanvas and es5-shim but i have an error "TypeError: 'document.defaultView' is null or not an object. Have you expected the same issue ? 
 Is it possible to have an example of your integration for IE8 ?
Thank you very much for your help

**Comment by jtblin** [comment]
@romain-ni, you're right IE8 does not support `rgba` so looks like it cannot work with IE8 unless you pass your own colour object with just `rgb` value. IE8 only has 1% usage now so I don't have plan to fix that.

**Comment by romain-ni** [comment]
Fair enough, thanks for the quick answers
