### ISSUE TITLE
When value is larger than 100 then chart's max value is set to 200. 

### ISSUE THREAD

**Issue by GreatAnubis** [jtblin/angular-chart.js#92]
HI, 
I've got a chart with some values. Sometimes the data value is 102 or 104. In general the highest value it can get is 120. But... if a value in my data array is larger than 100 then chart's max value is 200, but I do not really need so much blank space on the top in my chart. Is somehow possible setting the max value for the chart or maybe just to force that max value should not be larger than 20 from the max data value?

**Comment by GreatAnubis** [comment]
OK I've figured it out myself ;) It's probably not the best solution, but ... works for me. 
Chart.js lines starting from 407:
```
            var tmpMax = Math.round(maxValue/10);
			var	valueRange = Math.abs(maxValue - minValue),
				rangeOrderOfMagnitude = calculateOrderOfMagnitude(valueRange),
				//graphMax = Math.ceil(maxValue / (1 * Math.pow(10, rangeOrderOfMagnitude))) * Math.pow(10, rangeOrderOfMagnitude),
                graphMax = Math.round(maxValue+tmpMax),  // (1 * Math.pow(10, rangeOrderOfMagnitude))) * Math.pow(10, rangeOrderOfMagnitude),
				graphMin = (startFromZero) ? 0 : Math.floor(minValue / (1 * Math.pow(10, rangeOrderOfMagnitude))) * Math.pow(10, rangeOrderOfMagnitude),
				graphRange = graphMax - graphMin,
				stepValue = Math.pow(10, rangeOrderOfMagnitude),
				numberOfSteps = Math.round(graphRange / stepValue);
```

**Comment by jtblin** [comment]
Have you looked on overriding the scale options? See http://www.chartjs.org/docs/#getting-started-global-chart-configuration.

**Comment by GreatAnubis** [comment]
Yes, I've seen it. However, the scale config (as far as I understand) is constant. I was able to set it to have chart's max value 140, but... I would like to have a dynamic scale... it looks pretty cool. 
OK... I know what's going on. Please take a look at this example (yeah I know you know it ;) ):
http://jsbin.com/cidutimodo/1/edit?html,js,output
Replace data with this:
    $scope.data = [
      [104, 10, 80, 81, 104, 55, 40],
      [11, 48, 40, 19, 86, 27, 90]
    ];

There's 104 but nothing bad is happening, the chart looks nice... but... instead of value of 10 (second value) put a lower value, like 9 or 0. 
    $scope.data = [
      [104, 2, 80, 81, 104, 55, 40],
      [11, 48, 40, 19, 86, 27, 90]
    ];

Chart's max value is now 200 .

**Comment by GreatAnubis** [comment]
Have it been fixed... somehow? Or just simply closed?

**Comment by jtblin** [comment]
Sorry I wasn't clear but I don't maintain the chart.js library. If you want a new feature or a fix in this library, you'd need to do that on their github repo: https://github.com/nnnick/Chart.js

angular-chart.js is just a wrapper around chart.js.
