### ISSUE TITLE
Limit x axis labels

### ISSUE THREAD

**Issue by mikehm** [jtblin/angular-chart.js#93]
Is there an option to limit the number of your x-axis labels to a certain number?. My data is large and when the page is viewed on a smaller screen all the x-labels become stacked over each other.

**Comment by mariostesla** [comment]
i think what you are asking is related to [this pull request](https://github.com/nnnick/Chart.js/pull/897) in Chart.js, unfortunately it's still not merged

**Comment by mikehm** [comment]
Thanks, I instead had to use a for loop to loop over and push the values of my x-axis data into the labels array (while incrementing over the elements of the array (x-axis values) by two or i = i + 2). That removed the odd indexed elements.

**Comment by jtblin** [comment]
Thanks @mariostesla for the link to issue in Chart.js, closing as it looks like something that needs to be done in Chart.js itself.
