### ISSUE TITLE
Can't get it working with mean.io

### ISSUE THREAD

**Issue by jguix** [jtblin/angular-chart.js#94]
I followed the instructions on how to add an angular dependency to a custom mean package.

In my module's app.js:

    // Aggregate CSS assets
    Report.aggregateAsset('css', 'report.css');
    Report.aggregateAsset('css', '../lib/angular-chart.js/dist/angular-chart.css');

    // Aggregate JS assets
    Report.aggregateAsset('js','../lib/Chart.js/Chart.js');
    Report.aggregateAsset('js','../lib/angular-chart.js/dist/angular-chart.js');

    // Add dependency to modules in the custom package
    Report.angularDependencies(['chart.js']);

In theory, that would be equal to:

    angular.module('mean.report', ['chart.js']);

Which I also tried by the way.

When I run the application I can see that the JS and CSS files are downloaded, the CSS styles can be used, but I can not see any charts.

Trying many different ways of configuration at mean.io files I've been able to see a pie chart, but every time I try to feed it with real data I get some errors like Chart is not defined, etc.

So, either chart.js doesn't get injected in my module or the dependencies between angular-chart.js and Chart.js are not resolved.

I discussed for long with a guy from mean.io support team and he said everything was ok on the mean side, and that I probably should check angular-chart.js

**Comment by jtblin** [comment]
Have you added Chart.js as well? See readme for instructions.

**Comment by jguix** [comment]
The following line of code is supposed to add Chart.js

Report.aggregateAsset('js','../lib/Chart.js/Chart.js');

I also included it in bower dependencies and I am fairly sure that the JS file is being downloaded.

**Comment by jtblin** [comment]
Would need a repro case here. I don't use mean.io myself so can't help without a repro case, you can use http://jsbin.com/dufibi/3/edit?html,js,output as template.
