### ISSUE TITLE
Width and iOS

### ISSUE THREAD

**Issue by arjunroychowdhury** [jtblin/angular-chart.js#99]
Hi, I'm trying this library out. The library requires me to specify a chart width and height. What I want is for it to occupy the full width of the device but allow for horizontal scrolling beyond a point. For example, if I have 20 data items, I don't want them to be all squished within device width. What might be the right approach here?

**Comment by jtblin** [comment]
You don't need to specify dimensions, by default its responsive and will
use the dimensions of its container.

**Comment by arjunroychowdhury** [comment]
Jerome you are right. It works without it. Would you have any inputs on how
I can make sure it's not squished? Let's say I'm making bar charts and I
have 50 bars. I want to enable horizontal scrolling beyond 10 bars. I've
tried parent overflow containers but it always scrolls even with 3 bars.

On Thursday, April 23, 2015, Jerome Touffe-Blin <notifications@github.com>
wrote:

> You don't need to specify dimensions, by default its responsive and will
> use the dimensions of its container.
> On 23 Apr 2015 7:30 pm, "ARC" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Hi, I'm trying this library out. The library requires me to specify a
> > chart width and height. What I want is for it to occupy the full width of
> > the device but allow for horizontal scrolling beyond a point. For
> example,
> > if I have 20 data items, I don't want them to be all squished within
> device
> > width. What might be the right approach here?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jtblin/angular-chart.js/issues/99>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtblin/angular-chart.js/issues/99#issuecomment-95513866>
> .
>


-- 
Arjun Roychowdhury

**Comment by jtblin** [comment]
I think you'd have better luck asking this question on [SO](http://stackoverflow.com/) as it looks more like a css issue than an issue with the library itself. I'd use `overflow: auto` in this case, see https://developer.mozilla.org/en-US/docs/Web/CSS/overflow.

**Comment by wiii** [comment]
Hi @pliablepixels, do you find the solution for horizontal scrolling?

**Comment by jtblin** [comment]
@wiii have you tried `overflow: auto`?

**Comment by wiii** [comment]
Hi @jtblin I have already solved

```
<div style='overflow: auto;'>
   <canvas id='line' style='height:500px; min-width:2000px;' class='chart chart-line' data='data'   series='series'  options='{responsive: false,maintainAspectRatio: true}'></canvas>
</div>
```

Regards
